<%@ Page Title="Configurações de diferimento do ICMS" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="CONFIGURAESDEDIFERIMENTODOICMS" Title="Diferimento ICMS - Faturamento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="TR_IMPOSTODIFERIMENTOICMS.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="AGA_E_TRIBUTOS_IMPOSTOS_DIFERIMENTOICMS" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="ESTADOSDACONFIGURAODEDIFERIMENTODOICMS" Title="Estados - destino" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="CONFIGURAESDEDIFERIMENTODOICMS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="TR_IMPOSTODIFERIMENTOICMSUF.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="(A.IMPOSTODIFERIMENTOICMS = @CAMPO(HANDLE))" FormUrl="~/aga/a/Tributos/Diferimento/DiferimentoICMSUF/Form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_E_TRIBUTOS_IMPOSTOS_DIFERIMENTOICMS" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="OPERAESCOMERCIAISDACONFIGURAODEDIFERIMENTODOICMS" Title="Operações comerciais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="CONFIGURAESDEDIFERIMENTODOICMS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="TR_IMPOSTODIFERIMENTOICMSOP.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="(A.IMPOSTODIFERIMENTOICMS = @CAMPO(HANDLE))" FormUrl="~/aga/a/Tributos/Diferimento/DiferimentoICMSOperacoes/Form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_E_TRIBUTOS_IMPOSTOS_DIFERIMENTOICMS" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="CLASSIFICAESTRIBUTRIASVLIDASPARAODIFERIMENTO" Title="Classificações tributárias válidas para o diferimento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="CONFIGURAESDEDIFERIMENTODOICMS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="TR_IMPOSTODIFERIMENTOICMSCST.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="(A.IMPOSTODIFERIMENTOICMS = @CAMPO(HANDLE))" FormUrl="~/aga/a/Tributos/Diferimento/DiferimentoICMSCST/Form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_E_TRIBUTOS_IMPOSTOS_DIFERIMENTOICMS" Level="20" Order="40"  />
        </div>
    
      </asp:Content>
    