<%@ Page Title="Central de Atendimento" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:MenuWidget runat="server" ID="K_CENTRALDEATENDIMENTO" Title="Central de Atendimento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" MenuID="K_SUP_ATENDIMENTO" PageId="K_PAGES_K_SUP_ATENDIMENTO_HOME" Level="50" Order="10"  />
        <wes:ActionView runat="server" ID="K_CALENDRIOENTREGAR" Title="Calendário entregar" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" Controller="CalendarioSuporte" Action="CalendarioDefault" PageId="K_PAGES_K_SUP_ATENDIMENTO_HOME" Level="50" Order="20"  />
        <wes:ActionView runat="server" ID="K_INTERAESDODIA" Title="Interações do dia" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" Controller="CalendarioSuporte" Action="CalendarioAtendimentoDia" PageId="K_PAGES_K_SUP_ATENDIMENTO_HOME" Level="50" Order="30"  />
        <wes:AmCharts runat="server" ID="K_ATENDIMENTOSXCLIENTE" Title="Atendimentos x cliente" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_SUP_ATENDIMENTOSCLIENTE_V1.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" ChartType="Bar" ChartHeight="900" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJub21lIiwic3RhcnREdXJhdGlvbiI6MSwiY2hhcnRDdXJzb3IiOnsiY3Vyc29yQWxwaGEiOjAsInpvb21hYmxlIjpmYWxzZX0sImNhdGVnb3J5QXhpcyI6eyJncmlkUG9zaXRpb24iOiJzdGFydCIsImF4aXNBbHBoYSI6MCwiZmlsbEFscGhhIjowLjA1LCJmaWxsQ29sb3IiOiIjMDAwMDAwIn0sImdyYXBocyI6W3sibGFiZWxUZXh0IjoiIiwiYmFsbG9vblRleHQiOiIgSW5jbHVpZG9zIDogW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTEiLCJ0aXRsZSI6IkluY2x1aWRvcyIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwidmFsdWVGaWVsZCI6ImluY2x1aWRvcyIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiIEhvbW9sb2dhbmRvIDogW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTIiLCJ0aXRsZSI6IkhvbW9sb2dhbmRvIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoiaG9tb2xvZ2FuZG8iLCJ0eXBlIjoiY29sdW1uIiwiZmlsbEFscGhhcyI6MX0seyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6IiBSZXNvbHZpZG9zIDogW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTQiLCJ0aXRsZSI6IlJlc29sdmlkb3MiLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJyZXNvbHZpZG9zIiwidHlwZSI6ImNvbHVtbiIsImZpbGxBbHBoYXMiOjF9LHsibGFiZWxUZXh0IjoiIiwiYmFsbG9vblRleHQiOiIgTsOtdmVsSUkgOiBbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtMyIsInRpdGxlIjoiTsOtdmVsSUkiLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJuaXZlbGlpIiwidHlwZSI6ImNvbHVtbiIsImZpbGxBbHBoYXMiOjF9XSwidmFsdWVBeGVzIjpbeyJpZCI6IlZhbHVlQXhpcy0xIiwiaW50ZWdlcnNPbmx5Ijp0cnVlLCJheGlzQWxwaGEiOjAsImRhc2hMZW5ndGgiOjUsInBvc2l0aW9uIjoibGVmdCIsInRpdGxlIjoiIn1dLCJsZWdlbmQiOnsiZW5hYmxlZCI6dHJ1ZSwicG9zaXRpb24iOiJib3R0b20iLCJ1c2VHcmFwaFNldHRpbmdzIjp0cnVlfSwicm90YXRlIjp0cnVlfQ==" PageId="K_PAGES_K_SUP_ATENDIMENTO_HOME" Level="50" Order="40"  />
        <wes:AmCharts runat="server" ID="K_HORASXCLIENTE" Title="Horas x Cliente" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_SUP_HORASCLIENTE_V1.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" ChartType="Bar" ChartHeight="700" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJub21lIiwic3RhcnREdXJhdGlvbiI6MSwiY2hhcnRDdXJzb3IiOnsiY3Vyc29yQWxwaGEiOjAsInpvb21hYmxlIjpmYWxzZX0sImNhdGVnb3J5QXhpcyI6eyJncmlkUG9zaXRpb24iOiJzdGFydCJ9LCJncmFwaHMiOlt7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiSG9yYXMgVG90YWlzIDogW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTEiLCJ2YWx1ZUF4aXMiOiJWYWx1ZUF4aXMtMSIsInRpdGxlIjoiSG9yYXMgVG90YWlzIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoiaG9yYXMiLCJ0eXBlIjoiY29sdW1uIiwiZmlsbEFscGhhcyI6MSwibGluZUNvbG9yIjoiI2UxZWRlOSIsImZpbGxDb2xvcnMiOiIjZTFlZGU5IiwiY2x1c3RlcmVkIjpmYWxzZSwiY29sdW1uV2lkdGgiOjAuNX0seyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6IkhvcmFzIEZhdHVyYWRhcyA6IFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC0yIiwidmFsdWVBeGlzIjoiVmFsdWVBeGlzLTEiLCJ0aXRsZSI6IkhvcmFzIEZhdHVyYWRhcyIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwidmFsdWVGaWVsZCI6ImZhdHVyYWRhcyIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxLCJsaW5lQ29sb3IiOiIjNjJjZjczIiwiZmlsbENvbG9ycyI6IiM2MmNmNzMiLCJjbHVzdGVyZWQiOmZhbHNlLCJjb2x1bW5XaWR0aCI6MC4zfV0sInZhbHVlQXhlcyI6W3siaWQiOiJWYWx1ZUF4aXMtMSIsInRpdGxlIjoiIn1dLCJsZWdlbmQiOnsiZW5hYmxlZCI6dHJ1ZSwicG9zaXRpb24iOiJib3R0b20iLCJ1c2VHcmFwaFNldHRpbmdzIjp0cnVlfSwicm90YXRlIjp0cnVlfQ==" PageId="K_PAGES_K_SUP_ATENDIMENTO_HOME" Level="50" Order="50"  />
        <wes:ActionView runat="server" ID="K_HORASXCLIENTETESTE" Title="Horas x Cliente (Teste)" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" Controller="SuporteGraficos" Action="GraficoHorasCliente" PageId="K_PAGES_K_SUP_ATENDIMENTO_HOME" Level="50" Order="60"  />
        </div>
    
      </asp:Content>
    