//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class tesourariaGridPage : WesPage
{
    private bool executouFiltro = false;
    
    protected void Page_Load(object sender, System.EventArgs e)
    {
        GRIDTS_LANCAMENTOS.FilterControl.FilterExecute += FilterControl_FilterExecute;
    }

    private void FilterControl_FilterExecute(object sender, FilterExecuteEventArgs e)
    {
        executouFiltro = true;
        if (GRIDTS_LANCAMENTOS.FilterEntity != null && GRIDTS_LANCAMENTOS.FilterEntity.Fields["EMISSAOATE"] != null && 
            (GRIDTS_LANCAMENTOS.FilterEntity.Fields["EMISSAOATE"].ToDateTime() < GRIDTS_LANCAMENTOS.FilterEntity.Fields["EMISSAODE"].ToDateTime()))
            GRIDTS_LANCAMENTOS.ShowWidgetMessage("Data final não pode ser menor que a data inicial.", MessageType.Error);
    }

    protected override void OnLoadComplete(EventArgs e)
    {
        base.OnLoadComplete(e);
        
        if (GRIDTS_LANCAMENTOS.FilterEntity != null && !executouFiltro)
            GRIDTS_LANCAMENTOS.FilterEntity.Fields["EMISSAOATE"] = DateTime.Now;
    }
}
