//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class K_CRM_NOVIDADESNovidadesPage : WesPage
{
    
    protected void Page_Load(object sender, System.EventArgs e)
    {
        MarcarLidas();
    }

    private void MarcarLidas()
    {
        var todasAsNovidades = Entity.GetAll(EntityDefinition.GetByName("K_CRM_NOVIDADES"));

        foreach(var novidade in todasAsNovidades)
        {
            var crit = new Criteria("A.USUARIO = :USUARIO AND A.NOVIDADE = :NOVIDADE");
            crit.Parameters.Add("USUARIO", BennerContext.Security.GetLoggedUserHandle());
            crit.Parameters.Add("NOVIDADE", novidade.Handle);

            var jaLeu = Entity.GetFirstOrDefault(EntityDefinition.GetByName("K_CRM_NOVIDADESLIDAS"), crit);

            if (null != jaLeu)
                continue;
            else
            {
                var nova = Entity.Create(EntityDefinition.GetByName("K_CRM_NOVIDADESLIDAS"));
                (nova.Fields["USUARIO"] as EntityAssociation).Handle = BennerContext.Security.GetLoggedUserHandle();
                (nova.Fields["NOVIDADE"] as EntityAssociation).Handle = novidade.Handle;
                nova.Save();
            }
        }
    }
}
