//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Frotas.Definicoes.Entidades;
using Benner.Corporativo.Wes.WebApp;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class PortariaFormPage : WesPage
{
    protected void Page_Load(object sender, System.EventArgs e)
    {

        PORTARIA.CommandExecuted += Portaria_CommandExecute;
    }

    private void Portaria_CommandExecute(object sender, FormCommandExecuteArgs e)
    {
        if (e.CommandName == "CMD_EfetuarSaida")
        {
            var codigoErro = 0;
            var codigoErroIguais = 0;
            var entity = PORTARIA.GetEntity();
            MFPessoaFrotaDao consultaPessoa = new MFPessoaFrotaDao();
            RecursoDao consultaRecurso = new RecursoDao();

            var consultaMotorista = consultaPessoa.GetFirstOrDefault(x => x.Handle == entity["MOTORISTASAIDA"].GetInt64());
            var consultaVeiculo = consultaRecurso.GetFirstOrDefault(x => x.Handle == entity["VEICULO"].GetInt64());

            if (consultaMotorista != null)
            {
                if (consultaMotorista.CnhDataValidade != null)
                {
                    var horasRestantes = consultaMotorista.CnhDataValidade - DateTime.Now;

                    if (horasRestantes.Value.TotalHours < 24)
                    {
                        codigoErro = 1;
                        codigoErroIguais++;
                    }
                }
            }

            if (consultaVeiculo != null)
            {
                if (entity["HODOMETROSAIDA"].GetInt64() > 0 && consultaVeiculo.Desgastemaximo != null)
                {
                    var calculaDesgaste = entity["HODOMETROSAIDA"].GetInt64() - entity["SQL_MARCADORANTERIOR"].GetInt64();
                    if (calculaDesgaste >= consultaVeiculo.Desgastemaximo)
                    {
                        codigoErro = 2;
                        codigoErroIguais++;
                    }
                }
            }

            if(codigoErro == 1 && codigoErroIguais != 2)
            {
                PORTARIA.ShowWidgetMessage("Verificar a validade da CNH do motorista", MessageType.Error);
            }
            if (codigoErro == 2 && codigoErroIguais != 2)
            {
                PORTARIA.ShowWidgetMessage("Desgate máximo do veículo, atingido! Necessário realizar a manutenção do veículo!", MessageType.Error);
            }

            if (codigoErroIguais == 2)
            {
                PORTARIA.ShowWidgetMessage("Verificar a validade da CNH do motorista | Desgate máximo do veículo, atingido! Necessário realizar a manutenção do veículo! ", MessageType.Error);

            }
        }

        if (e.CommandName == "CMD_EfetuarRetorno"  )
        {
            var entity = PORTARIA.GetEntity();

            RecursoDao consultaRecurso = new RecursoDao();

            var consultaVeiculo = consultaRecurso.GetFirstOrDefault(x => x.Handle == entity["VEICULO"].GetInt64());

            if (consultaVeiculo != null)
            {
                if (consultaVeiculo.Desgastemaximo != null && consultaVeiculo.KmAtual != null)
                {
                    var calculaDesgasteAlerta = entity["HODOMETRORETORNO"].GetInt64() - consultaVeiculo.KmAtual;

                    if (calculaDesgasteAlerta >= consultaVeiculo.Desgastemaximo)
                    {

                        PORTARIA.ShowWidgetMessage("Desgate máximo do veículo, atingido! Necessário realizar a manutenção do veículo!", MessageType.Error);

                    }
                }
            }
        }

    }
}
