<%@ Page Title="Compensações" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:CommandsPanel runat="server" ID="PAINELDECOMPENSACOES" Title="Painel de compensações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="WEB_FN_COMPENSACOES.GRID" VerticalOrientation="False" PageId="AGA_A_FINANCEIRO_COMPENSACOES_INICIO" Level="20" Order="10"  />
        <wes:Tile runat="server" ID="ADIANTAMENTOSCLIENTESEMABERTO" Title="Adiantamentos clientes em aberto" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="ADIANTAMENTOCLIENTEABERTO.DATASOURCE.GRID" CompanyFilterMode="OnlyCompany" ValueFormat="C2" Value="SALDO" Description="Adiantamentos clientes em aberto" Icon="fa fa-user-plus" Color="blue" ValueAggregation="None" TileType="Default" PageId="AGA_A_FINANCEIRO_COMPENSACOES_INICIO" Level="20" Order="20"  />
        <wes:Tile runat="server" ID="ADIANTAMENTOSFORNECEDORESEMABERTO" Title="Adiantamentos fornecedores em aberto" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="ADIANTAMENTOFORNECEDORESABERTO.DATASOURCE.GRID" CompanyFilterMode="OnlyCompany" ValueFormat="C2" Value="SALDO" Description="Adiantamento fornecedores em aberto" Icon="fa fa-truck" Color="green-haze" ValueAggregation="None" TileType="Default" PageId="AGA_A_FINANCEIRO_COMPENSACOES_INICIO" Level="20" Order="30"  />
        <wes:Tile runat="server" ID="DEVOLUCAOCLIENTESEMABERTO" Title="Devolução clientes em aberto" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="DEVOLUCAOCLIENTEABERTO.DATASOURCE.GRID" CompanyFilterMode="OnlyCompany" ValueFormat="C2" Value="SALDO" Description="Devolução clientes em aberto" Icon="fa fa-user-times" Color="red" ValueAggregation="None" TileType="Default" PageId="AGA_A_FINANCEIRO_COMPENSACOES_INICIO" Level="20" Order="40"  />
        <wes:Tile runat="server" ID="DEVOLUCAOFORNECEDORESEMABERTO" Title="Devolução fornecedores em aberto" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="DEVOLUCAOFORNECEDORABERTO.DATASOURCE.GRID" CompanyFilterMode="OnlyCompany" ValueFormat="C2" Value="SALDO" Description="Devolução fornecedores em aberto" Icon="fa fa-truck" Color="purple-studio" ValueAggregation="None" TileType="Default" PageId="AGA_A_FINANCEIRO_COMPENSACOES_INICIO" Level="20" Order="50"  />
        <wes:AmCharts runat="server" ID="CLIENTESXADIANTAMENTOS" Title="Clientes com mais adiantamentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CLIENTESCOMMAISADIANTAMENTOS.DATASOURCE.GRID" Mode="None" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJwZXNzb2EiLCJzdGFydER1cmF0aW9uIjoxLCJjYXRlZ29yeUF4aXMiOnsiZ3JpZFBvc2l0aW9uIjoic3RhcnQifSwiZ3JhcGhzIjpbeyJiYWxsb29uVGV4dCI6IltbY2F0ZWdvcnldXSA6IFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC0xIiwidGl0bGUiOiJwZXNzb2EiLCJ2YWx1ZUZpZWxkIjoic2FsZG8iLCJmaWxsQWxwaGFzIjowLjUsInR5cGUiOiJjb2x1bW4iLCJsaW5lQWxwaGEiOjEsImJ1bGxldCI6bnVsbH1dLCJ2YWx1ZUF4ZXMiOlt7ImlkIjoiVmFsdWVBeGlzLTEiLCJ0aXRsZSI6IiAifV0sImxlZ2VuZCI6eyJlbmFibGVkIjp0cnVlLCJ1c2VHcmFwaFNldHRpbmdzIjp0cnVlfSwicm90YXRlIjp0cnVlfQ==" PageId="AGA_A_FINANCEIRO_COMPENSACOES_INICIO" Level="20" Order="60"  />
        <wes:AmCharts runat="server" ID="CLIENTESXDEVOLUCOES" Title="Clientes com mais devoluções" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CLIENTESCOMMAISDEVOLUCOES.DATASOURCE.GRID" Mode="None" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJwZXNzb2EiLCJzdGFydER1cmF0aW9uIjoxLCJjYXRlZ29yeUF4aXMiOnsiZ3JpZFBvc2l0aW9uIjoic3RhcnQifSwiZ3JhcGhzIjpbeyJiYWxsb29uVGV4dCI6IltbY2F0ZWdvcnldXSA6IFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC0xIiwidmFsdWVGaWVsZCI6InNhbGRvIiwiZmlsbEFscGhhcyI6MC41LCJ0eXBlIjoiY29sdW1uIiwibGluZUFscGhhIjoxLCJidWxsZXQiOm51bGwsInRpdGxlIjoiUGVzc29hIiwiZmlsbENvbG9ycyI6IiNmZjAwMDAifV0sInZhbHVlQXhlcyI6W3siaWQiOiJWYWx1ZUF4aXMtMSIsInRpdGxlIjoiICJ9XSwibGVnZW5kIjp7ImVuYWJsZWQiOnRydWUsInVzZUdyYXBoU2V0dGluZ3MiOnRydWV9LCJyb3RhdGUiOnRydWV9" PageId="AGA_A_FINANCEIRO_COMPENSACOES_INICIO" Level="20" Order="70"  />
        <wes:AmCharts runat="server" ID="FORNCEDORESCOMMAISADIANTAMENTOS" Title="Forncedores com mais adiantamentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="FORNECEDORESCOMMAISADIANTAMENTOS.DATASOURCE.GRID" Mode="None" ChartType="Bar" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInJvdGF0ZSI6dHJ1ZSwidGhlbWUiOiJsaWdodCIsImV4cG9ydCI6eyJlbmFibGVkIjp0cnVlfSwiY2F0ZWdvcnlGaWVsZCI6InBlc3NvYSIsInN0YXJ0RHVyYXRpb24iOjEsImNhdGVnb3J5QXhpcyI6eyJncmlkUG9zaXRpb24iOiJzdGFydCJ9LCJncmFwaHMiOlt7ImJhbGxvb25UZXh0IjoiW1tjYXRlZ29yeV1dIDogW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTEiLCJ0aXRsZSI6InBlc3NvYSIsInZhbHVlRmllbGQiOiJzYWxkbyIsImZpbGxBbHBoYXMiOjAuNSwidHlwZSI6ImNvbHVtbiIsImxpbmVBbHBoYSI6MSwiYnVsbGV0IjpudWxsLCJmaWxsQ29sb3JzIjoiIzI4Yzk2MyJ9XSwidmFsdWVBeGVzIjpbeyJpZCI6IlZhbHVlQXhpcy0xIiwidGl0bGUiOiIgIn1dLCJsZWdlbmQiOnsiZW5hYmxlZCI6dHJ1ZSwidXNlR3JhcGhTZXR0aW5ncyI6dHJ1ZX19" PageId="AGA_A_FINANCEIRO_COMPENSACOES_INICIO" Level="20" Order="80"  />
        <wes:AmCharts runat="server" ID="FORNECEDORESCOMMAISDEVOLUCOES" Title="Fornecedores com mais devoluções" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="FORNECEDORCOMMAISDEVOLUCAO.DATASOURCE.GRID" Mode="None" ChartType="Bar" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInJvdGF0ZSI6dHJ1ZSwidGhlbWUiOiJsaWdodCIsImV4cG9ydCI6eyJlbmFibGVkIjp0cnVlfSwiY2F0ZWdvcnlGaWVsZCI6InBlc3NvYSIsInN0YXJ0RHVyYXRpb24iOjEsImNhdGVnb3J5QXhpcyI6eyJncmlkUG9zaXRpb24iOiJzdGFydCJ9LCJncmFwaHMiOlt7ImJhbGxvb25UZXh0IjoiW1tjYXRlZ29yeV1dIDogW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTEiLCJ0aXRsZSI6InBlc3NvYSIsInZhbHVlRmllbGQiOiJzYWxkbyIsImZpbGxBbHBoYXMiOjAuNSwidHlwZSI6ImNvbHVtbiIsImxpbmVBbHBoYSI6MSwiYnVsbGV0IjpudWxsLCJmaWxsQ29sb3JzIjoiI2MyMjdkNiJ9XSwidmFsdWVBeGVzIjpbeyJpZCI6IlZhbHVlQXhpcy0xIiwidGl0bGUiOiIgIn1dLCJsZWdlbmQiOnsiZW5hYmxlZCI6dHJ1ZSwidXNlR3JhcGhTZXR0aW5ncyI6dHJ1ZX19" PageId="AGA_A_FINANCEIRO_COMPENSACOES_INICIO" Level="20" Order="90"  />
        </div>
    
      </asp:Content>
    