//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class ErpVisaoGeralPage : WesPage
{

    protected void Page_Load(object sender, System.EventArgs e)
    {
        var query = new Query(@"SELECT
            (SELECT SUM(B.VALOR - B.VALORESBAIXADOS) SALDOPARCELA
            FROM FN_DOCUMENTOS A
            JOIN FN_PARCELAS B ON (B.DOCUMENTO = A.HANDLE)
            WHERE (A.EMPRESA = @EMPRESA)
                AND (((A.ENTRADASAIDA = 'S'
                    OR A.ENTRADASAIDA = 'O')
                    AND (A.TIPODEMOVIMENTO IN (1,
                                                2)))
                    OR ((A.ENTRADASAIDA = 'E'
                        OR A.ENTRADASAIDA = 'I')
                        AND (A.TIPODEMOVIMENTO = 3)))
                AND (A.ABRANGENCIA <> 'R'
                    AND A.ABRANGENCIA <> 'F'
                    AND A.ABRANGENCIA <> 'A'
                    AND A.ABRANGENCIA <> 'B'
                    AND A.ABRANGENCIA <> 'D'
                    AND A.ABRANGENCIA <> 'G'
                    AND A.ABRANGENCIA <> 'H')
                AND (B.DATAVENCIMENTO = @HOJE)
                AND (B.EMABERTO = 'S')) RECEBERHOJE,

            (SELECT SUM(B.VALOR - B.VALORESBAIXADOS) SALDOPARCELA
            FROM FN_DOCUMENTOS A
            JOIN FN_PARCELAS B ON (B.DOCUMENTO = A.HANDLE)
            WHERE (A.EMPRESA = @EMPRESA)
                AND (((A.ENTRADASAIDA = 'E'
                    OR A.ENTRADASAIDA = 'I')
                    AND (A.TIPODEMOVIMENTO IN (1,
                                                2)))
                    OR ((A.ENTRADASAIDA = 'S'
                        OR A.ENTRADASAIDA = 'O')
                        AND (A.TIPODEMOVIMENTO = 3)))
                AND (A.ABRANGENCIA <> 'R'
                    AND A.ABRANGENCIA <> 'F'
                    AND A.ABRANGENCIA <> 'A'
                    AND A.ABRANGENCIA <> 'B'
                    AND A.ABRANGENCIA <> 'D'
                    AND A.ABRANGENCIA <> 'G'
                    AND A.ABRANGENCIA <> 'H')
                AND (B.DATAVENCIMENTO = @HOJE)
                AND (B.EMABERTO = 'S')) PAGARHOJE,

            (SELECT SUM(B.VALOR - B.VALORESBAIXADOS) SALDOPARCELA
            FROM FN_DOCUMENTOS A
            JOIN FN_PARCELAS B ON (B.DOCUMENTO = A.HANDLE)
            WHERE (A.EMPRESA = @EMPRESA)
                AND (((A.ENTRADASAIDA = 'E'
                    OR A.ENTRADASAIDA = 'I')
                    AND (A.TIPODEMOVIMENTO IN (1,
                                                2)))
                    OR ((A.ENTRADASAIDA = 'S'
                        OR A.ENTRADASAIDA = 'O')
                        AND (A.TIPODEMOVIMENTO = 3)))
                AND (A.ABRANGENCIA <> 'R'
                    AND A.ABRANGENCIA <> 'F'
                    AND A.ABRANGENCIA <> 'A'
                    AND A.ABRANGENCIA <> 'B'
                    AND A.ABRANGENCIA <> 'D'
                    AND A.ABRANGENCIA <> 'G'
                    AND A.ABRANGENCIA <> 'H')
                AND (B.DATAVENCIMENTO < @HOJE)
                AND (B.EMABERTO = 'S')) PAGARVENCIDO,
            (SELECT SUM(B.VALOR - B.VALORESBAIXADOS) SALDOPARCELA
            FROM FN_DOCUMENTOS A
            JOIN FN_PARCELAS B ON (B.DOCUMENTO = A.HANDLE)
            WHERE (A.EMPRESA = @EMPRESA)
                AND (((A.ENTRADASAIDA = 'S'
                    OR A.ENTRADASAIDA = 'O')
                    AND (A.TIPODEMOVIMENTO IN (1,
                                                2)))
                    OR ((A.ENTRADASAIDA = 'E'
                        OR A.ENTRADASAIDA = 'I')
                        AND (A.TIPODEMOVIMENTO = 3)))
                AND (A.ABRANGENCIA <> 'R'
                    AND A.ABRANGENCIA <> 'F'
                    AND A.ABRANGENCIA <> 'A'
                    AND A.ABRANGENCIA <> 'B'
                    AND A.ABRANGENCIA <> 'D'
                    AND A.ABRANGENCIA <> 'G'
                    AND A.ABRANGENCIA <> 'H')
                AND (B.DATAVENCIMENTO < @HOJE)
                AND (B.EMABERTO = 'S')) RECEBERVENCIDO");

        var entities = query.Execute();
        if (entities.Count == 0)
            return;

        var valueFieldDefinition = new CurrencyFieldDefinition() { Decimals = 2 };

        TileReceberHoje.Value = valueFieldDefinition.ToUI(entities[0]["RECEBERHOJE"].GetDecimal());
        TilePagarHoje.Value = valueFieldDefinition.ToUI(entities[0]["PAGARHOJE"].GetDecimal());
        TilePagamentosAtraso.Value = valueFieldDefinition.ToUI(entities[0]["PAGARVENCIDO"].GetDecimal());
        TileRecebimentosAtraso.Value = valueFieldDefinition.ToUI(entities[0]["RECEBERVENCIDO"].GetDecimal());

        var linkReceberHoje = new GridLinkDefinition();
        linkReceberHoje.TargetSystemInstanceName = BennerContext.Administration.DefaultSystemInstanceName;
        linkReceberHoje.TargetEntityDefinitionName = "CLOUD_CONTASARECEBER";
        linkReceberHoje.IsModalPage = true;
        linkReceberHoje.WhereClause = new WhereClause("A.DATAVENCIMENTO = @HOJE");
        linkReceberHoje.Url = "~/Erp/Financeiro/CRE/Relatorio.aspx";
        TileReceberHoje.Url = Benner.Tecnologia.Wes.Components.UriBuilder.Create(linkReceberHoje, modal: true, absoluteUrl: true);

        var linkRecebimentosEmAtraso = new GridLinkDefinition();
        linkRecebimentosEmAtraso.TargetSystemInstanceName = BennerContext.Administration.DefaultSystemInstanceName;
        linkRecebimentosEmAtraso.TargetEntityDefinitionName = "CLOUD_CONTASARECEBER";
        linkRecebimentosEmAtraso.IsModalPage = true;
        linkRecebimentosEmAtraso.WhereClause = new WhereClause("A.SITUACAO = 'V'");
        linkRecebimentosEmAtraso.Url = "~/Erp/Financeiro/CRE/Relatorio.aspx";
        TileRecebimentosAtraso.Url = Benner.Tecnologia.Wes.Components.UriBuilder.Create(linkRecebimentosEmAtraso, modal: true, absoluteUrl: true);

        var linkPagarHoje = new GridLinkDefinition();
        linkPagarHoje.TargetSystemInstanceName = BennerContext.Administration.DefaultSystemInstanceName;
        linkPagarHoje.TargetEntityDefinitionName = "CLOUD_CONTASAPAGAR";
        linkPagarHoje.IsModalPage = true;
        linkPagarHoje.WhereClause = new WhereClause("A.DATAVENCIMENTO = @HOJE");
        linkPagarHoje.Url = "~/Erp/Financeiro/CPA/Relatorio.aspx";
        TilePagarHoje.Url = Benner.Tecnologia.Wes.Components.UriBuilder.Create(linkPagarHoje, modal: true, absoluteUrl: true);

        var linkPagamentosEmAtraso = new GridLinkDefinition();
        linkPagamentosEmAtraso.TargetSystemInstanceName = BennerContext.Administration.DefaultSystemInstanceName;
        linkPagamentosEmAtraso.TargetEntityDefinitionName = "CLOUD_CONTASAPAGAR";
        linkPagamentosEmAtraso.IsModalPage = true;
        linkPagamentosEmAtraso.WhereClause = new WhereClause("A.SITUACAO = 'V'");
        linkPagamentosEmAtraso.Url = "~/Erp/Financeiro/CPA/Relatorio.aspx";
        TilePagamentosAtraso.Url = Benner.Tecnologia.Wes.Components.UriBuilder.Create(linkPagamentosEmAtraso, modal: true, absoluteUrl: true);

    }
}
