//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using SM.Crm.Definicoes.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class RamoAtividadeFormPage : WesPage
{
    public CrmPesquisa Questionario
    {
        get
        {
            return this.K_QUESTIONRIODEQUALIFICAO.GetEntity() as CrmPesquisa;
        }
    }

    public CrmPessoas RamoAtividade
    {
        get
        {
            return this.K_RAMODEATIVIDADE.GetEntity() as CrmPessoas;
        }
    }

    protected void Page_Load(object sender, System.EventArgs e)
    {
        this.K_RAMODEATIVIDADE.DataLoaded += K_RAMODEATIVIDADE_DataLoaded;
        this.K_RAMODEATIVIDADE.CommandExecuted += K_RAMODEATIVIDADE_CommandExecuted;
        
    }

    private void K_RAMODEATIVIDADE_CommandExecuted(object sender, FormCommandExecuteArgs e)
    {
        if (null != RamoAtividade.RamoAtividade.Instance)
        {
            if (RamoAtividade.RamoAtividade.Instance.Fields["NOME"].Equals("Vazio"))
                throw new ArgumentException("Escolha um Ramo de atividade diferente de \"Vazio\"");

            if (e.Entity.IsEditing == true)                
                e.Entity.Save();

            CurrentStep.Value = 2.ToString();
        }
        else
            throw new ArgumentException("Preencha todos os campos obrigatórios");
    }

    private void K_RAMODEATIVIDADE_DataLoaded(object sender, EventArgs e)
    {
        this.K_RAMODEATIVIDADE.ChangeMode(BennerFormViewMode.Edit);
    }
}
