//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Benner.Tecnologia.Business;




public partial class aquisicoesSelecionarRequisicoesPage : WesPage
{
    
    protected void Page_Load(object sender, System.EventArgs e)
    {
        REQUISIES.FilterControl.FilterExecute += REQUISIES_FilterExecute;
        REQUISIES.GridView.SelectedIndexChanged += GridView_SelectedIndexChanged;

        REQUISIES.CommandExecute += REQUISIES_CommandExecute;

        REQUISIES.FilterWhereClause = new WhereClause("A.FILIALCOMPRA IN @FILIAIS");
    }

    private void REQUISIES_CommandExecute(object sender, GridCommandExecuteArgs e)
    {
        if(REQUISIES.SelectedEntitiesHandles.Count <= 0)
        {
            throw new BusinessException("Nenhuma requisição selecionada.");
        }
        if(e.Command.Name.Equals("CMD_AGRUPARREQUISICAO")){
            try
            {
                var sessionVar = new Benner.Tecnologia.Common.BennerVariables.BennerVarsFactory().CreateSessionVars();

                var listaRequisicoesHandle = REQUISIES.SelectedEntitiesHandles;
                var aquisicaoHandle = sessionVar.GetSessionVar("AQUISICAO_SELECIONADA").ToLong();
                BennerContext.BusinessComponent.Call("Benner.Corporativo.Aquisicoes.Solicitacoes.SelecionarRequisicoes, Benner.Corporativo.Aquisicoes",
                    "Gerar",
                    listaRequisicoesHandle, aquisicaoHandle);

                REQUISIES.DeselectAllRows();
                REQUISIES.DataLoad();
                REQUISIES.ForceUpdate();
                ITENS.DataLoad();
                ITENS.ForceUpdate();
                ITENSAQUISIO.DataLoad();
                ITENSAQUISIO.ForceUpdate();
                REQUISIESDAAQUISIO.DataLoad();
                REQUISIESDAAQUISIO.ForceUpdate();
            }
            catch (Exception ex)
            {
                throw new BusinessException(ex.Message, ex);
            }   
        }
    }

    private void GridView_SelectedIndexChanged(object sender, EventArgs e)
    {
        UpdateLocalWhere();
    }

    private void REQUISIES_FilterExecute(object sender, FilterExecuteEventArgs e)
    {
        UpdateLocalWhere();
    }

    private void UpdateLocalWhere(){
        var tipo = REQUISIES.FilterEntity["TIPO"].GetInt32();
        var filial = REQUISIES.FilterEntity["FILIAL"].GetInt32();
        var familia = REQUISIES.FilterEntity["FAMILIA"].GetInt32();

        WhereClause where = new WhereClause("1=1");
        
        if(tipo > 0){
            where.AddWhereClause(string.Format("A.TIPO = {0}", tipo));
        }

        if(filial > 0){
            where.AddWhereClause(string.Format("A.FILIALCOMPRA = {0}", filial));
        }
        else{
            where.AddWhereClause(string.Format("A.FILIALCOMPRA IN @FILIAIS"));
        }

        if(familia > 0){
            where.AddWhereClause(string.Format(@"A.HANDLE IN (
                                                SELECT REQUISICAO FROM LC_REQUISICAOITENS A
                                                JOIN PD_FAMILIASPRODUTOS B ON B.HANDLE = A.FAMILIA
                                                WHERE B.HANDLE = {0}
                                                )", familia));
        }

        REQUISIES.FilterWhereClause = where;

        REQUISIES.DataLoad();
        REQUISIES.ForceUpdate();
    }
}
