<%@ Page Title="Oportunidades" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMWIDGET_635713394730945586" Title="Oportunidades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="CRM_OPORTUNIDADES.CUSTOM.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="FORMPAGEID_635713394730945586" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGETID_635744651985971187" Title="Documentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMWIDGET_635713394730945586" ChromeState="Normal" EntityViewName="CRM_OPORTUNIDADEDOCUMENTOS.CUSTOM.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(HANDLE)" FormUrl="~/PortalCRM/a/CRM_OPORTUNIDADEDOCUMENTOS/Form.aspx" UserDefinedDisableRowSelection="False" PageId="FORMPAGEID_635713394730945586" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGETID_635744657167986606" Title="Produtos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMWIDGET_635713394730945586" ChromeState="Normal" EntityViewName="CRM_OPORTUNIDADEPRODUTOS.CUSTOM.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(HANDLE)" FormUrl="~/PortalCRM/a/CRM_OPORTUNIDADEPRODUTOS/Form.aspx" UserDefinedDisableRowSelection="False" PageId="FORMPAGEID_635713394730945586" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGETID_635744711942031440" Title="Tarefas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMWIDGET_635713394730945586" ChromeState="Normal" EntityViewName="CRM_TAREFAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(HANDLE)" FormUrl="~/PortalCRM/a/CRM_TAREFAS/Form.aspx" UserDefinedDisableRowSelection="False" PageId="FORMPAGEID_635713394730945586" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGETID_635773261773136921" Title="E-mail's" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMWIDGET_635713394730945586" ChromeState="Normal" EntityViewName="CRM_OPORTUNIDADEEMAILS.CUSTOM.GRID" CanDelete="False" CanUpdate="False" CanInsert="True" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(HANDLE)" FormUrl="~/PortalCRM/a/CRM_OPORTUNIDADEEMAILS/Form.aspx" UserDefinedDisableRowSelection="False" PageId="FORMPAGEID_635713394730945586" Level="20" Order="50"  />
        <wes:SimpleGrid runat="server" ID="WIDGETID_635792858306885149" Title="Contatos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMWIDGET_635713394730945586" ChromeState="Normal" EntityViewName="CRM_OPORTUNIDADECONTATOS.CUSTOM.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(HANDLE)" FormUrl="~/PortalCRM/a/CRM_OPORTUNIDADECONTATOS/Form.aspx" UserDefinedDisableRowSelection="False" PageId="FORMPAGEID_635713394730945586" Level="20" Order="60"  />
        <wes:SimpleGrid runat="server" ID="WIDGETID_635749083100667497" Title="Históricos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMWIDGET_635713394730945586" ChromeState="Normal" EntityViewName="CRM_OPORTUNIDADEHISTORICOS.CUSTOM.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(HANDLE)" FormUrl="~/PortalCRM/a/CRM_OPORTUNIDADEHISTORICOS/Form.aspx" UserDefinedDisableRowSelection="False" PageId="FORMPAGEID_635713394730945586" Level="20" Order="70"  />
        </div>
    
      </asp:Content>
    