//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Definicoes.Financeiro;
using Benner.Corporativo.Definicoes.Tributos.ServiceInterface;
using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Common.Services;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using Ninject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class ItensSpedEdicaoItensPage : WesPage
{
    [Inject]
    public ISessionVars SessionVars { get; set; }


    protected void Page_Load(object sender, System.EventArgs e)
    {
        ITENSDODOCUMENTO.CommandExecute += ITENSDODOCUMENTO_CommandExecute;
        VisualizacaoComandosConfirmarBloquear();
    }

    private void ITENSDODOCUMENTO_CommandExecute(object sender, GridCommandExecuteArgs e)
    {
        if (e.Command.Name == "CMD_CONFIRMAR")
        {
            var itensSpedService = BusinessComponent.CreateProxyInstance<ITributosDocumentoItensSpedService>();
            var handleDoc = SessionVars.GetSessionVar("HANDLEDOCITENSSPED").ToInt();
            itensSpedService.ConfirmarAlteracoes(handleDoc);
        }
    }


    private void VisualizacaoComandosConfirmarBloquear()
    {
        var handleDoc = SessionVars.GetSessionVar("HANDLEDOCITENSSPED").ToInt();
        var entidade = FNDocumento.Get(handleDoc);
        

        if (entidade != null)
        {
            var comandosVisivel = entidade.EstaBloqueado();
            var confirmar = ITENSDODOCUMENTO.EntityViewCommands.Commands.Find(x => x.Name.Equals("CMD_CONFIRMAR"));
            if (confirmar != null)
                confirmar.Visible = comandosVisivel;

            var novo = ITEMDODOCUMENTO.EntityViewCommands.Commands.Find(x => x.Name.Equals("New"));
            var salvar = ITEMDODOCUMENTO.EntityViewCommands.Commands.Find(x => x.Name.Equals("Save"));
            var editar = ITEMDODOCUMENTO.EntityViewCommands.Commands.Find(x => x.Name.Equals("Edit"));
            var deletar = ITEMDODOCUMENTO.EntityViewCommands.Commands.Find(x => x.Name.Equals("Delete"));

            if (novo != null)
                novo.Visible = comandosVisivel;
            if (salvar != null)
                salvar.Visible = comandosVisivel;
            if (editar != null)
                editar.Visible = comandosVisivel;
            if (confirmar != null)
                deletar.Visible = comandosVisivel;

        }

    }
}
