//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Common.Security;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using IronPython.Runtime.Operations;
using SK.Integracoes.Benner.Services;
using SM.Crm.Definicoes.Entidades;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class KCrmTiposrecursospessoaBennerGridPage : WesPage
{
    private ContratosService contratos;

    public KCrmTiposrecursospessoaBennerGridPage()
    {
        contratos = new ContratosService(BennerContext.Administration.GetConfigurationParameter(BennerContext.Administration.BServerSystemName, "SINCKINTEGRACAOERPBASEURL", ConfigurationParameterType.System),
            BennerContext.Administration.GetConfigurationParameter(BennerContext.Administration.BServerSystemName, "SINCKINTEGRACAOERPUSER", ConfigurationParameterType.System),
            Scramble.ScrambleText(BennerContext.Administration.GetConfigurationParameter(BennerContext.Administration.BServerSystemName, "SINCKINTEGRACAOERPPASSWORD", ConfigurationParameterType.System)));
    }

    protected void Page_Load(object sender, System.EventArgs e)
    {
        var handle = K_VERTICAL.GetEntityHandle();

        if(null == handle.NullableValue)
        {
            var link = this.GetLinkDefinition();
            var parameters = link.Parameters.Values;

            foreach(var parameter in parameters)
            {
                var teste = parameter as Benner.Tecnologia.Common.WhereClause;
                if (null == teste)
                    continue;
                else
                {
                    handle = new Handle(teste.Parameters.FirstOrDefault().Value.ToString());
                    break;
                }
            }
        }

        var vertical = CrmPessoaVertical.Get(handle);

        if (!Page.IsPostBack)
            PrintaGrid(vertical.Cnpj.Instance.CNPJ);
    }

    protected void GrdContratos_RowCreated(object sender, GridViewRowEventArgs e)
    {
        if (e.Row.RowType == DataControlRowType.DataRow)
        {
            e.Row.Attributes["onclick"] = Page.ClientScript.GetPostBackClientHyperlink(GrdContratos, "Select$" + e.Row.RowIndex);
        }
    }

    protected void GrdContratos_RowDataBound(object sender, GridViewRowEventArgs e)
    {
        if (e.Row.RowType == DataControlRowType.DataRow)
        {
            EntityBase entity = e.Row.DataItem as EntityBase;

            // Obtém o número do contrato da entidade
            string numeroContrato = entity.Fields["Numero do Contrato"].ToString();

            // Define o ID da linha com o número do contrato
            e.Row.Attributes["id"] = numeroContrato;
        }
    }

    protected void GrdContratos_RowCommand(object sender, GridViewCommandEventArgs e)
    {
        if (e.CommandName == "Select")
        {
            int rowIndex = Convert.ToInt32(e.CommandArgument);
            GridViewRow row = GrdContratos.Rows[rowIndex];
            string numeroContrato = row.Cells[4].Text;
            PrintaGridFilho(numeroContrato);
        }
    }

    private void PrintaGrid(string PessoaCnpj)
    {
        //var capas = contratos.GetCapasPorCnpjCpf("21.228.754/0001-73");
        var capas = contratos.GetCapasPorCnpjCpf(PessoaCnpj);

        Entities<EntityBase> entities = new Entities<EntityBase>();

        foreach (var capa in capas)
        {
            EntityBase entity = new EntityBase();

            entity.Fields.Add("CNPJ ou CPF", capa.CnpjCpf);
            entity.Fields.Add("Empresa", capa.Contratado);
            entity.Fields.Add("Inicio da Vigência", Convert.ToDateTime(capa.InicioVigencia).ToShortDateString());
            entity.Fields.Add("Término da Vigência", Convert.ToDateTime(capa.TerminoVigencia).ToShortDateString());
            entity.Fields.Add("Numero do Contrato", capa.NumeroContrato);
            entity.Fields.Add("Status", capa.Status);
            entity.Fields.Add("Valor Total", string.Format(CultureInfo.GetCultureInfo("pt-BR"), "{0:C}", Convert.ToDecimal(capa.ValorTotal)));

            entities.Add(entity);
        }

        GrdContratos.DataSource = entities;
        GrdContratos.DataBind();
        GrdContratos.ApplyMetronicStyle();
    }

    private void PrintaGridFilho(string numeroContrato)
    {
        // Chame o método contratos.GetItensContrato() passando o número do contrato
        var itensContrato = contratos.GetItensContrato(numeroContrato);

        // Popule o GridView GrdItensContrato com os itens do contrato
        Entities<EntityBase> itens = new Entities<EntityBase>();

        foreach (var item in itensContrato)
        {
            EntityBase entityItem = new EntityBase();
            entityItem.Fields.Add("Numero do Contrato", item.NumeroContrato);
            entityItem.Fields.Add("Produto", item.Produto);
            entityItem.Fields.Add("Quantidade", item.Quantidade);
            entityItem.Fields.Add("Unidade", item.Unidade);
            entityItem.Fields.Add("Valor Unitário", string.Format(CultureInfo.GetCultureInfo("pt-BR"), "{0:C}", Convert.ToDecimal(item.ValorUnitario)));
            entityItem.Fields.Add("Valor Total", string.Format(CultureInfo.GetCultureInfo("pt-BR"), "{0:C}", Convert.ToDecimal(item.ValorTotal)));
            entityItem.Fields.Add("Familia", item.Familia);
            itens.Add(entityItem);
        }

        GrdItensContrato.DataSource = itens;
        GrdItensContrato.DataBind();
        GrdItensContrato.ApplyMetronicStyle();
    }
}
