//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Comum;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using Benner.Tecnologia.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class GestaoCobrancaParametrosPage : WesPage
{

    protected override void OnLoad(EventArgs e)
    {
        base.OnLoad(e);
        CONTAS.CommandExecute += CONTAS_CommandExecute;
        CONTAS.CommandExecuted += CONTAS_CommandExecuted;
    }

    protected override void OnPreRender(EventArgs e)
    {
        base.OnPreRender(e);
        CONTAS.DataLoad();
        CONTAS.FormDefinition.Commands["New"].Visible = FILIAIS.GetEntityHandle().IsReallyValid() && CONTAS.GetEntity() == null;
    }

    private void CONTAS_CommandExecute(object sender, FormCommandExecuteArgs e)
    {
        switch (e.CommandName)
        {
            case "Delete":
                FILIAIS.DataLoad();
                FILIAIS.DeselectAllRows();
                FILIAIS.DeselectEntity();

                FILIAIS.SelectRowByHandle(e.Entity["FILIAL"].GetInt64());

                break;
        }
    }

    private void CONTAS_CommandExecuted(object sender, FormCommandExecuteArgs e)
    {
        switch(e.CommandName)
        {
            case "Save":
			case "Cancel":
                FILIAIS.DataLoad();
                FILIAIS.SelectRowByHandle(e.Entity["FILIAL"].GetInt64());
                break;
        }
    }

    protected override void OnLoadComplete(EventArgs e)
    {
        base.OnLoadComplete(e);
        FILIAIS.ForceUpdate();
        CONTAS.ForceUpdate();
    }
}
