<%@ Page Title="Mapa de análise de cotações" Language="C#" Inherits="Benner.Corporativo.Wes.WebApp.aga.a.suprimentos.cotacoes.MapaAnaliseCotacoes" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:HtmlPanel runat="server" ID="PAINEL_PRINCIPAL_COMANDO_FLAG_E_TITULO" Title="GERAÇÃO DO MAPA DE ANÁLISE DE PREÇOS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Fixed" HtmlBase64="PGRpdiBjbGFzcz0icm93IiBpZD0iREVTQ1JJQ0FPX0FOQUxJU0VfQ09UQUNPRVMiPgogICAgPGRpdiBjbGFzcz0ibm90ZSBub3RlLWluZm8iIHN0eWxlPSJmb250LXNpemU6MTJweDsiPgogICAgICAgIEVzdGUgcmVsYXTDs3JpbyBtb3N0cmEgbnVtYSBncmFkZSBhcyBjb3Rhw6fDtWVzIGRlIDxzdHJvbmc+YXTDqSBxdWF0cm8gZm9ybmVjZWRvcmVzPC9zdHJvbmc+LCBwYXJhIG9zIHByb2R1dG9zIGVzY29saGlkb3MgYSBzZWd1aXIuIAogICAgICAgIDxici8+CiAgICAgICAgUGFyYSBjYWRhIGZvcm5lY2Vkb3IsIHRhbWLDqW0gc2Vyw6NvIGV4aWJpZG9zIG9zIGRpYXMgcGFyYSBlbnRyZWdhIGUgY29uZGnDp8O1ZXMgZGUgcGFnYW1lbnRvLiAKICAgICAgICA8YnIvPgogICAgICAgIEEgY290YcOnw6NvIHN1Z2VyaWRhIG91IGVzY29saGlkYSBhcGFyZWNlIGNvbSAiPHN0cm9uZz4qPC9zdHJvbmc+IiBqdW50byBhbyB2YWxvci4gUXVhbmRvIG7Do28gZm9yIHN1Z2VyaWRhIHBlbG8gc2lzdGVtYSBvIG1vdGl2byDDqSBsaXN0YWRvLgogICAgICAgIDxici8+CiAgICAgICAgw4kgZXhpYmlkYSB1bWEgcmVxdWlzacOnw6NvIHBhaSBwb3IgcMOhZ2luYS4gQXRpdmFuZG8gYSBvcMOnw6NvICJuw6NvIHNlcGFyYXIgcG9yIHJlcXVpc2nDp8OjbyBwYWkiLCBpdGVucyBpZ3VhaXMgc2Vyw6NvIGFncnVwYWRvcyBuYSBtZXNtYSBww6FnaW5hLiAKICAgIDwvZGl2Pgo8L2Rpdj4KPGRpdiBjbGFzcz0icm93Ij4KICAgIDxkaXYgY2xhc3M9ImNvbC1sZy0yIGNvbC1tZC0yIGNvbC1zbS0yIj48YSBpZD0idG9wLUdFUkFSIiBjbGFzcz0iYnRuIGNvbW1hbmQtYWN0aW9uIGN1c3RvbS1hY3Rpb24gYnRuIGNvbW1hbmQtYWN0aW9uIGJsdWUiIHN0eWxlPSIiIGhyZWY9ImphdmFzY3JpcHQ6X19kb1Bvc3RCYWNrKCdjdGwwMCRNYWluJFBST0RVVE9TJywnR0VSQVInKSI+PGkgY2xhc3M9ImZhIGZhLWNoZWNrIGJ0bi1hY3Rpb24iPjwvaT4gR2VyYXI8L2E+PC9kaXY+CiAgICA8ZGl2IGNsYXNzPSJjb2wtbGctMTAgY29sLW1kLTEwIGNvbC1zbS0xMCI+CiAgICAgICAgPGxhYmVsIGRhdGEtdHlwZT0iYm9vbGVhbiI+CiAgICAgICAgICAgIDxsYWJlbCBpZD0iRkxBR19OQU9TRVBBUkFSUE9SUkVRUEFJIiBjbGFzcz0iYm9vbGVhbi1jb250cm9sIG10LWNoZWNrYm94IG10LWNoZWNrYm94LW91dGxpbmUiPgogICAgICAgICAgICAgICAgPGlucHV0IGlkPSJOQU9TRVBBUkFSUE9SUkVRUEFJIiB0eXBlPSJjaGVja2JveCIgbmFtZT0iTkFPU0VQQVJBUlBPUlJFUVBBSSI+CiAgICAgICAgICAgICAgICA8bGFiZWwgZm9yPSJOQU9TRVBBUkFSUE9SUkVRUEFJIj5Ow6NvIHNlcGFyYXJhciBwb3IgcmVxdWlzacOnw6NvIHBhaTwvbGFiZWw+CiAgICAgICAgICAgICAgICA8c3Bhbj48L3NwYW4+CiAgICAgICAgICAgIDwvbGFiZWw+CiAgICAgICAgPC9sYWJlbD4KICAgIDwvZGl2Pgo8L2Rpdj4KCjxzY3JpcHQ+CiAgICAkKCIjREVTQ1JJQ0FPX0FOQUxJU0VfQ09UQUNPRVMiKS50b2dnbGUoJCgiI0VoQW50ZXNHZXJhY2FvT2MiKS52YWwoKSA9PSAiVHJ1ZSIpOwogICAgJCgiI0ZMQUdfTkFPU0VQQVJBUlBPUlJFUVBBSSIpLnRvZ2dsZSgkKCIjRWhBbnRlc0dlcmFjYW9PYyIpLnZhbCgpID09ICJUcnVlIik7Cjwvc2NyaXB0Pg==" PageId="AGA_A_SUPRIMENTOS_COTACOES_MAPAANALISECOTACOES" Level="20" Order="5"  />
        <wes:SimpleGrid runat="server" ID="PRODUTOS" Title="Produtos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="" ChromeState="Fixed" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="PD_PRODUTOVARIACOESMESTRE.MAPA_ANALISE_COTACOES.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="True" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="False" CompanyFilterMode="OnlyCompany" ShowExport="False" UserDefinedDisableRowSelection="False" PageId="AGA_A_SUPRIMENTOS_COTACOES_MAPAANALISECOTACOES" Level="20" Order="10"  />
        </div>
    
        <style>
              #PRODUTOS th, td {
    white-space: nowrap !important;
}
              </style>
      </asp:Content>
    