//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using Controllers.Models.Crm;
using Models.Crm;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class K_CRM_PESSOAOPORTUNIDADESAtivarOportunidadePage : WesPage
{
    
    protected void Page_Load(object sender, System.EventArgs e)
    {
        BtnConfirmar.Click += BtnConfirmar_Click;
        BtnCancelar.Click += BtnCancelar_Click;
    }

    private void BtnCancelar_Click(object sender, EventArgs e)
    {
        this.CloseModal();
        //Response.Redirect("http://localhost:7501");
    }

    private void BtnConfirmar_Click(object sender, EventArgs e)
    {
        try
        {
            K_OPORTUNIDADE.DataLoad();
            new Controllers.Crm.CrmPessoaOportunidadesController().AtivarOportunidade(new BuscaOportunidadeProdutoRequestModel() { Oportunidade = K_OPORTUNIDADE.GetEntity().Handle.Value.ToString() });
            this.CloseModal();

            //Response.Redirect("http://localhost:7501");
        }
        catch(Exception ex)
        {
            throw new BusinessException(ex.Message);
        }
    }
}
