//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using SM.Crm.Definicoes.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class K_CRM_PESSOAOPORTUNIDADESEmitirPropostaPage : WesPage
{
    private string Oportunidade { get;set;}
    private string Vertical { get; set; }
    protected void Page_Load(object sender, System.EventArgs e)
    {
        this.K_EMITIRPROPOSTA.CommandExecute += K_EMITIRPROPOSTA_CommandExecute;
        this.K_EMITIRPROPOSTA.CommandExecuted += K_EMITIRPROPOSTA_CommandExecuted;
        var linkDefinition = this.GetLinkDefinition() as FormLinkDefinition;

        if (null != linkDefinition)
        {
            Oportunidade = null == linkDefinition.Parameters["OPORTUNIDADE"] ? linkDefinition.WhereClause.Parameters[0].Value.ToString() : linkDefinition.Parameters["OPORTUNIDADE"].ToString();
            Vertical = null == linkDefinition.Parameters["VERTICAL"] ? linkDefinition.WhereClause.Parameters[1].Value.ToString() :  linkDefinition.Parameters["VERTICAL"].ToString();
        }
    }

    private void K_EMITIRPROPOSTA_CommandExecute(object sender, FormCommandExecuteArgs e)
    {
        K_EMITIRPROPOSTA_CommandExecuted(sender, e);
    }

    private void K_EMITIRPROPOSTA_CommandExecuted(object sender, FormCommandExecuteArgs e)
    {
        if (e.CommandName == "cmdCustomOk")
        {
            try
            {
                CrmPessoaOportunidades op = CrmPessoaOportunidades.Get(new Handle(Oportunidade));

                CrmPoProposta novaProposta = CrmPoProposta.Create();
                novaProposta.OportunidadeHandle = new Handle(Oportunidade);
                novaProposta.Versao = op.Versao;
                novaProposta.UsuarioEmissaoHandle = BennerContext.Security.GetLoggedUserHandle();
                novaProposta.Tipo = CrmPoPropostaTipoListaItens.ItemPropostaComercial;
                novaProposta.Save();
            }
            catch(Exception ex)
            {
                throw new BusinessException(ex.Message);
            }
        }
    }
}
