//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class K_CRM_PESSOAOPORTUNIDADESformPage : WesPage
{
    
    protected void Page_Load(object sender, System.EventArgs e)
    {
        this.K_OPORTUNIDADE.CommandExecuted += K_OPORTUNIDADE_CommandExecuted;
    }
    private void K_OPORTUNIDADE_CommandExecuted(object sender, FormCommandExecuteArgs e)
    {
        if(e.CommandName == "CmdCustomEdit")
        {
            this.K_OPORTUNIDADE.ChangeMode(BennerFormViewMode.Edit);
        }
        else if(e.CommandName == "CmdCustomSave")
        {
            e.Entity.Save();
            this.K_OPORTUNIDADE.ChangeMode(BennerFormViewMode.ReadOnly);
        }
    }
}
