<%@ Page Title="Oportunidades" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:SimpleGrid runat="server" ID="K_OPORTUNIDADES" Title="Oportunidades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="True" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADES/Resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAOPORTUNIDADES_GRID" Level="50" Order="10"  />
        <wes:SimpleGrid runat="server" ID="K_OPORTUNIDADES_1" Title="Oportunidades" Subtitle="Executivo / Arquiteto" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.EXECUTIVO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="True" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.RESPONSAVEL = @USUARIO OR A.HANDLE IN (SELECT BA.OPORTUNIDADE FROM K_CRM_PESSOAOPORTUNIDADESPROD BA WHERE BA.ARQUITETOSOLUCAO = @USUARIO AND BA.STATUS = 1) " FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADES/Resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAOPORTUNIDADES_GRID" Level="50" Order="20"  />
        <wes:SimpleGrid runat="server" ID="K_OPORTUNIDADES_2" Title="Oportunidades" Subtitle="Head Vertical" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.HEAD_VERTICAL.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.VERTICAL IN (SELECT VERTICAL FROM K_CRM_DIRETORVERTICAL WHERE NOME=@USUARIO)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADES/Resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAOPORTUNIDADES_GRID" Level="50" Order="30"  />
        <wes:SimpleGrid runat="server" ID="K_OPORTUNIDADES_3" Title="Oportunidades" Subtitle="Gerente de Relacionamento" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GER_REL.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.VERTICAL IN (SELECT HANDLE FROM K_CRM_VERTICAL P
JOIN STRING_SPLIT
((SELECT REPLACE(REPLACE(SUBSTRING(K_VERTICALPRODUTO,0, LEN(K_VERTICALPRODUTO)-1), '|', ''),'_',',')
FROM Z_GRUPOUSUARIOS WHERE HANDLE = @usuario), ',') ON VALUE = P.HANDLE)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADES/Resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAOPORTUNIDADES_GRID" Level="50" Order="40"  />
        <wes:SimpleGrid runat="server" ID="K_OPORTUNIDADES_4" Title="Oportunidades" Subtitle="Gerente de Produtos" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GER_PROD.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.VERTICAL IN (SELECT DISTINCT(HANDLE) FROM K_CRM_VERTICAL V
JOIN STRING_SPLIT
((SELECT REPLACE(REPLACE(SUBSTRING(K_VERTICALPRODUTO,0, LEN(K_VERTICALPRODUTO)-1), '|', ''),'_',',')
FROM Z_GRUPOUSUARIOS WHERE HANDLE = @USUARIO), ',') ON VALUE = V.HANDLE)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADES/Resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAOPORTUNIDADES_GRID" Level="50" Order="50"  />
        <wes:SimpleGrid runat="server" ID="K_OPORTUNIDADES_5" Title="Oportunidades" Subtitle="Arquiteto de Soluções" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.ARQUITETO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.VERTICAL IN (SELECT DISTINCT(V.HANDLE) FROM K_CRM_VERTICAL V
LEFT JOIN K_CRM_PESSOAEQUIPEOPORTUNIDADE  E ON E.OPORTUNIDADE = A.HANDLE
LEFT JOIN K_CRM_PESSOAOPORTUNIDADESPROD P ON P.OPORTUNIDADE = A.HANDLE
JOIN STRING_SPLIT
((SELECT REPLACE(REPLACE(SUBSTRING(K_VERTICALPRODUTO,0, LEN(K_VERTICALPRODUTO)-1), '|', ''),'_',',')
FROM Z_GRUPOUSUARIOS WHERE HANDLE = @USUARIO), ',') ON VALUE = V.HANDLE AND (E.USUARIO = @USUARIO OR P.ARQUITETOSOLUCAO = @USUARIO))" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADES/Resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAOPORTUNIDADES_GRID" Level="50" Order="60"  />
        </div>
    
      </asp:Content>
    