<%@ Page Title="Oportunidade" Language="C#" CodeFile="~/Pages/K_CRM_PESSOAOPORTUNIDADES/NovaOportunidadeManual.aspx.cs" Inherits="K_CRM_PESSOAOPORTUNIDADESNovaOportunidadeManualPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="K_OPORTUNIDADE" Title="Oportunidade" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.MANUAL.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="K_PAGES_K_CRM_PESSOAOPORTUNIDADES_NOVAOPORTUNIDADEMANUAL" Level="50" Order="10"  />
        <wes:SimpleGrid runat="server" ID="K_PRODUTOS" Title="Produtos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_OPORTUNIDADE" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADESPROD.MANUAL.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(CODIGO) AND A.VERSAO = @CAMPO(VERSAO) AND A.STATUS IN (1,3)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADESPROD/FormManual.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAOPORTUNIDADES_NOVAOPORTUNIDADEMANUAL" Level="50" Order="20"  />
        <wes:SimpleGrid runat="server" ID="K_ITENS" Title="Itens" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_PRODUTOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADESITENS.MANUAL.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.PRODUTO= @CAMPO(HANDLE) AND A.OPORTUNIDADE = @CAMPO(OPORTUNIDADE) AND A.VERSAO = @CAMPO(VERSAO)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADESITENS/FormManual.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAOPORTUNIDADES_NOVAOPORTUNIDADEMANUAL" Level="50" Order="30"  />
        <wes:SimpleGrid runat="server" ID="K_ESCOPO" Title="Escopo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_ITENS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADESATIV.MANUAL.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.ITEM = @CAMPO(HANDLE)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADESATIV/FormManual.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAOPORTUNIDADES_NOVAOPORTUNIDADEMANUAL" Level="50" Order="40"  />
        <wes:SimpleGrid runat="server" ID="K_ADICIONAIS" Title="Considerações Adicionais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_OPORTUNIDADE" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PO_ADICIONAL.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(HANDLE) AND A.VERSAO = @CAMPO(VERSAO)" FormUrl="~/Pages/KCrmPoAdicional/Form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAOPORTUNIDADES_NOVAOPORTUNIDADEMANUAL" Level="50" Order="50"  />
        <wes:SimpleGrid runat="server" ID="K_ARQUIVOS" Title="Arquivos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_OPORTUNIDADE" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADESDOC.MANUAL.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(HANDLE)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADESDOC/FormManual.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAOPORTUNIDADES_NOVAOPORTUNIDADEMANUAL" Level="50" Order="60"  />
        </div>
    
      </asp:Content>
    