<%@ Page Title="Resumo Oportunidade" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="K_RESUMOOPORTUNIDADE" Title="Resumo Oportunidade" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.RESUMO.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="K_RESUMO_OPORTUNIDADE" Level="50" Order="10"  />
        <wes:SimpleGrid runat="server" ID="K_PRODUTOS" Title="Produtos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOOPORTUNIDADE" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADESPROD.RESUMO.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(HANDLE) AND A.VERSAO = @CAMPO(VERSAO)" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_RESUMO_OPORTUNIDADE" Level="50" Order="20"  />
        <wes:SimpleGrid runat="server" ID="K_ITENS" Title="Itens" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_PRODUTOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADESITENS.RESUMO.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(OPORTUNIDADE) AND A.VERSAO = @CAMPO(VERSAO) AND A.PRODUTO = @CAMPO(HANDLE)" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_RESUMO_OPORTUNIDADE" Level="50" Order="30"  />
        <wes:SimpleGrid runat="server" ID="K_ESCOPO" Title="Escopo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_ITENS" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="K_CRM_PESSOAOPORTUNIDADESATIV.MANUAL.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.ITEM = @CAMPO(HANDLE)" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_RESUMO_OPORTUNIDADE" Level="50" Order="36"  />
        <wes:SimpleGrid runat="server" ID="K_ESCOPO_1" Title="Escopo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOOPORTUNIDADE" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="K_CRM_PO_ESCOPO.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(HANDLE) AND A.VERSAO = @CAMPO(VERSAO)" FormUrl="~/Pages/KCrmPoEscopo/Form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_RESUMO_OPORTUNIDADE" Level="50" Order="36"  />
        <wes:AjaxForm runat="server" ID="K_SAAS" Title="Data Center" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOOPORTUNIDADE" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PO_SAAS.RESUMO.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(HANDLE) AND A.VERSAO = @CAMPO(VERSAO) AND PRODUTO IS NULL" UserDefinedCommandsVisible="True" PageId="K_RESUMO_OPORTUNIDADE" Level="50" Order="40"  />
        <wes:ActionView runat="server" ID="K_MINUTA" Title="Minuta" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="K_RESUMOOPORTUNIDADE" ChromeState="Normal" Controller="CrmPessoaOportunidades" Action="Minuta" PageId="K_RESUMO_OPORTUNIDADE" Level="50" Order="50"  />
        <wes:AjaxForm runat="server" ID="K_DATACENTER" Title="Data Center" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_PRODUTOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PO_SAAS.RESUMO.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="A.PRODUTO = @CAMPO(HANDLE)" UserDefinedCommandsVisible="True" PageId="K_RESUMO_OPORTUNIDADE" Level="50" Order="60"  />
        <wes:SimpleGrid runat="server" ID="K_CONSIDERAESADICIONAIS" Title="Considerações Adicionais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOOPORTUNIDADE" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="K_CRM_PO_ADICIONAL.RESUMO.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(HANDLE)  AND A.VERSAO = @CAMPO(VERSAO)" FormUrl="~/Pages/KCrmPoAdicional/Readonlyform.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_RESUMO_OPORTUNIDADE" Level="50" Order="67"  />
        <wes:SimpleGrid runat="server" ID="K_ANEXOS" Title="Anexos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOOPORTUNIDADE" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="K_CRM_PESSOAOPORTUNIDADESDOC.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(HANDLE)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADESDOC/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_RESUMO_OPORTUNIDADE" Level="50" Order="77"  />
        <wes:SimpleGrid runat="server" ID="K_ANEXOS_1" Title="Anexos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOOPORTUNIDADE" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="K_CRM_PESSOAOPORTUNIDADESDOC.ADM.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(HANDLE) AND A.VERSAO = @CAMPO(VERSAO)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADESDOC/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_RESUMO_OPORTUNIDADE" Level="50" Order="87"  />
        </div>
    
        <script type="text/javascript">
              if(document.getElementById("top-cmdMinuta")){
    document.getElementById("top-cmdMinuta").onclick = function(){
        EmitirResumo();
    }
}
if(document.getElementById("top-cmdReMinuta")){
document.getElementById("top-cmdReMinuta").onclick = function(){
        EmitirResumo();
    }
}

              </script>
      </asp:Content>
    