<%@ Page Title="Indicadores Produção" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="PAINELAGENDAMENTO" Title="Painel Agendamento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="PR_VTFILTROINDICADORES.PAINEL_AGENDAMENTO_COLETA.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="AGA_A_PRODUCAO_INDICADORES" Level="20" Order="5"  />
        <wes:Tile runat="server" ID="ORDENSDEPRODUAOCADASTRADA" Title="Ordens de Produçao Cadastrada" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="PR_ORDENSPRODUCAO_STATUS.DATASOURCE.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 1" CommandName="CMD_ORDENSPRODUCAO_CADASTRADAS" Value="QUANTIDADE" Description="Ordens de Produçao Cadastrada" Icon="fa fa-pencil" Color="blue" ValueAggregation="None" TileType="Default" PageId="AGA_A_PRODUCAO_INDICADORES" Level="20" Order="10"  />
        <wes:Tile runat="server" ID="ORDENSPRODUOEMAPROVAO" Title="Ordens Produção Em Aprovação" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="PR_ORDENSPRODUCAO_STATUS.DATASOURCE.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 6" CommandName="CMD_ORDENS_PENDENTES" Value="QUANTIDADE" Description="Ordens Produção Em Aprovação" Icon="fa fa-plus" Color="green-meadow" ValueAggregation="None" TileType="Default" PageId="AGA_A_PRODUCAO_INDICADORES" Level="20" Order="20"  />
        <wes:Tile runat="server" ID="ORDENSPRODUOAPROVADAS" Title="Ordens Produção Aprovadas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="PR_ORDENSPRODUCAO_STATUS.DATASOURCE.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 2" CommandName="CMD_ORDENS_APROVADAS" Value="QUANTIDADE" Description="Ordens Produção Aprovadas" Icon="fa fa-check" Color="green" ValueAggregation="None" TileType="Default" PageId="AGA_A_PRODUCAO_INDICADORES" Level="20" Order="30"  />
        <wes:Tile runat="server" ID="APONTAMENTOSPENDENTES" Title="Apontamentos Pendentes" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="PR_APONTAMENTOS_PENDENTES.DATASOURCE.GRID" CompanyFilterMode="None" CommandName="CMD_APONTAMENTOS_PENDENTES" Value="QUANTIDADE" Description="Apontamentos Pendentes" Icon="fa fa-times" Color="red" ValueAggregation="None" TileType="Default" PageId="AGA_A_PRODUCAO_INDICADORES" Level="20" Order="40"  />
        <wes:AmCharts runat="server" ID="ORDENSPRODUO" Title="Ordens Produção" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="PR_ORDENSPRODUCAO_GRAFICO_12MESES.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" ChartType="Area" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsImV4cG9ydCI6eyJlbmFibGVkIjp0cnVlfSwiY2F0ZWdvcnlGaWVsZCI6ImNvbXBldGVuY2lhLnRvdWkiLCJzdGFydER1cmF0aW9uIjoxLCJjYXRlZ29yeUF4aXMiOnsiZ3JpZFBvc2l0aW9uIjoic3RhcnQiLCJsYWJlbFJvdGF0aW9uIjoxNX0sImdyYXBocyI6W3sibGFiZWxUZXh0IjoiIiwiYmFsbG9vblRleHQiOiJbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtMSIsInRpdGxlIjoiQ29uZmlybWFkYXMiLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJjb25maXJtYWRhcyIsInR5cGUiOiJsaW5lIiwiZmlsbEFscGhhcyI6MC4zLCJidWxsZXQiOiJyb3VuZCIsImxpbmVBbHBoYSI6MH0seyJiYWxsb29uVGV4dCI6IltbdmFsdWVdXSIsImxhYmVsVGV4dCI6IiIsImlkIjoic2VyaWUtMTYyOTc0Mjk2MTAzOCIsInRpdGxlIjoiRW5jZXJyYWRhcyIsInZhbHVlRmllbGQiOiJlbmNlcnJhZGFzIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ0eXBlIjoibGluZSIsImJ1bGxldCI6InJvdW5kIiwibGluZUFscGhhIjowLCJmaWxsQWxwaGFzIjowLjd9XSwidmFsdWVBeGVzIjpbeyJpZCI6IlZhbHVlQXhpcy0xIiwidGl0bGUiOiJRdWFudGlkYWRlIn1dLCJsZWdlbmQiOnsiZW5hYmxlZCI6dHJ1ZSwicG9zaXRpb24iOiJib3R0b20iLCJ1c2VHcmFwaFNldHRpbmdzIjp0cnVlfSwidmVyc2lvbiI6IjQifQ==" PageId="AGA_A_PRODUCAO_INDICADORES" Level="20" Order="50"  />
        <wes:AmCharts runat="server" ID="CUSTOPRODUO" Title="Custo produção" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="PR_ORDENSPRODUCAO_GRAFICO_12MESES.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" ChartType="Area" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsImV4cG9ydCI6eyJlbmFibGVkIjp0cnVlfSwiY2F0ZWdvcnlGaWVsZCI6ImNvbXBldGVuY2lhLnRvdWkiLCJzdGFydER1cmF0aW9uIjoxLCJjYXRlZ29yeUF4aXMiOnsiZ3JpZFBvc2l0aW9uIjoic3RhcnQifSwiZ3JhcGhzIjpbeyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6IltbY2F0ZWdvcnldXSA6IFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC0xIiwidGl0bGUiOiJQcmV2aXN0byIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwidmFsdWVGaWVsZCI6ImN1c3RvcHJldmlzdG8iLCJ0eXBlIjoibGluZSIsImZpbGxBbHBoYXMiOjAuMywiYnVsbGV0Ijoicm91bmQifSx7ImJhbGxvb25UZXh0IjoiW1tjYXRlZ29yeV1dIDogW1t2YWx1ZV1dIiwibGFiZWxUZXh0IjoiIiwiaWQiOiJzZXJpZS0xNjM1NDQ5NTExMzI5IiwidGl0bGUiOiJSZWFsaXphZG8iLCJ2YWx1ZUZpZWxkIjoiY3VzdG9yZWFsaXphZG8iLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInR5cGUiOiJsaW5lIiwiYnVsbGV0Ijoicm91bmQiLCJsaW5lQWxwaGEiOjAsImZpbGxBbHBoYXMiOjAuNywiZmlsbENvbG9ycyI6IiNmMjY4NjgiLCJsaW5lQ29sb3IiOiIjZjI2ODY4IiwiYnVsbGV0Q29sb3IiOiIjZjI2ODY4In0seyJiYWxsb29uVGV4dCI6IltbY2F0ZWdvcnldXSA6IFtbdmFsdWVdXSIsImxhYmVsVGV4dCI6IiIsImlkIjoic2VyaWUtMTYzNTQ0OTU3NDAzMyIsInRpdGxlIjoiUGFkcmFvIiwidmFsdWVGaWVsZCI6ImN1c3RvcGFkcmFvIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ0eXBlIjoibGluZSIsImJ1bGxldCI6InJvdW5kIiwibGluZUFscGhhIjowLCJmaWxsQWxwaGFzIjowLjcsImZpbGxDb2xvcnMiOiIjYmI2OGQ0IiwibGluZUNvbG9yIjoiI2JiNjhkNCIsImJ1bGxldENvbG9yIjoiI2JiNjhkNCJ9XSwidmFsdWVBeGVzIjpbeyJpZCI6IlZhbHVlQXhpcy0xIiwidGl0bGUiOiIifV0sImxlZ2VuZCI6eyJlbmFibGVkIjp0cnVlLCJwb3NpdGlvbiI6ImJvdHRvbSIsInVzZUdyYXBoU2V0dGluZ3MiOnRydWV9LCJ2ZXJzaW9uIjoiNCIsInJvdGF0ZSI6ZmFsc2V9" PageId="AGA_A_PRODUCAO_INDICADORES" Level="20" Order="60"  />
        </div>
    
      </asp:Content>
    