//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Cloud;
using Benner.Corporativo.Definicoes.Administracao;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class cadastroempresaPage : WesPage
{
    protected override void OnInit(EventArgs e)
    {
        base.OnInit(e);

        FORMDADOSDAEMPRESA.CommandExecuted += FORMDADOSDAEMPRESA_CommandExecuted;
    }

    protected override void OnPreRender(EventArgs e)
    {
        FORMDADOSDAEMPRESA.EnsureDataLoad();

        var entity = FORMDADOSDAEMPRESA.GetEntity();
        if (entity != null)
            FORMDADOSDAEMPRESA.CanInsert = false;

        base.OnPreRender(e);
    }

    private void FORMDADOSDAEMPRESA_CommandExecuted(object sender, FormCommandExecuteArgs e)
    {
        if (e.CommandName == PredefinedAction.ActionType.Save.ToString())
        {
            var filial = e.Entity;

            var empresa = Empresas.Get(Company.Current.Handle, GetMode.Edit);

            empresa.Cgc = filial.Properties[Filiais.FieldNames.Cgc].GetString();
            var codigoCnae = filial.Properties[Filiais.FieldNames.CodigoCnae].GetInt64();
            if (codigoCnae > 0)
                empresa.CodigoCnae.Handle = codigoCnae;
            var dataRegistro = filial.Properties[Filiais.FieldNames.DataRegistro].GetDateTime();
            if (dataRegistro != null)
                empresa.DataRegistro = dataRegistro;
            empresa.NomeFantasia = filial.Properties[Filiais.FieldNames.RazaoSocial].GetString();
            var inscricaoEstadual = filial.Properties[Filiais.FieldNames.InscricaoEstadual].GetString();
            if (!string.IsNullOrEmpty(inscricaoEstadual))
                empresa.InscricaoEstadual = inscricaoEstadual;
            var inscricaoMunicipal = filial.Properties[Filiais.FieldNames.InscricaoMunicipal].GetString();
            if (!string.IsNullOrEmpty(inscricaoMunicipal))
                empresa.InscricaoMunicipal = inscricaoMunicipal;
            // regime especial tributacao
            // simples nacional
            empresa.Cep = filial.Properties[Filiais.FieldNames.Cep].GetString();
            empresa.Pais.Handle = filial.Properties[Filiais.FieldNames.Pais].GetInt64();
            empresa.Estado.Handle = filial.Properties[Filiais.FieldNames.Estado].GetInt64();
            empresa.Municipio.Handle = filial.Properties[Filiais.FieldNames.Municipio].GetInt64();
            empresa.Bairro = filial.Properties[Filiais.FieldNames.Bairro].GetString();
            empresa.Logradouro = filial.Properties[Filiais.FieldNames.Logradouro].GetString();
            // número
            // complemento
            var correioEletronico = filial.Properties[Filiais.FieldNames.CorreioEletronico].GetString();
            if (!string.IsNullOrEmpty(correioEletronico))
                empresa.CorreioEletronico = correioEletronico;
            var telefone = filial.Properties[Filiais.FieldNames.Telefone].GetString();
            if (!string.IsNullOrEmpty(telefone))
                empresa.Telefone = telefone;

            empresa.Save();
        }
    }
}
