<%@ Page Title="Inclusões Manuais" Language="C#" Inherits="PortalReinf.a.Principal.Tabelas.InclusoesManuaisPage,Benner.Corporativo.Wes.WebApp" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="COMPETNCIA_1" Title="Inclusões manuais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_COPETENCIAWIDGET.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="R1050TABELADEENTIDADESLIGADAS" Title="R-1050 - Tabela de Entidades Ligadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_R1050.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AUDITORIA IN (SELECT AUDITORIAS.HANDLE
                                FROM REINF_AUDITORIAS AUDITORIAS
                                   JOIN REINF_COMPETENCIAS COMPETENCIAS ON COMPETENCIAS.HANDLE = AUDITORIAS.COMPETENCIA
                              WHERE COMPETENCIAS.COMPETENCIA = @CAMPO(COMPETENCIA))" FormUrl="~/PortalReinf/a/Registros/Cadastro/R1050.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="16"  />
        <wes:SimpleGrid runat="server" ID="R1070TABELASDEPROCESSOSADMINISTRATIVOSJUDICIAIS" Title="R-1070 - Tabela de processos administrativos/judiciais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_R1070.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.AUDITORIA IN (SELECT AUDITORIAS.HANDLE
                                FROM REINF_AUDITORIAS AUDITORIAS
                                   JOIN REINF_COMPETENCIAS COMPETENCIAS ON COMPETENCIAS.HANDLE = AUDITORIAS.COMPETENCIA
                              WHERE COMPETENCIAS.COMPETENCIA = @CAMPO(COMPETENCIA))" FormUrl="~/PortalReinf/a/Registros/Cadastro/R1070.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="R2010CONTRIBUIOPREVIDENCIRIASERVIOSTOMADOS" Title="R-2010 - Retenção contribuição previdenciária - Serviços tomados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_R2010.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AUDITORIA IN (SELECT AUDITORIAS.HANDLE
                                FROM REINF_AUDITORIAS AUDITORIAS
                                   JOIN REINF_COMPETENCIAS COMPETENCIAS ON COMPETENCIAS.HANDLE = AUDITORIAS.COMPETENCIA
                              WHERE COMPETENCIAS.COMPETENCIA = @CAMPO(COMPETENCIA))" FormUrl="~/PortalReinf/a/Registros/Cadastro/R2010.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="R2020CONTRIBUIOPREVIDENCIRIASERVIOSPRESTADOS" Title="R-2020 - Retenção contribuição previdenciária - Serviços prestados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_R2020.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AUDITORIA IN (SELECT AUDITORIAS.HANDLE
                                FROM REINF_AUDITORIAS AUDITORIAS
                                   JOIN REINF_COMPETENCIAS COMPETENCIAS ON COMPETENCIAS.HANDLE = AUDITORIAS.COMPETENCIA
                              WHERE COMPETENCIAS.COMPETENCIA = @CAMPO(COMPETENCIA))" FormUrl="~/PortalReinf/a/Registros/Cadastro/R2020.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="R2030RECURSOSRECEBIDOSPORASSOCIAODESPORTIVA" Title="R-2030 - Recursos recebidos por associação desportiva" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_R2030.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AUDITORIA IN (SELECT AUDITORIAS.HANDLE
                                FROM REINF_AUDITORIAS AUDITORIAS
                                   JOIN REINF_COMPETENCIAS COMPETENCIAS ON COMPETENCIAS.HANDLE = AUDITORIAS.COMPETENCIA
                              WHERE COMPETENCIAS.COMPETENCIA = @CAMPO(COMPETENCIA))" FormUrl="~/PortalReinf/a/Registros/Cadastro/R2030.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="50"  />
        <wes:SimpleGrid runat="server" ID="R2040RECURSOSREPASSADOSPARAASSOCIAODESPORTIVA" Title="R-2040 - Recursos repassados para associação desportiva" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_R2040.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AUDITORIA IN (SELECT AUDITORIAS.HANDLE
                                FROM REINF_AUDITORIAS AUDITORIAS
                                   JOIN REINF_COMPETENCIAS COMPETENCIAS ON COMPETENCIAS.HANDLE = AUDITORIAS.COMPETENCIA
                              WHERE COMPETENCIAS.COMPETENCIA = @CAMPO(COMPETENCIA))" FormUrl="~/PortalReinf/a/Registros/Cadastro/R2040.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="60"  />
        <wes:SimpleGrid runat="server" ID="R2050COMERCIALDEPRODUOPARAPRODUTORRURALPJAGROINDSTRIA" Title="R-2050 - Comercialização da produção por produtor rural PJ/Agroindústria" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_R2050.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AUDITORIA IN (SELECT AUDITORIAS.HANDLE
                                FROM REINF_AUDITORIAS AUDITORIAS
                                   JOIN REINF_COMPETENCIAS COMPETENCIAS ON COMPETENCIAS.HANDLE = AUDITORIAS.COMPETENCIA
                              WHERE COMPETENCIAS.COMPETENCIA = @CAMPO(COMPETENCIA))" FormUrl="~/PortalReinf/a/Registros/Cadastro/R2050.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="70"  />
        <wes:SimpleGrid runat="server" ID="R2055AQUISIODEPRODUTORRURAL" Title="R-2055 - Aquisição de Produtor Rural" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_R2055.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AUDITORIA IN (SELECT AUDITORIAS.HANDLE
                                FROM REINF_AUDITORIAS AUDITORIAS
                                   JOIN REINF_COMPETENCIAS COMPETENCIAS ON COMPETENCIAS.HANDLE = AUDITORIAS.COMPETENCIA
                              WHERE COMPETENCIAS.COMPETENCIA = @CAMPO(COMPETENCIA))" FormUrl="~/PortalReinf/a/Registros/Cadastro/R2055.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="78"  />
        <wes:SimpleGrid runat="server" ID="R2060CONTRIBUIOPREVIDNCIASOBRERECEITABRUTACPRB" Title="R-2060 - Contribuição previdenciária sobre a receita bruta - CPRB" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_R2060.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AUDITORIA IN (SELECT AUDITORIAS.HANDLE
                                FROM REINF_AUDITORIAS AUDITORIAS
                                   JOIN REINF_COMPETENCIAS COMPETENCIAS ON COMPETENCIAS.HANDLE = AUDITORIAS.COMPETENCIA
                              WHERE COMPETENCIAS.COMPETENCIA = @CAMPO(COMPETENCIA))" FormUrl="~/PortalReinf/a/Registros/Cadastro/R2060.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="80"  />
        <wes:SimpleGrid runat="server" ID="R3010RECEITADEESPETCULODESPORTIVO" Title="R-3010 - Receita de espetáculo desportivo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_R3010.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AUDITORIA IN (SELECT AUDITORIAS.HANDLE
                                FROM REINF_AUDITORIAS AUDITORIAS
                                   JOIN REINF_COMPETENCIAS COMPETENCIAS ON COMPETENCIAS.HANDLE = AUDITORIAS.COMPETENCIA
                              WHERE COMPETENCIAS.COMPETENCIA = @CAMPO(COMPETENCIA))" FormUrl="~/PortalReinf/a/Registros/Cadastro/R3010.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="90"  />
        <wes:SimpleGrid runat="server" ID="R4010PAGAMENTOSCRDITOSABENEFICIRIOPESSOAFSICA" Title="R-4010 - Pagamentos/Créditos a Beneficiário Pessoa Física" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_R4010.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AUDITORIA IN (SELECT AUDITORIAS.HANDLE
                                FROM REINF_AUDITORIAS AUDITORIAS
                                   JOIN REINF_COMPETENCIAS COMPETENCIAS ON COMPETENCIAS.HANDLE = AUDITORIAS.COMPETENCIA
                              WHERE COMPETENCIAS.COMPETENCIA = @CAMPO(COMPETENCIA))" FormUrl="~/PortalReinf/a/Registros/Cadastro/R4010.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="97"  />
        <wes:SimpleGrid runat="server" ID="R4020PAGAMENTOSCRDITOSABENEFICIRIOPESSOAJURDICA" Title="R-4020 - Pagamentos/Créditos a Beneficiário pessoa Jurídica" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_R4020.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AUDITORIA IN (SELECT AUDITORIAS.HANDLE
                                FROM REINF_AUDITORIAS AUDITORIAS
                                   JOIN REINF_COMPETENCIAS COMPETENCIAS ON COMPETENCIAS.HANDLE = AUDITORIAS.COMPETENCIA
                              WHERE COMPETENCIAS.COMPETENCIA = @CAMPO(COMPETENCIA))" FormUrl="~/PortalReinf/a/Registros/Cadastro/R4020.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="100"  />
        <wes:SimpleGrid runat="server" ID="R4040PAGAMENTOSCRDITOSABENEFICIRIOSNOIDENTIFICADOS" Title="R-4040 - Pagamentos/Créditos a Beneficiários não Identificados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_R4040.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AUDITORIA IN (SELECT AUDITORIAS.HANDLE
                                FROM REINF_AUDITORIAS AUDITORIAS
                                   JOIN REINF_COMPETENCIAS COMPETENCIAS ON COMPETENCIAS.HANDLE = AUDITORIAS.COMPETENCIA
                              WHERE COMPETENCIAS.COMPETENCIA = @CAMPO(COMPETENCIA))" FormUrl="~/PortalReinf/a/Registros/Cadastro/R4040.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="110"  />
        <wes:SimpleGrid runat="server" ID="R4080RETENONORECEBIMENTO" Title="R-4080 - Retenção no Recebimento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINF_R4080.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AUDITORIA IN (SELECT AUDITORIAS.HANDLE
                                FROM REINF_AUDITORIAS AUDITORIAS
                                   JOIN REINF_COMPETENCIAS COMPETENCIAS ON COMPETENCIAS.HANDLE = AUDITORIAS.COMPETENCIA
                              WHERE COMPETENCIAS.COMPETENCIA = @CAMPO(COMPETENCIA))" FormUrl="~/PortalReinf/a/Registros/Cadastro/R4080.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="PORTAL_REINF_INCLUSOES_MANUAIS" Level="20" Order="120"  />
        </div>
    
        <style>
              .col-md-4 {
	width: 50% !important;
}

.col-sm-4 {
	width: 50% !important;
}

              </style>
      </asp:Content>
    