<%@ Page Title="Início" Language="C#" Inherits="PortalReinf.a.Principal.InicioPage,Benner.Corporativo.Wes.WebApp" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="COMPETNCIA" Title="Quantidade de cada evento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="True" CanInsert="True" EntityViewName="REINF_GRAFICO_EVENTO.FORM" FormMode="View" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="False" PageId="PORTAL_REINF_INICIO" Level="20" Order="10"  />
        <wes:AmCharts runat="server" ID="QUANTIDADEDEEVENTOS" Title="Quantidade de eventos" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="7" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMPETNCIA" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINFTABELASEVENTOCONT.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.COMPETENCIA = @Campo(COMPETENCIA)" ChartType="Doughnut" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoicGllIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoiZGVmYXVsdCIsInB1bGxPdXRPbmx5T25lIjp0cnVlLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sInRpdGxlRmllbGQiOiJldmVudG8iLCJ2YWx1ZUZpZWxkIjoicXVhbnRpZGFkZSIsImFscGhhRmllbGQiOiIxMjMxMjMyMTMiLCJiYWxsb29uVGV4dCI6IltbdGl0bGVdXTxicj48c3BhbiBzdHlsZT0nZm9udC1zaXplOjE0cHgnPjxiPltbdmFsdWVdXTwvYj4gKFtbcGVyY2VudHNdXSUpPC9zcGFuPiIsImxhYmVsVGV4dCI6IltbdGl0bGVdXSIsImxhYmVsc0VuYWJsZWQiOnRydWUsImxlZ2VuZCI6eyJlbmFibGVkIjp0cnVlLCJhbGlnbiI6ImNlbnRlciIsIm1hcmtlclR5cGUiOiJjaXJjbGUiLCJwb3NpdGlvbiI6ImxlZnQiLCJsYWJlbFRleHQiOiJbW3RpdGxlXV0iLCJ2YWx1ZVRleHQiOiJbW3BlcmNlbnRzXV0lIn0sImlubmVyUmFkaXVzIjoiNDAlIiwiYW5nbGUiOjMwLCJkZXB0aDNEIjozMH0=" PageId="PORTAL_REINF_INICIO" Level="20" Order="20"  />
        <wes:AmCharts runat="server" ID="ESTADOSDOSEVENTOS" Title="EstadosDosEventos" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="5" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="QUANTIDADEDEEVENTOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="REINFSITUACAOEVENTOS.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="((@campo(EVENTO) = A.EVENTO) AND (@campo(COMPETENCIA) = A.COMPETENCIA))" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInN0YXJ0RHVyYXRpb24iOjAsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJzaXR1YWNhbyIsImNhdGVnb3J5QXhpcyI6eyJncmlkUG9zaXRpb24iOiJzdGFydCIsImxhYmVsUm90YXRpb24iOjE1fSwiZ3JhcGhzIjpbeyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6IltbY2F0ZWdvcnldXTogW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTEiLCJ0aXRsZSI6InF1YW50aWRhZGUiLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJxdWFudGlkYWRlIiwidHlwZSI6ImNvbHVtbiIsImZpbGxBbHBoYXMiOjEsImxpbmVDb2xvckZpZWxkIjoiY29sb3JhY2FvIiwiY29sb3JGaWVsZCI6ImNvbG9yYWNhbyJ9XSwidmFsdWVBeGVzIjpbeyJpZCI6IlZhbHVlQXhpcy0xIiwidGl0bGUiOiJFdmVudG9zIn1dLCJsZWdlbmQiOnsiZW5hYmxlZCI6ZmFsc2UsInBvc2l0aW9uIjoiYm90dG9tIiwidXNlR3JhcGhTZXR0aW5ncyI6dHJ1ZX0sImFuZ2xlIjozMCwiZGVwdGgzRCI6MzAsInJvdGF0ZSI6ZmFsc2V9" PageId="PORTAL_REINF_INICIO" Level="20" Order="40"  />
        </div>
    
      </asp:Content>
    