//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class K_CRM_METASdashboardPage : WesPage
{
    //protected override 

    protected void Page_Load(object sender, System.EventArgs e)
    {
        //this.K_METATRIMESTRAL.WidgetException += K_METATRIMESTRAL_WidgetException;
        //this.Page.
        //Page.LoadComplete += Page_LoadComplete;
        //this.K_USURIOS.LoadEntityViewComplete += K_USURIOS_LoadEntityViewComplete;
        //this.K_METATRIMESTRAL.LoadEntityViewComplete += K_METATRIMESTRAL_LoadEntityViewComplete;
        //this.K_METAMENSAL.LoadEntityViewComplete += K_METAMENSAL_LoadEntityViewComplete;
        //this.K_USURIOS.Disposed += K_USURIOS_Disposed;
        //var ab = this.K_USURIOS.DataSource;
        //var a = this.K_METATRIMESTRAL;
        //var b = this.K_METAMENSAL;
        //var c = b;
        //this.K_USURIOS.DataSource.Fields["MES"] = "Janeiro";
        //this.K_USURIOS.ForceUpdate();
        //this.K_USURIOS.ChangeMode(BennerFormViewMode.ReadOnly);
        //this.K_USURIOS.ChangeMode(BennerFormViewMode.Edit);
        //this.K_METATRIMESTRAL.ForceUpdate();
        //this.K_METAMENSAL.ForceUpdate();
    }

    //private void K_METATRIMESTRAL_WidgetException(object sender, WidgetExceptionEventArgs e)
    //{
    //    this.K_USURIOS.DataBind();
    //    this.K_METATRIMESTRAL.DataLoad();
    //    this.K_METAMENSAL.DataLoad();

    //    this.K_METATRIMESTRAL.ForceUpdate();
    //    this.K_METAMENSAL.ForceUpdate();
    //}

    private void K_USURIOS_LoadEntityViewComplete(object sender, EventArgs e)
    {
        //this.K_USURIOS.ForceUpdate();
        //this.Validate();
        //this.K_USURIOS.UpdateEntity();
        //this.K_USURIOS.RequiresUpdate("K_USURIOS");
        //this.K_USURIOS.ForceUpdate();
        //this.K_USURIOS.LoadEntityView()
        //this.K_USURIOS.DataBind();
        //this.K_METATRIMESTRAL.DataLoad();
        //this.K_METAMENSAL.DataLoad();

        //this.K_METATRIMESTRAL.ForceUpdate();
        //this.K_METAMENSAL.ForceUpdate();
    }

    //private void K_USURIOS_Disposed(object sender, EventArgs e)
    //{
    //    this.K_USURIOS.DataBind();
    //    this.K_METATRIMESTRAL.DataLoad();
    //    this.K_METAMENSAL.DataLoad();

    //    this.K_METATRIMESTRAL.ForceUpdate();
    //    this.K_METAMENSAL.ForceUpdate();
    //}

    //private void K_METAMENSAL_LoadEntityViewComplete(object sender, EventArgs e)
    //{
    //    this.K_USURIOS.DataBind();
    //    this.K_METATRIMESTRAL.DataLoad();
    //    this.K_METAMENSAL.DataLoad();

    //    this.K_METATRIMESTRAL.ForceUpdate();
    //    this.K_METAMENSAL.ForceUpdate();
    //}

    //private void K_METATRIMESTRAL_LoadEntityViewComplete(object sender, EventArgs e)
    //{
    //    this.K_USURIOS.DataBind();
    //    this.K_METATRIMESTRAL.DataLoad();
    //    this.K_METAMENSAL.DataLoad();

    //    this.K_METATRIMESTRAL.ForceUpdate();
    //    this.K_METAMENSAL.ForceUpdate();
    //}

    //private void Page_LoadComplete(object sender, EventArgs e)
    //{
    //    var a = this.K_USURIOS.DataSource;
    //    var b = this.K_METATRIMESTRAL;
    //    var c = b;
    //    //this.K_USURIOS.ForceUpdate();
    //    //this.K_METATRIMESTRAL.ForceUpdate();
    //    //this.K_METAMENSAL.ForceUpdate();
    //}
}
