<%@ Page Title="Dashboard - Metas (Revenda)" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:Tile runat="server" ID="K_METAANUAL" Title="Meta Anual" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTRODEUSURIOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_META_VENDA_V1.DATASOURCE.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClauseTotalValue="YEAR(C.DATA) = YEAR(GETDATE()) AND  ( (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND B.FILIAL = @FILIAL) OR ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  B.FILIAL &lt;&gt; @FILIAL))
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO NOT IN ( @CAMPO(USUARIOS))
)" CriteriaWhereClause="YEAR(C.DATA) = YEAR(GETDATE()) AND  ( (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND B.FILIAL = @FILIAL) OR ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  B.FILIAL &lt;&gt; @FILIAL))
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO NOT IN ( @CAMPO(USUARIOS))
)" Status="PLANEJADO_MONEY" TotalValue="PLANEJADO" ValueFormat="C" Value="REALIZADO" Description="Meta Anual" Icon="fa fa-check" Color="green" ValueAggregation="Sum" TileType="Progress" PageId="K_PAGES_K_CRM_METAS_DASHBOARDREVENDA" Level="50" Order="10"  />
        <wes:Tile runat="server" ID="K_METATRIMESTAL" Title="Meta Trimestal" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTRODEUSURIOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_META_VENDA_V1_TRI.DATASOURCE.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClauseTotalValue="YEAR(C.DATA) = YEAR(GETDATE())
AND  (
      (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND B.FILIAL = @FILIAL) OR
      ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  B.FILIAL &lt;&gt; @FILIAL)
      )
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO NOT IN ( @CAMPO(USUARIOS))
)
AND DATEPART(QUARTER,A.DATA) = DATEPART(QUARTER,GETDATE())" CriteriaWhereClause="YEAR(C.DATA) = YEAR(GETDATE())
AND  (
      (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND B.FILIAL = @FILIAL) OR
      ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  B.FILIAL &lt;&gt; @FILIAL)
      )
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO NOT IN ( @CAMPO(USUARIOS))
)
AND DATEPART(QUARTER,A.DATA) = DATEPART(QUARTER,GETDATE())" Status="PLANEJADO_MONEY" TotalValue="PLANEJADO" ValueFormat="C" Value="REALIZADO" Description="Meta Trimestal" Icon="fa fa-dollar" Color="green" ValueAggregation="Sum" TileType="Progress" PageId="K_PAGES_K_CRM_METAS_DASHBOARDREVENDA" Level="50" Order="20"  />
        <wes:Tile runat="server" ID="K_METAMENSAL" Title="Meta Mensal" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTRODEUSURIOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_META_VENDA_V1_MEN.DATASOURCE.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClauseTotalValue="YEAR(C.DATA) = YEAR(GETDATE())
AND  (
      (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND B.FILIAL = @FILIAL) OR
      ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  B.FILIAL &lt;&gt; @FILIAL)
      )
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO NOT IN ( @CAMPO(USUARIOS))
)
AND MONTH(A.DATA) = MONTH(GETDATE())" CriteriaWhereClause="YEAR(C.DATA) = YEAR(GETDATE())
AND  (
      (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND B.FILIAL = @FILIAL) OR
      ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  B.FILIAL &lt;&gt; @FILIAL)
      )
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO NOT IN ( @CAMPO(USUARIOS))
)
AND MONTH(A.DATA) = MONTH(GETDATE())" Status="PLANEJADO_MONEY" TotalValue="PLANEJADO" ValueFormat="C" Value="REALIZADO" Description="Meta Mensal" Icon="fa fa-dollar" Color="green" ValueAggregation="Sum" TileType="Progress" PageId="K_PAGES_K_CRM_METAS_DASHBOARDREVENDA" Level="50" Order="30"  />
        <wes:Tile runat="server" ID="K_METASECUNDRIAANUAL" Title="Meta Secundária Anual" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTRODEUSURIOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TILE_V1_METASEC_ANUAL.DATASOURCE.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClauseTotalValue="YEAR(C.DATA) = YEAR(GETDATE()) AND  ( (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND B.FILIAL = @FILIAL) OR ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  B.FILIAL &lt;&gt; @FILIAL))
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO NOT IN ( @CAMPO(USUARIOS))
)" CriteriaWhereClause="YEAR(C.DATA) = YEAR(GETDATE()) AND  ( (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND B.FILIAL = @FILIAL) OR ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  B.FILIAL &lt;&gt; @FILIAL))
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO NOT IN ( @CAMPO(USUARIOS))
)" Status="PLANEJADO_MONEY" TotalValue="PLANEJADO" ValueFormat="C" Value="REALIZADO" Description="Meta Secundária Anual" Icon="fa fa-dollar" Color="green" ValueAggregation="Sum" TileType="Progress" PageId="K_PAGES_K_CRM_METAS_DASHBOARDREVENDA" Level="50" Order="40"  />
        <wes:Tile runat="server" ID="K_METASECUNDRIATRIMESTRAL" Title="Meta Secundária Trimestral" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTRODEUSURIOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TILE_V1_METASEC_MES.DATASOURCE.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClauseTotalValue="YEAR(C.DATA) = YEAR(GETDATE())
AND  (
      (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND B.FILIAL = @FILIAL) OR
      ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  B.FILIAL &lt;&gt; @FILIAL)
      )
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO NOT IN ( @CAMPO(USUARIOS))
)
AND DATEPART(QUARTER,A.DATA) = DATEPART(QUARTER,GETDATE())" CriteriaWhereClause="YEAR(C.DATA) = YEAR(GETDATE())
AND  (
      (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND B.FILIAL = @FILIAL) OR
      ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  B.FILIAL &lt;&gt; @FILIAL)
      )
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO NOT IN ( @CAMPO(USUARIOS))
)
AND DATEPART(QUARTER,A.DATA) = DATEPART(QUARTER,GETDATE())" Status="PLANEJADO_MONEY" TotalValue="PLANEJADO" ValueFormat="C" Value="REALIZADO" Description="Meta Secundária Trimestral" Icon="fa fa-dollar" Color="green" ValueAggregation="Sum" TileType="Progress" PageId="K_PAGES_K_CRM_METAS_DASHBOARDREVENDA" Level="50" Order="50"  />
        <wes:Tile runat="server" ID="K_METASECUNDRIAMS" Title="Meta Secundária Mês" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTRODEUSURIOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TILE_V1_METASEC_MES.DATASOURCE.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClauseTotalValue="YEAR(C.DATA) = YEAR(GETDATE())
AND  (
      (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND B.FILIAL = @FILIAL) OR
      ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  B.FILIAL &lt;&gt; @FILIAL)
      )
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO NOT IN ( @CAMPO(USUARIOS))
)
AND MONTH(A.DATA) = MONTH(GETDATE())" CriteriaWhereClause="YEAR(C.DATA) = YEAR(GETDATE())
AND  (
      (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND B.FILIAL = @FILIAL) OR
      ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  B.FILIAL &lt;&gt; @FILIAL)
      )
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.USUARIO NOT IN ( @CAMPO(USUARIOS))
)
AND MONTH(A.DATA) = MONTH(GETDATE())" Status="PLANEJADO_MONEY" TotalValue="PLANEJADO" ValueFormat="C" Value="REALIZADO" Description="Meta Secundária Mês" Icon="fa fa-dollar" Color="green" ValueAggregation="Sum" TileType="Progress" PageId="K_PAGES_K_CRM_METAS_DASHBOARDREVENDA" Level="50" Order="60"  />
        <wes:AjaxForm runat="server" ID="K_FILTRODEUSURIOS" Title="Filtro de usuários" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_VT_USUARIOFILIAL.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="K_PAGES_K_CRM_METAS_DASHBOARDREVENDA" Level="50" Order="70"  />
        <wes:AmCharts runat="server" ID="K_TEMPERATURAMS" Title="Temperatura / Mês" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTRODEUSURIOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_GRAPH_V1_TEMPERATURA.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.DATAFECHAMENTO IS NOT NULL
AND B.GANHA = 'N' AND B.PERDE = 'N' AND B.CANCELA= 'N' AND B.SUSPENDE= 'N'
AND  ( (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND A.FILIAL = @FILIAL) OR ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  A.FILIAL &lt;&gt; @FILIAL)) 
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.RESPONSAVEL IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.RESPONSAVEL NOT IN ( @CAMPO(USUARIOS))
)
" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJtZXMiLCJzdGFydER1cmF0aW9uIjoxLCJjYXRlZ29yeUF4aXMiOnsiZ3JpZFBvc2l0aW9uIjoic3RhcnQifSwiZ3JhcGhzIjpbeyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6Ik5ldXRybyA6IFIkIFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC0xIiwidGl0bGUiOiJOZXV0cm8iLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJuZXV0cm8iLCJ0eXBlIjoiY29sdW1uIiwiZmlsbEFscGhhcyI6MSwiYnVsbGV0Ijoicm91bmQiLCJidWxsZXRCb3JkZXJBbHBoYSI6MSwiYnVsbGV0Q29sb3IiOiIjRkZGRkZGIiwiYnVsbGV0U2l6ZSI6NSwidXNlTGluZUNvbG9yRm9yQnVsbGV0Qm9yZGVyIjp0cnVlLCJuZXdTdGFjayI6dHJ1ZSwiY2x1c3RlcmVkIjpmYWxzZX0seyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6IkZpcm1lIDogUiQgW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTIiLCJ0aXRsZSI6IkZpcm1lIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoiZmlybWUiLCJ0eXBlIjoiY29sdW1uIiwiZmlsbEFscGhhcyI6MSwiYnVsbGV0Ijoicm91bmQiLCJidWxsZXRCb3JkZXJBbHBoYSI6MSwiYnVsbGV0Q29sb3IiOiIjRkZGRkZGIiwiYnVsbGV0U2l6ZSI6NSwidXNlTGluZUNvbG9yRm9yQnVsbGV0Qm9yZGVyIjp0cnVlLCJsaW5lQ29sb3IiOiIjMkVDQzcxIiwiZmlsbENvbG9ycyI6IiMyRUNDNzEiLCJjbHVzdGVyZWQiOmZhbHNlfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiUmlzY28gOiBSJCBbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtMyIsInRpdGxlIjoiUmlzY28iLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJyaXNjbyIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxLCJidWxsZXQiOiJyb3VuZCIsImJ1bGxldEJvcmRlckFscGhhIjoxLCJidWxsZXRDb2xvciI6IiNGRkZGRkYiLCJidWxsZXRTaXplIjo1LCJ1c2VMaW5lQ29sb3JGb3JCdWxsZXRCb3JkZXIiOnRydWUsImxpbmVDb2xvciI6IiNFNzRDM0MiLCJmaWxsQ29sb3JzIjoiI0U3NEMzQyIsImNsdXN0ZXJlZCI6ZmFsc2V9XSwidmFsdWVBeGVzIjpbeyJpZCI6IlZhbHVlQXhpcy0xIiwidGl0bGUiOiIiLCJzdGFja1R5cGUiOiJyZWd1bGFyIn1dLCJjaGFydEN1cnNvciI6eyJjdXJzb3JBbHBoYSI6MCwiem9vbWFibGUiOmZhbHNlfSwibGVnZW5kIjp7ImVuYWJsZWQiOnRydWUsInBvc2l0aW9uIjoiYm90dG9tIiwidXNlR3JhcGhTZXR0aW5ncyI6dHJ1ZX19" PageId="K_PAGES_K_CRM_METAS_DASHBOARDREVENDA" Level="50" Order="75"  />
        <wes:AmCharts runat="server" ID="K_FASEVALOR" Title="Fase / Valor" Subtitle="Privado" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTRODEUSURIOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_V1_FUNIL_FASE_VALOR.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="B.PUBLICOPRIVADO = 2 AND B.PERDE = 'N' AND B.GANHA = 'N' AND B.CANCELA= 'N' AND B.SUSPENDE= 'N' AND  ( (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND A.FILIAL = @FILIAL) OR ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  A.FILIAL &lt;&gt; @FILIAL)) 
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.RESPONSAVEL IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.RESPONSAVEL NOT IN ( @CAMPO(USUARIOS))
)
" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoiZnVubmVsIiwidGhlbWUiOiJsaWdodCIsImJhbGxvb24iOnsiZml4ZWRQb3NpdGlvbiI6dHJ1ZX0sIm5lY2tIZWlnaHQiOiIyMCUiLCJuZWNrV2lkdGgiOiIzMCUiLCJ2YWx1ZUZpZWxkIjoidmFsb3IiLCJ0aXRsZUZpZWxkIjoibm9tZSIsIm1hcmdpblJpZ2h0IjoyNDAsIm1hcmdpbkxlZnQiOjUwLCJzdGFydFgiOjAsImFuZ2xlIjo0MCwiZmlsbEFscGhhcyI6MC45LCJsaW5lQWxwaGEiOjAuMiwibGFiZWxQb3NpdGlvbiI6InJpZ2h0IiwibGFiZWxUZXh0IjoiW1tub21lXV0iLCJiYWxsb29uVGV4dCI6Iltbbm9tZV1dIiwiZXhwb3J0Ijp7ImVuYWJsZWQiOnRydWV9LCJjYXRlZ29yeUZpZWxkIjoibm9tZSJ9" PageId="K_PAGES_K_CRM_METAS_DASHBOARDREVENDA" Level="50" Order="80"  />
        <wes:AmCharts runat="server" ID="K_FASEVALOR_1" Title="FASE / VALOR" Subtitle="Público" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTRODEUSURIOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_V1_FUNIL_FASE_VALOR.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="B.PUBLICOPRIVADO = 1 AND B.PERDE = 'N' AND B.GANHA = 'N' AND B.CANCELA= 'N' AND B.SUSPENDE= 'N' AND  ( (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND A.FILIAL = @FILIAL) OR ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  A.FILIAL &lt;&gt; @FILIAL))
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.RESPONSAVEL IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.RESPONSAVEL NOT IN ( @CAMPO(USUARIOS))
)
" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoiZnVubmVsIiwidGhlbWUiOiJsaWdodCIsImJhbGxvb24iOnsiZml4ZWRQb3NpdGlvbiI6dHJ1ZX0sIm5lY2tIZWlnaHQiOiIyMCUiLCJuZWNrV2lkdGgiOiIzMCUiLCJ2YWx1ZUZpZWxkIjoidmFsb3IiLCJ0aXRsZUZpZWxkIjoibm9tZSIsIm1hcmdpblJpZ2h0IjoyNDAsIm1hcmdpbkxlZnQiOjUwLCJzdGFydFgiOjAsImFuZ2xlIjo0MCwiZmlsbEFscGhhcyI6MC45LCJsaW5lQWxwaGEiOjAuMiwibGFiZWxQb3NpdGlvbiI6InJpZ2h0IiwibGFiZWxUZXh0IjoiW1tub21lXV0iLCJiYWxsb29uVGV4dCI6Iltbbm9tZV1dIiwiZXhwb3J0Ijp7ImVuYWJsZWQiOnRydWV9LCJjYXRlZ29yeUZpZWxkIjoibm9tZSJ9" PageId="K_PAGES_K_CRM_METAS_DASHBOARDREVENDA" Level="50" Order="100"  />
        <wes:AmCharts runat="server" ID="K_ORIGEMMS" Title="Origem / Mês" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTRODEUSURIOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_GRAPH_V1_ORIGEM.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.DATAFECHAMENTO IS NOT NULL
AND B.GANHA = 'N' AND B.PERDE = 'N' AND B.CANCELA= 'N' AND B.SUSPENDE= 'N'
AND  ( (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND A.FILIAL = @FILIAL) OR ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  A.FILIAL &lt;&gt; @FILIAL)) 
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.RESPONSAVEL IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.RESPONSAVEL NOT IN ( @CAMPO(USUARIOS))
)
" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJtZXMiLCJzdGFydER1cmF0aW9uIjoxLCJjYXRlZ29yeUF4aXMiOnsiZ3JpZFBvc2l0aW9uIjoic3RhcnQifSwiZ3JhcGhzIjpbeyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6IlZlbmRhcyBJbnRlcm5hIDogUiQgW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTEiLCJ0aXRsZSI6IlZlbmRhcyBJbnRlcm5hIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoiaW50ZXJuYSIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiSW5ib3VuZCA6IFIkIFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC0yIiwidGl0bGUiOiJJbmJvdW5kIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoiaW5ib3VuZCIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiRXZlbnRvIDogUiQgW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTMiLCJ0aXRsZSI6IkV2ZW50byIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwidmFsdWVGaWVsZCI6ImV2ZW50byIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiSW5kLiBMaXZyZSA6IFIkIFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC00IiwidGl0bGUiOiJJbmQuIExpdnJlIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoiaW5kX2xpdnJlIiwidHlwZSI6ImNvbHVtbiIsImZpbGxBbHBoYXMiOjF9LHsibGFiZWxUZXh0IjoiIiwiYmFsbG9vblRleHQiOiJJbmQuIEJlbm5lciA6IFIkIFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC01IiwidGl0bGUiOiJJbmQuIEJlbm5lciIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwidmFsdWVGaWVsZCI6ImluZF9iZW5uZXIiLCJ0eXBlIjoiY29sdW1uIiwiZmlsbEFscGhhcyI6MX0seyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6IkZhbGUgQ29ub3NjbyA6IFIkIFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC02IiwidGl0bGUiOiJGYWxlIENvbm9zY28iLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJmYWxlIiwidHlwZSI6ImNvbHVtbiIsImZpbGxBbHBoYXMiOjF9LHsibGFiZWxUZXh0IjoiIiwiYmFsbG9vblRleHQiOiJFZGl0YWwgOiBSJCBbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtNyIsInRpdGxlIjoiRWRpdGFsIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoiZWRpdGFsIiwidHlwZSI6ImNvbHVtbiIsImZpbGxBbHBoYXMiOjF9LHsibGFiZWxUZXh0IjoiIiwiYmFsbG9vblRleHQiOiJCYXNlIDogUiQgW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTgiLCJ0aXRsZSI6IkJhc2UiLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJiYXNlIiwidHlwZSI6ImNvbHVtbiIsImZpbGxBbHBoYXMiOjF9XSwiY2hhcnRDdXJzb3IiOnsiY3Vyc29yQWxwaGEiOjAsInpvb21hYmxlIjpmYWxzZX0sInZhbHVlQXhlcyI6W3siaWQiOiJWYWx1ZUF4aXMtMSIsInRpdGxlIjoiIiwic3RhY2tUeXBlIjoicmVndWxhciJ9XSwibGVnZW5kIjp7ImVuYWJsZWQiOnRydWUsInBvc2l0aW9uIjoiYm90dG9tIiwidXNlR3JhcGhTZXR0aW5ncyI6dHJ1ZX19" PageId="K_PAGES_K_CRM_METAS_DASHBOARDREVENDA" Level="50" Order="120"  />
        <wes:AmCharts runat="server" ID="K_VERTICALMS" Title="Vertical / Mês" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTRODEUSURIOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_GRAPH_V1_VERTICAL.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.DATAFECHAMENTO IS NOT NULL
AND D.STATUS = 1
AND B.GANHA = 'N' AND B.PERDE = 'N' AND B.CANCELA= 'N' AND B.SUSPENDE= 'N'
AND  ( (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND A.FILIAL = @FILIAL) OR ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  A.FILIAL &lt;&gt; @FILIAL)) 
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.RESPONSAVEL IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.RESPONSAVEL NOT IN ( @CAMPO(USUARIOS))
)
" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJtZXMiLCJzdGFydER1cmF0aW9uIjoxLCJjYXRlZ29yeUF4aXMiOnsiZ3JpZFBvc2l0aW9uIjoic3RhcnQiLCJsYWJlbFJvdGF0aW9uIjoxNX0sImdyYXBocyI6W3sibGFiZWxUZXh0IjoiIiwiYmFsbG9vblRleHQiOiJSZWMuIEh1bWFub3MgOiBSJCBbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtMSIsInRpdGxlIjoiUmVjLiBIdW0uIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoicmVjdXJzb3NfaHVtYW5vcyIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxLCJidWxsZXQiOiJyb3VuZCIsImJ1bGxldEJvcmRlckFscGhhIjoxLCJidWxsZXRDb2xvciI6IiNGRkZGRkYiLCJidWxsZXRTaXplIjo1LCJ1c2VMaW5lQ29sb3JGb3JCdWxsZXRCb3JkZXIiOnRydWUsIm5ld1N0YWNrIjp0cnVlLCJjbHVzdGVyZWQiOmZhbHNlfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiUHJvZC4gSW5mb21lZCA6IFIkIFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC0yIiwidGl0bGUiOiJQcm9kLiBJbmZvLiIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwidmFsdWVGaWVsZCI6InByb2R1dG9faW5mb21lZCIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxLCJidWxsZXQiOiJyb3VuZCIsImJ1bGxldEJvcmRlckFscGhhIjoxLCJidWxsZXRDb2xvciI6IiNGRkZGRkYiLCJidWxsZXRTaXplIjo1LCJ1c2VMaW5lQ29sb3JGb3JCdWxsZXRCb3JkZXIiOnRydWUsImNsdXN0ZXJlZCI6ZmFsc2V9LHsibGFiZWxUZXh0IjoiIiwiYmFsbG9vblRleHQiOiJCUE8gOiBSJCBbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtMyIsInRpdGxlIjoiQlBPIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoiYnBvIiwidHlwZSI6ImNvbHVtbiIsImZpbGxBbHBoYXMiOjEsImJ1bGxldCI6InJvdW5kIiwiYnVsbGV0Qm9yZGVyQWxwaGEiOjEsImJ1bGxldENvbG9yIjoiI0ZGRkZGRiIsImJ1bGxldFNpemUiOjUsInVzZUxpbmVDb2xvckZvckJ1bGxldEJvcmRlciI6dHJ1ZSwiY2x1c3RlcmVkIjpmYWxzZX0seyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6Ikp1csOtZGljbyA6IFIkIFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC00IiwidGl0bGUiOiJKdXLDrWRpY28iLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJqdXJpZGljbyIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxLCJidWxsZXQiOiJyb3VuZCIsImJ1bGxldEJvcmRlckFscGhhIjoxLCJidWxsZXRDb2xvciI6IiNGRkZGRkYiLCJidWxsZXRTaXplIjo1LCJ1c2VMaW5lQ29sb3JGb3JCdWxsZXRCb3JkZXIiOnRydWUsImNsdXN0ZXJlZCI6ZmFsc2V9LHsibGFiZWxUZXh0IjoiIiwiYmFsbG9vblRleHQiOiJMb2fDrXN0aWNhIDogUiQgW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTUiLCJ0aXRsZSI6IkxvZ8Otc3RpY2EiLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJsb2dpc3RpY2EiLCJ0eXBlIjoiY29sdW1uIiwiZmlsbEFscGhhcyI6MSwiYnVsbGV0Ijoicm91bmQiLCJidWxsZXRCb3JkZXJBbHBoYSI6MSwiYnVsbGV0Q29sb3IiOiIjRkZGRkZGIiwiYnVsbGV0U2l6ZSI6NSwidXNlTGluZUNvbG9yRm9yQnVsbGV0Qm9yZGVyIjp0cnVlLCJjbHVzdGVyZWQiOmZhbHNlfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiVHVyaXNtbyA6IFIkIFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC02IiwidGl0bGUiOiJUdXJpc21vIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoidHVyaXNtbyIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxLCJidWxsZXQiOiJyb3VuZCIsImJ1bGxldEJvcmRlckFscGhhIjoxLCJidWxsZXRDb2xvciI6IiNGRkZGRkYiLCJidWxsZXRTaXplIjo1LCJ1c2VMaW5lQ29sb3JGb3JCdWxsZXRCb3JkZXIiOnRydWUsImNsdXN0ZXJlZCI6ZmFsc2V9LHsibGFiZWxUZXh0IjoiIiwiYmFsbG9vblRleHQiOiJTYcO6ZGUgOiBSJCBbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtNyIsInRpdGxlIjoiU2HDumRlIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoic2F1ZGUiLCJ0eXBlIjoiY29sdW1uIiwiZmlsbEFscGhhcyI6MSwiYnVsbGV0Ijoicm91bmQiLCJidWxsZXRCb3JkZXJBbHBoYSI6MSwiYnVsbGV0Q29sb3IiOiIjRkZGRkZGIiwiYnVsbGV0U2l6ZSI6NSwidXNlTGluZUNvbG9yRm9yQnVsbGV0Qm9yZGVyIjp0cnVlLCJjbHVzdGVyZWQiOmZhbHNlfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiRVJQIDogUiQgW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTgiLCJ0aXRsZSI6IkVSUCIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwidmFsdWVGaWVsZCI6ImVycCIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxLCJidWxsZXQiOiJyb3VuZCIsImJ1bGxldEJvcmRlckFscGhhIjoxLCJidWxsZXRDb2xvciI6IiNGRkZGRkYiLCJidWxsZXRTaXplIjo1LCJ1c2VMaW5lQ29sb3JGb3JCdWxsZXRCb3JkZXIiOnRydWUsImNsdXN0ZXJlZCI6ZmFsc2V9LHsibGFiZWxUZXh0IjoiIiwiYmFsbG9vblRleHQiOiJPdXRyYXMgOiBSJCBbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtOSIsInRpdGxlIjoiT3V0cmFzIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoib3V0cmFzIiwidHlwZSI6ImNvbHVtbiIsImZpbGxBbHBoYXMiOjEsImJ1bGxldCI6InJvdW5kIiwiYnVsbGV0Qm9yZGVyQWxwaGEiOjEsImJ1bGxldENvbG9yIjoiI0ZGRkZGRiIsImJ1bGxldFNpemUiOjUsInVzZUxpbmVDb2xvckZvckJ1bGxldEJvcmRlciI6dHJ1ZSwiY2x1c3RlcmVkIjpmYWxzZX0seyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6IkVBRCA6IFIkIFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC0xMCIsInRpdGxlIjoiRUFEIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoiZWFkIiwidHlwZSI6ImNvbHVtbiIsImZpbGxBbHBoYXMiOjEsImJ1bGxldCI6InJvdW5kIiwiYnVsbGV0Qm9yZGVyQWxwaGEiOjEsImJ1bGxldENvbG9yIjoiI0ZGRkZGRiIsImJ1bGxldFNpemUiOjUsInVzZUxpbmVDb2xvckZvckJ1bGxldEJvcmRlciI6dHJ1ZSwiY2x1c3RlcmVkIjpmYWxzZX0seyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6Ikp1ci4gTGl2cmUgOiBSJCBbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtMTEiLCJ0aXRsZSI6Ikp1ci4gTGl2cmUiLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJqdXJfbGl2cmUiLCJ0eXBlIjoiY29sdW1uIiwiZmlsbEFscGhhcyI6MSwiYnVsbGV0Ijoicm91bmQiLCJidWxsZXRCb3JkZXJBbHBoYSI6MSwiYnVsbGV0Q29sb3IiOiIjRkZGRkZGIiwiYnVsbGV0U2l6ZSI6NSwidXNlTGluZUNvbG9yRm9yQnVsbGV0Qm9yZGVyIjp0cnVlLCJjbHVzdGVyZWQiOmZhbHNlfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiSG9zcC4gTGl2cmUgOiBSJCBbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtMTIiLCJ0aXRsZSI6Ikhvc3AuIExpdnJlIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoiaG9zcF9saXZyZSIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxLCJidWxsZXQiOiJyb3VuZCIsImJ1bGxldEJvcmRlckFscGhhIjoxLCJidWxsZXRDb2xvciI6IiNGRkZGRkYiLCJidWxsZXRTaXplIjo1LCJ1c2VMaW5lQ29sb3JGb3JCdWxsZXRCb3JkZXIiOnRydWUsImNsdXN0ZXJlZCI6ZmFsc2V9XSwidmFsdWVBeGVzIjpbeyJpZCI6IlZhbHVlQXhpcy0xIiwidGl0bGUiOiIiLCJzdGFja1R5cGUiOiJyZWd1bGFyIn1dLCJjaGFydEN1cnNvciI6eyJjdXJzb3JBbHBoYSI6MCwiem9vbWFibGUiOmZhbHNlfSwibGVnZW5kIjp7ImVuYWJsZWQiOnRydWUsInBvc2l0aW9uIjoiYm90dG9tIiwidXNlR3JhcGhTZXR0aW5ncyI6dHJ1ZX19" PageId="K_PAGES_K_CRM_METAS_DASHBOARDREVENDA" Level="50" Order="130"  />
        <wes:AmCharts runat="server" ID="K_PERDIDOMS" Title="Perdido / Mês" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTRODEUSURIOS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_GRAPH_V1_PERDIDO.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.DATAFECHAMENTO IS NOT NULL
AND  ( (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND A.FILIAL = @FILIAL) OR ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  A.FILIAL &lt;&gt; @FILIAL)) 
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.RESPONSAVEL IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND A.RESPONSAVEL NOT IN ( @CAMPO(USUARIOS))
)
" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJtZXMiLCJzdGFydER1cmF0aW9uIjoxLCJjYXRlZ29yeUF4aXMiOnsiZ3JpZFBvc2l0aW9uIjoic3RhcnQifSwiZ3JhcGhzIjpbeyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6IlBlcmRpZG8gOiBSJCBbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtMSIsInRpdGxlIjoiUGVyZGlkbyIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwidmFsdWVGaWVsZCI6InBlcmRlIiwidHlwZSI6ImNvbHVtbiIsImZpbGxBbHBoYXMiOjF9LHsibGFiZWxUZXh0IjoiIiwiYmFsbG9vblRleHQiOiJDYW5jZWxhZG8gOiBSJCBbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtMiIsInRpdGxlIjoiQ2FuY2VsYWRvIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoiY2FuY2VsYSIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiU3VzcGVuc28gOiBSJCBbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtMyIsInRpdGxlIjoiU3VzcGVuc28iLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJzdXNwZW5kZSIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxfV0sImNoYXJ0Q3Vyc29yIjp7ImN1cnNvckFscGhhIjowLCJ6b29tYWJsZSI6ZmFsc2V9LCJ2YWx1ZUF4ZXMiOlt7ImlkIjoiVmFsdWVBeGlzLTEiLCJ0aXRsZSI6IiIsInN0YWNrVHlwZSI6InJlZ3VsYXIifV0sImxlZ2VuZCI6eyJlbmFibGVkIjp0cnVlLCJwb3NpdGlvbiI6ImJvdHRvbSIsInVzZUdyYXBoU2V0dGluZ3MiOnRydWV9fQ==" PageId="K_PAGES_K_CRM_METAS_DASHBOARDREVENDA" Level="50" Order="140"  />
        </div>
    
      </asp:Content>
    