<%@ Page Title="Versionamento Oportunidades" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="K_FORMK_CRM_PESSOAOPORTUNIDADESVERSA" Title="Versionamento Oportunidades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADESVERSA.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="K_PAGES_KCRMPESSOAOPORTUNIDADESVERSAO_FORM" Level="50" Order="100"  />
        <wes:SimpleGrid runat="server" ID="K_PRODUTOS_1" Title="Produtos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FORMK_CRM_PESSOAOPORTUNIDADESVERSA" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADESPROD.RESUMO.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(OPORTUNIDADE) AND A.VERSAO = @CAMPO(VERSAO)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADESPROD/Verticais.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_KCRMPESSOAOPORTUNIDADESVERSAO_FORM" Level="50" Order="126"  />
        <wes:SimpleGrid runat="server" ID="K_ITENS" Title="Itens" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_PRODUTOS_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADESITENS.RESUMO.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(OPORTUNIDADE) AND A.VERSAO = @CAMPO(VERSAO) AND A.PRODUTO = @CAMPO(HANDLE)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADESITENS/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_KCRMPESSOAOPORTUNIDADESVERSAO_FORM" Level="50" Order="133"  />
        <wes:SimpleGrid runat="server" ID="K_ESCOPO_1" Title="Escopo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_ITENS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADESATIV.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.ITEM = @CAMPO(HANDLE)" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_KCRMPESSOAOPORTUNIDADESVERSAO_FORM" Level="50" Order="137"  />
        <wes:SimpleGrid runat="server" ID="K_ESCOPO" Title="Escopo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_PRODUTOS_1" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="K_CRM_PO_ESCOPO.VERSAO.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="(A.OPORTUNIDADE = @CAMPO(OPORTUNIDADE) AND A.VERSAO = @CAMPO(VERSAO) AND A.PRODUTO = @CAMPO(HANDLE)) OR (A.OPORTUNIDADE = @CAMPO(OPORTUNIDADE) AND A.VERSAO = @CAMPO(VERSAO) AND A.PRODUTO IS NULL) " ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_KCRMPESSOAOPORTUNIDADESVERSAO_FORM" Level="50" Order="141"  />
        <wes:AjaxForm runat="server" ID="K_SAAS" Title="Saas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FORMK_CRM_PESSOAOPORTUNIDADESVERSA" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="K_CRM_PO_SAAS.RESUMO.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(OPORTUNIDADE) AND A.VERSAO = @CAMPO(VERSAO)" UserDefinedCommandsVisible="True" PageId="K_PAGES_KCRMPESSOAOPORTUNIDADESVERSAO_FORM" Level="50" Order="176"  />
        <wes:SimpleGrid runat="server" ID="K_ADICIONAIS" Title="Considerações Adicionais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FORMK_CRM_PESSOAOPORTUNIDADESVERSA" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="K_CRM_PO_ADICIONAL.VERSAO.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.OPORTUNIDADE = @CAMPO(OPORTUNIDADE) AND A.VERSAO = @CAMPO(VERSAO)" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_KCRMPESSOAOPORTUNIDADESVERSAO_FORM" Level="50" Order="211"  />
        </div>
    
      </asp:Content>
    