<%@ Page Title="Consulta Contas" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:SimpleGrid runat="server" ID="K_LEADS" Title="Contas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="20" SystemFilterOnly="True" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" FormUrl="~/Pages/K_CRM_PESSOAS/resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAS_GRID" Level="50" Order="10"  />
        <wes:SimpleGrid runat="server" ID="K_CONTAS" Title="Contas" Subtitle="Executivo / Arquiteto" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAS.EXECUTIVO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.USUARIOEXECUTIVO = @USUARIO OR A.USUARIORESPONSAVEL = @USUARIO OR  A.HANDLE IN (SELECT BC.PESSOA FROM K_CRM_PESSOAOPORTUNIDADESPROD BA JOIN K_CRM_PESSOAOPORTUNIDADES BC ON BA.OPORTUNIDADE = BC.HANDLE WHERE BA.ARQUITETOSOLUCAO = @USUARIO ) " FormUrl="~/Pages/K_CRM_PESSOAS/resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAS_GRID" Level="50" Order="20"  />
        <wes:SimpleGrid runat="server" ID="K_CONTAS_2" Title="Contas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAS.DIRETOR_REGIONAL.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" FormUrl="~/Pages/K_CRM_PESSOAS/resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAS_GRID" Level="50" Order="40"  />
        <wes:AjaxForm runat="server" ID="K_FILTRODECONTAS" Title="Filtro de Contas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_VT_FILTROSDR.SDR.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="K_PAGES_K_CRM_PESSOAS_GRID" Level="50" Order="50"  />
        <wes:SimpleGrid runat="server" ID="K_CONTAS_1" Title="Contas" Subtitle="SDR" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTRODECONTAS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAS_SDR_V2.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="True" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.CNPJ = @CAMPO(CNPJ) OR A.APELIDO = @CAMPO(NOMEFANTASIA) OR A.NOME = @CAMPO(RAZAOSOCIAL)" FormUrl="~/Pages/K_CRM_PESSOAS/resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAS_GRID" Level="50" Order="62"  />
        <wes:SimpleGrid runat="server" ID="K_CONTAS_3" Title="Contas" Subtitle="Minhas Contas - SDR" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="K_CRM_PESSOAS.SDR_V3.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.USUARIOGDQ = @USUARIO OR A.FILIAL IN (SELECT FILIAL FROM Z_GRUPOUSUARIOEMPRESAFILIAIS WHERE USUARIO = @USUARIO)" FormUrl="~/Pages/K_CRM_PESSOAS/resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAS_GRID" Level="50" Order="72"  />
        </div>
    
      </asp:Content>
    