<%@ Page Title="Resumo Lead" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="K_RESUMOLEAD" Title="Resumo Lead" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="7" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAS.RESUMO.FORM" FormMode="View" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="K_PAGES_K_CRM_PESSOAS_RESUMO" Level="50" Order="10"  />
        <wes:SimpleGrid runat="server" ID="K_CONTATOS" Title="Contatos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="5" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOLEAD" ChromeState="Normal" CanDelete="False" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOACONTATOS.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PESSOA = @CAMPO(HANDLE)" FormUrl="~/Pages/K_CRM_PESSOACONTATOS/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAS_RESUMO" Level="50" Order="20"  />
        <wes:SimpleGrid runat="server" ID="K_SATISFAODEPRODUTOS" Title="Satisfação de produtos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="5" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOLEAD" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOASATISFACAO.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PESSOA = @CAMPO(HANDLE)" FormUrl="~/Pages/K_CRM_PESSOASATISFACAO/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAS_RESUMO" Level="50" Order="21"  />
        <wes:CustomUserControl runat="server" ID="K_ATIVIDADESCONCLUIDAS" Title="Atividades Concluidas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="7" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOLEAD" ChromeState="Normal" UserControlName="~/Pages/K_CRM_PESSOAS/e/uc/AtividadesConcluidas.ascx" PageId="K_PAGES_K_CRM_PESSOAS_RESUMO" Level="50" Order="30"  />
        <wes:CustomUserControl runat="server" ID="K_ATIVIDADESPENDENTES" Title="Atividades Pendentes" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="5" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOLEAD" ChromeState="Normal" UserControlName="~/Pages/K_CRM_PESSOAS/e/uc/AtividadesPendentes.ascx" PageId="K_PAGES_K_CRM_PESSOAS_RESUMO" Level="50" Order="40"  />
        <wes:SimpleGrid runat="server" ID="K_OPORTUNIDADES" Title="Oportunidades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOLEAD" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PESSOA = @CAMPO(CODIGO)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADES/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAS_RESUMO" Level="50" Order="45"  />
        <wes:SimpleGrid runat="server" ID="K_OPORTUNIDADES_1" Title="Oportunidades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOLEAD" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.EXECUTIVO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="4" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PESSOA = @CAMPO(HANDLE)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADES/Resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAS_RESUMO" Level="50" Order="55"  />
        </div>
    
      </asp:Content>
    