//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;

public partial class zoomdedocumentosAnexarDocumentosPage : WesPage
{
    public long HandleDocumento
    {
        get
        {
            var linkDefinition = this.GetLinkDefinition() as FormLinkDefinition;

            if (linkDefinition != null)
            {
                var handle = linkDefinition.Parameters["HANDLEDOCUMENTO"];

                if (handle != null)
                {
                    return (long)handle;
                }
            }

            return 0;
        }
    }
	
    protected override void OnLoad(EventArgs e)
    {
        base.OnLoad(e);

        umfAnexarDocumentos.Title = "Arraste seus arquivos aqui";
        umfAnexarDocumentos.SubTitle = "ou se preferir clique, para fazer upload";
        var rq = new Benner.Erp.DataContracts.UploadMultipleFilesRQ()
        {
            BusinessComponentTypeName = "Benner.Corporativo.Financeiro.Documento.SalvarMultiplosArquivos, Benner.Corporativo.Financeiro",
            Description = "@FILENAME - Importar arquivos"
        };
        rq.Params.TransitoryVars["HANDLEDOCUMENTO"] = HandleDocumento;
        rq.Params.TransitoryVars["HANDLEUSUARIO"] = BennerIdentity.Current.UserHandle.NullableValue;

        umfAnexarDocumentos.RequestSubmit = rq;
    }
}
