//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;

public partial class orcamentoconsultarPage : WesPage
{
    public EntityBase PropriedadesParaComponent { get; set; }

    public DateTime DataInicio
    {
        get
        {
            if (PropriedadesParaComponent != null)
            {
                return PropriedadesParaComponent["MESINICIAL"].GetDateTime().PrimeiroDiaMes();
            }

            return DateTime.Now;
        }
    }

    public DateTime DataFim
    {
        get
        {
            if (PropriedadesParaComponent != null)
            {
                return PropriedadesParaComponent["MESFINAL"].GetDateTime().UltimoDiaMes();
            }

            return DateTime.Now;
        }
    }

    public long Plano
    {
        get
        {
            if (PropriedadesParaComponent != null)
            {
                return PropriedadesParaComponent["PLANO"].GetInt64();
            }

            return 0;
        }
    }

    public long VersaoOrcamento
    {
        get
        {
            if (PropriedadesParaComponent != null)
            {
                return PropriedadesParaComponent["HANDLE"].GetInt64();
            }
            else
            {
                throw new BusinessException("Versão orçamento necessário, entre em contato com suporte.");
            }
        }
    }

    private string RecuperarHandleVersao()
    {
        return RecuperarParametroQueryString("hnd");
    }

    private string RecuperarParametroQueryString(string parametro)
    {
        return Request.QueryString[parametro];
    }

    protected void Page_Load(object sender, System.EventArgs e)
    {
        if (!IsPostBack)
        {
            ObterPropriedadesDoComponent();
        }
    }

    private void ObterPropriedadesDoComponent()
    {
        var handleVersao = RecuperarHandleVersao();

        if (!string.IsNullOrEmpty(handleVersao))
        {
            var query = new Query(@"SELECT VER.HANDLE,
                                               VER.MESINICIAL,
                                               VER.MESFINAL,
                                               VER.PLANO
                                          FROM CT_VERSOESORCAMENTOS VER
                                         WHERE VER.HANDLE = :HANDLE ");

            query.AddParameter(new Parameter("HANDLE", handleVersao));

            var retorno = query.Execute();

            if (retorno.Count > 0)
            {
                PropriedadesParaComponent = retorno[0];
            }
        }
    }
}
