<%@ Page Title="Industrializados" Language="C#" Inherits="Benner.Corporativo.Wes.WebApp.aga.a.OrdemProducaoApontamentoIndustrializados.OrdemProducaoApontamentoIndustrializadosMetodoCompraPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:CommandsPanel runat="server" ID="CONCLUIR" Title="Concluir" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="PR_ORDEMINDUSTRIALIZADOS.METODOCOMPRA.COMANDOS.CUSTOM.GRID" VerticalOrientation="False" PageId="AGA_A_ORDEMPRODUCAOAPONTAMENTOINDUSTRIALIZADOS_METODOCOMPRA" Level="20" Order="5"  />
        <wes:SimpleGrid runat="server" ID="INDUSTRIALIZADOS" Title="Industrializados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="True" CanInsert="False" EntityViewName="PR_ORDEMINDUSTRIALIZADOS.METODOCOMPRA.CUSTOM.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_A_ORDEMPRODUCAOAPONTAMENTOINDUSTRIALIZADOS_METODOCOMPRA" Level="20" Order="10"  />
        <wes:AjaxForm runat="server" ID="DETALHE" Title="Detalhe industrializado" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="INDUSTRIALIZADOS" ChromeState="Normal" CanDelete="False" CanUpdate="True" CanInsert="False" EntityViewName="PR_ORDEMINDUSTRIALIZADOS.METODOCOMPRA.CUSTOM.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="A.HANDLE = @CAMPO(HANDLE)" UserDefinedCommandsVisible="True" PageId="AGA_A_ORDEMPRODUCAOAPONTAMENTOINDUSTRIALIZADOS_METODOCOMPRA" Level="20" Order="16"  />
        <wes:SimpleGrid runat="server" ID="INSUMOS" Title="Insumos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="INDUSTRIALIZADOS" ChromeState="Normal" CanDelete="False" CanUpdate="True" CanInsert="False" EntityViewName="PR_ORDEMINDUSTRIALIZADOITENS.METODOCOMPRA.CUSTOM.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.ORDEMINDUSTRIALIZADO = @CAMPO(HANDLE)" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_A_ORDEMPRODUCAOAPONTAMENTOINDUSTRIALIZADOS_METODOCOMPRA" Level="20" Order="20"  />
        <wes:AjaxForm runat="server" ID="DETALHEINSUMO" Title="Detalhe insumo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="INSUMOS" ChromeState="Normal" CanDelete="False" CanUpdate="True" CanInsert="False" EntityViewName="PR_ORDEMINDUSTRIALIZADOITENS.METODOCOMPRA.CUSTOM.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="A.HANDLE = @CAMPO(HANDLE)" UserDefinedCommandsVisible="True" PageId="AGA_A_ORDEMPRODUCAOAPONTAMENTOINDUSTRIALIZADOS_METODOCOMPRA" Level="20" Order="30"  />
        </div>
    
      </asp:Content>
    