//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Benner.Corporativo.Definicoes.Administracao;



public partial class financeiroInicioPage : WesPage
{
    public bool PermiteColetar
    {
        get
        {
            var papelAtual = BennerPrincipal.Current.ActiveRole;
            return BennerContext.Authorization
                                .GetTasksFromRole(BennerConfiguration.DefaultSystemInstanceName, papelAtual)
                                .Contains("FINANCEIRO_COLETAR_DASHBOARD");
        }
    }

    public DateTime Competencia
    {
        get
        {
            if (Request.QueryString.GetValues("competencia") != null)
            {
                return Request.QueryString.GetValues("competencia").First().ToDateTime();
            }
            else
            {
                return DateTime.Now;
            }
        }
    }

    public bool PermiteVisualizarModuloFinanceiro
    {
        get
        {
            if (BennerPrincipal.Current.IsDeveloperRoleActive)
            {
                return true;
            }
            else
            {
                var papelAtual = BennerPrincipal.Current.ActiveRole;
                return BennerContext.Authorization
                                    .GetTasksFromRole(BennerConfiguration.DefaultSystemInstanceName, papelAtual)
                                    .Contains("MODULO_FINANCEIRO");
            }
        }
    }

    public bool PermiteVisualizarDashFinanceiro
    {
        get
        {
            if (BennerPrincipal.Current.IsDeveloperRoleActive)
            {
                return true;
            }
            else
            {
                var papelAtual = BennerPrincipal.Current.ActiveRole;
                return BennerContext.Authorization
                                    .GetTasksFromRole(BennerConfiguration.DefaultSystemInstanceName, papelAtual)
                                    .Contains("VISUALIZAR_DASHFINANCEIROGERENCIAL");
            }
        }
    }

    protected void Page_Load(object sender, System.EventArgs e)
    {
        if (!IsPostBack)
		{
            BOTOES.Hidden = Empresas.EsconderComandosModulosWes();
			BennerContext.BusinessComponent.Call("Benner.Corporativo.SPED.REINF.Utils.CarregarNaturezaRendimentos, Benner.Corporativo.SPED", "DispararManutencaoNaturezasRendimento");
		}
        if(!BOTOES.Hidden)
        {
            ((CommandGroup)((CommandGroup)BOTOES.Commands["GRP_PROCESSOSDOCUMENTOPARCELA"])
               .Items["GRP_RENEGOCIAR"])
               .Items["CMD_RENEGOCIARCONTASPAGAR"]
               .Visible = Benner.ERP.Comum.Utils.VerificaPermissao("MANTER_RENEGOCIARCONTASAPAGAR");
            ((CommandGroup)((CommandGroup)BOTOES.Commands["GRP_PROCESSOSDOCUMENTOPARCELA"])
                .Items["GRP_RENEGOCIAR"])
                .Items["CMD_RENEGOCIARCONTASRECEBER"]
                .Visible = Benner.ERP.Comum.Utils.VerificaPermissao("MANTER_RENEGOCIARCONTASARECEBER");
        }
    }

    protected override void OnInit(EventArgs e)
    {
        base.OnInit(e);

        if (!IsPostBack)
            ScriptManager.RegisterHiddenField(this, "PERMITEVISUALIZARDASHBOARDFINANCEIRO", (PermiteVisualizarModuloFinanceiro || PermiteVisualizarDashFinanceiro).ToString());
    }
}
