<%@ Page Title="Verticais" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:SimpleGrid runat="server" ID="K_VERTICAIS" Title="Verticais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAVERTICAL.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.VERTICAL IN (SELECT DISTINCT(HANDLE) FROM K_CRM_VERTICAL P
JOIN STRING_SPLIT
((SELECT REPLACE(REPLACE(SUBSTRING(K_VERTICALPRODUTO,0, LEN(K_VERTICALPRODUTO)-1), '|', ''),'_',',')
FROM Z_GRUPOUSUARIOS WHERE HANDLE = @USUARIO), ',') ON VALUE = P.HANDLE)
AND A.USUARIOEXECUTIVO = @USUARIO" FormUrl="~/Pages/K_CRM_PESSOAVERTICAL/resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAVERTICAL_GRID" Level="50" Order="10"  />
        <wes:SimpleGrid runat="server" ID="K_VERTICAIS_1" Title="Verticais" Subtitle="Minha Vertical" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAVERTICAL.HEAD.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.VERTICAL IN (SELECT DISTINCT(HANDLE) FROM K_CRM_VERTICAL P
JOIN STRING_SPLIT
((SELECT REPLACE(REPLACE(SUBSTRING(K_VERTICALPRODUTO,0, LEN(K_VERTICALPRODUTO)-1), '|', ''),'_',',')
FROM Z_GRUPOUSUARIOS WHERE HANDLE = @USUARIO), ',') ON VALUE = P.HANDLE)" FormUrl="~/Pages/K_CRM_PESSOAVERTICAL/resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAVERTICAL_GRID" Level="50" Order="20"  />
        <wes:SimpleGrid runat="server" ID="K_VERTICAIS_2" Title="Verticais" Subtitle="Geral" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAVERTICAL.HEAD.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" FormUrl="~/Pages/K_CRM_PESSOAVERTICAL/resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAVERTICAL_GRID" Level="50" Order="30"  />
        <wes:SimpleGrid runat="server" ID="K_VERTICAIS_3" Title="Verticais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAVERTICAL.ARQUITETO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.VERTICAL IN (SELECT DISTINCT(HANDLE) FROM K_CRM_VERTICAL P
JOIN STRING_SPLIT
((SELECT REPLACE(REPLACE(SUBSTRING(K_VERTICALPRODUTO,0, LEN(K_VERTICALPRODUTO)-1), '|', ''),'_',',')
FROM Z_GRUPOUSUARIOS WHERE HANDLE = @USUARIO), ',') ON VALUE = P.HANDLE)" FormUrl="~/Pages/K_CRM_PESSOAVERTICAL/resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAVERTICAL_GRID" Level="50" Order="40"  />
        <wes:AjaxForm runat="server" ID="K_FILTRODECONTAS" Title="Filtro de Contas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_VT_FILTROSDR.SDR.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="K_PAGES_K_CRM_PESSOAVERTICAL_GRID" Level="50" Order="48"  />
        <wes:SimpleGrid runat="server" ID="K_VERTICAIS_4" Title="Verticais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTRODECONTAS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAVERTICAL_SDR_V2_CANAIS.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="True" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PESSOA IN (SELECT HANDLE FROM K_CRM_PESSOAS WHERE CNPJ = @CAMPO(CNPJ) OR APELIDO = @CAMPO(NOMEFANTASIA) OR NOME = @CAMPO(RAZAOSOCIAL))" FormUrl="~/Pages/K_CRM_PESSOAVERTICAL/resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAVERTICAL_GRID" Level="50" Order="50"  />
        <wes:SimpleGrid runat="server" ID="K_VERTICAIS_5" Title="Verticais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="K_CRM_PESSOAVERTICAL.SDR_V3.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.USUARIOSDR = @USUARIO" FormUrl="~/Pages/K_CRM_PESSOAVERTICAL/resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_PESSOAVERTICAL_GRID" Level="50" Order="60"  />
        </div>
    
      </asp:Content>
    