<%@ Page Title="Resumo Lead - Vertical" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="K_RESUMOLEADVERTICAL_1" Title="Resumo Lead - Vertical" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="7" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAVERTICAL.RESUMO.FORM" FormMode="View" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="K_CRM_PESSOAVERTICAL_RESUMO" Level="50" Order="5"  />
        <wes:SimpleGrid runat="server" ID="K_CONTATOS" Title="Contatos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="5" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOLEADVERTICAL_1" ChromeState="Normal" CanDelete="False" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOACONTATOS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PESSOA = @CAMPO(PESSOA)" FormUrl="~/Pages/K_CRM_PESSOACONTATOS/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_CRM_PESSOAVERTICAL_RESUMO" Level="50" Order="20"  />
        <wes:CustomUserControl runat="server" ID="K_ATIVIDADESCONCLUDAS" Title="Atividades Concluídas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="7" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOLEADVERTICAL_1" ChromeState="Normal" UserControlName="~/Pages/K_CRM_PESSOAVERTICAL/e/uc/AtividadesConcluidas.ascx" PageId="K_CRM_PESSOAVERTICAL_RESUMO" Level="50" Order="30"  />
        <wes:CustomUserControl runat="server" ID="K_ATIVIDADESPENDENTES" Title="Atividades Pendentes" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="5" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOLEADVERTICAL_1" ChromeState="Normal" UserControlName="~/Pages/K_CRM_PESSOAVERTICAL/e/uc/AtividadesPendentes.ascx" PageId="K_CRM_PESSOAVERTICAL_RESUMO" Level="50" Order="50"  />
        <wes:SimpleGrid runat="server" ID="K_OPORTUNIDADES" Title="Oportunidades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOLEADVERTICAL_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PESSOA = @CAMPO(PESSOA) AND A.VERTICAL = @CAMPO(VERTICAL)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADES/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_CRM_PESSOAVERTICAL_RESUMO" Level="50" Order="60"  />
        <wes:SimpleGrid runat="server" ID="K_OPORTUNIDADES_1" Title="Oportunidades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOLEADVERTICAL_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.ARQUITETO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PESSOA = @CAMPO(PESSOA) AND A.VERTICAL = @CAMPO(VERTICAL)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADES/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_CRM_PESSOAVERTICAL_RESUMO" Level="50" Order="70"  />
        <wes:SimpleGrid runat="server" ID="K_OPORTUNIDADES_2" Title="OPORTUNIDADES" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOLEADVERTICAL_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GER_PROD.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PESSOA = @CAMPO(PESSOA) AND A.VERTICAL = @CAMPO(VERTICAL)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADES/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_CRM_PESSOAVERTICAL_RESUMO" Level="50" Order="80"  />
        <wes:SimpleGrid runat="server" ID="K_OPORTUNIDADES_3" Title="Oportunidades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_RESUMOLEADVERTICAL_1" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.EXECUTIVO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="4" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PESSOA = @CAMPO(PESSOA) AND A.VERTICAL = @CAMPO(VERTICAL)" FormUrl="~/Pages/K_CRM_PESSOAOPORTUNIDADES/Resumo.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_CRM_PESSOAVERTICAL_RESUMO" Level="50" Order="90"  />
        </div>
    
      </asp:Content>
    