<%@ Page Title="Encerrar orçamento público" Language="C#" Inherits="aga.a.orcamento.OrcamentoEncerrarVercao" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="COMANDOS" Title="Comandos" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="9" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="CT_VERSOESORCAMENTOS.ORCAMENTOEMEXECUCAO.FORM" FormMode="None" IncludeRecordInRecentItems="False" UserDefinedCommandsVisible="True" PageId="AGA_A_ORCAMENTO_ENCERRARVERCAO" Level="20" Order="0"  />
        <wes:AjaxForm runat="server" ID="COMANDOSENCERRAR" Title="Comandos encerrar" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="COMANDOS" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="CT_VERSOESORCAMENTOS.ORCAMENTOEMEXECUCAOENCERRAR.FORM" FormMode="None" IncludeRecordInRecentItems="False" UserDefinedCommandsVisible="True" PageId="AGA_A_ORCAMENTO_ENCERRARVERCAO" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="ENCERRARORAMENTOPBLICO" Title="Encerrar orçamento público" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMANDOS" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="CT_PEDIDOSEMPENHOS.ENCERRAR_ORCAMENTO_PUBLICO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.VERSAO = @CAMPO(HANDLE) AND A.STATUS &lt;&gt; 4 AND  (ROUND(A.VALOR, 2) - ROUND(A.VALORUTILIZADO, 2) - ROUND(A.VALORENCERRADO, 2)) &gt; 0.0001" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_A_ORCAMENTO_ENCERRARVERCAO" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="ORDENSDECOMPRASASSOCIADAS" Title="Ordens de compras Associadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="CP_ITEMPEDIDOSEMPENHOS.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="False" CompanyFilterMode="OnlyCompany" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_A_ORCAMENTO_ENCERRARVERCAO" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="DOCUMENTOSDECONTAAPAGARASSOCIADOS" Title="Documentos de conta a pagar associados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COMANDOS" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="FN_DOCUMENTOPEDIDOSEMPENHOS.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="False" CompanyFilterMode="OnlyCompany" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_A_ORCAMENTO_ENCERRARVERCAO" Level="20" Order="30"  />
        </div>
    
      </asp:Content>
    