//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Definicoes.FluxoCaixa.Virtuais;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System.Collections.Generic;

public class RateioDto
{
    public decimal? Valor { get; set; }
    public string PlanoGerencialHandle { get; set; }
    public string NomePlano { get; set; }
    public string ContaGerencialHandle { get; set; }
    public string NomeConta { get; set; }
}

public partial class FxLancamentosWizardLancamentoManualPage : WesPage
{
    public FxVirtualWizardLanc Lancamento
    {
        get { return LANAMENTOMANUAL.GetEntity() as FxVirtualWizardLanc; }
    }

    public FxVirtualWizardRateio Rateio
    {
        get { return RATEIODOLANAMENTO.GetEntity() as FxVirtualWizardRateio; }
    }

    public List<RateioDto> Rateios
    {
        get;
        set;
    }

    protected override void OnPreRender(System.EventArgs e)
    {
        RATEIODOLANAMENTO.EnsureDataLoad();

        if (CurrentStep.Value == "3")
        {
            var rateioLanc = RATEIODOLANAMENTO.GetEntity() as FxVirtualWizardRateio;

            EntityBase entity = RATEIODOLANAMENTO.GetEntity();

            if (entity == null)
            {
                RATEIODOLANAMENTO.ChangeMode(BennerFormViewMode.Insert);
                RATEIODOLANAMENTO.ForceUpdate();
            }
            else
            {
                var rateio = new RateioDto();
                rateio.Valor = Rateio.Valor;
                rateio.PlanoGerencialHandle = Rateio.PlanoGerencial.Handle.ToString();
                rateio.NomePlano = Rateio.PlanoGerencial.Instance.Nome;
                rateio.ContaGerencialHandle = Rateio.ContaGerencial.Handle.ToString();
                rateio.NomeConta = Rateio.ContaGerencial.Instance.Nome;

                Rateios.Add(rateio);

                AtualizarGridRateios();
            }
        }
    }

    protected void Page_Init(object sender, System.EventArgs e)
    {
        Rateios = new List<RateioDto>();
    }

    protected void Page_Load(object sender, System.EventArgs e)
    {
        Rateios.Add(new RateioDto { Valor = 55 });
        LANAMENTOMANUAL.CommandExecuted += FormularioLancamento_CommandExecuted;
        RATEIODOLANAMENTO.CommandExecuted += FormularioRateio_CommandExecuted;
    }

    void FormularioLancamento_CommandExecuted(object sender, FormCommandExecuteArgs e)
    {
        CurrentStep.Value = "2";
    }

    void FormularioRateio_CommandExecuted(object sender, FormCommandExecuteArgs e)
    {
        if (e.CommandName == PredefinedAction.ActionType.Cancel.ToString())
        {
            CurrentStep.Value = "1";
        }

        if (e.CommandName == PredefinedAction.ActionType.Save.ToString())
        {
            AtualizarGridRateios();

            CurrentStep.Value = "3";
        }

        if (e.CommandName == "CMD_PASSO3")
        {
            CurrentStep.Value = "3";
        }
    }

    void AtualizarGridRateios()
    {
        GridRateios.DataSource = Rateios;
        GridRateios.DataBind();
        //var rateios = RATEIOSDOLANAMENTO.GetEntity();
        //throw new System.Exception(rateios.ToString());
    }
}
