//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Cloud.Vendas;
using Benner.Corporativo.Definicoes.Tributos;
using Benner.ERP.Comum;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.IO;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Erp_Vendas_NFS_Configuracao : WesPage
{
    private bool _excluirCertificado = false;
    protected override void OnLoad(EventArgs e)
    {
        //Sempre limpa a mensagem de erro
        lblMsg.Text = string.Empty;
        msgError.Visible = false;

        FORMCONFIRAOSDADOSDESUAEMPRESA.CommandExecuted += FORMCONFIRAOSDADOSDESUAEMPRESA_CommandExecuted;
        FORMCONFIGURACAODOCERTIFICADODIGITAL.CommandExecute += FORMCONFIGURACAODOCERTIFICADODIGITAL_CommandExecute;

        base.OnLoad(e);
    }
    protected override void OnPreRender(EventArgs e)
    {
        FORMCONFIGURACAODOCERTIFICADODIGITAL.EnsureDataLoad();

        if (CurrentStep.Value == "2")
        {
            //Verifica se já possui um certificado na base
            //Não possuindo prepara o formulário para inserir o dado
            EntityBase entity = FORMCONFIGURACAODOCERTIFICADODIGITAL.GetEntity();
            if (entity == null)
            {
                FORMCONFIGURACAODOCERTIFICADODIGITAL.ChangeMode(BennerFormViewMode.Insert);
                FORMCONFIGURACAODOCERTIFICADODIGITAL.ForceUpdate();
            }
            else
            {
                //Possuindo um certificado realiza a validação do mesmo
                divCadastroCertificado.Visible = true;
                comCertificadoDigital.Checked = true;

                ValidarCertificado(entity);
                //Atualiza o update panel para a tela refletir a alteração
                updatePanelMsgErro.Update();
            }
            //Para garantir que a tela já venha com os radio checados quando possuir um certificado
            if (!_excluirCertificado)
                ScriptManager.RegisterStartupScript(
                    Page,
                    Page.GetType(),
                    "VisibilidadeComponentes",
                    string.Format("VisibilidadeComponentes({0});", entity == null ? "true" : "false"),
                    true);
        }

        base.OnPreRender(e);
    }

    private void FORMCONFIGURACAODOCERTIFICADODIGITAL_CommandExecute(object sender, FormCommandExecuteArgs e)
    {
        if (e.CommandName == "CMD_Voltar")
            CurrentStep.Value = "1";
        else if (e.CommandName == PredefinedAction.ActionType.Delete.ToString())
        {
            updatePanelMsgErro.Update();
            _excluirCertificado = true;
        }
    }

    private void FORMCONFIRAOSDADOSDESUAEMPRESA_CommandExecuted(object sender, FormCommandExecuteArgs e)
    {
        if (e.CommandName == PredefinedAction.ActionType.Edit.ToString())
            return;

        CurrentStep.Value = 2.ToString();
    }

    /// <summary>
    /// Validação do certificado digital
    /// </summary>
    /// <param name="entity"></param>
    private void ValidarCertificado(EntityBase entity)
    {
        FileField fileField = entity.Fields[TRParametroFilial.FieldNames.ArquivoAssinaturaNfe] as FileField;
        if (fileField != null)
        {
            Guid temporaryId = Guid.NewGuid();
            (entity.Fields[TRParametroFilial.FieldNames.ArquivoAssinaturaNfe] as FileField).TemporaryId = temporaryId;

            FileField.RetrieveContents(entity, TRParametroFilial.FieldNames.ArquivoAssinaturaNfe, null);

            string temporaryFilePath = Path.Combine(BennerConfiguration.TemporaryContentsDirectory, temporaryId.ToString());

            try
            {
                LeitorCertificadoDigital leitor = new LeitorCertificadoDigital();
                leitor.CarregaDeArquivo(temporaryFilePath, entity.Fields[TRParametroFilial.FieldNames.SenhaAssinaturaNfe].ToString());

                if (leitor.Validade < DateTime.Now)
                {
                    lblMsg.Text = "Verifique a data de validade do seu certificado.";
                    msgError.Visible = true;
                }
            }
            catch (Exception e)
            {
                lblMsg.Text = e.Message;
                msgError.Visible = true;
            }
        }
    }
}
