//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Definicoes.Comercial;
using Benner.Corporativo.Definicoes.Financeiro;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class OrdemVendaPage : WesPage
{

    protected void Page_Load(object sender, System.EventArgs e)
    {
        PreencherOrdemVenda();

        ORDEMDEVENDA.CommandExecuted += ORDEMDEVENDA_CommandExecuted;

        if (ORDEMDEVENDA.GetEntityHandle().NullableValue != null)
        {
            ITENS.CommandExecute += ITENS_CommandExecute;
            ITENS.GridView.RowCreated += GridView_RowCreated;
            ITENS.GridView.RowDeleted += GridView_RowDeleted;

            int statusOrdemVenda = ((Benner.Tecnologia.Common.ListItem)CMOrdensVenda.Get(ORDEMDEVENDA.GetEntityHandle()).Fields["STATUS"]).Value;
            if (statusOrdemVenda != CMOrdensVendaStatusListaItens.ItemCadastrada.Index)
                OcultarCompletamenteItensDaOv();
        }
        else
        {
            ITENS.AllowEditing = false;
            ITENS.EntityViewCommands.Commands.Where(P => P.Key == "InsercaoDetalhada").FirstOrDefault().Enabled = false;
        }
    }

    private void GridView_RowDeleted(object sender, GridViewDeletedEventArgs e)
    {
        if (ITENS.GridView.Rows.Count == 0)
            HabilitarRecebimentoEComissoes(false);
    }
    private void HabilitarRecebimentoEComissoes(bool statusDesejado)
    {
        ((CommandGroup)ORDEMDEVENDA.EntityViewCommands.Commands.Where(p => p.Key == "GRP_COMANDOS").FirstOrDefault()).Items.Where(p => p.Key == "CMD_COMISSOES").FirstOrDefault().Visible = statusDesejado;
        ((CommandGroup)ORDEMDEVENDA.EntityViewCommands.Commands.Where(p => p.Key == "GRP_COMANDOS").FirstOrDefault()).Items.Where(p => p.Key == "CMD_COMISSOES").FirstOrDefault().Enabled = statusDesejado;
        ((CommandGroup)ORDEMDEVENDA.EntityViewCommands.Commands.Where(p => p.Key == "GRP_COMANDOS").FirstOrDefault()).Items.Where(p => p.Key == "CMD_RECEBIMENTOS").FirstOrDefault().Enabled = statusDesejado;
        ((CommandGroup)ORDEMDEVENDA.EntityViewCommands.Commands.Where(p => p.Key == "GRP_COMANDOS").FirstOrDefault()).Items.Where(p => p.Key == "CMD_RECEBIMENTOS").FirstOrDefault().Visible = statusDesejado;
        ORDEMDEVENDA.ForceUpdate();
    }

    private void OcultarCompletamenteItensDaOv()
    {
        //Comandos e itens só podem ser editáveis caso o status seja Cadastrado, Caso contrário usuário poderá ver apenas comando "visualizar"
        ITENS.AllowEditing = false;
        ITENS.EntityViewCommands.Commands.Where(P => P.Key == "InsercaoDetalhada").FirstOrDefault().Enabled = false;
        ITENS.EntityViewCommands.Commands.Where(P => P.Key == "Editar").FirstOrDefault().Context = FunctionContext.Table;
        ITENS.EntityViewCommands.Commands.Where(P => P.Key == "Editar").FirstOrDefault().Enabled = false;
        ITENS.EntityViewCommands.Commands.Where(P => P.Key == "CMD_Comissoes").FirstOrDefault().Context = FunctionContext.Table;
        ITENS.EntityViewCommands.Commands.Where(P => P.Key == "CMD_Comissoes").FirstOrDefault().Enabled = false;
    }

    private void ORDEMDEVENDA_CommandExecuted(object sender, FormCommandExecuteArgs e)
    {
        if (e.CommandName =="Save")
        {
            //Ao salvar a capa da OV, é necessário habilitar os comandos de adição à grid.
            ITENS.AllowEditing = true;
            ITENS.EntityViewCommands.Commands.Where(P => P.Key == "InsercaoDetalhada").FirstOrDefault().Enabled = true;
        }
        if(e.CommandName == "CMD_LANCAMENTOSFINANCEIROS")
        {
            var link = new FormLinkDefinition();
            link.TargetSystemInstanceName = BennerContext.Administration.DefaultSystemInstanceName;
            link.WhereClause = new WhereClause("A.LANCAMENTOORDEMVENDA = :DOCUMENTO", new Benner.Tecnologia.Common.Parameter("DOCUMENTO", ORDEMDEVENDA.GetEntityHandle().ToInt()));
            link.TargetEntityDefinitionName = "FN_LANCAMENTOS";
            link.TargetFormMode = FormLinkDefinition.FormMode.View;
            link.Url = "~/aga/a/financeiro/documentos/Lancamentos.aspx";
            link.Parameters.Add("ENTIDADEORIGEM", ORDEMDEVENDA.GetEntity());
            link.Parameters.Add("CODIGOINTERNO", FNLancamentoCodigoInterno.ciOVI);
            link.Parameters.Add("DESTINO", "~/aga/e/comercial/OrdensVenda/OrdemVenda.aspx?hdl=" + ORDEMDEVENDA.GetEntityHandle().ToInt());

            string url = Benner.Tecnologia.Wes.Components.UriBuilder.Create(link);

            Response.Redirect(url);
        }
    }

    private void GridView_RowCreated(object sender, GridViewRowEventArgs e)
    {
        //Caso seja uma linha de DADOS, habilitar comandos recebimento e comissões
        if (ITENS.GridView.Rows.Count > 0 )
            HabilitarRecebimentoEComissoes(true);
        else
            HabilitarRecebimentoEComissoes(false);


        //Cada vez que é criado uma nova linha no grid , o grid "reseta", sendo necessário mapear novamente os eventos jquery
        ScriptManager.RegisterStartupScript(this, GetType(), "eventoChange", "eventoChange();", true);
        ScriptManager.RegisterStartupScript(this, GetType(), "mapearVariacoes", "mapearVariacoes();", true);
    }

    private void ITENS_CommandExecute(object sender, EditableGridCommandExecuteArgs e)
    {
        if (e.Command.Key == "InsercaoDetalhada")
        {
            FormLinkDefinition ComandoDestino = ((FormLinkDefinition)e.Command.OutputDefinition);
            ComandoDestino.WhereClause = new WhereClause("A.ORDEMVENDA = " + ORDEMDEVENDA.GetEntityHandle());
            ComandoDestino.IsModalPage = true;
            ComandoDestino.TargetEntityDefinitionName = "CM_ORDEMVENDAITENS";
            e.Command.OutputDefinition = ComandoDestino;
        }
    }

    private void PreencherOrdemVenda()
    {
        var requestDocumento = Request["hdl"];

        if (requestDocumento != null)
        {
            long handleDocumento;

            if (long.TryParse(requestDocumento.ToString(), out handleDocumento))
            {
                ORDEMDEVENDA.UserDefinedCriteriaWhereClause += "A.HANDLE = " + handleDocumento;
                ORDEMDEVENDA.ForceUpdate();
            }
        }
    }
}
