<%@ Page Title="Conjuntos - Almoxarifados" Language="C#" CodeFile="~/aga/e/f/aga_t2349_at6922_hs5b1309dc.aspx.cs" Inherits="faga_t2349_at6922_hs5b1309dcPage" %>

<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>

<asp:content id="Content1" contentplaceholderid="Main" runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Conjuntos - Almoxarifados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_MA_RECURSOPARTES.FORM" CanDelete="False" CanUpdate="True" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="MF_CONJUNTOS_MECANICOS__ALMOXARIFADOS_FORM" Level="20" Order="1" />
        <wes:SimpleGrid runat="server" ID="WIDGET_3931" Title="Histórico de desgastes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="False" CanUpdate="True" CanInsert="False" EntityViewName="AGA_MF_PARTEDESGASTES.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PARTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2617_at3931_hs33cda74d.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="MF_CONJUNTOS_MECANICOS__ALMOXARIFADOS_FORM" Level="20" Order="10" />
        <wes:SimpleGrid runat="server" ID="WIDGET_3926" Title="Histórico de localizações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="AGA_MF_HISTORICOLOCACAOPARTES.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PARTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2623_at3926_hs7c33e6f3.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="MF_CONJUNTOS_MECANICOS__ALMOXARIFADOS_FORM" Level="20" Order="15" />
        <wes:SimpleGrid runat="server" ID="WIDGET_7084" Title="Histórico de manutenções" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="AGA_MF_ORDEMSERVICOS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT ORDEMSERVICO FROM MF_ORDEMPRODUTOINTERNOS WHERE CONJUNTO = @RASTRO(MA_RECURSOPARTES))
OR A.HANDLE IN (SELECT ORDEMSERVICO FROM MF_ORDEMSERVICOPRODUTOS WHERE PARTE  = @RASTRO(MA_RECURSOPARTES))
OR A.HANDLE IN (SELECT ORDEMSERVICO FROM MF_ORDEMSERVICOINTERNOS WHERE CONJUNTO =  @RASTRO(MA_RECURSOPARTES))"
            FormUrl="~/aga/a/f/aga_t2619_at7084_hs30313909.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="MF_CONJUNTOS_MECANICOS__ALMOXARIFADOS_FORM" Level="20" Order="20" />
        <wes:SimpleGrid runat="server" ID="WIDGET_7025" Title="Roteiros de lubrificações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_MF_PARTEMANUTENCAOPREVENTIVA.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.MANUTENCAO IN
(SELECT HANDLE FROM MA_ROTEIROMANUTENCAO WHERE UTILIZARPLANOLUBRIFICACAO = 'S') AND (A.CONJUNTO = @CAMPO(HANDLE))"
            FormUrl="~/aga/a/f/aga_t4649_at7025_hsc74536.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="MF_CONJUNTOS_MECANICOS__ALMOXARIFADOS_FORM" Level="20" Order="25" />
        <wes:SimpleGrid runat="server" ID="WIDGET_7024" Title="Roteiros de manutenções preventivas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_MF_PARTEMANUTENCAOPREVENTIVA.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.MANUTENCAO IN
(SELECT HANDLE FROM MA_ROTEIROMANUTENCAO WHERE UTILIZAPLANOPREVENTIVO= 'S') AND (A.CONJUNTO = @CAMPO(HANDLE))"
            FormUrl="~/aga/a/f/aga_t4649_at7024_hsc88df198.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="MF_CONJUNTOS_MECANICOS__ALMOXARIFADOS_FORM" Level="20" Order="30" />
    </div>

</asp:content>
