<%@ Page Title="Alocação de Conta" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="ALOCAODECONTA" Title="Alocação de Conta" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CT_ALOCACOES.CUSTOM.FORM" FormMode="View" IncludeRecordInRecentItems="False" UserDefinedCommandsVisible="True" PageId="AGA_A_CONTABIL_ALOCACAOCONTA" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="ITENS" Title="Itens" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="ALOCAODECONTA" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CT_ALOCACAOITEM.CUSTOM.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="5" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" FormUrl="~/aga/a/Contabil/cadastros/AlocacaoItem.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_A_CONTABIL_ALOCACAOCONTA" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="CENTROSDECUSTOSDACONTADESTINO" Title="Centros de custos da conta destino" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="ITENS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CT_ALOCACAOITEMCC.CUSTOM.GRID" Mode="Search" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="5" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="(A.ITEM = @CAMPO(HANDLE) AND A.ORIGEM = 1)" FormUrl="~/aga/a/Contabil/AlocacaoContas/CentrosDeCustos.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_A_CONTABIL_ALOCACAOCONTA" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="CENTROSDECUSTOSDACONTRAPARTIDA" Title="Centros de custos da contra partida" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="ITENS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CT_ALOCACAOITEMCC.CUSTOM.GRID" Mode="Search" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="5" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="(A.ITEM = @CAMPO(HANDLE) AND A.ORIGEM = 2)" FormUrl="~/aga/a/Contabil/AlocacaoContas/CentrosDeCustos.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_A_CONTABIL_ALOCACAOCONTA" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="RATEIODESTINO" Title="Rateio destino" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="ITENS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CT_ALOCACAOITEMCRITERIOS.GRID" Mode="Search" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="5" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="(A.ITEM = @CAMPO(HANDLE) AND A.ORIGEM = 1)" FormUrl="~/aga/a/Contabil/AlocacaoContas/Rateios.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_A_CONTABIL_ALOCACAOCONTA" Level="20" Order="50"  />
        <wes:SimpleGrid runat="server" ID="RATEIOPARTIDA" Title="Rateio partida" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="ITENS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CT_ALOCACAOITEMCRITERIOS.GRID" Mode="Search" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="5" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="(A.ITEM = @CAMPO(HANDLE) AND A.ORIGEM = 2)" FormUrl="~/aga/a/Contabil/AlocacaoContas/Rateios.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_A_CONTABIL_ALOCACAOCONTA" Level="20" Order="60"  />
        </div>
    
      </asp:Content>
    