<%@ Page Title="Consultas contábeis" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:ActionView runat="server" ID="CONSULTASCONTBEIS" Title="Consultas contábeis" Subtitle="(Perfis)" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="fa fa-filter" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" Controller="ConsultasContabil" Action="Filtros" PageId="AGA_A_CONTABIL_CONSULTAS" Level="20" Order="10"  />
        <wes:HtmlPanel runat="server" ID="CONSULTACUSTOMIZADA" Title="Consulta customizada" Subtitle="(filtros)" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="fa fa-database" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" HtmlBase64="PHA+SW7DrWNpbyBjb25zdWx0YSBjdXN0b21pemFkYTwvcD4=" PageId="AGA_A_CONTABIL_CONSULTAS" Level="20" Order="20"  />
        <wes:HtmlPanel runat="server" ID="CONSULTAPORPERFIL" Title="Consulta simplificada" Subtitle="(perfil)" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="fa fa-database" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" HtmlBase64="PHA+Q29uc3VsdGEgcG9yIHBlcmZpbDwvcD4=" PageId="AGA_A_CONTABIL_CONSULTAS" Level="20" Order="30"  />
        <wes:HtmlPanel runat="server" ID="RESULTADOCONSULTA" Title="Resultado consulta" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" HtmlBase64="PGRpdiBjbGFzcz0icG9ydGxldCBsaWdodCI+CiAgICA8ZGl2IGNsYXNzPSJwb3J0bGV0LXRpdGxlIj4KICAgICAgICA8ZGl2IGNsYXNzPSJjYXB0aW9uIGNvbGxhcHNpYmxlIj4KICAgICAgICAgICAgPGkgY2xhc3M9ImZhIGZhLXRhYmxlIj48L2k+PHNwYW4gY2xhc3M9ImNhcHRpb24tc3ViamVjdCBmb250LWdyZWVuLXNoYXJwIGJvbGQgdXBwZXJjYXNlIj5ERU1PTlNUUkFUSVZPIENPTlNVTFRBUyBDT05Uw4FCRUlTPC9zcGFuPgogICAgICAgIDwvZGl2PgogICAgPC9kaXY+CiAgICA8ZGl2IGNsYXNzPSJwb3J0bGV0LWJvZHkgZm9ybSI+CiAgICAgICAgPGRpdiBjbGFzcz0icm93IG1hcmdpbi1ib3R0b20tMTAiPgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJjb2wtbWQtMTIgY29sLWxnLTEyIGNvbC1zbS0xMiBjb2wteHMtMTIiPgogICAgICAgICAgICAgICAgPGEgaHJlZj0iIyIgb25jbGljaz0iUmVkaXJlY2lvbmFQYXJhRmlsdHJvcygpIiBjbGFzcz0iYnRuIGRlZmF1bHQgYnRuLXNhdmUgY29tbWFuZC1hY3Rpb24gcHJlZGVmLWFjdGlvbiBlZGl0YWJsZSIgdGl0bGU9IlZvbHRhciBwYXJhIGZvcm11bMOhcmlvIGRlIGZpbHRyby4iPjxpIGNsYXNzPSJmYSBmYS1hcnJvdy1sZWZ0Ij48L2k+ICBWb2x0YXIgcGFyYSBmaWx0cm9zPC9hPgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICA8L2Rpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJyb3ciPgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJjb2wtbWQtMTIgY29sLWxnLTEyIGNvbC1zbS0xMiBjb2wteHMtMTIiPgogICAgICAgICAgICAgICAgPGRpdiBpZD0idGJsUmVzdWx0YWRvIiBjbGFzcz0iY29sLW1kLTEyIj48L2Rpdj4KICAgICAgICAgICAgICAgIDxkaXYgaWQ9InNhbGVzLWZpZWxkY2hvb3NlciI+PC9kaXY+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgIDwvZGl2PgogICAgPC9kaXY+CjwvZGl2Pgo=" PageId="AGA_A_CONTABIL_CONSULTAS" Level="20" Order="40"  />
        </div>
    
      </asp:Content>
    