//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Definicoes.Financeiro;
using Benner.Tecnologia.Business;
using Benner.ERP.Comum;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class aglutinadoraglutinarPage : WesPage
{
    private LinkDefinition LinkDefinition
    {
        get
        {
            var retorno = this.GetLinkDefinition();
            if (retorno != null)
            {
                return retorno;
            }
            else
            {
                throw new BusinessException("Não foi possível obter o LinkDefinition");
            }
        }
    }

    public string handlesDocumentos
    {
        get
        {
            var retorno = string.Empty;

            if (LinkDefinition.Parameters.ContainsKey("DOCUMENTOS"))
            {
                var handles = LinkDefinition.Parameters["DOCUMENTOS"] as List<Handle>;
                retorno = string.Join(",", handles.Select(x => x.Value.ToString()));
            }
            else
            {
                throw new BusinessException("Não foi possível obter os documentos selecionados");
            }

            return retorno;
        }
    }

    public Handle Filial
    {
        get
        {
            FNDocumento doc = FNDocumento.GetFirstOrDefault(handlesDocumentos.Split(',')[0].ToInt32OrDefault());
            if (doc != null && doc.FilialHandle.IsValid() && doc.FilialHandle > 0)
                return doc.FilialHandle;
            else
                return Utils.ObterFilialCorrente();
        }
    }

    private bool EhCRE
    {
        get
        {
            bool? retorno = false;

            if (LinkDefinition.Parameters.ContainsKey("EhCRE"))
            {
                retorno = LinkDefinition.Parameters["EhCRE"] as bool?;
            }
            else
            {
                throw new BusinessException("Falta informar se é CRE ou CPA");
            }

            return (bool)retorno;
        }
    }

    protected void Page_Load(object sender, System.EventArgs e)
    {
        AGLUTINADOR.CommandExecute += AGLUTINADOR_CommandExecute;
        AGLUTINADOR.CommandExecuted += AGLUTINADOR_CommandExecuted;

        if (!IsPostBack)
        {
            decimal total = (decimal)BennerContext.BusinessComponent.Call("Benner.Corporativo.Financeiro.Aglutinador, " +
                                                                          "Benner.Corporativo.Financeiro",
                                                                          "ObterSomaValoresDocumentos",
                                                                          handlesDocumentos);

            hf_value.Value = (total.ToString()).Replace(",", ".");
            ScriptManager.RegisterStartupScript(this, GetType(), "setValue", "setValue();", true);

            AGLUTINADOR.TransitoryVars["EHCRE"] = EhCRE;
            AGLUTINADOR.TransitoryVars["FILIAL"] = Filial;
        }

        string script = @"$(document).ready(function() {
                            $('.concluir.btn-save').attr('href', '');
                            $('.concluir.btn-save').attr('onclick', 'concluir()');
                        });";
        ScriptManager.RegisterStartupScript(this, GetType(), "ConfigurarConcluirScript", script, true);

    }

    void AGLUTINADOR_CommandExecuted(object sender, FormCommandExecuteArgs e)
    {
        this.CloseModalAndRefreshOrRedirect();
    }

    void AGLUTINADOR_CommandExecute(object sender, FormCommandExecuteArgs e)
    {
        if (e.CommandName.Equals("Save"))
        {
            AGLUTINADOR.InMemoryEntity.TransitoryData["DOCUMENTOS"] = handlesDocumentos;
            AGLUTINADOR.InMemoryEntity.TransitoryData["EHCRE"] = EhCRE;
        }
    }
}
