//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Comum;
using Benner.Corporativo.Definicoes.Contabil;
using Benner.Corporativo.Definicoes.Financeiro;
using Benner.Corporativo.Definicoes.Financeiro.Interfaces;
using Benner.Erp.Wes.Components;
using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using Ninject;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class CPALiberarCPAVisualizarPage : WesPage
{
    [Inject]
    public FNParcelaDao parcelaDao { get; set; }
    
    [Inject]
    public FNDocumentoDao documentoDao { get; set; }

    [Inject]
    public IGeradorOrcamentoParcela  geradorOrcamento { get; set; }

    protected void Page_Load(object sender, System.EventArgs e)
    {
        long handleParcela = Request.QueryString["hdl"].ToLong();

        AprovacaoDetalheDocumento.Title = "Informações documento AP " + handleParcela.ToString();

        var sessionVars = new Benner.Tecnologia.Common.BennerVariables.BennerVarsFactory().CreateSessionVars();
        var parcela = parcelaDao.GetFirstOrDefault(handleParcela);
        var documento = documentoDao.GetFirstOrDefault(parcela.DocumentoHandle);

        sessionVars.SetSessionVar("APROVACAO.AP.CONTRATOS.HANDLE", documento.Handle.ToString());

		var documentoFromParcela = geradorOrcamento.GetDocumentoFromParcela(handleParcela);
		var contasContabeisFromDocumentoParcela = geradorOrcamento.GetContasContabeisFromDocumentoParcela(documentoFromParcela);
		var contasGerenciaisFromContasContabeisParcela = geradorOrcamento.GetContasGerenciaisFromContasContabeisParcela(contasContabeisFromDocumentoParcela);
		
        var dadosConta = geradorOrcamento.ObterOrcamentoContasParcela(parcela, documentoFromParcela, contasContabeisFromDocumentoParcela, contasGerenciaisFromContasContabeisParcela).Select(conta => (IEntityBase)conta).ToList();

        new SimpleGridVisaoDinamica(OrcamentoContas, dadosConta)
               .AdicionarColunaFields("ESTRUTURACONTAS", "Conta", true, 50)
               .AdicionarColunaFields("VALORORCADOCONTAS", "Orçado", true, 50)
               .AdicionarColunaFields("VALORREALIZADOCONTAS", "Realizado", true, 50)
               .AdicionarColunaFields("VALORSALDOCONTAS", "Saldo", true, 50)
               .AdicionarColunaFields("ORCADOACUMULADOCONTAS", "Orçado acumulado", true, 50)
               .AdicionarColunaFields("REALIZADOACUMULADOCONTAS", "Realizado acumulado", true, 50)
               .AdicionarColunaFields("SALDOACUMULADOCONTAS", "Saldo acumulado", true, 50)
               .BuildFields();

        var dadosCC = geradorOrcamento.ObterOrcamentoCCParcela(parcela, documentoFromParcela, contasContabeisFromDocumentoParcela, contasGerenciaisFromContasContabeisParcela).Select(conta => (IEntityBase)conta).ToList();

        new SimpleGridVisaoDinamica(OrcamentoCCs, dadosCC)
                   .AdicionarColunaFields("ESTRUTURACC", "Centro de resultados", true, 50)
                   .AdicionarColunaFields("VALORORCADOCC", "Orçado", true, 50)
                   .AdicionarColunaFields("VALORREALIZADOCC", "Realizado", true, 50)
                   .AdicionarColunaFields("VALORSALDOCC", "Saldo", true, 50)
                   .AdicionarColunaFields("ORCADOACUMULADOCC", "Orçado acumulado", true, 50)
                   .AdicionarColunaFields("REALIZADOACUMULADOCC", "Realizado acumulado", true, 50)
                   .AdicionarColunaFields("SALDOACUMULADOCC", "Saldo acumulado", true, 50)
                   .BuildFields();
    }

}
    

