//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Definicoes.Comercial;
using Benner.Corporativo.Definicoes.Genericos;
using Benner.Tecnologia.Business;
using Benner.Tecnologia.Business.Tasks;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using System.Web;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using Benner.Corporativo.Definicoes.Comercial.Interfaces;
using Benner.Corporativo.DataContracts.Comercial;

public partial class AlterarPrecoProdutosPage : WesPage
{
    private FiltroAtual FiltroAtual = new FiltroAtual();
    private List<EntityBase> itensDaGrid = new List<EntityBase>();

    #region     Eventos
    protected void Page_Load(object sender, System.EventArgs e)
    {
        ITENS.GridView.RowDataBound += GridView_RowDataBound;
        CLCULODEPREODOSPRODUTOS.FilterControl.FilterExecute += FilterControl_FilterExecute;

        if (!IsPostBack)
        {
            if (CLCULODEPREODOSPRODUTOS.FilterControl.CurrentFilterWhereClause != null)
            {
                CLCULODEPREODOSPRODUTOS.FilterControl.FilterEntity = null;
                ITENS.UserDefinedCriteriaWhereClause = "1 = 2";
                ScriptManager.RegisterStartupScript(this, GetType(), "LimparJsonListaItens", "LimparJsonListaItens();", true);
            }

            Session["FiltroAtual"] = null;
            ScriptManager.RegisterHiddenField(this, "JsonListaItens", "[]");
        }
        else
            ITENS.UserDefinedCriteriaWhereClause = "@CRITERIOSELECAO";


        FiltroAtual = ((FiltroAtual)Session["FiltroAtual"]);
        if (FiltroAtual == null)
            FiltroAtual = new FiltroAtual();
    }


    private void FilterControl_FilterExecute(object sender, FilterExecuteEventArgs e)
    {
        CarregarFiltro(e);

        Handle moedaListaOriginal = CMListasPrecos.GetFirstOrDefault(new Criteria(string.Format("A.HANDLE = {0}", e.Entity["LISTAORIGINAL"].GetInt64()))).MoedaHandle;

        /*Comeca com o valor da lista original, caso a lista destino tenha valor, ele troca o para lista destino.*/
        Handle moedaListaDestino = moedaListaOriginal;
        if (!e.Entity["LISTADESTINO"].IsNull)
            moedaListaDestino = CMListasPrecos.GetFirstOrDefault(new Criteria(string.Format("A.HANDLE = {0}",
                e.Entity["LISTADESTINO"].GetInt64()))).MoedaHandle;

        decimal CotacaoEmissao = 0;
        string erroCotacao = null;
        //Caso seja uma moeda estrangeira, Verifica se a mesma tem uma cotação associada, via dll Delphi.
        if (moedaListaOriginal != GNParametro.ObterHandleMoedaPadrao())
        {
            FiltroAtual.EhMoedaEstrangeira = true;
            try
            {
                CotacaoEmissao = BuscaCotacao(moedaListaOriginal.Value, CMListasPrecos.GetFirstOrDefault(new Criteria(string.Format("A.HANDLE = {0}", e.Entity["LISTAORIGINAL"].GetInt64()))).DataInicial.Value);
            }
            catch (Exception ex)
            {
                erroCotacao = string.Format("Não foi possível buscar a cotação da moeda selecionada: {0}", ex.Message);
            }
        }

        //Verifica se a data validade da lista Preço é uma data válida em relação ao dia de hoje.
        bool listaDestinoValidadeOK = true;
        if (!e.Entity["LISTADESTINO"].IsNull)
        {
            listaDestinoValidadeOK = (DateTime.Now >= CMListasPrecos.GetFirstOrDefault(new Criteria(string.Format("A.HANDLE = {0}", e.Entity["LISTADESTINO"].GetInt64())))
                .DataInicial) && (DateTime.Now <= CMListasPrecos.GetFirstOrDefault(new Criteria(string.Format("A.HANDLE = {0}", e.Entity["LISTADESTINO"].GetInt64())))
                .DataFinal);
        }

        //Caso não tenha selecionado Lista destino, avisa (ALERT) que será alterado os preços da tabela origem. ( Tabela destino vira tabela origem)
        if (!e.Entity["LISTAORIGINAL"].IsNull && e.Entity["LISTADESTINO"].IsNull)
        {
            FiltroAtual.ListaDestino = FiltroAtual.ListaOriginal;
            FiltroAtual.TabelaDestino = FiltroAtual.TabelaOriginal;
            ScriptManager.RegisterStartupScript(this, GetType(), "AvisoAlterarPrecosNaTabelaOrigem", "AvisoAlterarPrecosNaTabelaOrigem();", true);

        }

        //Série de validações 
        if (e.Entity["LISTAORIGINAL"].GetInt64() == e.Entity["LISTADESTINO"].GetInt64())
            LimparFiltroEExibeMensagemGrid(e, "A lista destino não pode ser igual a original");

        else if (!e.Entity["LISTADESTINO"].IsNull && e.Entity["TABELADESTINO"].IsNull)
            LimparFiltroEExibeMensagemGrid(e, "A tabela destino deve ser informada.");

        else if ((moedaListaOriginal != GNParametro.ObterHandleMoedaPadrao()) && CotacaoEmissao == 0)
            LimparFiltroEExibeMensagemGrid(e, erroCotacao);

        else if (moedaListaOriginal != moedaListaDestino)
            LimparFiltroEExibeMensagemGrid(e, "Moeda da lista origem difere da moeda da lista destino.");

        else if (!listaDestinoValidadeOK)
            LimparFiltroEExibeMensagemGrid(e, "A Data de validade da lista destino expirou ou ainda não entrou em atividade!");
        //Caso esteja tudo ok, oculta o filtro e calcula o preço dos itens buscados.
        else
            ScriptManager.RegisterStartupScript(this, GetType(), "OcultarFiltros", "OcultarFiltros();", true);
    }

    private void GridView_RowDataBound(object sender, GridViewRowEventArgs e)
    {
        if (e.Row.RowType == DataControlRowType.DataRow)
        {
            //Se for moeda estrangeira, O valor do campo PRECO MOEDA toma conta do espaco reservado para o Preco.
            var CampoEditavelPrecoNovo = ((HtmlAnchor)e.Row.Cells[6].Controls[0]);

            if (FiltroAtual.EhMoedaEstrangeira)
            {
                int inicioPropriedadeValor = CampoEditavelPrecoNovo.InnerHtml.IndexOf("valorHandle");
                int inicioValorHandle = CampoEditavelPrecoNovo.InnerHtml.IndexOf("'", inicioPropriedadeValor) + 1;
                int finalValorHandle = CampoEditavelPrecoNovo.InnerHtml.IndexOf("'", inicioValorHandle);
                string valorHandle = CampoEditavelPrecoNovo.InnerHtml.Substring(inicioValorHandle, (finalValorHandle - inicioValorHandle));

                var EssaListaPrecoProduto = CMListaPrecoProduto.GetFirstOrDefault(new Handle(valorHandle));
                e.Row.Cells[5].Text = EssaListaPrecoProduto.PrecoMoeda.Value.ToString("F4");

                string precoAtual = EssaListaPrecoProduto.Preco.Value.ToString("F4"); ; //Linha do preco
                CampoEditavelPrecoNovo.InnerHtml = CampoEditavelPrecoNovo.InnerHtml.Replace(precoAtual, CalcularPreco(EssaListaPrecoProduto.PrecoMoeda.Value)); // atualiza o preço antigo com o novo preço
            }

            else
            {
                string precoAtual = e.Row.Cells[5].Text; //Linha do preco
                CampoEditavelPrecoNovo.InnerHtml = CampoEditavelPrecoNovo.InnerHtml.Replace(precoAtual, CalcularPreco(Convert.ToDecimal(precoAtual))); // atualiza o preço antigo com o novo preço
            }
        }

    }

    protected override void OnLoadComplete(EventArgs e)
    {
        base.OnLoadComplete(e);
        //Chama o script para adicionar o html dos botões de visibilidade do filtro.
        ScriptManager.RegisterStartupScript(this, GetType(), "InserirBotoesOcultarExibirFiltro", "InserirBotoesOcultarExibirFiltro();", true);
    }

    protected void ITENS_CommandExecuted(object sender, GridCommandExecuteArgs e)
    {
        if (e.Command.Name == "CMD_REAJUSTAR")
        {
            if (ItensSelecionados().Count > 0)
                ProcessarItensSelecionados();
            else
                ITENS.ShowWidgetMessage("Selecione pelo menos um item para processar os itens!", MessageType.Information);
        }
    }

    #endregion

    #region Métodos
    private void LimparFiltroEExibeMensagemGrid(FilterExecuteEventArgs e, string mensagem)
    {
        if (e.WhereClause != null)
            e.WhereClause.Where = "1 = 2"; /*Obrigado a usar esta condição, Comando e.whereclause.clear() da tec causa problemas*/
        //Limpar JsonListaItens para não trazer itens que pararam na validaçãop.
        ScriptManager.RegisterStartupScript(this, GetType(), "LimparJsonListaItens", "LimparJsonListaItens();", true);
        CLCULODEPREODOSPRODUTOS.ShowWidgetMessage(mensagem, MessageType.Warning);
    }

    public void CarregarFiltro(FilterExecuteEventArgs e)
    {
        //Carrega localmente valores do filtro que serão usados para calcular sugestão de preço.
        var familia = ((EntityAggregation)e.Entity["FAMILIA"].Value).ToHandleList();
        var itens = ((EntityAggregation)e.Entity["ITENS"].Value).ToHandleList();
        var fornecedores = ((EntityAggregation)e.Entity["FORNECEDORES"].Value).ToHandleList();

        FiltroAtual = new FiltroAtual(e.Entity["LISTAORIGINAL"].GetInt64(), e.Entity["TABELAORIGINAL"].GetInt64(),
            e.Entity["LISTADESTINO"].GetInt64(), e.Entity["TABELADESTINO"].GetInt64(), e.Entity["APLICARNOVOPRECO"].GetBoolean(),
            e.Entity["TIPOFATOR"].GetString()[0], e.Entity["ARRENDONDAMENTO"].GetDecimal(), e.Entity["FATOR"].GetDecimal(),
            familia, itens, fornecedores);

        Session["FiltroAtual"] = FiltroAtual;
    }

    public void ProcessarItensSelecionados()
    {
        IniciaReajuste();
        AlterarPrecoProdutos(itensDaGrid);
        LimparGridEMostrarFiltroLimpo();
    }

    private void LimparGridEMostrarFiltroLimpo()
    {
        ITENS.SelectedEntitiesHandles.Clear();
        ITENS.ShowWidgetMessage("Sucesso! Criado um processo para alteração dos preços, para mais detalhes acompanhar na aba Processos.", MessageType.Success);
        ITENS.UserDefinedCriteriaWhereClause = "1 = 2";
        CLCULODEPREODOSPRODUTOS.FilterControl.ClearFilterValues();
        Session["FiltroAtual"] = null;
        ScriptManager.RegisterStartupScript(this, GetType(), "MostrarFiltros", "MostrarFiltros();", true);
    }

    //Invoca objeto de negócio responsável pela transação de dados dos itens.
    private void AlterarPrecoProdutos(List<EntityBase> item)
    {
        //Depurar
        //AlterarPrecoRequest alterarPrecoRequest = new AlterarPrecoRequest()
        //{
        //    AplicarNovoPrecoNasTabelasSeguintes = FiltroAtual.AplicarNovoPrecoNasTabelasSeguintes,
        //    ListaDestino = FiltroAtual.ListaDestino.Value,
        //    TabelaDestino = FiltroAtual.TabelaDestino.Value,
        //    Itens = itensDaGrid
        //};
        //BusinessComponent.CreateProxyInstance<IAlterarPreco>().Run(alterarPrecoRequest);


        //Invocar BTL
        object handleProcesso = BusinessComponent.CreateProxyInstance<IAlterarPreco>().AlterarPrecosPorBTL(itensDaGrid, FiltroAtual.AplicarNovoPrecoNasTabelasSeguintes,
            FiltroAtual.ListaDestino.Value, FiltroAtual.TabelaDestino.Value);

        var notification = new AsyncProcessDetails()
        {
            Id = handleProcesso.ToString(),
            Description = "Alterando preços dos produtos selecionados"
        };

        Notification.Processes.New(notification);
    }

    private void AplicarNovosPrecosNaGrid()
    {
        //Cria um DataSource local com os valores editáveis em conjunto com o restante dos valores do grid.
        List<ItemSelecionado> itensJsonListaItens = ItensSelecionados();
        foreach (ItemSelecionado item in itensJsonListaItens)
        {
            NameValueDictionary novoPreco = new NameValueDictionary();
            novoPreco.Add(item.Handle, item.Preco);
            ITENS.SelectEntityMethod(new Handle(item.Handle)).Fields["PRECO"] = novoPreco;

            NameValueDictionary novoPrecoMaxConsumidor = new NameValueDictionary();
            novoPrecoMaxConsumidor.Add(item.Handle, item.PrecoMaximoConsumidor);
            ITENS.SelectEntityMethod(new Handle(item.Handle)).Fields["PRECOMAXIMOCONSUMIDOR"] = novoPrecoMaxConsumidor;
            var linhaGrid = ITENS.SelectEntityMethod(new Handle(item.Handle));
            itensDaGrid.Add(linhaGrid);
        }
    }

    private string CalcularPreco(decimal valorAtual)
    {
        if (FiltroAtual.Fator == 0)
            return valorAtual.ToString("F4").Replace(".", ","); ;

        decimal preco = 0;
        switch (FiltroAtual.TipoFator)
        {
            case 'P':
                preco = valorAtual + (valorAtual * FiltroAtual.Fator / 100);
                break;
            case 'M':
                preco = valorAtual * FiltroAtual.Fator;
                break;
            case 'D':
                if (FiltroAtual.Fator > 0)
                    preco = valorAtual / FiltroAtual.Fator;
                break;
            default: break;
        }
        preco = preco + FiltroAtual.Arredondamento;
        return preco.ToString("F4").Replace(".", ",");
    }

    private void IniciaReajuste()
    {
        AplicarNovosPrecosNaGrid();
        ExcluirTabelaDestino();
    }

    private decimal BuscaCotacao(long handleMoeda, DateTime DataInicioLista)
    {
        decimal cotacao = BennerContext.BusinessComponent.Call("Benner.Corporativo.Comercial.Services.OrdensVenda.OrdensVendaServices, Benner.Corporativo.Comercial",
            "ObterCotacao", handleMoeda.ToInt(), DataInicioLista).ToDecimal();

        return cotacao;
    }

    private void ExcluirTabelaDestino()
    {
        Criteria whereTabelaDestino = new Criteria();
        whereTabelaDestino.AddWhereClause(string.Format("A.LISTA = {0}", FiltroAtual.ListaDestino));
        whereTabelaDestino.AddWhereClause(string.Format("A.TABELA = {0}", FiltroAtual.TabelaDestino));
        whereTabelaDestino.AddWhereClause(string.Format("A.PRODUTO IN ( SELECT HANDLE FROM PD_PRODUTOS WHERE EMPRESA = {0} AND FILIAL = {1} )", FiltroAtual.TabelaDestino, FiltroAtual.TabelaDestino));

        if (FiltroAtual.Itens.Count > 0)
            whereTabelaDestino.AddWhereClause(string.Format("A.PRODUTO IN ({0})", FiltroAtual.Itens.ToStringSeparator()));

        if (FiltroAtual.Fornecedores.Count > 0)
            whereTabelaDestino.AddWhereClause(string.Format("A.PRODUTO IN (SELECT PRODUTO FROM PD_VARIACAOFORNECEDORES WHERE PRODUTO = A.PRODUTO AND FORNECEDOR IN ({0}) )", FiltroAtual.Fornecedores.ToStringSeparator()));

        if (FiltroAtual.Familia.Count > 0)
            whereTabelaDestino.AddWhereClause(string.Format("A.PRODUTO IN (SELECT HANDLE FROM PD_PRODUTOS WHERE FAMILIA IN  ({0}))", FiltroAtual.Familia.ToStringSeparator()));

        RegistrarAuditoria();
        var delete = CMListaPrecoProduto.DeleteMany(whereTabelaDestino);
    }

    private void RegistrarAuditoria()
    {
        //TODO: Traduzir de UcalculoPreco - ExcluirTabelaDestino.
        var todo = "Traduzir de UcalculoPreco - ExcluirTabelaDestino. NewAudit para RawAuditWriter";
    }


    private List<ItemSelecionado> ItensDesmarcadosGrid()
    {
        //mapeia os itens selecionados que estão contidos no #jsonListaItens
        var stringJson = Request.Form.GetValues("JsonListaItens")[0];
        var listaTodosItens = JsonConvert.DeserializeObject<List<ItemSelecionado>>(stringJson);
        return listaTodosItens;
    }

    private List<ItemSelecionado> ItensSelecionados()
    {
        //mapeia os itens selecionados que estão contidos no #jsonListaItens
        var stringJson = Request.Form.GetValues("JsonListaItens")[0];
        var listaTodosItens = JsonConvert.DeserializeObject<List<ItemSelecionado>>(stringJson);

        return listaTodosItens
            .Where(item => ITENS.SelectedEntitiesHandles.Contains(new Handle(item.Handle)))
            .ToList();
    }
}
#endregion

#region Classes poco e Structs

[Serializable]
public class FiltroAtual
{
    public FiltroAtual()
    {
    }
    public FiltroAtual(long prListaOriginal, long prTabelaOriginal, long? prListaDestino, long? prTabelaDestino, bool prAplicarNovoPreco,
        char prTipoFatorm, decimal prArredondamento, decimal prFator, List<Handle> prFamilia, List<Handle> prItens, List<Handle> prFornecedores)
    {
        this.TipoFator = prTipoFatorm;
        this.Arredondamento = prArredondamento;
        this.Fator = prFator;
        this.Familia = prFamilia;
        this.Itens = prItens;
        this.Fornecedores = prFornecedores;
        this.AplicarNovoPrecoNasTabelasSeguintes = prAplicarNovoPreco;
        this.ListaOriginal = prListaOriginal;
        this.TabelaOriginal = prTabelaOriginal;
        this.ListaDestino = prListaDestino;
        this.TabelaDestino = prTabelaDestino;
        this.EhMoedaEstrangeira = false;
    }

    public Char TipoFator { get; set; }
    public decimal Arredondamento { get; set; }
    public decimal Fator { get; set; }

    public bool AplicarNovoPrecoNasTabelasSeguintes { get; set; }

    public bool EhMoedaEstrangeira { get; set; }
    public long ListaOriginal { get; set; }
    public long TabelaOriginal { get; set; }
    public long? ListaDestino { get; set; }
    public long? TabelaDestino { get; set; }

    public List<Handle> Familia { get; set; }
    public List<Handle> Itens { get; set; }
    public List<Handle> Fornecedores { get; set; }

}

public struct ItemSelecionado
{
    public string Handle { get; set; }
    public decimal Preco { get; set; }
    public decimal PrecoMaximoConsumidor { get; set; }

}
#endregion