//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Definicoes.Financeiro;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using Ninject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class financeiroConsultaDocNomePage : WesPage
{
    [Inject]
    public IFNConsultaDocDao ConsultaDocDao { get; set; }

    protected void Page_Load(object sender, System.EventArgs e)
    {
        NOMEPARAAVISO.CommandExecute += NOMEPARAAVISO_CommandExecute;
    }

    private void NOMEPARAAVISO_CommandExecute(object sender, FormCommandExecuteArgs e)
    {
        if (e.CommandName == "Save")
        {
            var consulta = ConsultaDocDao.GetFirstOrDefault(new Criteria("A.NOME = :NOME AND A.USUARIO = :USUARIO AND PADRAO <> 'S'", new Benner.Tecnologia.Common.Parameter("NOME", NOMEPARAAVISO.GetEntity()["NOME"].Value), new Benner.Tecnologia.Common.Parameter("USUARIO", BennerContext.Security.GetLoggedUserHandle())));
            if (consulta != null)
            {
                NOMEPARAAVISO.FormDefinition.Commands["Save"].RequestConfirmation = true;
                NOMEPARAAVISO.FormDefinition.Commands["Save"].RequestConfirmationMessage = "Deseja substituir a visão existente com esse nome?";
            }
        }
        else
            BennerVars.UserVars["CONSULTADOCUMENTOS.DEFINICAOGRID"] = "";
    }
}
