<%@ Page Title="Cotações" Language="C#" Inherits="Benner.Corporativo.Wes.WebApp.aga.a.Aquisicoes.JulgamentoComercial" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:SimpleGrid runat="server" ID="ITENS" Title="Itens da aquisição" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="LC_AQUISICAOITENS.COTACAO.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AQUISICAO=@CAMPO(HANDLE) AND  (A.STATUS IS NULL OR A.STATUS NOT IN (2, 3, 4, 5, 7, 8, 9))" FormUrl="~/aga/a/f/aga_t1801_at3646_hs85e7a36a.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AQUISICAO_COMERCIAL" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="COTAES" Title="Cotações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="ITENS" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="LC_AQUISICAOCOTACOESITEM.COTACAO.GRID" Mode="None" UserDefinedSelectColumnVisible="True" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.AQUISICAOITEM = @CAMPO(HANDLE) AND A.AQUISICAO = @CAMPO(AQUISICAO)" FormUrl="~/aga/a/aquisicoes/Comercial/CotacaoItemForm.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AQUISICAO_COMERCIAL" Level="20" Order="20"  />
        <wes:EditableGrid runat="server" ID="ENTREGAS" Title="Entregas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COTAES" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="LC_COTACAOITEMENTREGAS.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.COTACAOITEM=@CAMPO(HANDLE)" ShowExport="True" PageId="AQUISICAO_COMERCIAL" Level="20" Order="30"  />
        <wes:EditableGrid runat="server" ID="VENCIMENTOS" Title="Vencimentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="COTAES" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="LC_COTACAOITEMVENCIMENTOS.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.COTACAOITEM=@CAMPO(HANDLE)" ShowExport="True" PageId="AQUISICAO_COMERCIAL" Level="20" Order="40"  />
        </div>
    
      </asp:Content>
    