<%@ Page Title="Atividades Leads" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:SimpleGrid runat="server" ID="K_ATIVIDADES" Title="Atividades" Subtitle="Minhas tarefas" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="20" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.RESPONSAVEL = @USUARIO" FormUrl="~/Pages/K_CRM_TAREFAUSUARIO/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_TAREFAUSUARIO_GRID" Level="50" Order="10"  />
        <wes:SimpleGrid runat="server" ID="K_ATIVIDADES_1" Title="ATIVIDADES" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.DIRETOR_REGIONAL.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.RESPONSAVEL IN (SELECT USUARIO FROM Z_GRUPOUSUARIOEMPRESAFILIAIS WHERE FILIAL = @FILIAL) AND A.PESSOA IN (SELECT CODIGO FROM K_CRM_PESSOAS WHERE FILIAL=@FILIAL)" FormUrl="~/Pages/K_CRM_TAREFAUSUARIO/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_TAREFAUSUARIO_GRID" Level="50" Order="20"  />
        <wes:SimpleGrid runat="server" ID="K_ATIVIDADES_2" Title="Atividades" Subtitle="Todas" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.ADM.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" FormUrl="~/Pages/K_CRM_TAREFAUSUARIO/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_TAREFAUSUARIO_GRID" Level="50" Order="30"  />
        <wes:SimpleGrid runat="server" ID="K_ATIVIDADES_3" Title="Atividades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.HEAD_VERTICAL.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.VERTICAL IN (SELECT VERTICAL FROM K_CRM_DIRETORVERTICAL WHERE NOME=@USUARIO)" FormUrl="~/Pages/K_CRM_TAREFAUSUARIO/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_TAREFAUSUARIO_GRID" Level="50" Order="40"  />
        <wes:SimpleGrid runat="server" ID="K_ATIVIDADES_4" Title="Atividades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.DIRETOR_RELACIONAMENTO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.RESPONSAVEL IN (SELECT USUARIO FROM Z_GRUPOUSUARIOEMPRESAFILIAIS WHERE FILIAL = @FILIAL) AND A.PESSOA IN (SELECT CODIGO FROM K_CRM_PESSOAS WHERE FILIAL=@FILIAL) AND A.VERTICAL IN (SELECT DISTINCT(HANDLE) FROM K_CRM_VERTICAL V
JOIN STRING_SPLIT
((SELECT REPLACE(REPLACE(SUBSTRING(K_VERTICALPRODUTO,0, LEN(K_VERTICALPRODUTO)-1), '|', ''),'_',',')
FROM Z_GRUPOUSUARIOS WHERE HANDLE = @USUARIO), ',') ON VALUE = V.HANDLE)" FormUrl="~/Pages/K_CRM_TAREFAUSUARIO/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_TAREFAUSUARIO_GRID" Level="50" Order="50"  />
        <wes:SimpleGrid runat="server" ID="K_ATIVIDADES_5" Title="Atividades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GERENTE_PRODUTOS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.VERTICAL IN (SELECT DISTINCT(HANDLE) FROM K_CRM_VERTICAL V
JOIN STRING_SPLIT
((SELECT REPLACE(REPLACE(SUBSTRING(K_VERTICALPRODUTO,0, LEN(K_VERTICALPRODUTO)-1), '|', ''),'_',',')
FROM Z_GRUPOUSUARIOS WHERE HANDLE = @USUARIO), ',') ON VALUE = V.HANDLE)" FormUrl="~/Pages/K_CRM_TAREFAUSUARIO/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_TAREFAUSUARIO_GRID" Level="50" Order="60"  />
        <wes:SimpleGrid runat="server" ID="K_ATIVIDADES_6" Title="Atividades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.CANAIS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PESSOA IN (SELECT PESSOA FROM K_CRM_PESSOAVERTICAL WHERE FILIAL IN (SELECT HANDLE FROM FILIAIS WHERE K_EHREVENDA='S' AND K_FILIALATIVA='S') GROUP BY PESSOA)" FormUrl="~/Pages/K_CRM_TAREFAUSUARIO/form.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="K_PAGES_K_CRM_TAREFAUSUARIO_GRID" Level="50" Order="70"  />
        </div>
    
      </asp:Content>
    