<%@ Page Title="Indicadores contratos faturamento" Language="C#" Inherits="Benner.Corporativo.Wes.WebApp.aga.a.contratos.faturamento.dashboard.HomeDashboard" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:FilterWidget runat="server" ID="FILTRO" Title="Filtro" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CN_DWINDICADORES.FILTRO_INDICADORES.GRID" DefaultFilterName="Filtro indicadores" Mode="FixedRequired" PageId="AGA_A_CONTRATOS_INDICADORES_CONTRATOSINDICADORES" Level="20" Order="4"  />
        <wes:AjaxForm runat="server" ID="PAINEL_COLETA_AGENDAMENTO" Title="PAINEL_COLETA_AGENDAMENTO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FILTRO" ChromeState="Fixed" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CN_VTDETALHECONTRATOS.PAINEL_COLETA_AGENDAMENTO.FORM" FormMode="None" IncludeRecordInRecentItems="False" UserDefinedCriteriaWhereClause="@CONDICAO('COMPETENCIA', '=', COMPETENCIA) AND A.CONTEXTO = 2" UserDefinedCommandsVisible="False" PageId="AGA_A_CONTRATOS_INDICADORES_CONTRATOSINDICADORES" Level="20" Order="6"  />
        <wes:Tile runat="server" ID="VALORTOTALPREVISTO_1" Title="VALOR TOTAL PREVISTO" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CONTRATOS_FATURAMENTO_PREVISTO_FATURAR.DATASOURCE.DASHBOARD.GRID" CompanyFilterMode="None" CommandName="DETALHE_PREVISTO_FATURAR" ValueFormat="N" Value="VALOR_PREVISTO" Description="TOTAL PREVISTO" Icon="fa fa-line-chart" Color="blue-madison" ValueAggregation="Sum" TileType="Flat" PageId="AGA_A_CONTRATOS_INDICADORES_CONTRATOSINDICADORES" Level="20" Order="6"  />
        <wes:Tile runat="server" ID="VALORFATURADO_1" Title="VALOR FATURADO" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CONTRATOS_FATURAMENTO_VALOR_FATURADO.DATASOURCE.DASHBOARD.GRID" CompanyFilterMode="None" CommandName="DETALHE_VALOR_FATURADO" ValueFormat="N" Value="FATURADO" Description="TOTAL FATURADO" Icon="fa fa-bank" Color="green-meadow" ValueAggregation="Sum" TileType="Flat" PageId="AGA_A_CONTRATOS_INDICADORES_CONTRATOSINDICADORES" Level="20" Order="11"  />
        <wes:Tile runat="server" ID="FALTAFATURAR_1" Title="FALTA FATURAR" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CONTRATOS_FATURAMENTO_FALTA_FATURAR.DATASOURCE.DASHBOARD.GRID" CompanyFilterMode="None" CommandName="DETALHE_FALTA_FATURAR" ValueFormat="N" Value="TOTAL_FALTAFATURAR" Description="TOTAL FALTA FATURAR" Icon="fa fa-calculator" Color="red" ValueAggregation="Sum" TileType="Flat" PageId="AGA_A_CONTRATOS_INDICADORES_CONTRATOSINDICADORES" Level="20" Order="18"  />
        <wes:Tile runat="server" ID="FATMDIOPORCONTRATO_1" Title="FAT. MÉDIO POR CONTRATO" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CONTRATOS_FATURAMENTO_FATURAMENTO_MEDIO_CONTRATO.DATASOURCE.DASHBOARD.GRID" CompanyFilterMode="None" ValueFormat="N" Value="FATURAMENTO" Description="FAT. MÉDIO POR CONTRATO" Icon="fa fa-money" Color="purple" ValueAggregation="Sum" TileType="Flat" PageId="AGA_A_CONTRATOS_INDICADORES_CONTRATOSINDICADORES" Level="20" Order="48"  />
        <wes:Tile runat="server" ID="CONTRATOSVENCENDOXDIAS" Title="CONTRATOS VENCENDO X DIAS" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CONTRATOS_FATURAMENTO_VENCENDO_DIAS.DATASOURCE.DASHBOARD.GRID" CompanyFilterMode="None" CommandName="DETALHE_VENCENDO_DIAS" ValueFormat="N" Value="VALOR_VENCENDO_DIAS" Description="TOTAL ITENS VENCENDO 60 DIAS" Icon="fa fa-calendar-times-o" Color="yellow-casablanca" ValueAggregation="Sum" TileType="Flat" PageId="AGA_A_CONTRATOS_INDICADORES_CONTRATOSINDICADORES" Level="20" Order="50"  />
        <wes:Tile runat="server" ID="CONTRATOSSEMFATURAMENTO" Title="CONTRATOS SEM FATURAMENTO" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CONTRATOS_FATURAMENTO_SEM_FATURAMENTO.DATASOURCE.DASHBOARD.GRID" CompanyFilterMode="None" CommandName="DETALHE_SEM_FATURAMENTO" ValueFormat="N" Value="VALOR_NAO_FATURADO" Description="TOTAL SEM FATURAMENTO" Icon="fa fa-fire" Color="dark" ValueAggregation="Sum" TileType="Flat" PageId="AGA_A_CONTRATOS_INDICADORES_CONTRATOSINDICADORES" Level="20" Order="70"  />
        <wes:Tile runat="server" ID="FATURAMENTOEMATRASO" Title="FATURAMENTO EM ATRASO" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CONTRATOS_FATURAMENTO_FATURAMENTO_ATRASADO.DATASOURCE.DASHBOARD.GRID" CompanyFilterMode="None" CommandName="DETALHE_FATURAMENTO_ATRASADO" ValueFormat="N" Value="VALOR_FATURAMENTO_ATRASO" Description="TOTAL FATURAMENTO EM ATRASO" Icon="fa fa-clock-o" Color="red-intense" ValueAggregation="Sum" TileType="Flat" PageId="AGA_A_CONTRATOS_INDICADORES_CONTRATOSINDICADORES" Level="20" Order="80"  />
        <wes:PartialView runat="server" ID="LTIMOS12MESES" Title="Últimos 12 meses" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Fixed" ViewPath="~/Views/Contratos/Faturamento/GraficoUltimos12MesesDashboard.cshtml" PageId="AGA_A_CONTRATOS_INDICADORES_CONTRATOSINDICADORES" Level="20" Order="98"  />
        <wes:SimpleGrid runat="server" ID="TOP10CONTRATOSFATURAMENTO" Title="Top 5 - Clientes Cont. Faturados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Fixed" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="CONTRATOS_FATURAMENTO_TOP_FATURADO_CLIENTE.DATASOURCE.DASHBOARD.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="5" SystemFilterOnly="False" DisplayRowCommand="False" CompanyFilterMode="None" ShowExport="True" UserDefinedDisableRowSelection="True" PageId="AGA_A_CONTRATOS_INDICADORES_CONTRATOSINDICADORES" Level="20" Order="100"  />
        <wes:SimpleGrid runat="server" ID="TOP10PRODUTOSESERVIOSFATURADOSEMCONTRATOS" Title="Top 5 - Produtos e serviços cont. faturados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Fixed" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="CONTRATOS_FATURAMENTO_TOP_FATURADO_PRODUTO.DATASOURCE.DASHBOARD.GRID" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="5" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="None" ShowExport="True" UserDefinedDisableRowSelection="True" PageId="AGA_A_CONTRATOS_INDICADORES_CONTRATOSINDICADORES" Level="20" Order="110"  />
        <wes:SimpleGrid runat="server" ID="TOP10CONTRATOSSEMFATURAMENTOEEMATRASO" Title="Top 5 - Clientes Cont. sem faturamento e em atraso" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Fixed" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="CONTRATOS_FATURAMENTO_TOP_SEM_FATURAMENTO_EM_ATRASO_CLIENTE.DATASOURCE.DASHBOARD" Mode="None" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="5" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="None" ShowExport="True" UserDefinedDisableRowSelection="True" PageId="AGA_A_CONTRATOS_INDICADORES_CONTRATOSINDICADORES" Level="20" Order="120"  />
        </div>
    
      </asp:Content>
    