//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class ContaBancariaFormPage : WesPage
{
    public DateTime DataInicio { set; get; }
    public DateTime DataFim { set; get; }

    public int ConciliacoesPentendes;
    public int RetornosPentendes;

    protected override void OnLoad(EventArgs e)
    {
        base.OnLoad(e);

        if (!IsPostBack)
        {
            CarregaDataInicio();

            SetPendentes();
        }

        CarregaFiltroWidgets();
    }

    private void SetPendentes()
    {
        var link = Page.GetLinkDefinition() as FormLinkDefinition;

        if (link == null)
            return;

        Query query = new Query(@"SELECT COUNT(*) CONTADOR
                FROM TS_EXTRATOBANCARIO 
                WHERE CONCILIADO <> 'S'
                    AND CONTA = :CONTA AND DATAEMISSAO BETWEEN :DATAINICIO AND :DATAFIM", 
                    new Benner.Tecnologia.Common.Parameter("CONTA", link.TargetEntityHandle),
                    new Benner.Tecnologia.Common.Parameter("DATAINICIO", DataInicio),
                    new Benner.Tecnologia.Common.Parameter("DATAFIM", DataFim));


        ConciliacoesPentendes = query.Execute()[0]["CONTADOR"].GetInt32();

        query = new Query(@"SELECT COUNT(*) CONTADOR
                FROM GN_HBRETORNOS
                WHERE CONTA = :CONTA AND 
                    DATA BETWEEN :DATAINICIO AND :DATAFIM
                    AND STATUS IN(1, 2, 3, 5, 6)",
                    new Benner.Tecnologia.Common.Parameter("CONTA", link.TargetEntityHandle),
                    new Benner.Tecnologia.Common.Parameter("DATAINICIO", DataInicio),
                    new Benner.Tecnologia.Common.Parameter("DATAFIM", DataFim));

        RetornosPentendes = query.Execute()[0]["CONTADOR"].GetInt32();
    }

    private void CarregaFiltroWidgets()
    {
        DataInicio = DateTime.Parse(HiddenDataInicio.Value);
        DataFim = DateTime.Parse(HiddenDataFim.Value);

        RouteData.Values["DataInicio"] = DataInicio;
        RouteData.Values["DataFim"] = DataFim;
        GRIDMOVIMENTACOES.ForceUpdate();
        GRIDCONCILIACOESPENDENTES.ForceUpdate();

        GRIDREMESSAS.UserDefinedCriteriaParameters.Add("DATAINICIO", DataInicio);
        GRIDREMESSAS.UserDefinedCriteriaParameters.Add("DATAFIM", DataFim);
        GRIDREMESSAS.ForceUpdate();

        GRIDRETORNOSDECOBRANCA.UserDefinedCriteriaParameters.Add("DATAINICIO", DataInicio);
        GRIDRETORNOSDECOBRANCA.UserDefinedCriteriaParameters.Add("DATAFIM", DataFim);
        GRIDRETORNOSDECOBRANCA.ForceUpdate();
    }

    private void CarregaDataInicio()
    {
        DataInicio = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
        DataFim = DataInicio.AddMonths(1).AddDays(-1);

        HiddenDataInicio.Value = DataInicio.ToString("yyyy/MM/dd");
        HiddenDataFim.Value = DataFim.ToString("yyyy/MM/dd");
    }
}
