//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class ImportarRecEntregaPage : WesPage
{

    public long HandlePeriodo
    {
        get
        {
            var linkDefinition = this.GetLinkDefinition() as FormLinkDefinition;
            if (linkDefinition != null)
            {
                var handle = linkDefinition.Parameters["HANDLEPERIODO"];
                if (handle != null)                
                    return (long)handle;                
            }
            return 0;
        }
    }

    protected void Page_Load(object sender, System.EventArgs e)
    {
        umfRecEntrega.Title = "Arraste seu arquivo aqui";
        umfRecEntrega.SubTitle = "ou se preferir clique, para fazer upload";
        var rq = new Benner.Erp.DataContracts.UploadMultipleFilesRQ()
        {
            BusinessComponentTypeName = "Benner.Corporativo.SPED.ImportarDocumento, Benner.Corporativo.SPED",
            Description = "@FILENAME - Importar arquivo"
        };
        rq.Params.TransitoryVars["HANDLEPERIODO"] = HandlePeriodo;
        rq.Params.TransitoryVars["CAMPO"] = "RECIBO";

        umfRecEntrega.RequestSubmit = rq;
    }
}
