<%@ Page Title="Aprovação preparação remessa" Language="C#" CodeFile="~/aga/e/financeiro/OfficeBanking/PreRemessaAConfirmar.aspx.cs" Inherits="OfficeBankingPreRemessaAConfirmarPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components.UI" TagPrefix="wes" %>

      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
          <div class="row">
        <wes:CommandsPanel 
            runat="server" 
            ID="COMANDOS" 
            Title="Comandos" 
            Subtitle="" 
            PortletCssClass="" 
            PortletLayout="Default" 
            BootstrapCols="12" 
            FontIcon="" 
            ShowTitle="false" 
            ProviderWidgetUniqueId="" 
            ChromeState="Normal" 
            CanDelete="False" 
            CanUpdate="False" 
            CanInsert="False" 
            EntityViewName="GN_PREREMESSAS.GRID" 
            VerticalOrientation="False" 
            Level="20" 
            Order="20"  />
        <wes:Tile
            runat="server"
            ID="VALORTOTAL_TILE"
            Title=""
            Subtitle=""
            PortletCssClass=""
            PortletLayout="None"
            BootstrapCols="3"
            FontIcon=""
            ShowTitle="false"
            ProviderWidgetUniqueId="TTULOS"
            ChromeState="Normal"
            CanDelete="True"
            CanUpdate="True"
            CanInsert="True"
            EntityViewName="FN_PARCELAPREREMESSAS.CUSTOM.GRID"
            CompanyFilterMode="OnlyCompany"
            ValueFormat="0.00"
            Prefix="Valor total"
            Description=""
            Icon="fa fa-dollar"
            Color="red"
            TileType="Flat"
            Level="20"
            Order="5"
            />
        <wes:Tile
            runat="server"
            ID="TOTALDESCONTO_TILE"
            Title=""
            Subtitle=""
            PortletCssClass=""
            PortletLayout="None"
            BootstrapCols="3"
            FontIcon=""
            ShowTitle="false"
            ProviderWidgetUniqueId="TTULOS"
            ChromeState="Normal"
            CanDelete="True"
            CanUpdate="True"
            CanInsert="True"
            EntityViewName="FN_PARCELAPREREMESSAS.CUSTOM.GRID"
            CompanyFilterMode="OnlyCompany"
            ValueFormat="0.00"
            Prefix="Total desconto"
            Description=""
            Icon="fa fa-dollar"
            Color="red"
            TileType="Flat"
            Level="20"
            Order="7"
            />
        <wes:Tile
            runat="server"
            ID="VALORESBAIXADOS_TILE"
            Title=""
            Subtitle=""
            PortletCssClass=""
            PortletLayout="None"
            BootstrapCols="3"
            FontIcon=""
            ShowTitle="false"
            ProviderWidgetUniqueId="TTULOS"
            ChromeState="Normal"
            CanDelete="True"
            CanUpdate="True"
            CanInsert="True"
            EntityViewName="FN_PARCELAPREREMESSAS.CUSTOM.GRID"
            CompanyFilterMode="OnlyCompany"
            ValueFormat="0.00"
            Prefix="Valor total baixado"
            Description=""
            Icon="fa fa-dollar"
            Color="red"
            TileType="Flat"
            Level="20"
            Order="8"
            />
        <wes:Tile
            runat="server"
            ID="VALORTOTALLQUIDO_TILE"
            Title=""
            Subtitle=""
            PortletCssClass=""
            PortletLayout="None"
            BootstrapCols="3"
            FontIcon=""
            ShowTitle="false"
            ProviderWidgetUniqueId="TTULOS"
            ChromeState="Normal"
            CanDelete="True"
            CanUpdate="True"
            CanInsert="True"
            EntityViewName="FN_PARCELAPREREMESSAS.CUSTOM.GRID"
            CompanyFilterMode="OnlyCompany"
            ValueFormat="0.00"
            Prefix="Valor total líquido"
            Description=""
            Icon="fa fa-dollar"
            Color="red"
            TileType="Flat"
            Level="20"
            Order="9"
            />
        <wes:SimpleGrid
            runat="server"
            ID="TTULOS"
            Title="Títulos"
            Subtitle=""
            PortletCssClass=""
            PortletLayout="Default"
            BootstrapCols="12"
            FontIcon=""
            ShowTitle="true"
            ProviderWidgetUniqueId=""
            ChromeState="Normal"
            CanDelete="False"
            CanUpdate="False"
            CanInsert="False"
            EntityViewName="FN_PARCELAPREREMESSAS.APROVACAO.GRID"
            Mode="None"
            UserDefinedSelectColumnVisible="False"
            UserDefinedPageSize="10"
            SystemFilterOnly="False"
            DisplayRowCommand="True"
            CompanyFilterMode="OnlyCompany"
            ShowExport="True" 
            UserDefinedDisableRowSelection="False"
            FormUrl="~/aga/e/financeiro/zoomdeparcelas/Form.aspx"
            Level="20"
            Order="10"
            />
        </div>
        <style type="text/css">
            .widget-thumb .widget-thumb-body .widget-thumb-body-stat {
                font-size: 18px;
            }
        </style>
      </asp:Content>
    