<%@ Page Title="Produção" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:Tile runat="server" ID="K9_CADASTRADAS" Title="cadastradas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K9_ORDEMPRODUCAO.DATASOURCE.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 1" Value="STATUS" Description="cadastradas" Icon="fa fa-plus" Color="blue" ValueAggregation="Count" TileType="Default" PageId="MENU_PRODUCAO" Level="40" Order="1"  />
        <wes:Tile runat="server" ID="K9_CANCELADAS" Title="Canceladas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K9_ORDEMPRODUCAO.DATASOURCE.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 5" Value="STATUS" Description="Canceladas" Icon="fa fa-times" Color="red" ValueAggregation="Count" TileType="Default" PageId="MENU_PRODUCAO" Level="40" Order="1"  />
        <wes:Tile runat="server" ID="K9_COMFIRMADAS" Title="Comfirmadas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K9_ORDEMPRODUCAO.DATASOURCE.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 2" Value="STATUS" Description="Comfirmadas" Icon="fa fa-check" Color="green" ValueAggregation="Count" TileType="Default" PageId="MENU_PRODUCAO" Level="40" Order="1"  />
        <wes:Tile runat="server" ID="K9_ENCERRADAS" Title="Encerradas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K9_ORDEMPRODUCAO.DATASOURCE.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 4" Value="STATUS" Description="Encerradas" Icon="fa fa-minus" Color="dark" ValueAggregation="Count" TileType="Default" PageId="MENU_PRODUCAO" Level="40" Order="1"  />
        <wes:AmCharts runat="server" ID="K9_PRODUO" Title="Produção" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K9_CUSTOSORDEMPRODUCAO2020_2.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJ0ZXN0ZSIsInN0YXJ0RHVyYXRpb24iOjEsImNhdGVnb3J5QXhpcyI6eyJncmlkUG9zaXRpb24iOiJzdGFydCJ9LCJncmFwaHMiOlt7ImxhYmVsVGV4dCI6IltbdmFsdWVdXSIsImJhbGxvb25UZXh0IjoiW1tjYXRlZ29yeV1dIiwiaWQiOiJBbUdyYXBoLTEiLCJ0aXRsZSI6IkN1c3RvIFByZXZpc3RvIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoiY3VzdG9wcmV2aXN0byIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxfSx7ImJhbGxvb25UZXh0IjoiW1t2YWx1ZV1dIiwibGFiZWxUZXh0IjoiW1tjYXRlZ29yeV1dIiwiaWQiOiJzZXJpZS0xNjE2NDIyODUyODIyIiwidGl0bGUiOiJDdXN0byBNYXRlcmlhbCIsInZhbHVlRmllbGQiOiJjdXN0b21hdGVyaWFsIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ0eXBlIjoiY29sdW1uIiwiYnVsbGV0IjpudWxsLCJsaW5lQWxwaGEiOjAsImZpbGxBbHBoYXMiOjEsImZpbGxDb2xvcnMiOiIjOWU5YzljIiwibGluZUNvbG9yIjoiIzllOWM5YyIsImJ1bGxldENvbG9yIjoiIzllOWM5YyJ9XSwidmFsdWVBeGVzIjpbeyJpZCI6IlZhbHVlQXhpcy0xIiwidGl0bGUiOiJUb3RhaXMifV0sImxlZ2VuZCI6eyJlbmFibGVkIjp0cnVlLCJwb3NpdGlvbiI6ImJvdHRvbSIsInVzZUdyYXBoU2V0dGluZ3MiOnRydWV9LCJyb3RhdGUiOmZhbHNlfQ==" PageId="MENU_PRODUCAO" Level="40" Order="1"  />
        <wes:MenuWidget runat="server" ID="MENU" Title="Produção" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" MenuID="AGA_PRODUCAO" PageId="MENU_PRODUCAO" Level="20" Order="2"  />
        </div>
    
      </asp:Content>
    