<%@ Page Title="Pré-recebimento físico" Language="C#" Inherits="Benner.Corporativo.Wes.WebApp.aga.a.materiais.preRecebimentoFisico.PreRecebimentoItens" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="PRRECEBIMENTOFSICO" Title="Pré-recebimento físico" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="5" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="True" CanInsert="False" EntityViewName="CP_PRERECEBIMENTONFES.PRERECEBIMENTO.FORM" FormMode="View" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="AGA_A_MATERIAIS_PRERECEBIMENTOFISICO_PRERECEBIMENTOFISICOFORM" Level="20" Order="10"  />
        <wes:Tile runat="server" ID="QUANTIDADEDEREGISTROS" Title="Quantidade de registros" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="PRRECEBIMENTOFSICO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CP_PRERECEBIMENTONFEITENS.PRERECEBIMENTO.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.PRERECEBIMENTO = @TABELA(CP_PRERECEBIMENTONFES)" Value="HANDLE" Description="Total de itens" Icon="fa fa-check" Color="blue" ValueAggregation="Count" TileType="Default" PageId="AGA_A_MATERIAIS_PRERECEBIMENTOFISICO_PRERECEBIMENTOFISICOFORM" Level="20" Order="15"  />
        <wes:Tile runat="server" ID="VALORTOTALDOSITENS" Title="Valor total dos itens" Subtitle="" PortletCssClass="" PortletLayout="Custom" BootstrapCols="4" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="PRRECEBIMENTOFSICO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CP_PRERECEBIMENTONFEITENS.QUNTIDADEITENS.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.PRERECEBIMENTO = @CAMPO(HANDLE)" ValueFormat="C2" Value="VALORTOTAL" Description="Valor total dos itens" Icon="fa fa-money" Color="blue" ValueAggregation="Sum" TileType="Default" PageId="AGA_A_MATERIAIS_PRERECEBIMENTOFISICO_PRERECEBIMENTOFISICOFORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="ITENSNFE" Title="Itens NF-E" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="7" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="PRRECEBIMENTOFSICO" ChromeState="Normal" CanDelete="False" CanUpdate="True" CanInsert="False" EntityViewName="CP_PRERECEBIMENTONFEITENS.PRERECEBIMENTO.GRID" DefaultFilterName="Visualizar somente itens sem informação do produto" Mode="Fixed" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PRERECEBIMENTO = @CAMPO(HANDLE)" FormUrl="~/aga/a/materiais/preRecebimentoFisico/itensNFeForm.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_A_MATERIAIS_PRERECEBIMENTOFISICO_PRERECEBIMENTOFISICOFORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="ITENSNFE_1" Title="Itens NF-e" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="ITENSNFE" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CP_PRERECEBIMENTONFEITEMCONT.PRERECEBIMENTO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_A_MATERIAIS_PRERECEBIMENTOFISICO_PRERECEBIMENTOFISICOFORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="ITENSNFE_2" Title="Itens NF-e" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="ITENSNFE" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CP_PRERECEBIMENTONFEITEMDEV.PRERECEBIMENTO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_A_MATERIAIS_PRERECEBIMENTOFISICO_PRERECEBIMENTOFISICOFORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="ITENSNFE_3" Title="Itens NF-e" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="ITENSNFE" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="CP_PRERECEBIMENTONFEITEMOCS.ITENSOC.GRID" Mode="Search" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" FormUrl="~/aga/a/materiais/preRecebimentoFisico/ItemPreRecebimentoNfe.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="AGA_A_MATERIAIS_PRERECEBIMENTOFISICO_PRERECEBIMENTOFISICOFORM" Level="20" Order="50"  />
        </div>
    
        <style>
              .wes-tile a:not([href]) {
    height: 100px !important;
}

              </style>
      </asp:Content>
    