<%@ Page Title="Inicio - GDQ" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:Tile runat="server" ID="K_ATIVIDADESREALIZADASNASEMANA" Title="Atividades Realizadas na Semana" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.STATUS = 2 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO BETWEEN @SEMANA[1] AND @SEMANA[2] " CommandName="cmdAtividades" Value="CODIGO" Description="Atividades Realizadas na Semana" Icon="fa fa-cog fa-spin" Color="green-jungle" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEGDQ" Level="50" Order="10"  />
        <wes:Tile runat="server" ID="K_AGENDAMENTOSATRASADOS" Title="Agendamentos Atrasados" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &lt; @HOJE " CommandName="cmdAgendamentosAtrasados" Value="CODIGO" Description="Agendamentos Atrasados" Icon="fa fa-clock-o" Color="red" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEGDQ" Level="50" Order="20"  />
        <wes:Tile runat="server" ID="K_SUPORTESEMABERTO" Title="Suportes em Aberto" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="2" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_CHAMADOS.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.USUARIOINCLUSAO = @USUARIO AND A.STATUS IN (1)" CommandName="REDIRECT_MEUS_CHAMADOS" Value="HANDLE" Description="Suportes em Aberto" Icon="fa fa-list" Color="blue" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEGDQ" Level="50" Order="27"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESAGENDADASPARAHOJE" Title="Atividades Agendadas para hoje" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="2" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt;= DATEADD(day, DATEDIFF(day,0,GETDATE()),0) 
AND A.DATAAGENDAMENTO &lt; DATEADD(day, DATEDIFF(day,0,GETDATE())+1,0)
" CommandName="cmdAtividadesHoje" Value="CODIGO" Description="Atividades Agendadas para hoje" Icon="fa fa-clock-o" Color="yellow-gold" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEGDQ" Level="50" Order="30"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESAGENDADASFUTURAS" Title="Atividades Agendadas Futuras" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="2" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt; DATEADD(day, DATEDIFF(day,0,GETDATE())+1,0)" CommandName="cmdAtividadesFuturas" Value="CODIGO" Description="Atividades Agendadas Futuras" Icon="fa fa-line-chart" Color="blue" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEGDQ" Level="50" Order="40"  />
        <wes:ActionView runat="server" ID="K_CALENDRIOUSURIO" Title="Calendário Usuário" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" Controller="CalendarioCrm" Action="CalendarioUsuario" PageId="K_PAGES_HOMEGDQ" Level="50" Order="48"  />
        <wes:AmCharts runat="server" ID="K_CONTASXSUFASE" Title="Contas X Sufase" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_GRAPH_QTD_CONTAS_POR_SUBFASE.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" ChartType="Pie" ChartHeight="500" ChartDefinition="eyJ0eXBlIjoicGllIiwibGFuZ3VhZ2UiOiJwdCIsInB1bGxPdXRPbmx5T25lIjp0cnVlLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sInRpdGxlRmllbGQiOiJub21lIiwidmFsdWVGaWVsZCI6InF0ZCIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwiYmFsbG9vblRleHQiOiJbW3RpdGxlXV08YnI+PHNwYW4gc3R5bGU9J2ZvbnQtc2l6ZToxNHB4Jz48Yj5bW3ZhbHVlXV08L2I+IChbW3BlcmNlbnRzXV0lKTwvc3Bhbj4iLCJsYWJlbFRleHQiOiJbW3RpdGxlXV06IFtbcGVyY2VudHNdXSUiLCJsYWJlbHNFbmFibGVkIjp0cnVlLCJsZWdlbmQiOnsiZW5hYmxlZCI6ZmFsc2UsImFsaWduIjoiY2VudGVyIiwibWFya2VyVHlwZSI6ImNpcmNsZSJ9LCJpbm5lclJhZGl1cyI6IjAlIiwidmVyc2lvbiI6IjQifQ==" PageId="K_PAGES_HOMEGDQ" Level="50" Order="50"  />
        </div>
    
      </asp:Content>
    