<%@ Page Title="Início - Administrador" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:Tile runat="server" ID="K_ATIVIDADESREALIZADASNASEMANA" Title="Atividades Realizadas na Semana" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.RESPONSAVEL = @USUARIO and A.DATACONCLUSAO BETWEEN @SEMANA[1] AND @SEMANA[2] " CommandName="cmdAtividades" Value="CODIGO" Description="Ativ. Realizadas na Semana" Icon="fa fa-cog fa-spin" Color="green-jungle" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEADMINISTRADOR" Level="50" Order="10"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESPENDENTES" Title="Atividades Pendentes" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &lt; @HOJE" CommandName="cmdAtividadesPendentes" Value="CODIGO" Description="Atividades Pendentes" Icon="fa fa-clock-o" Color="red" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEADMINISTRADOR" Level="50" Order="20"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESPARAHOJE" Title="Atividades para hoje" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="2" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt;= DATEADD(day, DATEDIFF(day,0,GETDATE()),0) 
AND A.DATAAGENDAMENTO &lt; DATEADD(day, DATEDIFF(day,0,GETDATE())+1,0)
" CommandName="cmdAtividadesHoje" Value="CODIGO" Description="Atividades para hoje" Icon="fa fa-clock-o" Color="yellow-gold" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEADMINISTRADOR" Level="50" Order="30"  />
        <wes:Tile runat="server" ID="K_SOLICITAESDEDESCONTO" Title="Solicitações de Desconto" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="2" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PO_DESCONTOS.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 2 AND A.OPORTUNIDADE IN (SELECT HANDLE FROM K_CRM_PESSOAOPORTUNIDADES WHERE FILIAL IN (SELECT HANDLE FROM FILIAIS WHERE K_EHREVENDA = 'N'))" CommandName="REDIRECT_DESCONTO" Value="OPORTUNIDADE" Description="Solicitações de Desconto" Icon="fa fa-dollar" Color="green-jungle" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEADMINISTRADOR" Level="50" Order="38"  />
        <wes:Tile runat="server" ID="K_SOLICITAESDECONTA" Title="Solicitações de conta" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="2" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOASOLICITACOES.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 1" CommandName="GO_SOLICITACOES" Value="SOLICITACAO" Description="Solicitações de conta" Icon="fa fa-clock-o fa-spin" Color="yellow-casablanca" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEADMINISTRADOR" Level="50" Order="46"  />
        <wes:Tile runat="server" ID="K_ATENDIMENTOSN1" Title="Atendimentos N1" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_CHAMADOS.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.NIVEL IN (1)" CommandName="REDIRECT_CHAMADOS_N1" Value="HANDLE" Description="Suporte N1" Icon="fa fa-list" Color="red-intense" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEADMINISTRADOR" Level="50" Order="50"  />
        <wes:Tile runat="server" ID="K_ATENDIMENTOSN2" Title="Atendimentos N2" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_CHAMADOS.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.NIVEL IN (2)" CommandName="REDIRECT_CHAMADOS_N2" Value="HANDLE" Description="Suporte N2" Icon="fa fa-list" Color="yellow-casablanca" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEADMINISTRADOR" Level="50" Order="51"  />
        <wes:Tile runat="server" ID="K_SUPORTESEMABERTO" Title="Suportes em Aberto" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_CHAMADOS.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS IN (1)" CommandName="REDIRECT_CHAMADOS" Value="HANDLE" Description="Suportes em Aberto" Icon="fa fa-list" Color="blue" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEADMINISTRADOR" Level="50" Order="51"  />
        <wes:Tile runat="server" ID="K_EMATENDIMENTO" Title="Em Atendimento" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_CHAMADOS.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS NOT IN (1,4)" CommandName="REDIRECT_CHAMADOS_EM_ATENDIMENTO" Value="HANDLE" Description="Em Atendimento" Icon="fa fa-clock-o" Color="yellow-crusta" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEADMINISTRADOR" Level="50" Order="52"  />
        <wes:ActionView runat="server" ID="K_CALENDRIOUSURIO" Title="Calendário Usuário" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" Controller="CalendarioCrm" Action="CalendarioUsuario" PageId="K_PAGES_HOMEADMINISTRADOR" Level="50" Order="52"  />
        <wes:AmCharts runat="server" ID="K_CONTASSUGAR" Title="Contas Sugar" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_SUGAR_STATUS.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" ChartType="Pie" ChartHeight="500" ChartDefinition="eyJ0eXBlIjoicGllIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJwdWxsT3V0T25seU9uZSI6dHJ1ZSwiZXhwb3J0Ijp7ImVuYWJsZWQiOnRydWV9LCJ0aXRsZUZpZWxkIjoicm90dWxvIiwidmFsdWVGaWVsZCI6InRvdGFsIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJiYWxsb29uVGV4dCI6IltbdGl0bGVdXTxicj48c3BhbiBzdHlsZT0nZm9udC1zaXplOjE0cHgnPjxiPltbdmFsdWVdXTwvYj4gKFtbcGVyY2VudHNdXSUpPC9zcGFuPiIsImxhYmVsVGV4dCI6IltbdGl0bGVdXTogW1t2YWx1ZV1dIiwibGFiZWxzRW5hYmxlZCI6dHJ1ZSwibGVnZW5kIjp7ImVuYWJsZWQiOmZhbHNlLCJhbGlnbiI6ImNlbnRlciIsIm1hcmtlclR5cGUiOiJjaXJjbGUifSwiaW5uZXJSYWRpdXMiOiIwJSIsImFuZ2xlIjozMCwiZGVwdGgzRCI6MzB9" PageId="K_PAGES_HOMEADMINISTRADOR" Level="50" Order="80"  />
        <wes:AmCharts runat="server" ID="K_CONTASXRAMODEATIVIDADE" Title="Contas x Ramo de atividade" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_GDQ_CONTA_RAMOATIVIDADE.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" ChartType="Pie" ChartHeight="500" ChartDefinition="eyJ0eXBlIjoicGllIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJwdWxsT3V0T25seU9uZSI6dHJ1ZSwiZXhwb3J0Ijp7ImVuYWJsZWQiOnRydWV9LCJ0aXRsZUZpZWxkIjoidGV4dG8iLCJ2YWx1ZUZpZWxkIjoicXVhbnRpZGFkZSIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwiYmFsbG9vblRleHQiOiJbW3RpdGxlXV08YnI+PHNwYW4gc3R5bGU9J2ZvbnQtc2l6ZToxNHB4Jz48Yj5bW3ZhbHVlXV08L2I+IChbW3BlcmNlbnRzXV0lKTwvc3Bhbj4iLCJsYWJlbFRleHQiOiJbW3RpdGxlXV06IFtbcGVyY2VudHNdXSUiLCJsYWJlbHNFbmFibGVkIjp0cnVlLCJsZWdlbmQiOnsiZW5hYmxlZCI6dHJ1ZSwiYWxpZ24iOiJjZW50ZXIiLCJtYXJrZXJUeXBlIjoiY2lyY2xlIiwicG9zaXRpb24iOiJib3R0b20ifSwiaW5uZXJSYWRpdXMiOiIwJSIsImFuZ2xlIjowLCJkZXB0aDNEIjowfQ==" PageId="K_PAGES_HOMEADMINISTRADOR" Level="50" Order="91"  />
        </div>
    
      </asp:Content>
    