<%@ Page Title="Início - Gestor Produto" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AmCharts runat="server" ID="K_FUNILDESTATUSQUANTIDADE" Title="Funil de Status (Quantidade)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_FUNIL_STATUS_QTDE_GESTOR_PRODUTO.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoiZnVubmVsIiwidGhlbWUiOiJsaWdodCIsImJhbGxvb24iOnsiZml4ZWRQb3NpdGlvbiI6dHJ1ZX0sInZhbHVlRmllbGQiOiJxdGRldGVtcCIsInRpdGxlRmllbGQiOiJ0ZW1wZXJhdHVyYSIsIm1hcmdpblJpZ2h0IjoyNDAsIm1hcmdpbkxlZnQiOjUwLCJzdGFydFgiOi01MDAsImRlcHRoM0QiOjEwMCwiYW5nbGUiOjQwLCJjb2xvckZpZWxkIjoiY29yIiwiZmlsbEFscGhhcyI6MC45LCJsaW5lQWxwaGEiOjAuMiwibGFiZWxQb3NpdGlvbiI6InJpZ2h0IiwiYmFsbG9vblRleHQiOiJbW3RlbXBlcmF0dXJhXV06IFtbcXRkZXRlbXBdXSIsImV4cG9ydCI6eyJlbmFibGVkIjp0cnVlfX0=" PageId="K_PAGES_HOMEGESTORPRODUTO" Level="50" Order="10"  />
        <wes:AmCharts runat="server" ID="K_FUNILDESTATUSVALOR" Title="Funil de Status (Valor)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_FUNIL_STATUS_VALOR_GESTOR_PRODUTO.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoiZnVubmVsIiwidGhlbWUiOiJsaWdodCIsImJhbGxvb24iOnsiZml4ZWRQb3NpdGlvbiI6dHJ1ZX0sInZhbHVlRmllbGQiOiJ2YWxvcnRlbXAiLCJ0aXRsZUZpZWxkIjoidGVtcGVyYXR1cmEiLCJtYXJnaW5SaWdodCI6MjQwLCJtYXJnaW5MZWZ0Ijo1MCwic3RhcnRYIjotNTAwLCJkZXB0aDNEIjoxMDAsImFuZ2xlIjo0MCwiY29sb3JGaWVsZCI6ImNvciIsImZpbGxBbHBoYXMiOjAuOSwibGluZUFscGhhIjowLjIsImxhYmVsUG9zaXRpb24iOiJyaWdodCIsImJhbGxvb25UZXh0IjoiW1t0ZW1wZXJhdHVyYV1dOiBbW3ZhbG9ydGVtcF1dIiwiZXhwb3J0Ijp7ImVuYWJsZWQiOnRydWV9fQ==" PageId="K_PAGES_HOMEGESTORPRODUTO" Level="50" Order="20"  />
        <wes:AmCharts runat="server" ID="K_FUNILDEFASESQUANTIDADE" Title="Funil de Fases (Quantidade)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_FUNIL_FASE_QTDE_GESTOR_PRODUTO.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoiZnVubmVsIiwidGhlbWUiOiJsaWdodCIsImJhbGxvb24iOnsiZml4ZWRQb3NpdGlvbiI6dHJ1ZX0sInZhbHVlRmllbGQiOiJxdGRlZmFzZXMiLCJ0aXRsZUZpZWxkIjoiZmFzZSIsIm1hcmdpblJpZ2h0IjoyNDAsIm1hcmdpbkxlZnQiOjUwLCJzdGFydFgiOi01MDAsImRlcHRoM0QiOjEwMCwiYW5nbGUiOjQwLCJmaWxsQWxwaGFzIjowLjksImxpbmVBbHBoYSI6MC4yLCJsYWJlbFBvc2l0aW9uIjoicmlnaHQiLCJiYWxsb29uVGV4dCI6IltbZmFzZV1dOiBbW3F0ZGVmYXNlc11dIiwiZXhwb3J0Ijp7ImVuYWJsZWQiOnRydWV9fQ==" PageId="K_PAGES_HOMEGESTORPRODUTO" Level="50" Order="30"  />
        <wes:AmCharts runat="server" ID="K_FUNILDEFASESVALOR" Title="Funil de Fases (Valor)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_FUNIL_FASE_VALOR_GESTOR_PRODUTO.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoiZnVubmVsIiwidGhlbWUiOiJsaWdodCIsImJhbGxvb24iOnsiZml4ZWRQb3NpdGlvbiI6dHJ1ZX0sInZhbHVlRmllbGQiOiJ2YWxvcmZhc2VzIiwidGl0bGVGaWVsZCI6ImZhc2UiLCJtYXJnaW5SaWdodCI6MjQwLCJtYXJnaW5MZWZ0Ijo1MCwic3RhcnRYIjotNTAwLCJkZXB0aDNEIjoxMDAsImFuZ2xlIjo0MCwiZmlsbEFscGhhcyI6MC45LCJsaW5lQWxwaGEiOjAuMiwibGFiZWxQb3NpdGlvbiI6InJpZ2h0IiwiYmFsbG9vblRleHQiOiJbW2Zhc2VdXTogW1t2YWxvcmZhc2VzXV0iLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX19" PageId="K_PAGES_HOMEGESTORPRODUTO" Level="50" Order="40"  />
        </div>
    
      </asp:Content>
    