<%@ Page Title="Home" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:Tile runat="server" ID="K_ATIVIDADESDASEMANA" Title="Atividades da Semana" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CriteriaWhereClause="A.STATUS = 2 AND A.RESPONSAVEL = @USUARIO and A.DATACONCLUSAO BETWEEN @SEMANA[1] AND @SEMANA[2] " CommandName="cmdAtividades" Value="CODIGO" Description="Atividades Realizadas na Semana" Icon="fa fa-cog fa-spin" Color="green" ValueAggregation="Count" TileType="Default" PageId="PAGES_HOME" Level="50" Order="10"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESPENDENTES" Title="Atividades Pendentes" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &lt; @HOJE " CommandName="cmdAgendamentosAtrasados" Value="CODIGO" Description="Agendamentos Atrasados" Icon="fa fa-clock-o" Color="red" ValueAggregation="Count" TileType="Default" PageId="PAGES_HOME" Level="50" Order="20"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESPARAHOJE" Title="Atividades para hoje" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt;= DATEADD(day, DATEDIFF(day,0,GETDATE()),0) 
AND A.DATAAGENDAMENTO &lt; DATEADD(day, DATEDIFF(day,0,GETDATE())+1,0)" CommandName="cmdAtividadesHoje" Value="CODIGO" Description="Atividades Agendadas para hoje" Icon="fa fa-clock-o" Color="green-jungle" ValueAggregation="Count" TileType="Default" PageId="PAGES_HOME" Level="50" Order="30"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESFUTURAS" Title="Atividades Futuras" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt; DATEADD(day, DATEDIFF(day,0,GETDATE())+1,0)" CommandName="cmdAtividadesFuturas" Value="CODIGO" Description="Atividades Agendadas Futuras" Icon="fa fa-line-chart" Color="blue" ValueAggregation="Count" TileType="Default" PageId="PAGES_HOME" Level="50" Order="40"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADESAGUARDANDOAPROVAO" Title="Oportunidades Aguardando Aprovação" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CriteriaWhereClause="A.STATUS IN (11,12,13)" CommandName="cmdCancelaOportunidade" Value="CODIGO" Description="Oportunidades Aguardando Posição" Icon="fa fa-check" Color="grey-cascade" ValueAggregation="Count" TileType="Default" PageId="PAGES_HOME" Level="50" Order="50"  />
        <wes:Tile runat="server" ID="K_LEADSAGUARDANDOAPROVAO" Title="Leads Aguardando Aprovação" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAS.GRID" CriteriaWhereClause="A.SUBFASE = 43" CommandName="cmdRedirectRecLead" Value="CODIGO" Description="Leads Aguardando Aprovação" Icon="fa fa-check" Color="grey-cascade" ValueAggregation="Count" TileType="Default" PageId="PAGES_HOME" Level="50" Order="60"  />
        </div>
    
      </asp:Content>
    