<%@ Page Title="Início - Vendedor" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:Tile runat="server" ID="K_ATIVIDADESREALIZADASNASEMANA" Title="Atividades Realizadas na Semana" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CriteriaWhereClause="A.RESPONSAVEL = @USUARIO and A.DATACONCLUSAO BETWEEN @SEMANA[1] AND @SEMANA[2] " CommandName="cmdAtividades" Value="CODIGO" Description="Atividades Realizadas na Semana" Icon="fa fa-cog fa-spin" Color="green" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEVENDEDOR" Level="50" Order="10"  />
        <wes:Tile runat="server" ID="K_AGENDAMENTOSPENDENTES" Title="Agendamentos Pendentes" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &lt; @HOJE " CommandName="cmdAgendamentosAtrasados" Value="CODIGO" Description="Agendamentos Atrasados" Icon="fa fa-clock-o" Color="red" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEVENDEDOR" Level="50" Order="14"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESPARAHOJE" Title="Atividades para hoje" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt;= DATEADD(day, DATEDIFF(day,0,GETDATE()),0) 
AND A.DATAAGENDAMENTO &lt; DATEADD(day, DATEDIFF(day,0,GETDATE())+1,0)" CommandName="cmdAtividadesHoje" Value="CODIGO" Description="Atividades Agendadas para hoje" Icon="fa fa-clock-o" Color="green-jungle" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEVENDEDOR" Level="50" Order="16"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESFUTURAS" Title="Atividades Futuras" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt; DATEADD(day, DATEDIFF(day,0,GETDATE())+1,0)" CommandName="cmdAtividadesFuturas" Value="CODIGO" Description="Atividades Agendadas Futuras" Icon="fa fa-line-chart" Color="blue" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEVENDEDOR" Level="50" Order="18"  />
        <wes:AmCharts runat="server" ID="K_EFICINCIASEMANAS" Title="Eficiência - semanas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PERFORMANCE_SEMANAS_ANTERIORES_V3.DATASOURCE.GRID" Mode="None" ChartType="Line" ChartHeight="320" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJzZW1hbmEiLCJzdGFydER1cmF0aW9uIjoxLCJjYXRlZ29yeUF4aXMiOnsiZ3JpZFBvc2l0aW9uIjoic3RhcnQifSwiZ3JhcGhzIjpbeyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6IlNlbWFuYSBbW2NhdGVnb3J5XV0gOiBbW3ZhbHVlXV0gJSIsImlkIjoiQW1HcmFwaC0xIiwidGl0bGUiOiJQZXJmb3JtYW5jZSAlIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoicG9yY2VudGFnZW0iLCJ0eXBlIjoibGluZSIsImZpbGxBbHBoYXMiOjAsImJ1bGxldCI6InJvdW5kIn1dLCJ2YWx1ZUF4ZXMiOlt7ImlkIjoiVmFsdWVBeGlzLTEiLCJ0aXRsZSI6IiJ9XSwibGVnZW5kIjp7ImVuYWJsZWQiOnRydWUsInBvc2l0aW9uIjoiYm90dG9tIiwidXNlR3JhcGhTZXR0aW5ncyI6dHJ1ZX19" PageId="K_PAGES_HOMEVENDEDOR" Level="50" Order="20"  />
        <wes:CustomUserControl runat="server" ID="K_TESTE" Title="Teste" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" UserControlName="~/Pages/K_CRM_PESSOAS/e/uc/PerformancePreVendedor.ascx" PageId="K_PAGES_HOMEVENDEDOR" Level="50" Order="22"  />
        <wes:CustomUserControl runat="server" ID="K_PERFORMANCEMSANTERIOR" Title="Performance Mês Anterior" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" UserControlName="~/Pages/K_CRM_PESSOAS/e/uc/PerPreVendedorMesAnterior.ascx" PageId="K_PAGES_HOMEVENDEDOR" Level="50" Order="24"  />
        <wes:AmCharts runat="server" ID="K_FUNILLEADSMS" Title="Funil - Leads mês" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PERFORMANCE_SUSP.DATASOURCE.GRID" Mode="None" ChartType="Column" ChartHeight="300" ChartDefinition="eyJ0eXBlIjoiZnVubmVsIiwidGhlbWUiOiJsaWdodCIsImJhbGxvb24iOnsiZml4ZWRQb3NpdGlvbiI6dHJ1ZX0sInZhbHVlRmllbGQiOiJlbnRyYWRhIiwidGl0bGVGaWVsZCI6InN1YmZhc2UiLCJtYXJnaW5SaWdodCI6MjQwLCJtYXJnaW5MZWZ0Ijo1MCwic3RhcnRYIjotNTAwLCJkZXB0aDNEIjoxMDAsImFuZ2xlIjo0MCwiZmlsbEFscGhhcyI6MC45LCJsaW5lQWxwaGEiOjAuMiwibGFiZWxQb3NpdGlvbiI6InJpZ2h0IiwiYmFsbG9vblRleHQiOiJbW3N1YmZhc2VdXTogW1tlbnRyYWRhXV0iLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX19" PageId="K_PAGES_HOMEVENDEDOR" Level="50" Order="32"  />
        <wes:AmCharts runat="server" ID="K_SUSPECO" Title="Suspecção" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_LEADS_PORFASE.DATASOURCE.GRID" Mode="None" ChartType="Pie" ChartHeight="300" ChartDefinition="eyJ0eXBlIjoicGllIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJwdWxsT3V0T25seU9uZSI6dHJ1ZSwiZXhwb3J0Ijp7ImVuYWJsZWQiOnRydWV9LCJ0aXRsZUZpZWxkIjoic3ViZmFzZSIsInZhbHVlRmllbGQiOiJxdGRlIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJiYWxsb29uVGV4dCI6IltbdGl0bGVdXTxicj48c3BhbiBzdHlsZT0nZm9udC1zaXplOjE0cHgnPjxiPltbdmFsdWVdXTwvYj4gKFtbcGVyY2VudHNdXSUpPC9zcGFuPiIsImxhYmVsVGV4dCI6IltbdmFsdWVdXSIsImxhYmVsc0VuYWJsZWQiOnRydWUsImxlZ2VuZCI6eyJlbmFibGVkIjp0cnVlLCJhbGlnbiI6ImNlbnRlciIsIm1hcmtlclR5cGUiOiJjaXJjbGUiLCJwb3NpdGlvbiI6ImxlZnQifSwiaW5uZXJSYWRpdXMiOiIwJSJ9" PageId="K_PAGES_HOMEVENDEDOR" Level="50" Order="36"  />
        </div>
    
      </asp:Content>
    