<%@ Page Title="Inicio - Assist. Com." Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:Tile runat="server" ID="K_ATIVIDADESREALIZADASNASEMANA" Title="Atividades Realizadas na Semana" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.DIRETOR_REGIONAL.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.DATACONCLUSAO BETWEEN @SEMANA[1] AND @SEMANA[2]  AND A.RESPONSAVEL IN (SELECT USUARIO FROM Z_GRUPOUSUARIOEMPRESAFILIAIS WHERE FILIAL = @FILIAL) AND A.PESSOA IN (SELECT CODIGO FROM K_CRM_PESSOAS WHERE FILIAL=@FILIAL)" CommandName="cmdAtividadesFilial" Value="CODIGO" Description="Atividades Realizadas na Semana" Icon="fa fa-cog fa-spin" Color="green-jungle" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEASSISTENTECOMERCIAL" Level="50" Order="10"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESPENDENTES" Title="Atividades Pendentes" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.DIRETOR_REGIONAL.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL IN (SELECT USUARIO FROM Z_GRUPOUSUARIOEMPRESAFILIAIS WHERE FILIAL = @FILIAL) AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &lt; @HOJE AND A.PESSOA IN (SELECT CODIGO FROM K_CRM_PESSOAS WHERE FILIAL=@FILIAL)" CommandName="cmdAtividadesPendentesFilial" Value="CODIGO" Description="Atividades Pendentes" Icon="fa fa-clock-o" Color="red" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEASSISTENTECOMERCIAL" Level="50" Order="20"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESPARAHOJE" Title="Atividades para hoje" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.DIRETOR_REGIONAL.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL IN (SELECT USUARIO FROM Z_GRUPOUSUARIOEMPRESAFILIAIS WHERE FILIAL = @FILIAL) AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt;= DATEADD(day, DATEDIFF(day,0,GETDATE()),0) 
AND A.DATAAGENDAMENTO &lt; DATEADD(day, DATEDIFF(day,0,GETDATE())+1,0) AND A.PESSOA IN (SELECT CODIGO FROM K_CRM_PESSOAS WHERE FILIAL=@FILIAL)
" CommandName="cmdAtividadesHojeFilial" Value="CODIGO" Description="Atividades para hoje" Icon="fa fa-clock-o" Color="yellow-gold" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEASSISTENTECOMERCIAL" Level="50" Order="30"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESFUTURAS" Title="Atividades Futuras" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.DIRETOR_REGIONAL.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.RESPONSAVEL IN (SELECT USUARIO FROM Z_GRUPOUSUARIOEMPRESAFILIAIS WHERE FILIAL = @FILIAL) AND A.STATUS = 1 AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt; DATEADD(day, DATEDIFF(day,0,GETDATE())+1,0) AND A.PESSOA IN (SELECT CODIGO FROM K_CRM_PESSOAS WHERE FILIAL=@FILIAL)" CommandName="cmdAtividadesFuturasFilial" Value="CODIGO" Description="Atividades Futuras" Icon="fa fa-line-chart" Color="blue" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEASSISTENTECOMERCIAL" Level="50" Order="40"  />
        <wes:Tile runat="server" ID="K_MINHASCONTAS" Title="Minhas Contas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAS.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.USUARIOEXECUTIVO IN (SELECT USUARIO FROM Z_GRUPOUSUARIOEMPRESAFILIAIS WHERE FILIAL = @FILIAL)" CommandName="REDIRECT_CONTAS_FILIAL" Value="CODIGO" Description="Minhas Contas" Icon="fa fa-user" Color="default" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEASSISTENTECOMERCIAL" Level="50" Order="50"  />
        <wes:Tile runat="server" ID="K_MINHASVERTICAIS" Title="Minhas Verticais" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAVERTICAL.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.USUARIOEXECUTIVO IN (SELECT USUARIO FROM Z_GRUPOUSUARIOEMPRESAFILIAIS WHERE FILIAL = @FILIAL)" CommandName="REDIRECT_CONTAS_FILIAL" Value="CODIGO" Description="Minhas Verticais" Icon="fa fa-user" Color="default" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEASSISTENTECOMERCIAL" Level="50" Order="60"  />
        <wes:Tile runat="server" ID="K_MINHASOPORTUNIDADES" Title="Minhas Oportunidades" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.RESPONSAVEL IN (SELECT USUARIO FROM Z_GRUPOUSUARIOEMPRESAFILIAIS WHERE FILIAL = @FILIAL) AND A.STATUSOPORTUNIDADE NOT IN (7,14,15,16,17,18)" CommandName="REDIRECT_OPORTUNIDADES_FILIAL" Value="CODIGO" Description="Minhas Oportunidades" Icon="fa fa-dollar" Color="default" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEASSISTENTECOMERCIAL" Level="50" Order="70"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADESVENCIDAS" Title="Oportunidades Vencidas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.RESPONSAVEL IN (SELECT USUARIO FROM Z_GRUPOUSUARIOEMPRESAFILIAIS WHERE FILIAL = @FILIAL) AND A.DATAFECHAMENTO &lt; GETDATE() AND A.STATUSOPORTUNIDADE NOT IN (7,14,15,16,17,18,19,20)" CommandName="REDIRECT_OPORTUNIDADES_VENCIDAS_FILIAL" Value="CODIGO" Description="Oportunidades Vencidas" Icon="fa fa-dollar" Color="red" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEASSISTENTECOMERCIAL" Level="50" Order="80"  />
        <wes:Tile runat="server" ID="K_SUPORTESEMABERTO" Title="Suportes em Aberto" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_CHAMADOS.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.USUARIOINCLUSAO  = @USUARIO AND A.STATUS IN (1)" CommandName="REDIRECT_MEUS_CHAMADOS" Value="HANDLE" Description="Suportes em Aberto" Icon="fa fa-list" Color="blue" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEASSISTENTECOMERCIAL" Level="50" Order="89"  />
        <wes:Tile runat="server" ID="K_MEUSSEMFOROS" Title="Meus Semáforos" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOASEMAFORO.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.EXECUTIVOCONTAS IN (SELECT USUARIO FROM Z_GRUPOUSUARIOEMPRESAFILIAIS WHERE FILIAL = @FILIAL) AND A.PESSOA IN (SELECT HANDLE FROM K_CRM_PESSOAS WHERE FILIAL = @FILIAL)" CommandName="REDIRECT_SEMAFORO_FILIAL" Value="CODIGO" Description="Meus Semáforos" Icon="fa fa-check" Color="blue-hoki" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEASSISTENTECOMERCIAL" Level="50" Order="90"  />
        </div>
    
      </asp:Content>
    