<%@ Page Title="Inicio - Diretoria" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:Tile runat="server" ID="K_ATIVIDADESREALIZADASNASEMANA" Title="Atividades Realizadas na Semana" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.DATACONCLUSAO BETWEEN @SEMANA[1] AND @SEMANA[2]" CommandName="cmdAtividadesSemana" Value="CODIGO" Description="Atividades Realizadas na Semana" Icon="fa fa-cog fa-spin" Color="green-jungle" ValueAggregation="Count" TileType="Default" PageId="K_CRM_DIRETORIA" Level="50" Order="10"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESPENDENTES" Title="Atividades Pendentes" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.STATUS = 1 AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &lt; @HOJE" CommandName="cmdAtividadesPendentesGeral" Value="CODIGO" Description="Atividades Pendentes" Icon="fa fa-clock-o" Color="red" ValueAggregation="Count" TileType="Default" PageId="K_CRM_DIRETORIA" Level="50" Order="20"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESPARAHOJE" Title="Atividades para hoje" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.STATUS = 1 AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt;= DATEADD(day, DATEDIFF(day,0,GETDATE()),0) AND A.DATAAGENDAMENTO &lt; DATEADD(day, DATEDIFF(day,0,GETDATE())+1,0)" CommandName="cmdAtividadesHojeGeral" Value="CODIGO" Description="Atividades para hoje" Icon="fa fa-clock-o" Color="yellow-gold" ValueAggregation="Count" TileType="Default" PageId="K_CRM_DIRETORIA" Level="50" Order="30"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESFUTURAS" Title="Atividades Futuras" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.STATUS = 1 AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt; DATEADD(day, DATEDIFF(day,0,GETDATE())+1,0)" CommandName="cmdAtividadesFuturasGeral" Value="CODIGO" Description="Atividades Futuras" Icon="fa fa-line-chart" Color="blue" ValueAggregation="Count" TileType="Default" PageId="K_CRM_DIRETORIA" Level="50" Order="40"  />
        <wes:Tile runat="server" ID="K_MINHASCONTAS" Title="Minhas Contas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAS.GRID" CompanyFilterMode="OnlyCompany" CommandName="REDIRECT_CONTAS" Value="CODIGO" Description="Contas" Icon="fa fa-user" Color="default" ValueAggregation="Count" TileType="Default" PageId="K_CRM_DIRETORIA" Level="50" Order="50"  />
        <wes:Tile runat="server" ID="K_VERTICAIS" Title="Verticais" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAVERTICAL.GRID" CompanyFilterMode="OnlyCompany" CommandName="REDIRECT_TOTAL" Value="CODIGO" Description="Verticais" Icon="fa fa-user" Color="default" ValueAggregation="Count" TileType="Default" PageId="K_CRM_DIRETORIA" Level="50" Order="60"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADES" Title="Oportunidades" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.STATUSOPORTUNIDADE NOT IN (7,14,15,16,17,18)" CommandName="REDIRECT_OPORTUNIDADES_ATIVAS" Value="CODIGO" Description="Oportunidades" Icon="fa fa-dollar" Color="default" ValueAggregation="Count" TileType="Default" PageId="K_CRM_DIRETORIA" Level="50" Order="70"  />
        <wes:Tile runat="server" ID="K_SOLICITAESDEDESCONTO" Title="Solicitações de Desconto" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PO_DESCONTOS.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 2" CommandName="REDIRECT_DESCONTO" Value="OPORTUNIDADE" Description="Solicitações de Desconto" Icon="fa fa-dollar" Color="green-jungle" ValueAggregation="Count" TileType="Default" PageId="K_CRM_DIRETORIA" Level="50" Order="78"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADESVENCIDAS" Title="Oportunidades Vencidas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.DATAFECHAMENTO &lt; GETDATE() AND A.STATUSOPORTUNIDADE NOT IN (7,14,15,16,17,18,19,20)" CommandName="REDIRECT_OPORTUNIDADES_VENCIDAS" Value="CODIGO" Description="Oportunidades Vencidas" Icon="fa fa-dollar" Color="red" ValueAggregation="Count" TileType="Default" PageId="K_CRM_DIRETORIA" Level="50" Order="80"  />
        <wes:Tile runat="server" ID="K_SUPORTESEMABERTO" Title="Suportes em Aberto" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_CHAMADOS.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.USUARIOINCLUSAO = @USUARIO AND A.STATUS IN (1)" CommandName="REDIRECT_MEUS_CHAMADOS" Value="HANDLE" Description="Suportes em Aberto" Icon="fa fa-list" Color="blue" ValueAggregation="Count" TileType="Default" PageId="K_CRM_DIRETORIA" Level="50" Order="88"  />
        <wes:Tile runat="server" ID="K_SEMFORO" Title="Semáforo" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOASEMAFORO.GRID" CompanyFilterMode="OnlyCompany" CommandName="REDIRECT_TOTALSEMAFORO" Value="CODIGO" Description="Semáforos" Icon="fa fa-check" Color="blue-hoki" ValueAggregation="Count" TileType="Default" PageId="K_CRM_DIRETORIA" Level="50" Order="90"  />
        <wes:Tile runat="server" ID="K_MEUSRECURSOS" Title="Meus Recursos" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TIPOSRECURSOSFILIAIS.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.VIGENCIA IN (SELECT HANDLE FROM K_CRM_TIPOSRECURSOSVIGENCIA WHERE DATAINICIO&lt;=GETDATE() AND DATAFIM&gt;=GETDATE()) " CommandName="REDIRECT_DIRETORVENDAS" Value="TIPORECURSO" Description="Meus Recursos" Icon="fa fa-book" Color="blue" ValueAggregation="Count" TileType="Default" PageId="K_CRM_DIRETORIA" Level="50" Order="100"  />
        </div>
    
      </asp:Content>
    