<%@ Page Title="Inicio - Arquiteto" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:Tile runat="server" ID="K_ATIVIDADESREALIZADASNASEMANA" Title="Atividades Realizadas na Semana" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.RESPONSAVEL = @USUARIO and A.DATACONCLUSAO BETWEEN @SEMANA[1] AND @SEMANA[2] " CommandName="cmdAtividades" Value="CODIGO" Description="Atividades Realizadas na Semana" Icon="fa fa-cog fa-spin" Color="green-jungle" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEARQUITETO" Level="50" Order="10"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESPENDENTES" Title="Atividades Pendentes" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &lt; @HOJE" CommandName="cmdAtividadesPendentes" Value="CODIGO" Description="Atividades Pendentes" Icon="fa fa-clock-o" Color="red" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEARQUITETO" Level="50" Order="20"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESPARAHOJE" Title="Atividades para hoje" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="2" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt;= DATEADD(day, DATEDIFF(day,0,GETDATE()),0) 
AND A.DATAAGENDAMENTO &lt; DATEADD(day, DATEDIFF(day,0,GETDATE())+1,0)" CommandName="cmdAtividadesHoje" Value="CODIGO" Description="Atividades para hoje" Icon="fa fa-clock-o" Color="yellow-gold" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEARQUITETO" Level="50" Order="30"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESFUTURAS" Title="Atividades Futuras" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="2" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt; @HOJE" CommandName="cmdAtividadesFuturas" Value="CODIGO" Description="Atividades Futuras" Icon="fa fa-line-chart" Color="blue" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEARQUITETO" Level="50" Order="40"  />
        <wes:Tile runat="server" ID="K_SUPORTESEMABERTO" Title="Suportes em Aberto" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="2" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_CHAMADOS.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.USUARIOINCLUSAO = @USUARIO AND A.STATUS IN (1)" CommandName="REDIRECT_MEUS_CHAMADOS" Value="HANDLE" Description="Suportes em Aberto" Icon="fa fa-list" Color="blue" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEARQUITETO" Level="50" Order="40"  />
        <wes:Tile runat="server" ID="K_MINHASOPORTUNIDADES" Title="Minhas Oportunidades" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.ARQUITETO.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.VERTICAL IN (SELECT DISTINCT(V.HANDLE) FROM K_CRM_VERTICAL V
LEFT JOIN K_CRM_PESSOAEQUIPEOPORTUNIDADE  E ON E.OPORTUNIDADE = A.HANDLE
LEFT JOIN K_CRM_PESSOAOPORTUNIDADESPROD P ON P.OPORTUNIDADE = A.HANDLE
JOIN STRING_SPLIT
((SELECT REPLACE(REPLACE(SUBSTRING(K_VERTICALPRODUTO,0, LEN(K_VERTICALPRODUTO)-1), '|', ''),'_',',')
FROM Z_GRUPOUSUARIOS WHERE HANDLE = @USUARIO), ',') ON VALUE = V.HANDLE AND (E.USUARIO = @USUARIO OR P.ARQUITETOSOLUCAO = @USUARIO))" CommandName="REDIRECT_OPORTUNIDADES_FILIAL" Value="CODIGO" Description="Minhas Oportunidades" Icon="fa fa-dollar" Color="default" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEARQUITETO" Level="50" Order="41"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADESVENCIDAS" Title="Oportunidades Vencidas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.ARQUITETO.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.DATAFECHAMENTO &lt; GETDATE() AND A.STATUSOPORTUNIDADE NOT IN (7,14,15,16,17,18,19,20) AND A.VERTICAL IN (SELECT DISTINCT(V.HANDLE) FROM K_CRM_VERTICAL V
LEFT JOIN K_CRM_PESSOAEQUIPEOPORTUNIDADE  E ON E.OPORTUNIDADE = A.HANDLE
LEFT JOIN K_CRM_PESSOAOPORTUNIDADESPROD P ON P.OPORTUNIDADE = A.HANDLE
JOIN STRING_SPLIT
((SELECT REPLACE(REPLACE(SUBSTRING(K_VERTICALPRODUTO,0, LEN(K_VERTICALPRODUTO)-1), '|', ''),'_',',')
FROM Z_GRUPOUSUARIOS WHERE HANDLE = @USUARIO), ',') ON VALUE = V.HANDLE AND (E.USUARIO = @USUARIO OR P.ARQUITETOSOLUCAO = @USUARIO))" CommandName="REDIRECT_OPORTUNIDADES_VENCIDAS_FILIAL" Value="CODIGO" Description="Oportunidades Vencidas" Icon="fa fa-dollar" Color="red" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMEARQUITETO" Level="50" Order="41"  />
        <wes:ActionView runat="server" ID="K_CALENDRIOUSURIO" Title="Calendário Usuário" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" Controller="CalendarioCrm" Action="CalendarioUsuario" PageId="K_PAGES_HOMEARQUITETO" Level="50" Order="42"  />
        </div>
    
      </asp:Content>
    