<%@ Page Title="Inicio - CS" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:Tile runat="server" ID="K_ATIVIDADESFUTURAS" Title="Atividades Futuras" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt; DATEADD(day, DATEDIFF(day,0,GETDATE())+1,0)" CommandName="cmdAtividadesFuturas" Value="CODIGO" Description="Atividades Futuras" Icon="fa fa-line-chart" Color="blue" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMECS" Level="50" Order="0"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESPARAHOJE" Title="Atividades para hoje" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &gt;= DATEADD(day, DATEDIFF(day,0,GETDATE()),0) 
AND A.DATAAGENDAMENTO &lt; DATEADD(day, DATEDIFF(day,0,GETDATE())+1,0)" CommandName="cmdAtividadesHoje" Value="CODIGO" Description="Atividades para hoje" Icon="fa fa-clock-o" Color="yellow-gold" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMECS" Level="50" Order="0"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESPENDENTES" Title="Atividades Pendentes" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS = 1 AND A.RESPONSAVEL = @USUARIO AND A.DATACONCLUSAO IS NULL AND A.DATAAGENDAMENTO &lt; @HOJE" CommandName="cmdAtividadesPendentes" Value="CODIGO" Description="Atividades Pendentes" Icon="fa fa-clock-o" Color="red" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMECS" Level="50" Order="0"  />
        <wes:Tile runat="server" ID="K_ATIVIDADESREALIZADASNASEMANA" Title="Atividades Realizadas na Semana" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_TAREFAUSUARIO.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.RESPONSAVEL = @USUARIO and A.DATACONCLUSAO BETWEEN @SEMANA[1] AND @SEMANA[2] " CommandName="cmdAtividades" Value="CODIGO" Description="Atividades Realizadas na Semana" Icon="fa fa-cog fa-spin" Color="green-jungle" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMECS" Level="50" Order="0"  />
        <wes:Tile runat="server" ID="K_TOTALDESEMFOROS" Title="Total de semáforos" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOASEMAFORO.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.EXECUTIVOCONTAS IN (SELECT USUARIO FROM Z_GRUPOUSUARIOEMPRESAFILIAIS WHERE FILIAL = @FILIAL) AND A.PESSOA IN (SELECT HANDLE FROM K_CRM_PESSOAS WHERE FILIAL = @FILIAL) AND A.STATUS NOT IN (2)" CommandName="REDIRECT_TOTALSEMAFORO" Value="CODIGO" Description="Total de semáforos" Icon="fa fa-check" Color="blue-hoki" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMECS" Level="50" Order="1"  />
        <wes:Tile runat="server" ID="K_SEMFOROSVERDES" Title="Semáforos Verdes" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOASEMAFORO.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS NOT IN (2) AND A.SEMAFORO = 1" CommandName="REDIRECT_SEMAFOROBAIXO" Value="CODIGO" Description="Semáforos Verdes" Icon="fa fa-check" Color="green-jungle" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMECS" Level="50" Order="3"  />
        <wes:Tile runat="server" ID="K_SUPORTESEMABERTO" Title="Suportes em Aberto" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="2" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_CHAMADOS.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.USUARIOINCLUSAO = @USUARIO AND A.STATUS IN (1)" CommandName="REDIRECT_MEUS_CHAMADOS" Value="HANDLE" Description="Suportes em Aberto" Icon="fa fa-list" Color="blue" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMECS" Level="50" Order="3"  />
        <wes:Tile runat="server" ID="K_SEMFOROSAMARELOS" Title="Semáforos amarelos" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="2" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOASEMAFORO.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS NOT IN (2) AND A.SEMAFORO IN (2)" CommandName="REDIRECT_SEMAFOROMEDIO" Value="CODIGO" Description="Semáforos amarelos" Icon="fa fa-check" Color="yellow-crusta" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMECS" Level="50" Order="6"  />
        <wes:Tile runat="server" ID="K_SEMFOROSEMABERTO" Title="Semáforos em Aberto" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="2" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOASEMAFORO.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.STATUS NOT IN (2) AND A.SEMAFORO IN (3)" CommandName="REDIRECT_SEMAFOROALTO" Value="CODIGO" Description="Semáforos Vermelhos" Icon="fa fa-clock-o" Color="red" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_HOMECS" Level="50" Order="8"  />
        <wes:ActionView runat="server" ID="K_CALENDRIOUSURIO" Title="Calendário Usuário" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" Controller="CalendarioCrm" Action="CalendarioUsuario" PageId="K_PAGES_HOMECS" Level="50" Order="18"  />
        <wes:AmCharts runat="server" ID="K_SEMFOROS" Title="Semáforos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_GRAPH_SEMAFORO_STATUS.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" CommandName="REDIRECT_TOTALSEMAFORO" ChartType="Pie" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoicGllIiwibGFuZ3VhZ2UiOiJwdCIsInB1bGxPdXRPbmx5T25lIjp0cnVlLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sInRpdGxlRmllbGQiOiJyb3R1bG8iLCJ2YWx1ZUZpZWxkIjoidmFsb3IiLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsImJhbGxvb25UZXh0IjoiW1t0aXRsZV1dPGJyPjxzcGFuIHN0eWxlPSdmb250LXNpemU6MTRweCc+PGI+W1t2YWx1ZV1dPC9iPiAoW1twZXJjZW50c11dJSk8L3NwYW4+IiwibGFiZWxUZXh0IjoiW1t0aXRsZV1dOiBbW3ZhbHVlXV0iLCJsYWJlbHNFbmFibGVkIjp0cnVlLCJsZWdlbmQiOnsiZW5hYmxlZCI6dHJ1ZSwiYWxpZ24iOiJjZW50ZXIiLCJtYXJrZXJUeXBlIjoiY2lyY2xlIiwicG9zaXRpb24iOiJsZWZ0In0sImlubmVyUmFkaXVzIjoiMCUiLCJ2ZXJzaW9uIjoiNCIsInRoZW1lNCI6Im1hdGVyaWFsIn0=" PageId="K_PAGES_HOMECS" Level="50" Order="28"  />
        </div>
    
      </asp:Content>
    