<%@ Page Title="Gestor - Indicadores" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="K_FILTROUSURIO" Title="Filtro usuário" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_VT_USUARIOFILIAL.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="K_PAGES_INDICADORES" Level="50" Order="10"  />
        <wes:AmCharts runat="server" ID="K_EVOLUODASCONTAS" Title="Evolução das contas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTROUSURIO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_GRAPH_EVOLUCAO.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" CriteriaWhereClause=" ( (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND B.FILIAL = @FILIAL) OR (@FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  B.FILIAL &lt;&gt; @FILIAL))
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND B.USUARIOEXECUTIVO IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND B.USUARIOEXECUTIVO NOT IN ( @CAMPO(USUARIOS))
)" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJkYXRhIiwic3RhcnREdXJhdGlvbiI6MSwiY2F0ZWdvcnlBeGlzIjp7ImdyaWRQb3NpdGlvbiI6InN0YXJ0In0sImdyYXBocyI6W3siaWQiOiJBbUdyYXBoLTEiLCJiYWxsb29uVGV4dCI6Ik5vdmFzIENvbnRhcyA6IFtbdmFsdWVdXSIsInRpdGxlIjoiTm92YXMgQ29udGFzIiwiYnVsbGV0Ijoicm91bmQiLCJidWxsZXRTaXplIjo1LCJsaW5lQ29sb3IiOiIjOWI1OWI2IiwibGluZVRoaWNrbmVzcyI6MiwidHlwZSI6InNtb290aGVkTGluZSIsInZhbHVlRmllbGQiOiJjb250YXMifSx7ImlkIjoiQW1HcmFwaC0yIiwiYmFsbG9vblRleHQiOiJQcm9zcGVjdHMgOiBbW3ZhbHVlXV0iLCJ0aXRsZSI6IlByb3NwZWN0cyIsImJ1bGxldCI6InJvdW5kIiwiYnVsbGV0U2l6ZSI6NSwibGluZUNvbG9yIjoiI2Y0YjM1MCIsImxpbmVUaGlja25lc3MiOjIsInR5cGUiOiJzbW9vdGhlZExpbmUiLCJ2YWx1ZUZpZWxkIjoicHJvc3BlY3RzIn0seyJpZCI6IkFtR3JhcGgtMyIsImJhbGxvb25UZXh0IjoiT3BvcnR1bmlkYWRlcyA6IFtbdmFsdWVdXSIsInRpdGxlIjoiT3BvcnR1bmlkYWRlcyIsImJ1bGxldCI6InJvdW5kIiwiYnVsbGV0U2l6ZSI6NSwibGluZUNvbG9yIjoiIzAxOTg3NSIsImxpbmVUaGlja25lc3MiOjIsInR5cGUiOiJzbW9vdGhlZExpbmUiLCJ2YWx1ZUZpZWxkIjoib3BvcnR1bmlkYWRlcyJ9LHsiaWQiOiJBbUdyYXBoLTQiLCJiYWxsb29uVGV4dCI6IjHCqiBWaXNpdGEgOiBbW3ZhbHVlXV0iLCJ0aXRsZSI6IjHCqiBWaXNpdGEiLCJidWxsZXQiOiJyb3VuZCIsImJ1bGxldFNpemUiOjUsImxpbmVDb2xvciI6IiMwMGU2NDAiLCJsaW5lVGhpY2tuZXNzIjoyLCJ0eXBlIjoic21vb3RoZWRMaW5lIiwidmFsdWVGaWVsZCI6InByaW12aXNpdGFzIn0seyJpZCI6IkFtR3JhcGgtNSIsImJhbGxvb25UZXh0IjoiVmlzaXRhcyA6IFtbdmFsdWVdXSIsInRpdGxlIjoiVmlzaXRhcyIsImJ1bGxldCI6InJvdW5kIiwiYnVsbGV0U2l6ZSI6NSwibGluZUNvbG9yIjoiI2QxNjU1ZCIsImxpbmVUaGlja25lc3MiOjIsIm5lZ2F0aXZlTGluZUNvbG9yIjoiIzYzN2JiNiIsInR5cGUiOiJzbW9vdGhlZExpbmUiLCJ2YWx1ZUZpZWxkIjoidmlzaXRhcyJ9XSwidmFsdWVBeGVzIjpbeyJpZCI6IlZhbHVlQXhpcy0xIiwidGl0bGUiOiIiLCJzdGFjayI6InJlZ3VsYXIifV0sImNoYXJ0Q3Vyc29yIjp7ImN1cnNvckFscGhhIjowLCJ6b29tYWJsZSI6ZmFsc2V9LCJsZWdlbmQiOnsiZW5hYmxlZCI6dHJ1ZSwicG9zaXRpb24iOiJib3R0b20iLCJ1c2VHcmFwaFNldHRpbmdzIjp0cnVlfSwicm90YXRlIjpmYWxzZX0=" PageId="K_PAGES_INDICADORES" Level="50" Order="20"  />
        <wes:AmCharts runat="server" ID="K_TIPODETAREFAMS" Title="Tipo de tarefa / Mês" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="K_FILTROUSURIO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_GRAPH_TIPOTAREFA.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" CriteriaWhereClause=" ( (@FILIAL IN (SELECT HANDLE FROM FILIAIS) AND B.FILIAL = @FILIAL) OR ( @FILIAL NOT IN (SELECT HANDLE FROM FILIAIS) AND  B.FILIAL &lt;&gt; @FILIAL))
AND (
       (SELECT CASE WHEN COUNT(HANDLE) &gt; 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND B.USUARIOEXECUTIVO IN ( @CAMPO(USUARIOS)) 
OR
(SELECT CASE WHEN COUNT(HANDLE) = 0 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END FROM Z_GRUPOUSUARIOS WHERE HANDLE IN (@CAMPO(USUARIOS) ) ) = CAST(1 AS BIT) AND B.USUARIOEXECUTIVO NOT IN ( @CAMPO(USUARIOS))
)" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJkYXRhIiwic3RhcnREdXJhdGlvbiI6MSwiY2F0ZWdvcnlBeGlzIjp7ImdyaWRQb3NpdGlvbiI6InN0YXJ0IiwibGFiZWxSb3RhdGlvbiI6MTV9LCJncmFwaHMiOlt7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiVGVsZWZvbmUgUmVjZWJpZG8gOiBbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtMSIsInRpdGxlIjoiVGVsZWZvbmUgUmVjZWJpZG8iLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJ0ZWxlZl9yZWNlYmlkbyIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiVGVsZWZvbmUgUmVhbGl6YWRvIDogW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTIiLCJ0aXRsZSI6IlRlbGVmb25lIFJlYWxpemFkbyIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwidmFsdWVGaWVsZCI6InRlbGVmX3JlYWxpemFkbyIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiQW5vdGHDp8OjbyA6IFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC0zIiwidGl0bGUiOiJBbm90YcOnw6NvIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoiYW5vdGFjYW8iLCJ0eXBlIjoiY29sdW1uIiwiZmlsbEFscGhhcyI6MX0seyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6IlRhcmVmYSA6IFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC00IiwidGl0bGUiOiJUYXJlZmEiLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJ0YXJlZmEiLCJ0eXBlIjoiY29sdW1uIiwiZmlsbEFscGhhcyI6MX0seyJsYWJlbFRleHQiOiIiLCJiYWxsb29uVGV4dCI6IlJldW5pw6NvIDogW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTUiLCJ0aXRsZSI6IlJldW5pw6NvIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoicmV1bmlhbyIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiRW1haWwgOiBbW3ZhbHVlXV0iLCJpZCI6IkFtR3JhcGgtNiIsInRpdGxlIjoiRW1haWwiLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInZhbHVlRmllbGQiOiJlbWFpbCIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiVmlzaXRhIDogW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTciLCJ0aXRsZSI6IlZpc2l0YSIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwidmFsdWVGaWVsZCI6InZpc2l0YSIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxfSx7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiMcKqIFZpc2l0YSA6IFtbdmFsdWVdXSIsImlkIjoiQW1HcmFwaC04IiwidGl0bGUiOiIxwqogVmlzaXRhIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ2YWx1ZUZpZWxkIjoicHJpbV92aXNpdGEiLCJ0eXBlIjoiY29sdW1uIiwiZmlsbEFscGhhcyI6MX1dLCJ2YWx1ZUF4ZXMiOlt7ImlkIjoiVmFsdWVBeGlzLTEiLCJ0aXRsZSI6IiIsInN0YWNrIjoicmVndWxhciIsInN0YWNrVHlwZSI6InJlZ3VsYXIifV0sImNoYXJ0Q3Vyc29yIjp7ImN1cnNvckFscGhhIjowLCJ6b29tYWJsZSI6ZmFsc2V9LCJsZWdlbmQiOnsiZW5hYmxlZCI6dHJ1ZSwicG9zaXRpb24iOiJib3R0b20iLCJ1c2VHcmFwaFNldHRpbmdzIjp0cnVlfX0=" PageId="K_PAGES_INDICADORES" Level="50" Order="30"  />
        </div>
    
      </asp:Content>
    