<%@ Page Title="Painel Atividades" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:Tile runat="server" ID="K_LEADSEMSUSPECO" Title="Leads em Suspecção" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAS.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.FASE IN (1) AND A.SUBFASE NOT IN (2,30)" CommandName="cmdLeadSuspect" Value="CODIGO" Description="Contas em Suspecção" Icon="fa fa-check" Color="purple-wisteria" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="10"  />
        <wes:Tile runat="server" ID="K_LEADSEMPROSPECO" Title="Leads em Prospecção" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAS.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.FASE = 3" CommandName="cmdLeadProspect" Value="CODIGO" Description="Contas em Prospecção" Icon="fa fa-check" Color="blue" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="12"  />
        <wes:Tile runat="server" ID="K_LEADSEMRELACIONAMENTO" Title="Leads em Relacionamento" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAS.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.FASE IN (6) " CommandName="cmdLeadRelacionamento" Value="CODIGO" Description="Contas em Prospecção com Oportunidade" Icon="fa fa-check" Color="green-haze" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="20"  />
        <wes:Tile runat="server" ID="K_LEADSEMCLIENTE" Title="Leads em Cliente" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAS.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.FASE in (4) AND A.SUBFASE IN (10)" CommandName="cmdLeadCliente" Value="CODIGO" Description="Clientes" Icon="fa fa-check" Color="green-jungle" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="22"  />
        <wes:Tile runat="server" ID="K_CLIENTESSUSPENSOS" Title="Clientes Suspensos" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAS.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.FASE = 5 AND A.SUBFASE = 11" CommandName="REDIRECT_CLIENTE_SUSPENSO" Value="CODIGO" Description="Clientes Suspensos" Icon="fa fa-check" Color="green-sharp" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="23"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADEPBLICAS" Title="Oportunidade Públicas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.STATUS IN (1,2,14) AND A.PESSOA IN (SELECT HANDLE FROM K_CRM_PESSOAS WHERE PUBLICOPRIVADO = 1)" CommandName="REDIRECT_OPORTUNIDADES_PUBLICAS" Value="CODIGO" Description="Oportunidade Públicas" Icon="fa fa-check" Color="grey-gallery" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="24"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADESPRIVADA" Title="Oportunidades Privada" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.STATUS IN (1,2,14) AND A.PESSOA IN (SELECT HANDLE FROM K_CRM_PESSOAS WHERE PUBLICOPRIVADO = 2)" CommandName="REDIRECT_OPORTUNIDADES_PRIVADAS" Value="CODIGO" Description="Oportunidades Privada" Icon="fa fa-check" Color="grey-cascade" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="25"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADESPERDIDAS" Title="Oportunidades Perdidas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.STATUS IN (9)" CommandName="REDIRECT_OPORTUNIDADES_PERDIDAS" Value="CODIGO" Description="Oportunidades Perdidas" Icon="fa fa-check" Color="grey-silver" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="26"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADESEMABERTO" Title="Oportunidades em aberto" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.STATUS IN (1,2) " CommandName="cmdOportunidadeAberta" Value="CODIGO" Description="Oportunidades em aberto" Icon="fa fa-dollar" Color="grey-silver" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="60"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADESVENCIDAS" Title="Oportunidades Vencidas" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.DATAFECHAMENTO &lt; @HOJE AND A.STATUS NOT IN (3,5,9,10,11,12,13)" CommandName="cmdOportunidadeVencida" Value="CODIGO" Description="Oportunidades Vencidas" Icon="fa fa-check" Color="grey-silver" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="62"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADESDOMS" Title="Oportunidades do Mês" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="MONTH(A.DATAINCLUSAO) = MONTH(GETDATE()) AND YEAR(A.DATAINCLUSAO) = YEAR(GETDATE())" CommandName="cmdOportunidadeMes" Value="CODIGO" Description="Oportunidades do Mês" Icon="fa fa-line-chart" Color="grey-silver" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="66"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADESEMABERTOMS" Title="Oportunidades em aberto (Mês)" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="MONTH(A.DATAFECHAMENTO) = MONTH(GETDATE()) AND YEAR(A.DATAFECHAMENTO) = YEAR(GETDATE())" CommandName="cmdOportunidadeFechamentoMes" Value="CODIGO" Description="Oportunidades Fechamento (Mês)" Icon="fa fa-dollar" Color="grey-silver" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="68"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADESPBLICASMS" Title="Oportunidades Públicas Mês" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.PESSOA IN (SELECT HANDLE FROM K_CRM_PESSOAS WHERE PUBLICOPRIVADO = 1) AND MONTH(A.DATAINCLUSAO) = MONTH(GETDATE()) AND YEAR(A.DATAINCLUSAO) = YEAR(GETDATE())" CommandName="REDIRECT_OPORTUNIDADES_PUBLICAS_MES" Value="CODIGO" Description="Oportunidades Públicas Mês" Icon="fa fa-check" Color="grey-gallery" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="69"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADESPRIVADASMS" Title="Oportunidades Privadas Mês" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CompanyFilterMode="CompanyAndBranch" CriteriaWhereClause="A.PESSOA IN (SELECT HANDLE FROM K_CRM_PESSOAS WHERE PUBLICOPRIVADO = 2) AND MONTH(A.DATAINCLUSAO) = MONTH(GETDATE()) AND YEAR(A.DATAINCLUSAO) = YEAR(GETDATE())" CommandName="REDIRECT_OPORTUNIDADES_PRIVADAS_MES" Value="CODIGO" Description="Oportunidades Privadas Mês" Icon="fa fa-check" Color="grey-cascade" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="70"  />
        <wes:Tile runat="server" ID="K_OPORTUNIDADESAGUARDANDOAUTORIZAO" Title="Oportunidades aguardando autorização" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="K_CRM_PESSOAOPORTUNIDADES.GRID" CompanyFilterMode="None" CriteriaWhereClause="A.FILIAL = @FILIAL AND A.STATUS IN (11,12,13)" CommandName="cmdCancelaOportunidade" Value="CODIGO" Description="Oportunidades com itens aguardando aprovação" Icon="fa fa-clock-o" Color="red" ValueAggregation="Count" TileType="Default" PageId="K_PAGES_PAINELATIVIDADES" Level="50" Order="94"  />
        </div>
    
      </asp:Content>
    