//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Common.Security;
using Benner.Tecnologia.Metadata.Entities;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using Benner.Tecnologia.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
//using System.Web.UI.WebControls;
using SK.Integracoes.Benner;
using SK.Integracoes.Benner.Services;
using Amazon.Runtime.Internal.Transform;
using DocumentFormat.OpenXml.Wordprocessing;
//using Sgml;
using Benner.Corporativo.DataContracts.Contratos.Consultas;
using Models.Crm;
using System.Globalization;
using System.IO;
using SM.Crm.Definicoes.Entidades;
using Benner.Corporativo.Common.Extensions;
using Benner.Tecnologia.Common.Legacy;
//using Benner.Tecnologia.Bas.AppServer.Classes;
using Benner.Tecnologia.Common.DataSources.Definition;
using Benner.Tecnologia.Common.Exceptions;
using Benner.Tecnologia.Wes.Components.Properties;
using Microsoft.Win32;
using System.Drawing;
using System.Drawing.Imaging;
using System.Web.SessionState;
using Borland.Vcl;
using Models.Generico;
using System.Collections;
using System.Runtime.Serialization.Formatters.Binary;
using System.Security.Policy;

public partial class PagesSandboxPage : WesPage
{
    protected void Page_Load(object sender, System.EventArgs e)
    {
        
    }
}
