//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Definicoes.FluxoCaixa.Servicos;
using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;




public partial class ComparacaoFluxosComparacao_FormPage : WesPage
{


    protected void Page_Load(object sender, System.EventArgs e)
    {
        if (!IsPostBack)
        {

            ValidacaoFluxo validacaoFluxo = new ValidacaoFluxo();
            var whereClause = ((Benner.Tecnologia.Common.Components.EntityLinkDefinition)this.GetLinkDefinition()).WhereClause.Where;
            var startIndex = whereClause.IndexOf('(') + 1;
            var secondIndex = whereClause.IndexOf(')');
            var handlesStr = whereClause.Substring(startIndex, secondIndex - startIndex);
            if (string.IsNullOrEmpty(handlesStr))
            {
                validacaoFluxo.Msg = "Não foi possível obter os fluxos selecionados.";
                FluxoHandlesHiddenField.Value = ToJson(validacaoFluxo);
                return;
            }

            var handles = handlesStr.Split(',').Select(long.Parse).ToList();
            var validaFluxoSelecionados = FluxoFinanceiroServico.ValidarFluxoParaComparacao(handles);
            if (!validaFluxoSelecionados)
            {
                validacaoFluxo.Msg =  "A periodicidade, plano de contas e/ou moeda não consiste nos fluxos selecionados";
                FluxoHandlesHiddenField.Value = ToJson(validacaoFluxo);
            }
            else
            {
                validacaoFluxo.HandleList = handles;
            }

            FluxoHandlesHiddenField.Value = ToJson(validacaoFluxo);
        }
    }

    private class ValidacaoFluxo
    {
        public string Msg { get; set; }
        public List<long> HandleList { get; set; }
        public ValidacaoFluxo()
        {
            Msg = string.Empty;
            HandleList = new List<long>();
        }
    }

    private string ToJson(object o)
    {
        return JsonConvert.SerializeObject(o, new JsonSerializerSettings
        {
            ContractResolver = new CamelCasePropertyNamesContractResolver()
        });
    }
}
