<%@ Page Title="Ordens retrabalho - Confirmar" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Ordens retrabalho - Confirmar" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_PR_ORDENSRETRABALHO.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="ORDENS_RETRABALHO__CONFIRMAR_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8274" Title="Apontamentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PR_ORDEMRETRABALHOAPONTAMENTO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMRETRABALHO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5742_at8274_hs32447776.aspx" UserDefinedDisableRowSelection="False" PageId="ORDENS_RETRABALHO__CONFIRMAR_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8262" Title="Histórico" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_STATUS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.HANDLETABELAORIGEM IN (SELECT B.HANDLE FROM Z_TABELAS B WHERE B.NOME = 'PR_ORDENSRETRABALHO') AND A.HANDLEREGISTROORIGEM = @RASTRO(PR_ORDENSRETRABALHO))" FormUrl="~/aga/a/f/aga_t1951_at8262_hs36680a6b.aspx" UserDefinedDisableRowSelection="False" PageId="ORDENS_RETRABALHO__CONFIRMAR_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8259" Title="Itens de consumo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PR_ORDEMRETRABALHOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TIPOITEM = 1) AND (A.ORDEMRETRABALHO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5740_at8259_hsbafd9a93.aspx" UserDefinedDisableRowSelection="False" PageId="ORDENS_RETRABALHO__CONFIRMAR_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8260" Title="Itens de retorno" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PR_ORDEMRETRABALHOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TIPOITEM = 2) AND (A.ORDEMRETRABALHO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5740_at8260_hsde9822f8.aspx" UserDefinedDisableRowSelection="False" PageId="ORDENS_RETRABALHO__CONFIRMAR_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8261" Title="Lotes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PR_ORDEMRETRABALHOLOTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMRETRABALHO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5739_at8261_hsffd2f650.aspx" UserDefinedDisableRowSelection="False" PageId="ORDENS_RETRABALHO__CONFIRMAR_FORM" Level="20" Order="30"  />
        </div>
    
      </asp:Content>
    