<%@ Page Title="Sintegra" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Sintegra" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_GN_FRPARAMETROCONSULTAS.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="CARGA_DE_PARAMETROS_CONSULTA_FR__FR_SINTEGRA_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2473_8288" Title="Log de Consultas&gt;Aguardando Retorno" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_FRRETORNOSSINTEGRA.GRID" CanDelete="True" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 2 AND (A.CONSULTA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5753_at8288_hs726cb662.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_PARAMETROS_CONSULTA_FR__FR_SINTEGRA_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2473_8287" Title="Log de Consultas&gt;Cadastradas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_FRRETORNOSSINTEGRA.GRID" CanDelete="True" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 1 AND (A.CONSULTA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5753_at8287_hs3ab1ff.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_PARAMETROS_CONSULTA_FR__FR_SINTEGRA_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2473_8290" Title="Log de Consultas&gt;Com Erro" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_FRRETORNOSSINTEGRA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 4 AND (A.CONSULTA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5753_at8290_hs9a13b3d5.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_PARAMETROS_CONSULTA_FR__FR_SINTEGRA_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2473_8289" Title="Log de Consultas&gt;Concluídas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_FRRETORNOSSINTEGRA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 3 AND (A.CONSULTA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5753_at8289_hs1304d735.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_PARAMETROS_CONSULTA_FR__FR_SINTEGRA_FORM" Level="20" Order="25"  />
        </div>
    
      </asp:Content>
    