<%@ Page Title="Requisições" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Requisições" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOESPAI.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="MI_ORDEMSERVICO_LEITURA__REQUISICOES_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3046" Title="Histórico" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_STATUS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.HANDLETABELAORIGEM IN (SELECT B.HANDLE FROM Z_TABELAS B WHERE B.NOME = 'CP_REQUISICOESPAI') AND A.HANDLEREGISTROORIGEM = @RASTRO(CP_REQUISICOESPAI))" FormUrl="~/aga/a/f/aga_t1951_at3046_hs861d3ee2.aspx" UserDefinedDisableRowSelection="False" PageId="MI_ORDEMSERVICO_LEITURA__REQUISICOES_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1929" Title="Itens (todos)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.REQUISICAOPAI = @RASTRO(CP_REQUISICOESPAI))" FormUrl="~/aga/a/f/aga_t868_at1929_hs35095e21.aspx" UserDefinedDisableRowSelection="False" PageId="MI_ORDEMSERVICO_LEITURA__REQUISICOES_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3037" Title="Itens de compra" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TIPO = 'C' AND A.REQUISICAOPAI = @RASTRO(CP_REQUISICOESPAI))" FormUrl="~/aga/a/f/aga_t868_at3037_hse29466f2.aspx" UserDefinedDisableRowSelection="False" PageId="MI_ORDEMSERVICO_LEITURA__REQUISICOES_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3038" Title="Itens de consumo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TIPO = 'O' AND A.REQUISICAOPAI = @RASTRO(CP_REQUISICOESPAI))" FormUrl="~/aga/a/f/aga_t868_at3038_hsf4df263.aspx" UserDefinedDisableRowSelection="False" PageId="MI_ORDEMSERVICO_LEITURA__REQUISICOES_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5423" Title="Itens de consumo de produção" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TIPO = 'P' AND A.REQUISICAOPAI = @RASTRO(CP_REQUISICOESPAI))" FormUrl="~/aga/a/f/aga_t868_at5423_hs552e7691.aspx" UserDefinedDisableRowSelection="False" PageId="MI_ORDEMSERVICO_LEITURA__REQUISICOES_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3434" Title="Itens de contrato" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TIPO = 'N' AND A.REQUISICAOPAI = @RASTRO(CP_REQUISICOESPAI))" FormUrl="~/aga/a/f/aga_t868_at3434_hs5d6d4974.aspx" UserDefinedDisableRowSelection="False" PageId="MI_ORDEMSERVICO_LEITURA__REQUISICOES_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7464" Title="Itens de reclassificação de estoque" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TIPO = 'R' AND A.REQUISICAOPAI = @RASTRO(CP_REQUISICOESPAI))" FormUrl="~/aga/a/f/aga_t868_at7464_hsb83e053b.aspx" UserDefinedDisableRowSelection="False" PageId="MI_ORDEMSERVICO_LEITURA__REQUISICOES_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3039" Title="Itens de transferência de almoxarifado" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TIPO = 'T' AND A.REQUISICAOPAI = @RASTRO(CP_REQUISICOESPAI))" FormUrl="~/aga/a/f/aga_t868_at3039_hs7535b77c.aspx" UserDefinedDisableRowSelection="False" PageId="MI_ORDEMSERVICO_LEITURA__REQUISICOES_FORM" Level="20" Order="45"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3040" Title="Itens de transferência de filial" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TIPO = 'F' AND A.REQUISICAOPAI = @RASTRO(CP_REQUISICOESPAI))" FormUrl="~/aga/a/f/aga_t868_at3040_hsf8417c01.aspx" UserDefinedDisableRowSelection="False" PageId="MI_ORDEMSERVICO_LEITURA__REQUISICOES_FORM" Level="20" Order="50"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8351" Title="Termo de referência" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_TR.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.HANDLE IN (SELECT TERMOREFERENCIA FROM CP_REQUISICOESPAI WHERE HANDLE = @RASTRO(CP_REQUISICOESPAI)))" FormUrl="~/aga/a/f/aga_t5780_at8351_hs92e1747b.aspx" UserDefinedDisableRowSelection="False" PageId="MI_ORDEMSERVICO_LEITURA__REQUISICOES_FORM" Level="20" Order="55"  />
        </div>
    
      </asp:Content>
    