<%@ Page Title="Importação de abastecimentos - Pendentes" Language="C#" Inherits="Benner.Corporativo.Frotas.WebApp.aga.e.CTFLote.MFCtflote" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Importação de abastecimentos - Pendentes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_MF_CTFLOTE.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="MF_ABASTECIMENTOSCTF__PENDENTES_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6985" Title="Cancelados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="AGA_MF_CTFLOTEABASTECIMENTO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS = 2) AND (A.CTFLOTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4664_at6985_hs19b354f8.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="MF_ABASTECIMENTOSCTF__PENDENTES_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6987" Title="Com OS gerado" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="AGA_MF_CTFLOTEABASTECIMENTO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS = 3) AND (A.CTFLOTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4664_at6987_hs93b1eabe.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="MF_ABASTECIMENTOSCTF__PENDENTES_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6988" Title="Com problemas para gerar OS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="False" CanUpdate="True" CanInsert="False" EntityViewName="AGA_MF_CTFLOTEABASTECIMENTO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS = 4) AND (A.CTFLOTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4664_at6988_hs4fcec17.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="MF_ABASTECIMENTOSCTF__PENDENTES_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6986" Title="Importados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="False" CanUpdate="True" CanInsert="False" EntityViewName="AGA_MF_CTFLOTEABASTECIMENTO.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS = 1) AND (A.CTFLOTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4664_at6986_hse32ca138.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="MF_ABASTECIMENTOSCTF__PENDENTES_FORM" Level="20" Order="25"  />
        </div>
    
      </asp:Content>
    