<%@ Page Title="Aguardando Retorno - Lotes" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Aguardando Retorno - Lotes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_TR_SSLOTES.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="SS_AGUARDANDORETORNO__TR_SSLOTES_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8460" Title="Aditivos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_SSRVSADITIVOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN ( SELECT TR_SSLOTESASSOCIACAO.LIGACAO FROM TR_SSLOTESASSOCIACAO WHERE TR_SSLOTESASSOCIACAO.LOTE = @RASTRO(TR_SSLOTES) AND TR_SSLOTESASSOCIACAO.TIPO = 3) AND (A.LOTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4621_at8460_hsd9b8eac.aspx" UserDefinedDisableRowSelection="False" PageId="SS_AGUARDANDORETORNO__TR_SSLOTES_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8462" Title="Faturamentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_SSRVSFATURAMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN ( SELECT TR_SSLOTESASSOCIACAO.LIGACAO FROM TR_SSLOTESASSOCIACAO WHERE TR_SSLOTESASSOCIACAO.LOTE = @RASTRO(TR_SSLOTES) AND TR_SSLOTESASSOCIACAO.TIPO = 5) AND (A.LOTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4627_at8462_hs301d0f55.aspx" UserDefinedDisableRowSelection="False" PageId="SS_AGUARDANDORETORNO__TR_SSLOTES_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8458" Title="RVS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_SSRVS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN ( SELECT TR_SSLOTESASSOCIACAO.LIGACAO FROM TR_SSLOTESASSOCIACAO WHERE TR_SSLOTESASSOCIACAO.LOTE = @RASTRO(TR_SSLOTES) AND TR_SSLOTESASSOCIACAO.TIPO = 1) AND (A.LOTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4620_at8458_hs2657fb8e.aspx" UserDefinedDisableRowSelection="False" PageId="SS_AGUARDANDORETORNO__TR_SSLOTES_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8461" Title="Retificação Aditivos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_SSRVSADITIVORETIFICACOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN ( SELECT TR_SSLOTESASSOCIACAO.LIGACAO FROM TR_SSLOTESASSOCIACAO WHERE TR_SSLOTESASSOCIACAO.LOTE = @RASTRO(TR_SSLOTES) AND TR_SSLOTESASSOCIACAO.TIPO = 4) AND (A.LOTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4622_at8461_hs78d0d29d.aspx" UserDefinedDisableRowSelection="False" PageId="SS_AGUARDANDORETORNO__TR_SSLOTES_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8459" Title="Retificações RVS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_SSRVSRETIFICACOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN ( SELECT TR_SSLOTESASSOCIACAO.LIGACAO FROM TR_SSLOTESASSOCIACAO WHERE TR_SSLOTESASSOCIACAO.LOTE = @RASTRO(TR_SSLOTES) AND TR_SSLOTESASSOCIACAO.TIPO = 2) AND (A.LOTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4623_at8459_hs67c5b876.aspx" UserDefinedDisableRowSelection="False" PageId="SS_AGUARDANDORETORNO__TR_SSLOTES_FORM" Level="20" Order="30"  />
        </div>
    
      </asp:Content>
    