<%@ Page Title="Conjuntos mecânicos e eixos - Conjuntos mecânicos avulsos" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Conjuntos mecânicos e eixos - Conjuntos mecânicos avulsos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_MA_RECURSOPARTES.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="MF_VEICULOPARTES_SOLEITURA__PARTESAVULSAS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3931" Title="Histórico de desgastes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_PARTEDESGASTES.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PARTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2617_at3931_hs33cda74d.aspx" UserDefinedDisableRowSelection="False" PageId="MF_VEICULOPARTES_SOLEITURA__PARTESAVULSAS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3926" Title="Histórico de localizações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_HISTORICOLOCACAOPARTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PARTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2623_at3926_hs7c33e6f3.aspx" UserDefinedDisableRowSelection="False" PageId="MF_VEICULOPARTES_SOLEITURA__PARTESAVULSAS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7084" Title="Histórico de manutenções" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_ORDEMSERVICOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT ORDEMSERVICO FROM MF_ORDEMPRODUTOINTERNOS WHERE CONJUNTO = @RASTRO(MA_RECURSOPARTES))
OR A.HANDLE IN (SELECT ORDEMSERVICO FROM MF_ORDEMSERVICOPRODUTOS WHERE PARTE  = @RASTRO(MA_RECURSOPARTES))
OR A.HANDLE IN (SELECT ORDEMSERVICO FROM MF_ORDEMSERVICOINTERNOS WHERE CONJUNTO =  @RASTRO(MA_RECURSOPARTES))" FormUrl="~/aga/a/f/aga_t2619_at7084_hs30313909.aspx" UserDefinedDisableRowSelection="False" PageId="MF_VEICULOPARTES_SOLEITURA__PARTESAVULSAS_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7025" Title="Roteiros de lubrificações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_PARTEMANUTENCAOPREVENTIVA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.MANUTENCAO IN
(SELECT HANDLE FROM MA_ROTEIROMANUTENCAO WHERE UTILIZARPLANOLUBRIFICACAO = 'S') AND (A.CONJUNTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4649_at7025_hsc74536.aspx" UserDefinedDisableRowSelection="False" PageId="MF_VEICULOPARTES_SOLEITURA__PARTESAVULSAS_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7024" Title="Roteiros de manutenções preventivas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_PARTEMANUTENCAOPREVENTIVA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.MANUTENCAO IN
(SELECT HANDLE FROM MA_ROTEIROMANUTENCAO WHERE UTILIZAPLANOPREVENTIVO= 'S') AND (A.CONJUNTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4649_at7024_hsc88df198.aspx" UserDefinedDisableRowSelection="False" PageId="MF_VEICULOPARTES_SOLEITURA__PARTESAVULSAS_FORM" Level="20" Order="30"  />
        </div>
    
      </asp:Content>
    