<%@ Page Title="Componentes do conjunto" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Componentes do conjunto" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_MI_ESTRUTURAS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="MI_COMPONENTES_MANUTENCOES__COMPONENTES_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4447" Title="Componentes do conjunto" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MI_ESTRUTURAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PRODUTO IS NOT NULL)" FormUrl="~/aga/a/f/aga_t2683_at4447_hsff4b5fc6.aspx" UserDefinedDisableRowSelection="False" PageId="MI_COMPONENTES_MANUTENCOES__COMPONENTES_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1283_4219" Title="Manutenções preventivas&gt;Ativas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MI_FREQUENCIA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.ROTEIRO IN (SELECT HANDLE FROM MI_ROTEIRO WHERE ATIVO = 'S')" FormUrl="~/aga/a/f/aga_t2769_at4219_hs16d4e830.aspx" UserDefinedDisableRowSelection="False" PageId="MI_COMPONENTES_MANUTENCOES__COMPONENTES_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1283_4220" Title="Manutenções preventivas&gt;Não utilizadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MI_FREQUENCIA.GRID" CanDelete="True" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.ROTEIRO IN (SELECT HANDLE FROM MI_ROTEIRO WHERE ATIVO = 'N')" FormUrl="~/aga/a/f/aga_t2769_at4220_hsb009b2ec.aspx" UserDefinedDisableRowSelection="False" PageId="MI_COMPONENTES_MANUTENCOES__COMPONENTES_FORM" Level="20" Order="20"  />
        </div>
    
      </asp:Content>
    