<%@ Page Title="Declarações / Arquivos magnéticos - Informações" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Declarações / Arquivos magnéticos - Informações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_TR_INFORMACOES.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="TRIBUTOS_DECLARACAOARQUIVOMAGNETICO__INFORMACOES_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2968" Title="Período" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_TR_INFORMACAOPERIODOS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.INFORMACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2121_at2968_hs6b17dc89.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="TRIBUTOS_DECLARACAOARQUIVOMAGNETICO__INFORMACOES_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4844" Title="Período" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_TR_INFORMACAOPERIODOS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.INFORMACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2121_at4844_hs7f3bdc8c.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="TRIBUTOS_DECLARACAOARQUIVOMAGNETICO__INFORMACOES_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4545" Title="Período" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_TR_INFORMACAOPERIODOS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.INFORMACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2121_at4545_hsd328c198.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="TRIBUTOS_DECLARACAOARQUIVOMAGNETICO__INFORMACOES_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2967" Title="Período" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_TR_INFORMACAOPERIODOS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.INFORMACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2121_at2967_hsf868d5c1.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="TRIBUTOS_DECLARACAOARQUIVOMAGNETICO__INFORMACOES_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3683" Title="Período" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_TR_INFORMACAOPERIODOS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.INFORMACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2121_at3683_hs6b1adc90.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="TRIBUTOS_DECLARACAOARQUIVOMAGNETICO__INFORMACOES_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2965" Title="Período" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_TR_INFORMACAOPERIODOS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.INFORMACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2121_at2965_hs35020ff5.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="TRIBUTOS_DECLARACAOARQUIVOMAGNETICO__INFORMACOES_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2966" Title="Período" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_TR_INFORMACAOPERIODOS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.INFORMACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2121_at2966_hs98404d05.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="TRIBUTOS_DECLARACAOARQUIVOMAGNETICO__INFORMACOES_FORM" Level="20" Order="40"  />
        </div>
    
      </asp:Content>
    