<%@ Page Title="Eixos - Veículos" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Eixos - Veículos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_MA_RECURSOPARTES.FORM" CanDelete="False" CanUpdate="True" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="MF_CONJUNTOS_EIXOS__CONJUNTOS_EIXOS_VEICULOS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6961" Title="Histórico de desgastes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_PARTEDESGASTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PARTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2617_at6961_hsd37aa346.aspx" UserDefinedDisableRowSelection="False" PageId="MF_CONJUNTOS_EIXOS__CONJUNTOS_EIXOS_VEICULOS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7069" Title="Histórico de localizações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_HISTORICOLOCACAOPARTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PARTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2623_at7069_hs3454ed87.aspx" UserDefinedDisableRowSelection="False" PageId="MF_CONJUNTOS_EIXOS__CONJUNTOS_EIXOS_VEICULOS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7085" Title="Histórico de manutenções" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_ORDEMSERVICOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT ORDEMSERVICO FROM MF_ORDEMPRODUTOINTERNOS WHERE CONJUNTO = @RASTRO(MA_RECURSOPARTES))
OR A.HANDLE IN (SELECT ORDEMSERVICO FROM MF_ORDEMSERVICOPRODUTOS WHERE PARTE  = @RASTRO(MA_RECURSOPARTES))
OR A.HANDLE IN (SELECT ORDEMSERVICO FROM MF_ORDEMSERVICOINTERNOS WHERE CONJUNTO =  @RASTRO(MA_RECURSOPARTES))" FormUrl="~/aga/a/f/aga_t2619_at7085_hs1e87f775.aspx" UserDefinedDisableRowSelection="False" PageId="MF_CONJUNTOS_EIXOS__CONJUNTOS_EIXOS_VEICULOS_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6956" Title="Pneus lado direito" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MA_RECURSOPARTES.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="PARTEPNEU = 2 AND POSICAO &lt; 0 AND (A.EIXOVEICULO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2349_at6956_hs23b93d1.aspx" UserDefinedDisableRowSelection="False" PageId="MF_CONJUNTOS_EIXOS__CONJUNTOS_EIXOS_VEICULOS_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6957" Title="Pneus lado esquerdo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MA_RECURSOPARTES.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="PARTEPNEU = 2 AND POSICAO &gt; 0 AND (A.EIXOVEICULO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2349_at6957_hs48bd06e4.aspx" UserDefinedDisableRowSelection="False" PageId="MF_CONJUNTOS_EIXOS__CONJUNTOS_EIXOS_VEICULOS_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7026" Title="Roteiros de lubrificações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_PARTEMANUTENCAOPREVENTIVA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.MANUTENCAO IN
(SELECT HANDLE FROM MA_ROTEIROMANUTENCAO WHERE UTILIZARPLANOLUBRIFICACAO = 'S') AND (A.CONJUNTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4649_at7026_hs3348ca32.aspx" UserDefinedDisableRowSelection="False" PageId="MF_CONJUNTOS_EIXOS__CONJUNTOS_EIXOS_VEICULOS_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7027" Title="Roteiros de manutenções preventivas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_PARTEMANUTENCAOPREVENTIVA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.MANUTENCAO IN
(SELECT HANDLE FROM MA_ROTEIROMANUTENCAO WHERE UTILIZAPLANOPREVENTIVO= 'S') AND (A.CONJUNTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4649_at7027_hs940b5591.aspx" UserDefinedDisableRowSelection="False" PageId="MF_CONJUNTOS_EIXOS__CONJUNTOS_EIXOS_VEICULOS_FORM" Level="20" Order="40"  />
        </div>
    
      </asp:Content>
    