<%@ Page Title="Operações" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Operações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_TR_SSRVSOPERACOES.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="SISCOSERV_RVS_ADITIVOS_RETIFICACOES__TR_SS_RVS_OPERACOES_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8398" Title="Declaração de Importação" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_SSRVSDECLARACAOIMPORTACAO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.OPERACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5813_at8398_hs9a82549e.aspx" UserDefinedDisableRowSelection="False" PageId="SISCOSERV_RVS_ADITIVOS_RETIFICACOES__TR_SS_RVS_OPERACOES_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6865" Title="Enquadramentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_SSRVSOPERACAOENQUADRAMENTOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.OPERACAORVS = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4626_at6865_hs19613b40.aspx" UserDefinedDisableRowSelection="False" PageId="SISCOSERV_RVS_ADITIVOS_RETIFICACOES__TR_SS_RVS_OPERACOES_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8397" Title="Registro de Exportação" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_SSRVSREGISTROEXPORTACAO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.OPERACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5812_at8397_hsd85b906e.aspx" UserDefinedDisableRowSelection="False" PageId="SISCOSERV_RVS_ADITIVOS_RETIFICACOES__TR_SS_RVS_OPERACOES_FORM" Level="20" Order="20"  />
        </div>
    
      </asp:Content>
    