<%@ Page Title="Orçamentos" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Orçamentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_FT_SOLICITACAODOCUMENTOS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="FT_CARGA_SOLICITACOES_GERADO__ORCAMENTOS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2986" Title="Itens" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_FT_SOLICITACAODOCUMENTOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.SOLICITACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2278_at2986_hsade2e1b0.aspx" UserDefinedDisableRowSelection="False" PageId="FT_CARGA_SOLICITACOES_GERADO__ORCAMENTOS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2984" Title="Obrigações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_FN_DOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.EHPREVISAO = 'N' AND A.HANDLE IN (SELECT DOCUMENTO FROM FT_SOLICITACAODOCUMENTOBAIXAS WHERE SOLICITACAO  = @RASTRO(FT_SOLICITACAODOCUMENTOS))" FormUrl="~/aga/a/f/aga_t1216_at2984_hs4b2f0c05.aspx" UserDefinedDisableRowSelection="False" PageId="FT_CARGA_SOLICITACOES_GERADO__ORCAMENTOS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2983" Title="Previsão" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_FN_DOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.EHPREVISAO = 'S' AND A.DOCUMENTODIGITADO IN (SELECT NUMERO FROM FT_SOLICITACAODOCUMENTOS WHERE HANDLE = @RASTRO(FT_SOLICITACAODOCUMENTOS))" FormUrl="~/aga/a/f/aga_t1216_at2983_hsc0964d1c.aspx" UserDefinedDisableRowSelection="False" PageId="FT_CARGA_SOLICITACOES_GERADO__ORCAMENTOS_FORM" Level="20" Order="20"  />
        </div>
    
      </asp:Content>
    