<%@ Page Title="Saídas - REG.D600: COMUNICAÇÃO/TELECOM. 21,22" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Saídas - REG.D600: COMUNICAÇÃO/TELECOM. 21,22" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_ED_PCPERIODOSREGISTROD600.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="ED_CARGA_EFDPC_SAIDAS__ED_CARGA_EFDPC_SAIDAS_REGISTROD600_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6647" Title="D601" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PCPERIODOSREGISTROD601.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.REGISTROD600 = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4338_at6647_hsc8c173c2.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFDPC_SAIDAS__ED_CARGA_EFDPC_SAIDAS_REGISTROD600_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6648" Title="D605" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PCPERIODOSREGISTROD605.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.REGISTROD600 = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4339_at6648_hsc8c573c2.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFDPC_SAIDAS__ED_CARGA_EFDPC_SAIDAS_REGISTROD600_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6650" Title="Documentos Gerados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PCPERIODOSREGISTROD600DOC.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="SITUACAO IN (00,06,07,08) AND (A.REGISTROD600 = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4340_at6650_hsc8d3d3db.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFDPC_SAIDAS__ED_CARGA_EFDPC_SAIDAS_REGISTROD600_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6651" Title="Documentos Não Gerados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PCPERIODOSREGISTROD600DOC.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="SITUACAO IN (01,02,03,04,05) AND (A.REGISTROD600 = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4340_at6651_hsf6a8956e.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFDPC_SAIDAS__ED_CARGA_EFDPC_SAIDAS_REGISTROD600_FORM" Level="20" Order="25"  />
        </div>
    
      </asp:Content>
    