<%@ Page Title="Orçamentos" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Orçamentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_PJ_TAREFAORCAMENTOS.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2117" Title="Aquisições" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" FormUrl="~/aga/a/f/aga_t1797_at2117_hs60c8b970.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2137" Title="Competências" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PJ_ORCAMENTOCOMPETENCIAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1905_at2137_hs16e18426.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2102" Title="Compromissos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PJ_ORCAMENTOCOMPROMISSOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1903_at2102_hs1f71fff5.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_696_4366" Title="Ordens de venda&gt;Canceladas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS=5 ) AND (A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4366_hs955d91ec.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_696_4363" Title="Ordens de venda&gt;Confirmadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS=2 ) AND (A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4363_hsb96fb5d3.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_696_4367" Title="Ordens de venda&gt;Confirmar" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="((A.LIBERADOCONFIRMACAO = 'S' OR A.LIBERADOCONFIRMACAO IS NULL) AND 
(A.STATUS = 1) AND ((A.GRUPOASSINATURAS IS NULL AND A.CONFIRMANTE = @USUARIO) OR
 (A.GRUPOASSINATURAS IN(SELECT C.HANDLE FROM CP_GRUPOALCADASINTEGRANTES B,
CP_GRUPOALCADAS C WHERE B.GRUPO = C.HANDLE AND C.EHHIERARQUIA = 'S' 
AND B.SEQUENCIA &gt;= A.SEQUENCIAALCADA AND B.USUARIO = @USUARIO AND B.ATIVO = 'S') OR 
(A.GRUPOASSINATURAS IN
 (SELECT C.HANDLE FROM CP_GRUPOALCADASINTEGRANTES B,CP_GRUPOALCADAS C 
WHERE B.GRUPO = C.HANDLE AND C.EHHIERARQUIA &lt;&gt; 'S' AND
 B.SEQUENCIA = A.SEQUENCIAALCADA AND B.USUARIO = @USUARIO AND B.ATIVO = 'S'))))) AND (A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4367_hs104c05dd.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_696_4362" Title="Ordens de venda&gt;Em elaboração" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS=1 AND A.LIBERADOCONFIRMACAO &lt;&gt; 'S') AND (A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4362_hs66b7783a.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_696_4364" Title="Ordens de venda&gt;Em faturamento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS=3) AND (A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4364_hs6b2c578f.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="45"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_696_4365" Title="Ordens de venda&gt;Encerradas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS=4) AND (A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4365_hs84f9639c.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="50"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_696_4369" Title="Ordens de venda&gt;Faturadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS = 6) AND (A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4369_hsc4035823.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="55"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_696_4368" Title="Ordens de venda&gt;Todas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4368_hs94a79834.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="60"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2877" Title="Ordens de viagem" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_OV_ORDENSVIAGEM.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1406_at2877_hsecad0b8e.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="65"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2285" Title="Rateio das fontes financiadoras" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PJ_ORCAMENTOENTIDADES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.REQUISICAOITEM IS NULL) AND (A.REQUISICAO IS NULL) AND (A.ORDEMVIAGEM IS NULL) AND (A.ORDEMVENDAITEM IS NULL) AND (A.ORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2006_at2285_hs373997de.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="70"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2833" Title="Requisições de aquisições" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_REQUISICOES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TAREFAPROJETO = @RASTRO(PJ_TAREFAORCAMENTOS))" FormUrl="~/aga/a/f/aga_t1792_at2833_hs7e58f68f.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="75"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2118" Title="Requisições suprimentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOESPAI.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TAREFAPROJETO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2311_at2118_hs678554c3.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA__ORCAMENTOS_FORM" Level="20" Order="80"  />
        </div>
    
      </asp:Content>
    