<%@ Page Title="Fórmulas - IVA Próprio" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Fórmulas - IVA Próprio" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_TR_CREDITOACUMULADOFORMULAS.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="SAOPAULO_FORMULAS__FORMULA_IVA_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7263" Title="Compras" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_CREDITOACUMULADOCAMPOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="TIPO = 1 AND (A.FORMULA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4900_at7263_hs1a96aecb.aspx" UserDefinedDisableRowSelection="False" PageId="SAOPAULO_FORMULAS__FORMULA_IVA_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7264" Title="Devolução de combustíveis" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_CREDITOACUMULADOCAMPOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="TIPO = 4 AND (A.FORMULA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4900_at7264_hse49fef4e.aspx" UserDefinedDisableRowSelection="False" PageId="SAOPAULO_FORMULAS__FORMULA_IVA_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7265" Title="Devolução de compras" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_CREDITOACUMULADOCAMPOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="TIPO = 3 AND (A.FORMULA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4900_at7265_hsdef62e42.aspx" UserDefinedDisableRowSelection="False" PageId="SAOPAULO_FORMULAS__FORMULA_IVA_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7266" Title="Devolução de vendas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_CREDITOACUMULADOCAMPOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="TIPO = 6 AND (A.FORMULA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4900_at7266_hs672310f2.aspx" UserDefinedDisableRowSelection="False" PageId="SAOPAULO_FORMULAS__FORMULA_IVA_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7267" Title="Energia, comunicação e combustíveis" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_CREDITOACUMULADOCAMPOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="TIPO = 2 AND (A.FORMULA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4900_at7267_hsdb4ef138.aspx" UserDefinedDisableRowSelection="False" PageId="SAOPAULO_FORMULAS__FORMULA_IVA_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7268" Title="Rubricas de crédito acmulado" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_RUBRICAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="EHCREDITOACUMULADOICMS = 'S'" FormUrl="~/aga/a/f/aga_t1331_at7268_hscb7437b9.aspx" UserDefinedDisableRowSelection="False" PageId="SAOPAULO_FORMULAS__FORMULA_IVA_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7269" Title="Vendas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_CREDITOACUMULADOCAMPOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="TIPO = 5 AND (A.FORMULA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4900_at7269_hs96680f35.aspx" UserDefinedDisableRowSelection="False" PageId="SAOPAULO_FORMULAS__FORMULA_IVA_FORM" Level="20" Order="40"  />
        </div>
    
      </asp:Content>
    