<%@ Page Title="Itens de transferência de filial" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Itens de transferência de filial" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOES.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="REQUISICOES_SO_LEITURA__ITENSDETRANSFERENCIADEFILIAL_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7302" Title="Anexos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICAOANEXOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.REQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4935_at7302_hs1269d595.aspx" UserDefinedDisableRowSelection="False" PageId="REQUISICOES_SO_LEITURA__ITENSDETRANSFERENCIADEFILIAL_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3608" Title="Cláusulas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CN_CONTRATOCLAUSULAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.REQUISICAOSUPRIMENTOS = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2111_at3608_hs946cd07b.aspx" UserDefinedDisableRowSelection="False" PageId="REQUISICOES_SO_LEITURA__ITENSDETRANSFERENCIADEFILIAL_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7914" Title="Contratos de compra" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CN_APONTAMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT REQITEMCONT.APONTAMENTO FROM CN_ITENSCONTRATOREQUISICAO REQITEMCONT WHERE REQITEMCONT.ITEMREQUISICAOITEMCONTRATO  IN
(SELECT ITEMREQ.HANDLE FROM CN_ITEMREQUISICAOITEMCONTRATO ITEMREQ
WHERE ITEMREQ.ITEMREQUISICAO = @RASTRO(CP_REQUISICOES)))" FormUrl="~/aga/a/f/aga_t2184_at7914_hs7c46a541.aspx" UserDefinedDisableRowSelection="False" PageId="REQUISICOES_SO_LEITURA__ITENSDETRANSFERENCIADEFILIAL_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5083" Title="Fornecedores" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_VARIACAOFORNECEDORES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.VARIACAO IN (SELECT B.VARIACAO FROM CP_REQUISICOES B WHERE HANDLE = @RASTRO(CP_REQUISICOES))" FormUrl="~/aga/a/f/aga_t1506_at5083_hs9c26d19b.aspx" UserDefinedDisableRowSelection="False" PageId="REQUISICOES_SO_LEITURA__ITENSDETRANSFERENCIADEFILIAL_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2690" Title="Histórico" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_STATUS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.HANDLETABELAORIGEM IN (SELECT B.HANDLE FROM Z_TABELAS B WHERE B.NOME = 'CP_REQUISICOES') AND A.HANDLEREGISTROORIGEM = @RASTRO(CP_REQUISICOES) AND A.DATAINCLUSAO &gt;= (SELECT DATAINCLUSAO FROM CP_REQUISICOES WHERE HANDLE = @RASTRO(CP_REQUISICOES)))" FormUrl="~/aga/a/f/aga_t1951_at2690_hsb9f66b18.aspx" UserDefinedDisableRowSelection="False" PageId="REQUISICOES_SO_LEITURA__ITENSDETRANSFERENCIADEFILIAL_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7252" Title="Inspeções Adicionais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ROTEIROSADICIONAIS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.REQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4889_at7252_hsd97c11b7.aspx" UserDefinedDisableRowSelection="False" PageId="REQUISICOES_SO_LEITURA__ITENSDETRANSFERENCIADEFILIAL_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7323" Title="Inspeções Adicionais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ROTEIROSADICIONAIS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.REQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4889_at7323_hs5a5dc37e.aspx" UserDefinedDisableRowSelection="False" PageId="REQUISICOES_SO_LEITURA__ITENSDETRANSFERENCIADEFILIAL_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2691" Title="Log" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_Z_LOG.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.REGISTRO = @RASTRO(CP_REQUISICOES))" FormUrl="~/aga/a/f/aga_t425_at2691_hs5f436c8b.aspx" UserDefinedDisableRowSelection="False" PageId="REQUISICOES_SO_LEITURA__ITENSDETRANSFERENCIADEFILIAL_FORM" Level="20" Order="45"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2692" Title="Lotes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICAOATENDIMENTOLOTES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.TIPOLOTE &lt;&gt; 2 AND (A.REQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1758_at2692_hs89456660.aspx" UserDefinedDisableRowSelection="False" PageId="REQUISICOES_SO_LEITURA__ITENSDETRANSFERENCIADEFILIAL_FORM" Level="20" Order="50"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7462" Title="Lotes Destino" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICAOATENDIMENTOLOTES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.TIPOLOTE = 2 AND (A.REQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1758_at7462_hs6f956b1d.aspx" UserDefinedDisableRowSelection="False" PageId="REQUISICOES_SO_LEITURA__ITENSDETRANSFERENCIADEFILIAL_FORM" Level="20" Order="55"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5408" Title="Notas fiscais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_FN_DOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.HANDLE IN(SELECT DOCUMENTO FROM CM_ITENS WHERE REQUISICAO = @RASTRO(CP_REQUISICOES))" FormUrl="~/aga/a/f/aga_t1216_at5408_hs19cf08a1.aspx" UserDefinedDisableRowSelection="False" PageId="REQUISICOES_SO_LEITURA__ITENSDETRANSFERENCIADEFILIAL_FORM" Level="20" Order="60"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8082" Title="Requisição de aquisição" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN ( SELECT REQUISICAO FROM LC_REQUISICAOITENS WHERE HANDLE IN ( SELECT REQUISICAOAQUISICAO FROM CP_REQUISICOES WHERE HANDLE = @RASTRO(CP_REQUISICOES)))" FormUrl="~/aga/a/f/aga_t1792_at8082_hsa0895d17.aspx" UserDefinedDisableRowSelection="False" PageId="REQUISICOES_SO_LEITURA__ITENSDETRANSFERENCIADEFILIAL_FORM" Level="20" Order="65"  />
        </div>
    
      </asp:Content>
    