<%@ Page Title="REG.C110: INFORMAÇÃO COMPLEMENTAR" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="REG.C110: INFORMAÇÃO COMPLEMENTAR" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_ED_DOCUMENTOOBSERVACOES.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="ED_CARGA_EFD_C_100_SAIDAS__REGISTRO_C110_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5523" Title="REG.C111: PROCESSO REFERENCIADO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_DOCUMENTOOBSPROCESSO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DOCUMENTOOBS = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3149_at5523_hs177f4fe0.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFD_C_100_SAIDAS__REGISTRO_C110_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5524" Title="REG.C112: DOC. ARRECADAÇÃO REFERENCIADO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_DOCUMENTOOBSARRECADACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DOCUMENTOOBS = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3150_at5524_hs2f88f20f.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFD_C_100_SAIDAS__REGISTRO_C110_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5525" Title="REG.C113: DOCUMENTO FISCAL REFERENCIADO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_DOCUMENTOOBSDOCFISCAL.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (
              SELECT HANDLE
                FROM ED_DOCUMENTOOBSDOCFISCAL
               WHERE DOCUMENTOOBS = @RASTRO(ED_DOCUMENTOOBSERVACOES)
            )" FormUrl="~/aga/a/f/aga_t3152_at5525_hsd23066aa.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFD_C_100_SAIDAS__REGISTRO_C110_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5526" Title="REG.C114: CUPOM FISCAL REFERENCIADO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_DOCUMENTOOBSCUPOMFISCAL.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DOCUMENTOOBS = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3151_at5526_hsff75adb1.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFD_C_100_SAIDAS__REGISTRO_C110_FORM" Level="20" Order="25"  />
        </div>
    
      </asp:Content>
    