<%@ Page Title="Planos de inspeção" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Planos de inspeção" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_QL_PLANOSINSPECAO.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="QUALIDADE__PLANOS_DE_INSPECAO_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7245" Title="Códigos amostragem" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_QL_CODIGOSAMOSTRAGEM.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOINSPECAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4878_at7245_hs463a08c9.aspx" UserDefinedDisableRowSelection="False" PageId="QUALIDADE__PLANOS_DE_INSPECAO_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7247" Title="NQA - Níveis de qualidade aceitável" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_QL_NQA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOINSPECAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4880_at7247_hs2f966b91.aspx" UserDefinedDisableRowSelection="False" PageId="QUALIDADE__PLANOS_DE_INSPECAO_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7244" Title="Níveis Inspeção" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_QL_NIVEISINSPECAO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOINSPECAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4877_at7244_hs1b2d818e.aspx" UserDefinedDisableRowSelection="False" PageId="QUALIDADE__PLANOS_DE_INSPECAO_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7248" Title="Níveis de severidade" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_QL_NIVEISSEVERIDADE.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOINSPECAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4881_at7248_hsc00bf90d.aspx" UserDefinedDisableRowSelection="False" PageId="QUALIDADE__PLANOS_DE_INSPECAO_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7282" Title="Planos Amostragem" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_QL_PLANOSAMOSTRAGEM.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOINSPECAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4882_at7282_hs8082eae9.aspx" UserDefinedDisableRowSelection="False" PageId="QUALIDADE__PLANOS_DE_INSPECAO_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7246" Title="Tamanhos de lotes x Níveis de inspeção" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_QL_TAMANHOLOTES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOINSPECAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4879_at7246_hs3bc2c805.aspx" UserDefinedDisableRowSelection="False" PageId="QUALIDADE__PLANOS_DE_INSPECAO_FORM" Level="20" Order="35"  />
        </div>
    
      </asp:Content>
    