<%@ Page Title="Itens" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Itens" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_CM_CONTRATOITENS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="CM_CONTRATOIMOBILIARIO__ITENSRO_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3542" Title="Comissões" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_CONTRATOITEMCOMISSOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2041_at3542_hs6f9adf6d.aspx" UserDefinedDisableRowSelection="False" PageId="CM_CONTRATOIMOBILIARIO__ITENSRO_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3538" Title="Comissões" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_CONTRATOITEMCOMISSOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2041_at3538_hsa70b9384.aspx" UserDefinedDisableRowSelection="False" PageId="CM_CONTRATOIMOBILIARIO__ITENSRO_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3543" Title="Documentos para locação" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_CONTRATOITEMDOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2447_at3543_hs778d9a64.aspx" UserDefinedDisableRowSelection="False" PageId="CM_CONTRATOIMOBILIARIO__ITENSRO_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3539" Title="Faixas de itens de apontamento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_CONTRATOITEMFAIXAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2042_at3539_hs71093169.aspx" UserDefinedDisableRowSelection="False" PageId="CM_CONTRATOIMOBILIARIO__ITENSRO_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3544" Title="Garantias para locação" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_CONTRATOITEMGARANTIAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2446_at3544_hs3acea6b6.aspx" UserDefinedDisableRowSelection="False" PageId="CM_CONTRATOIMOBILIARIO__ITENSRO_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3537" Title="Liberações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDEMVENDALIBERACOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ITEMCONTRATO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1960_at3537_hs7d6b841f.aspx" UserDefinedDisableRowSelection="False" PageId="CM_CONTRATOIMOBILIARIO__ITENSRO_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3541" Title="Ocorrências" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_CONTRATOOCORRENCIAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.EHHISTORICO='N'  AND A.ITEMFATURAMENTO IS NULL AND (A.ITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2037_at3541_hsc43734a2.aspx" UserDefinedDisableRowSelection="False" PageId="CM_CONTRATOIMOBILIARIO__ITENSRO_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3535" Title="Períodos reajuste" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_CONTRATOITEMPERIODOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2068_at3535_hs21099ce4.aspx" UserDefinedDisableRowSelection="False" PageId="CM_CONTRATOIMOBILIARIO__ITENSRO_FORM" Level="20" Order="45"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3536" Title="Reajustes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_CONTRATOITEMREAJUSTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ITEMCONTRATO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2004_at3536_hs760cdc1a.aspx" UserDefinedDisableRowSelection="False" PageId="CM_CONTRATOIMOBILIARIO__ITENSRO_FORM" Level="20" Order="50"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3540" Title="Renovações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_CONTRATOITEMRENOVACOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2044_at3540_hs3e09b9dd.aspx" UserDefinedDisableRowSelection="False" PageId="CM_CONTRATOIMOBILIARIO__ITENSRO_FORM" Level="20" Order="55"  />
        </div>
    
      </asp:Content>
    