//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using Ninject;
using Benner.Tecnologia.Common.Services;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Benner.Corporativo.Definicoes.Suprimentos;
using Benner.Tecnologia.Business;

public partial class faga_t1645_at8039_hse56c35d7Page : WesPage
{
    [Inject]
    public ISessionVars SessionVars { get; set; }

    [Inject]
    public ICPGrupoAlcadaDao CPGrupoAlcadasDao { get; set; }

    protected override void OnLoad(EventArgs e)
    {
        base.OnLoad(e);
        FORMULARIO.CommandExecute += FORMULARIO_CommandExecute;
    }

    private void FORMULARIO_CommandExecute(object sender, FormCommandExecuteArgs e)
    {
        if (e.CommandName == "CMD_DUPLICAR")
        {
            var handleGrupoAlcada = new Handle(FORMULARIO.GetEntity().Fields["HANDLE"].ToLong());
            SessionVars.SetSessionVar("HANDLE_GRUPOALCADA", handleGrupoAlcada.IsValid() ? handleGrupoAlcada.ToString() : "0");

        }
    }
}
