<%@ Page Title="Quest - Qualificação fornecedor - Por pessoa" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Quest - Qualificação fornecedor - Por pessoa" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_GN_PESSOAS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="QL_QUALIDADEFORNECEDOR__PORPESSOA_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7549" Title="Aguardando liberação" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_QL_RESPOSTASFORNECEDOR.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 4 AND (A.FORNECEDOR = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4890_at7549_hsc04aa9d9.aspx" UserDefinedDisableRowSelection="False" PageId="QL_QUALIDADEFORNECEDOR__PORPESSOA_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7546" Title="Cadastrada" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_QL_RESPOSTASFORNECEDOR.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 1 AND (A.FORNECEDOR = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4890_at7546_hse61f4968.aspx" UserDefinedDisableRowSelection="False" PageId="QL_QUALIDADEFORNECEDOR__PORPESSOA_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7550" Title="Liberada" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_QL_RESPOSTASFORNECEDOR.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 5 AND (A.FORNECEDOR = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4890_at7550_hs7a24999.aspx" UserDefinedDisableRowSelection="False" PageId="QL_QUALIDADEFORNECEDOR__PORPESSOA_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7547" Title="Pendente interna" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_QL_RESPOSTASFORNECEDOR.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 2 AND (A.FORNECEDOR = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4890_at7547_hs948347f5.aspx" UserDefinedDisableRowSelection="False" PageId="QL_QUALIDADEFORNECEDOR__PORPESSOA_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7548" Title="Pendente na web" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_QL_RESPOSTASFORNECEDOR.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 3 AND (A.FORNECEDOR = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4890_at7548_hs904e97b6.aspx" UserDefinedDisableRowSelection="False" PageId="QL_QUALIDADEFORNECEDOR__PORPESSOA_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7552" Title="Reenviada web" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_QL_RESPOSTASFORNECEDOR.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 7 AND (A.FORNECEDOR = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4890_at7552_hs745dd844.aspx" UserDefinedDisableRowSelection="False" PageId="QL_QUALIDADEFORNECEDOR__PORPESSOA_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7551" Title="Reprovada" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_QL_RESPOSTASFORNECEDOR.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 6 AND (A.FORNECEDOR = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4890_at7551_hs9d9212e1.aspx" UserDefinedDisableRowSelection="False" PageId="QL_QUALIDADEFORNECEDOR__PORPESSOA_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7553" Title="Todos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_QL_RESPOSTASFORNECEDOR.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.FORNECEDOR = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4890_at7553_hs56be7c0.aspx" UserDefinedDisableRowSelection="False" PageId="QL_QUALIDADEFORNECEDOR__PORPESSOA_FORM" Level="20" Order="45"  />
        </div>
    
      </asp:Content>
    