<%@ Page Title="Arquivos - Processados" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Arquivos - Processados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_GN_HBVARREDURASACADO.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="FN_CARGA_HBVARREDURASACADO_ARQUIVOS__PROCESSADOS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6635" Title="Excluídos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_HBVARREDURASACADOPARCELAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.SITUACAO = 4 AND (A.VARREDURA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3641_at6635_hscbd1c5e8.aspx" UserDefinedDisableRowSelection="False" PageId="FN_CARGA_HBVARREDURASACADO_ARQUIVOS__PROCESSADOS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5875" Title="Não reconhecidos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_HBVARREDURASACADOPARCELAS.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.SITUACAO = 2 AND (A.VARREDURA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3641_at5875_hs73d73df8.aspx" UserDefinedDisableRowSelection="False" PageId="FN_CARGA_HBVARREDURASACADO_ARQUIVOS__PROCESSADOS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5876" Title="Pendentes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_HBVARREDURASACADOPARCELAS.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.SITUACAO = 3 AND (A.VARREDURA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3641_at5876_hs92532bfb.aspx" UserDefinedDisableRowSelection="False" PageId="FN_CARGA_HBVARREDURASACADO_ARQUIVOS__PROCESSADOS_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5874" Title="Reconhecidos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_HBVARREDURASACADOPARCELAS.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.SITUACAO = 1 AND (A.VARREDURA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3641_at5874_hs93680dc3.aspx" UserDefinedDisableRowSelection="False" PageId="FN_CARGA_HBVARREDURASACADO_ARQUIVOS__PROCESSADOS_FORM" Level="20" Order="25"  />
        </div>
    
      </asp:Content>
    