<%@ Page Title="Este grupo é permissão adicional para..." Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Este grupo é permissão adicional para..." Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_Z_GRUPOUSUARIOS.FORM" CanDelete="False" CanUpdate="True" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="ADM_GRUPOS_DE_SEGURANCA__USUARIOSADICIONADOS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1820" Title="Adicionar permissões" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_Z_GRUPOUSUARIOGRUPOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.USUARIO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1763_at1820_hs4eb5a2ba.aspx" UserDefinedDisableRowSelection="False" PageId="ADM_GRUPOS_DE_SEGURANCA__USUARIOSADICIONADOS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_451" Title="Agendas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_Z_AGENDAUSUARIOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="  AND (A.USUARIO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t905_at451_hs6e2037db.aspx" UserDefinedDisableRowSelection="False" PageId="ADM_GRUPOS_DE_SEGURANCA__USUARIOSADICIONADOS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1995" Title="Alçadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_Z_GRUPOUSUARIOALCADAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.USUARIO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1863_at1995_hs5d6637a1.aspx" UserDefinedDisableRowSelection="False" PageId="ADM_GRUPOS_DE_SEGURANCA__USUARIOSADICIONADOS_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1001" Title="Empresas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_Z_GRUPOUSUARIOEMPRESAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.USUARIO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1281_at1001_hs2aca00ff.aspx" UserDefinedDisableRowSelection="False" PageId="ADM_GRUPOS_DE_SEGURANCA__USUARIOSADICIONADOS_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2524" Title="Filtro de registros" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_Z_FILTROS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(PERMISSAO = 'S') AND (A.USUARIO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t631_at2524_hs8e935239.aspx" UserDefinedDisableRowSelection="False" PageId="ADM_GRUPOS_DE_SEGURANCA__USUARIOSADICIONADOS_FORM" Level="20" Order="30"  />
        <wes:AjaxForm runat="server" ID="WIDGET_7588" Title="Integrar lembrete" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PARAMETROSLEMBRETES.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="(A.USUARIO = @CAMPO(HANDLE))" UserDefinedCommandsVisible="True" PageId="ADM_GRUPOS_DE_SEGURANCA__USUARIOSADICIONADOS_FORM" Level="20" Order="35"  />
        <wes:AjaxForm runat="server" ID="WIDGET_7112" Title="Permissões do mód. manutenção de frotas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_USUARIOPERMISSOES.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="A.TIPOREGISTRO = 1 AND (A.USUARIO = @CAMPO(HANDLE))" UserDefinedCommandsVisible="True" PageId="ADM_GRUPOS_DE_SEGURANCA__USUARIOSADICIONADOS_FORM" Level="20" Order="40"  />
        </div>
    
      </asp:Content>
    