<%@ Page Title="Contas" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="PLANO" Title="Plano" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_CT_PLANOSGERENCIAIS.GERENCIAL.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="CARGA_DE_PLANO_GERENCIAL__CONTAS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="CONTAS" Title="Contas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="5" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="PLANO" ChromeState="Normal" CanDelete="False" CanUpdate="True" CanInsert="True" EntityViewName="AGA_CT_CONTASGERENCIAIS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="(A.PLANO= @CAMPO(HANDLE))" FormUrl="~/aga/a/Contabil/contas/ContaGerencial.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_PLANO_GERENCIAL__CONTAS_FORM" Level="20" Order="5"  />
        <wes:AjaxForm runat="server" ID="CONTAGERENCIAL" Title="Conta Gerencial" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="7" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="CONTAS" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="True" EntityViewName="AGA_CT_CONTASGERENCIAIS.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="CARGA_DE_PLANO_GERENCIAL__CONTAS_FORM" Level="20" Order="7"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2192" Title="Contas calculadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="CONTAGERENCIAL" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_CT_CONTAGERENCIALFORMULAS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.CONTAINFORMADA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1957_at2192_hsace42200.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_PLANO_GERENCIAL__CONTAS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_747" Title="Contas contábeis" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="CONTAGERENCIAL" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_CT_CONTAGERENCIALCONTAS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.CONTAGERENCIAL = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t917_at747_hs35e70fc9.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_PLANO_GERENCIAL__CONTAS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1029" Title="Contas financeiras" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="CONTAGERENCIAL" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_CT_CONTAGERENCIALFINANCEIRAS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.CONTAGERENCIAL = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1298_at1029_hsabf1c84a.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_PLANO_GERENCIAL__CONTAS_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6053" Title="Contas gerenciais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="CONTAGERENCIAL" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_CT_CONTAGERENCIALORCAMENTARIAS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.CONTAGERENCIAL = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2025_at6053_hs1a1775e1.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_PLANO_GERENCIAL__CONTAS_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8179" Title="Subcontas Correlatas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="CONTAGERENCIAL" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_CT_SUBCONTASGERENCIAIS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.CONTAGERENCIAL = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5644_at8179_hsde6bb23.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_PLANO_GERENCIAL__CONTAS_FORM" Level="20" Order="55"  />
        </div>
    
        <style>
              #ctl00_Main_PLANO {
    display: none;
}

              </style>
      </asp:Content>
    