<%@ Page Title="Ordens serviço - Canceladas" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Ordens serviço - Canceladas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_OS_ORDENSSERVICO.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="ORDENS_SERVICO__CANCELADAS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2012" Title="Itens" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_OS_APONTAMENTOINSUMOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.ORDEMSERVICO = @RASTRO(OS_ORDENSSERVICO) AND (A.ORDEMSERVICO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1851_at2012_hsf237a430.aspx" UserDefinedDisableRowSelection="False" PageId="ORDENS_SERVICO__CANCELADAS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2200" Title="Liberações para faturamento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDEMVENDALIBERACOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TABELAORIGEM = 3 AND A.HANDLEORIGEM = @RASTRO(OS_ORDENSSERVICO)) OR (A.TABELAORIGEM = 2 AND A.HANDLEORIGEM IN (SELECT B.HANDLE FROM OS_APONTAMENTOINSUMOS B WHERE B.ORDEMSERVICO = @RASTRO(OS_ORDENSSERVICO)))" FormUrl="~/aga/a/f/aga_t1960_at2200_hs2b75f116.aspx" UserDefinedDisableRowSelection="False" PageId="ORDENS_SERVICO__CANCELADAS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2013" Title="Tarefas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_OS_ORDEMSERVICOTAREFAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.ORDEMSERVICO = @RASTRO(OS_ORDENSSERVICO) AND (A.ORDEMSERVICO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1855_at2013_hs66c3f158.aspx" UserDefinedDisableRowSelection="False" PageId="ORDENS_SERVICO__CANCELADAS_FORM" Level="20" Order="20"  />
        </div>
    
      </asp:Content>
    