<%@ Page Title="Parâmetros de Integração FR" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Parâmetros de Integração FR" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_GN_FRPARAMETROINTEGRACOES.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="CARGA_DE_EMPRESA__GN_FRPARAMETROSINTEGRACOES_FORM" Level="20" Order="1"  />
        <wes:AjaxForm runat="server" ID="WIDGET_8292" Title="Receita Federal CNPJ" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_FRPARAMETROCONSULTAS.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="A.TIPOCONSULTA = 2 AND (A.PARAMETROINTEGRACAO = @CAMPO(HANDLE))" UserDefinedCommandsVisible="True" PageId="CARGA_DE_EMPRESA__GN_FRPARAMETROSINTEGRACOES_FORM" Level="20" Order="10"  />
        <wes:AjaxForm runat="server" ID="WIDGET_8293" Title="Receita Federal CPF" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_FRPARAMETROCONSULTAS.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="A.TIPOCONSULTA = 3 AND (A.PARAMETROINTEGRACAO = @CAMPO(HANDLE))" UserDefinedCommandsVisible="True" PageId="CARGA_DE_EMPRESA__GN_FRPARAMETROSINTEGRACOES_FORM" Level="20" Order="15"  />
        <wes:AjaxForm runat="server" ID="WIDGET_8291" Title="Sintegra" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_FRPARAMETROCONSULTAS.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="A.TIPOCONSULTA = 1 AND (A.PARAMETROINTEGRACAO = @CAMPO(HANDLE))" UserDefinedCommandsVisible="True" PageId="CARGA_DE_EMPRESA__GN_FRPARAMETROSINTEGRACOES_FORM" Level="20" Order="20"  />
        </div>
    
      </asp:Content>
    