<%@ Page Title="FCONT - Escrituração Fiscal Contábil - Períodos" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="FCONT - Escrituração Fiscal Contábil - Períodos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_ED_PERIODOS.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="FCONT_MODULO__PERIODOS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1715_5849" Title="Cadastros&gt;I050 - Plano de Contas Contábil" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PLANOVERSOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" FormUrl="~/aga/a/f/aga_t3436_at5849_hs2368744f.aspx" UserDefinedDisableRowSelection="False" PageId="FCONT_MODULO__PERIODOS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1715_5850" Title="Cadastros&gt;I051 - Plano de Contas Referencial" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_CONTAPLANOSREFERENCIAIS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.ORIGEM IN (
   SELECT REL.HANDLE
     FROM CT_CONTAGERENCIALCONTAS REL
    WHERE REL.PLANO = 
       (SELECT PAR.PLANOREFERENCIAL
          FROM ED_PARAMETROSFCONT PAR
         WHERE PAR.EMPRESA = @EMPRESAMESTRE(ED_PARAMETROSFCONT)
           AND (SELECT PERIODO.DATAINICIAL
                  FROM ED_PERIODOS PERIODO
                 WHERE PERIODO.HANDLE = @RASTRO(ED_PERIODOS) 
                )
               BETWEEN PAR.DATAINICIAL AND PAR.DATAFINAL
        )
  )" FormUrl="~/aga/a/f/aga_t3230_at5850_hs45697b55.aspx" UserDefinedDisableRowSelection="False" PageId="FCONT_MODULO__PERIODOS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1715_5852" Title="Cadastros&gt;I075 - Tabela de históricos padronizados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_HISTORICOSPADROES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" FormUrl="~/aga/a/f/aga_t3232_at5852_hs27bf24da.aspx" UserDefinedDisableRowSelection="False" PageId="FCONT_MODULO__PERIODOS_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1715_5848" Title="Cadastros&gt;I100 - Centros de custos (Subcontas)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_CENTROSCUSTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" FormUrl="~/aga/a/f/aga_t3233_at5848_hs76e046f8.aspx" UserDefinedDisableRowSelection="False" PageId="FCONT_MODULO__PERIODOS_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1715_5854" Title="Cadastros&gt;J930 - Signatários" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_TERMOENCERRAMENTOSIGNATARIO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.PERIODO = @RASTRO(ED_PERIODOS)" FormUrl="~/aga/a/f/aga_t3251_at5854_hs518780ff.aspx" UserDefinedDisableRowSelection="False" PageId="FCONT_MODULO__PERIODOS_FORM" Level="20" Order="30"  />
        <wes:AjaxForm runat="server" ID="WIDGET_1715_5853" Title="Cadastros&gt;M020 - Qualificação da PJ e Retificação" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_QUALIFICACOESPJ.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" UserDefinedCommandsVisible="True" PageId="FCONT_MODULO__PERIODOS_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5851" Title="Histórico" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_LOG.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3219_at5851_hs83cc33bd.aspx" UserDefinedDisableRowSelection="False" PageId="FCONT_MODULO__PERIODOS_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1715_1716_5855" Title="Movimentações&gt;I200 - Lançamentos contábeis&gt;Expurgos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_LANCAMENTOSCONTABEISFCONT.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="TIPO = 1 AND (A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3628_at5855_hs8bb5584e.aspx" UserDefinedDisableRowSelection="False" PageId="FCONT_MODULO__PERIODOS_FORM" Level="20" Order="45"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1715_1716_5856" Title="Movimentações&gt;I200 - Lançamentos contábeis&gt;Fiscais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_LANCAMENTOSCONTABEISFCONT.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="TIPO &lt;&gt; 1 AND (A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3628_at5856_hs23e7db5e.aspx" UserDefinedDisableRowSelection="False" PageId="FCONT_MODULO__PERIODOS_FORM" Level="20" Order="50"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1715_5857" Title="Movimentações&gt;M030 - Períodos de apuração" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PERIODOSAPURACAO.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3625_at5857_hse8da90ff.aspx" UserDefinedDisableRowSelection="False" PageId="FCONT_MODULO__PERIODOS_FORM" Level="20" Order="55"  />
        </div>
    
      </asp:Content>
    