<%@ Page Title="Orçamentos despesas" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Orçamentos despesas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_PJ_TAREFAORCAMENTOS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="PJ_TAREFA_LEITURA__ORCAMENTO_DEBITOS_SL_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3837" Title="Aquisições" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" FormUrl="~/aga/a/f/aga_t1797_at3837_hs65da645b.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTO_DEBITOS_SL_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3839" Title="Competências" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PJ_ORCAMENTOCOMPETENCIAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1905_at3839_hs1dec1dfe.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTO_DEBITOS_SL_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3836" Title="Compromissos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PJ_ORCAMENTOCOMPROMISSOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1903_at3836_hse2bda1a.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTO_DEBITOS_SL_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1167_3843" Title="Prestação de contas&gt;Cadastradas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PJ_ORCAMENTODOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(DOCUMENTOGERADO IS NULL) AND (NATUREZA= 'D') AND (TIPO = 1) AND (A.ORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2585_at3843_hse022cffc.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTO_DEBITOS_SL_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1167_3845" Title="Prestação de contas&gt;Cancelados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PJ_ORCAMENTODOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(NATUREZA = 'X') AND (TIPO = 1) AND (A.ORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2585_at3845_hsbdcbf41f.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTO_DEBITOS_SL_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1167_3844" Title="Prestação de contas&gt;Emitidos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PJ_ORCAMENTODOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(DOCUMENTOGERADO IS NOT NULL) AND (NATUREZA= 'D')  AND (TIPO = 1) AND (A.ORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2585_at3844_hsbb88a2d2.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTO_DEBITOS_SL_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3840" Title="Requisições de aquisições" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TAREFAPROJETO = @RASTRO(PJ_TAREFAORCAMENTOS))" FormUrl="~/aga/a/f/aga_t1792_at3840_hs75a7e05e.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTO_DEBITOS_SL_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3838" Title="Requisições suprimentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOESPAI.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TAREFAPROJETO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2311_at3838_hs631d1807.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTO_DEBITOS_SL_FORM" Level="20" Order="45"  />
        </div>
    
      </asp:Content>
    