<%@ Page Title="Itens" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Itens" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_PR_ORDEMPRODUCAOITENS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="CARGA_DE_ITENS_OP_SOLEITURA__ITENS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6593" Title="Consumo previsto" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PR_ITEMCONSUMOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.APONTAMENTO IN (SELECT B.HANDLE FROM PR_ORDEMPRODUCAOAPONTAMENTOS B WHERE (B.STATUS=1) OR (B.STATUS=3))) AND (A.ORDEMPRODUCAOITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1843_at6593_hsa3474836.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_ITENS_OP_SOLEITURA__ITENS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6594" Title="Consumo realizado" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PR_ITEMCONSUMOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.APONTAMENTO IN (SELECT B.HANDLE FROM PR_ORDEMPRODUCAOAPONTAMENTOS B WHERE (B.STATUS=2))) AND (A.ORDEMPRODUCAOITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1843_at6594_hsfbab6797.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_ITENS_OP_SOLEITURA__ITENS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6595" Title="Lotes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PR_ORDEMPRODUCAOITEMLOTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMPRODUCAOITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1974_at6595_hs4f0b66e0.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_ITENS_OP_SOLEITURA__ITENS_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6598" Title="Ordem de compra" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN ( SELECT O.ORDEMCOMPRA  FROM CP_ORDENSCOMPRAITENS O WHERE O.HANDLE IN (SELECT I.ORDEMCOMPRAITEM FROM PR_ORDEMPRODUCAOITENS I WHERE I.HANDLE = @RASTRO(PR_ORDEMPRODUCAOITENS) ) )" FormUrl="~/aga/a/f/aga_t1529_at6598_hs80826de1.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_ITENS_OP_SOLEITURA__ITENS_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6596" Title="Requisição consumo de produção" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOESPAI.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT REQUISICAOPAI FROM CP_REQUISICOES WHERE HANDLE IN (SELECT REQUISICAO FROM PR_REQUISICOESCONSUMOITEM WHERE ORDEMPRODUCAOITEM =  @RASTRO(PR_ORDEMPRODUCAOITENS)))" FormUrl="~/aga/a/f/aga_t2311_at6596_hs2e5ce26.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_ITENS_OP_SOLEITURA__ITENS_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6597" Title="Requisições de compra" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOESPAI.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN ( SELECT REQUISICAOPAI FROM CP_REQUISICOES
  WHERE HANDLE = (SELECT REQUISICAO FROM PR_ORDEMPRODUCAOITENS WHERE HANDLE = @RASTRO(PR_ORDEMPRODUCAOITENS)))" FormUrl="~/aga/a/f/aga_t2311_at6597_hs35bec45b.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_ITENS_OP_SOLEITURA__ITENS_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7981" Title="Substitutos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PR_ORDEMPRODUCAOITENSSUBST.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMPRODUCAOITENS = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2534_at7981_hs25fea8a1.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_ITENS_OP_SOLEITURA__ITENS_FORM" Level="20" Order="40"  />
        </div>
    
      </asp:Content>
    