<%@ Page Title="Aquisições - Cadastradas" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Aquisições - Cadastradas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICOES.FORM" CanDelete="False" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2509" Title="Anexos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOANEXOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.RECURSO IS NULL) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1964_at2509_hsd295708b.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4451" Title="Cláusulas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CN_CONTRATOCLAUSULAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="CLAUSULA IS NULL AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2111_at4451_hsab29e86d.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2146" Title="Documentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAODOCUMENTOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ITEM IS NULL) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1799_at2146_hs9f17f6e2.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3615" Title="Documentos emitidos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_MODELODOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="((A.INATIVO = 'N') OR (A.INATIVO IS NULL)) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2468_at3615_hs91bb7dd5.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8306" Title="Integrantes da comissão" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_COMISSAOINTEGRANTES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1950_at8306_hs60d4c76d.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_621_3641" Title="Itens Aquisição&gt;Cancelados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS IN (2,8) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1801_at3641_hsb6487205.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_621_3654" Title="Itens Aquisição&gt;Comprados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="( A.AQUISICAO IN (SELECT AQUISICAO FROM CP_ORDENSCOMPRA 
                   WHERE HANDLE IN (SELECT ORDEMCOMPRA FROM CP_ORDENSCOMPRAITENS 
                                     WHERE PRODUTO IN (SELECT PRODUTO FROM LC_AQUISICAOITENS 
                                                        WHERE HANDLE = A.HANDLE)))
)OR
( A.STATUS = 7 ) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1801_at3654_hsb59eb49c.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_621_3639" Title="Itens Aquisição&gt;Desertos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS=4 AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1801_at3639_hscad36088.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="45"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_621_3640" Title="Itens Aquisição&gt;Fracassados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS=5 AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1801_at3640_hs5033aa8b.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="50"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_621_8142" Title="Itens Aquisição&gt;Não encerrados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 1 AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1801_at8142_hs7e423fb9.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="55"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_621_3638" Title="Itens Aquisição&gt;Todos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOITENS.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1801_at3638_hseaaa6582.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="60"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6090" Title="Log e-mails" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_LOGEMAIL.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.TABELAORIGEM = (SELECT HANDLE FROM Z_TABELAS WHERE NOME = 'LC_AQUISICOES') AND (A.HANDLEORIGEM = @RASTRO(LC_AQUISICOES))" FormUrl="~/aga/a/f/aga_t3904_at6090_hs14f4a127.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="65"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3665" Title="Lotes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOLOTES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2494_at3665_hs93bd1052.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="70"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3806" Title="Parecer" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_PARECER.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2583_at3806_hs7310b7ab.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="75"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3763" Title="Participantes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOPARTICIPANTES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1803_at3763_hs737f9257.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="80"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1885" Title="Requisições" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="(A.AQUISICAOGERADA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1792_at1885_hsc1f11de2.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="85"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8219" Title="Responsáveis" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CN_CONTRATOCOORDENADORES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2051_at8219_hsa5e4b775.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="90"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3617" Title="Retificações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAORETIFICACOES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2490_at3617_hseb97d486.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="95"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3737" Title="Roteiros" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOROTEIROS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2535_at3737_hs722331ef.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="100"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8354" Title="Termo de referência" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_TR.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.HANDLE IN (SELECT REQUISICAO.TERMOREFERENCIA  
                FROM LC_REQUISICOES REQUISICAO
               WHERE REQUISICAO.AQUISICAOGERADA = @RASTRO(LC_AQUISICOES)))" FormUrl="~/aga/a/f/aga_t5780_at8354_hsedcb8669.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CADASTRADAS_FORM" Level="20" Order="105"  />
        </div>
    
      </asp:Content>
    