<%@ Page Title="Registro de preço - Cadastrados" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Registro de preço - Cadastrados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOREGISTROPRECO.FORM" CanDelete="False" CanUpdate="True" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="LC_CARGA_DE_REGISTROPRECO__LC_CARGA_DE_REGISTROPRECO_CADASTRADOS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8168" Title="Histórico" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_STATUS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLETABELAORIGEM IN (SELECT B.HANDLE FROM Z_TABELAS B WHERE B.NOME = 'LC_AQUISICAOREGISTROPRECO') AND  A.HANDLEREGISTROORIGEM = @RASTRO(LC_AQUISICAOREGISTROPRECO)" FormUrl="~/aga/a/f/aga_t1951_at8168_hse554a1d4.aspx" UserDefinedDisableRowSelection="False" PageId="LC_CARGA_DE_REGISTROPRECO__LC_CARGA_DE_REGISTROPRECO_CADASTRADOS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8167" Title="Itens" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOREGISTROPRECOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.REGISTROPRECO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5667_at8167_hsb3931863.aspx" UserDefinedDisableRowSelection="False" PageId="LC_CARGA_DE_REGISTROPRECO__LC_CARGA_DE_REGISTROPRECO_CADASTRADOS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8182" Title="Ordens de compra" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.REGISTROPRECO = @RASTRO(LC_AQUISICAOREGISTROPRECO) AND A.STATUS &lt;&gt; 5 AND (A.REGISTROPRECO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1529_at8182_hsc6f8a5ff.aspx" UserDefinedDisableRowSelection="False" PageId="LC_CARGA_DE_REGISTROPRECO__LC_CARGA_DE_REGISTROPRECO_CADASTRADOS_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8193" Title="Prorrogações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_REGISTROPRECOPRORROGACOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.REGISTROPRECO = @RASTRO(LC_AQUISICAOREGISTROPRECO) AND (A.REGISTROPRECO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5691_at8193_hsa342783d.aspx" UserDefinedDisableRowSelection="False" PageId="LC_CARGA_DE_REGISTROPRECO__LC_CARGA_DE_REGISTROPRECO_CADASTRADOS_FORM" Level="20" Order="25"  />
        </div>
    
      </asp:Content>
    