<%@ Page Title="Histórico de manutenções" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Histórico de manutenções" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_MF_ORDEMSERVICOS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="MF_PNEUS__HISTORICO_DAS_MANUTENCOES_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7046" Title="Aquisições externas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_ORDEMAQUISICAOEXTERNA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMSERVICO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4666_at7046_hs8a862d7.aspx" UserDefinedDisableRowSelection="False" PageId="MF_PNEUS__HISTORICO_DAS_MANUTENCOES_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7045" Title="Aquisições internas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_ORDEMAQUISICAOINTERNA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMSERVICO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4665_at7045_hs6cfd4da5.aspx" UserDefinedDisableRowSelection="False" PageId="MF_PNEUS__HISTORICO_DAS_MANUTENCOES_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7050" Title="Combustíveis" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_ORDEMSERVICOCOMBUSTIVEIS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMSERVICO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4648_at7050_hs9c38faf0.aspx" UserDefinedDisableRowSelection="False" PageId="MF_PNEUS__HISTORICO_DAS_MANUTENCOES_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7049" Title="Documentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_ORDEMSERVICODOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMSERVICO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4645_at7049_hsbc7a1ea1.aspx" UserDefinedDisableRowSelection="False" PageId="MF_PNEUS__HISTORICO_DAS_MANUTENCOES_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7042" Title="Materiais internos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_ORDEMPRODUTOINTERNOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMSERVICO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4636_at7042_hs4992e1a9.aspx" UserDefinedDisableRowSelection="False" PageId="MF_PNEUS__HISTORICO_DAS_MANUTENCOES_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7043" Title="Materiais/Serviços externos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_ORDEMSERVICOPRODUTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMSERVICO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2624_at7043_hsa11b9b9e.aspx" UserDefinedDisableRowSelection="False" PageId="MF_PNEUS__HISTORICO_DAS_MANUTENCOES_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7048" Title="Multas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_ORDEMSERVICOMULTAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMSERVICO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4647_at7048_hs4e408d01.aspx" UserDefinedDisableRowSelection="False" PageId="MF_PNEUS__HISTORICO_DAS_MANUTENCOES_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7047" Title="Pneus" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_ORDEMSERVICOPNEUS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMSERVICO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4668_at7047_hsa8abd94b.aspx" UserDefinedDisableRowSelection="False" PageId="MF_PNEUS__HISTORICO_DAS_MANUTENCOES_FORM" Level="20" Order="45"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7044" Title="Serviços internos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MF_ORDEMSERVICOINTERNOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMSERVICO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4633_at7044_hs65a2c2cd.aspx" UserDefinedDisableRowSelection="False" PageId="MF_PNEUS__HISTORICO_DAS_MANUTENCOES_FORM" Level="20" Order="50"  />
        </div>
    
      </asp:Content>
    