<%@ Page Title="Apontamentos/medições - Em aprovação" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Apontamentos/medições - Em aprovação" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_CN_APONTAMENTOS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="CN_APONTAMENTOS__EMAPROVACAO_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4398" Title="Documentos financeiros" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_FN_DOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN ( SELECT DOCUMENTOCONVENIO FROM  CN_APONTAMENTOOBJETOS  
 WHERE APONTAMENTO = @RASTRO(CN_APONTAMENTOS) )" FormUrl="~/aga/a/f/aga_t1216_at4398_hs14965b89.aspx" UserDefinedDisableRowSelection="False" PageId="CN_APONTAMENTOS__EMAPROVACAO_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2887" Title="Histórico" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_STATUS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.HANDLETABELAORIGEM IN (SELECT B.HANDLE FROM Z_TABELAS B WHERE B.NOME = 'CN_APONTAMENTOS') AND A.HANDLEREGISTROORIGEM = @RASTRO(CN_APONTAMENTOS))" FormUrl="~/aga/a/f/aga_t1951_at2887_hs8890ce6d.aspx" UserDefinedDisableRowSelection="False" PageId="CN_APONTAMENTOS__EMAPROVACAO_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2829" Title="Itens/objetos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CN_APONTAMENTOOBJETOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.APONTAMENTO  IN (@RASTRO(CN_APONTAMENTOS))" FormUrl="~/aga/a/f/aga_t2226_at2829_hsf7c83b3b.aspx" UserDefinedDisableRowSelection="False" PageId="CN_APONTAMENTOS__EMAPROVACAO_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3908" Title="Municípios" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CN_APONTAMENTOMUNICIPIOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.APONTAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2601_at3908_hsef5f450.aspx" UserDefinedDisableRowSelection="False" PageId="CN_APONTAMENTOS__EMAPROVACAO_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3001" Title="Notas NDC associadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_FN_LANCAMENTOSNDC.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLEAPONTAMENTO  IN (@RASTRO(CN_APONTAMENTOS))" FormUrl="~/aga/a/f/aga_t1593_at3001_hs3d8a9d1e.aspx" UserDefinedDisableRowSelection="False" PageId="CN_APONTAMENTOS__EMAPROVACAO_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3798" Title="Notas fiscais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_FN_DOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT DOCUMENTO FROM CM_ITENS 
WHERE HANDLE IN (SELECT ITEMNF FROM CN_LIBERACOESFATURAMENTO WHERE
APONTAMENTO = @RASTRO(CN_APONTAMENTOS)))" FormUrl="~/aga/a/f/aga_t1216_at3798_hs3a560b6b.aspx" UserDefinedDisableRowSelection="False" PageId="CN_APONTAMENTOS__EMAPROVACAO_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3292" Title="Ordens de compra geradas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.APONTAMENTOGERADOR = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1529_at3292_hsd27bd2ef.aspx" UserDefinedDisableRowSelection="False" PageId="CN_APONTAMENTOS__EMAPROVACAO_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3747" Title="Recebimentos físicos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_RECEBIMENTOFISICO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.APONTAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1584_at3747_hsa29a25b.aspx" UserDefinedDisableRowSelection="False" PageId="CN_APONTAMENTOS__EMAPROVACAO_FORM" Level="20" Order="45"  />
        </div>
    
      </asp:Content>
    