<%@ Page Title="Saídas - REG.F200: OPERAÇÕES IMOBILIÁRIAS" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Saídas - REG.F200: OPERAÇÕES IMOBILIÁRIAS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_ED_PCOPERACOESIMOB.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="ED_CARGA_EFDPC_SAIDAS__ED_CARGA_EFDPC_SAIDAS_CARGAF200_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6804" Title="REG.F205: CRÉDITOS DE OP. IMOB." Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PCOPERACAOIMOBCREDITOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.OPERACAOIMOBILIARIA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4545_at6804_hs285016ae.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFDPC_SAIDAS__ED_CARGA_EFDPC_SAIDAS_CARGAF200_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6805" Title="REG.F210: CRÉDITOS FUTUROS DE OP. IMOB." Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PCOPERACAOIMOBCREDFUTUROS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.OPERACAOIMOBILIARIA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4546_at6805_hs405ab8dd.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFDPC_SAIDAS__ED_CARGA_EFDPC_SAIDAS_CARGAF200_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6806" Title="REG.F211: PROCESSOS REFERENCIADOS." Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PCOPERACAOIMOBPROCESSOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.OPERACAOIMOBILIARIA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4547_at6806_hs9db34442.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFDPC_SAIDAS__ED_CARGA_EFDPC_SAIDAS_CARGAF200_FORM" Level="20" Order="20"  />
        </div>
    
      </asp:Content>
    