<%@ Page Title="Participantes" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Participantes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOPARTICIPANTES.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="LC_CARGA_DE_AQUISICAO_CONFIRMADA__AQUISICAOPARTICIPANTES_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3311" Title="Anexos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_PARTICIPANTEANEXOS.GRID" CanDelete="True" CanUpdate="False" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PARTICIPANTE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2378_at3311_hs996818fe.aspx" UserDefinedDisableRowSelection="False" PageId="LC_CARGA_DE_AQUISICAO_CONFIRMADA__AQUISICAOPARTICIPANTES_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1881" Title="Qualificação econômico financeira" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_FORNECEDORIQF.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DATAINCLUSAO=(SELECT MAX(DATAINCLUSAO) FROM LC_FORNECEDORIQF WHERE FORNECEDOR = (SELECT PARTICIPANTE FROM LC_AQUISICAOPARTICIPANTES WHERE HANDLE=@RASTRO(LC_AQUISICAOPARTICIPANTES)))) AND (A.FORNECEDOR = (SELECT PARTICIPANTE FROM LC_AQUISICAOPARTICIPANTES WHERE HANDLE=@RASTRO(LC_AQUISICAOPARTICIPANTES)))" FormUrl="~/aga/a/f/aga_t1811_at1881_hsb5b6cb9e.aspx" UserDefinedDisableRowSelection="False" PageId="LC_CARGA_DE_AQUISICAO_CONFIRMADA__AQUISICAOPARTICIPANTES_FORM" Level="20" Order="15"  />
        </div>
    
      </asp:Content>
    