<%@ Page Title="Confirmar" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Confirmar" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.FORM" CanDelete="False" CanUpdate="True" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="ORDENSVENDAEXPOSICOES__CONFIRMAR_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3435" Title="Comissões" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDEMVENDACOMISSOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMVENDA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1979_at3435_hsc96ec297.aspx" UserDefinedDisableRowSelection="False" PageId="ORDENSVENDAEXPOSICOES__CONFIRMAR_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2180" Title="Condições de recebimento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDEMVENDARECEBIMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMVENDA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1945_at2180_hs4fecd74b.aspx" UserDefinedDisableRowSelection="False" PageId="ORDENSVENDAEXPOSICOES__CONFIRMAR_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2181" Title="Itens da OV" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDEMVENDAITENS.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMVENDA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1944_at2181_hs46f1c05f.aspx" UserDefinedDisableRowSelection="False" PageId="ORDENSVENDAEXPOSICOES__CONFIRMAR_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3210" Title="Notas fiscais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_FN_DOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT DOCUMENTO FROM CM_ITENS 
WHERE HANDLE IN (SELECT ITEMNF FROM CM_ORDEMVENDALIBERACOES WHERE
ORDEMVENDAITEM IN (SELECT HANDLE FROM CM_ORDEMVENDAITENS WHERE ORDEMVENDA = @RASTRO(CM_ORDENSVENDA))))" FormUrl="~/aga/a/f/aga_t1216_at3210_hs365c677e.aspx" UserDefinedDisableRowSelection="False" PageId="ORDENSVENDAEXPOSICOES__CONFIRMAR_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7580" Title="Ordens de produção" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PR_ORDENSPRODUCAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT A.HANDLE FROM PR_ORDENSPRODUCAO WHERE A.HANDLEORIGEM IN (SELECT CM_ORDEMVENDAITENS.HANDLE FROM CM_ORDEMVENDAITENS WHERE CM_ORDEMVENDAITENS.ORDEMVENDA = @RASTRO(CM_ORDENSVENDA)))" FormUrl="~/aga/a/f/aga_t1835_at7580_hs5f253169.aspx" UserDefinedDisableRowSelection="False" PageId="ORDENSVENDAEXPOSICOES__CONFIRMAR_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2190" Title="Tributações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDEMVENDATRIBUTACOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DOCUMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1953_at2190_hsd29d17b9.aspx" UserDefinedDisableRowSelection="False" PageId="ORDENSVENDAEXPOSICOES__CONFIRMAR_FORM" Level="20" Order="35"  />
        </div>
    
      </asp:Content>
    