<%@ Page Title="REG.C170: ITENS DO DOC (01, 1B, 04 e 55)" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="REG.C170: ITENS DO DOC (01, 1B, 04 e 55)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_ED_DOCUMENTOITENS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="ED_CARGA_EFD_C100__REGSTRO_C170_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5559" Title="REG.C172: OP. C/ ISSQN (01,55)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_DOCUMENTOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE = @RASTRO(ED_DOCUMENTOITENS)" FormUrl="~/aga/a/f/aga_t3137_at5559_hse066db03.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFD_C100__REGSTRO_C170_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5560" Title="REG.C173: OP.COM MEDICAMENTOS (01,55)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_DOCUMENTOITEMMEDICAMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DOCUMENTOITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3140_at5560_hse065db03.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFD_C100__REGSTRO_C170_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5561" Title="REG.C174: OP. C/ ARMAS DE FOGO (01)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_DOCUMENTOITEMARMAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DOCUMENTOITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3141_at5561_hse068db03.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFD_C100__REGSTRO_C170_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5562" Title="REG.C175: OP. C/ VEÍCULOS NOVOS (01,55)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_DOCUMENTOITEMVEICULOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DOCUMENTOITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3142_at5562_hse067db03.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFD_C100__REGSTRO_C170_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5563" Title="REG.C176: RESSARCIMENTO ICMS EM OP." Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_DOCUMENTOITEMRESST.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DOCUMENTOITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3162_at5563_hse06adb03.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFD_C100__REGSTRO_C170_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5564" Title="REG.C177: OP. C/ PROD. SUJ. SELO CONT." Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_DOCUMENTOITEMSELOIPI.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DOCUMENTOITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3163_at5564_hse069db03.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFD_C100__REGSTRO_C170_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5565" Title="REG.C178: OP. C/ PROD. SUJ. IPI (01)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_DOCUMENTOITEMOPERACOESIPI.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DOCUMENTOITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3164_at5565_hse06cdb03.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFD_C100__REGSTRO_C170_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5566" Title="REG.C179: INFORMAÇÕES COMPLEMENTARES ST" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_DOCUMENTOITEMCOMPLEMENTOST.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DOCUMENTOITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3165_at5566_hse06bdb03.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFD_C100__REGSTRO_C170_FORM" Level="20" Order="45"  />
        </div>
    
      </asp:Content>
    