//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Common.Services;
using Benner.Tecnologia.Metadata.Entities;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using Benner.ERP.Comum;
using Ninject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Parameter = Benner.Tecnologia.Common.Parameter;

public partial class faga_t1797_at1857_hs7532f9ebPage : WesPage
{
    [Inject]
    IAdministrationService AdministrationService { get; set; }




    protected void Page_Load(object sender, System.EventArgs e)
    {
        FORMULARIO.CommandExecute += FORMULARIO_CommandExecute;

        //Select para pegar o status
        if (FORMULARIO.GetEntityHandle().NullableValue != null)
        {
            var aquisicao = new Query("SELECT STATUS FROM LC_AQUISICOES WHERE HANDLE = :AQUISICAO", new Parameter("AQUISICAO", FORMULARIO.GetEntityHandle())).Execute().FirstOrDefault();



            //Seta widget's como invisivel dependendo do status retornado da consulta ---
            switch (aquisicao["STATUS"].GetInt32())
            {
                case 1: //Status == Cadastrada
                    WIDGET_8048.Hidden = true; //Divulgação de fornecedores 
                    WIDGET_8215.Hidden = true; //Ocorrências 
                    JULGAMENTOCOMERCIAL.Hidden = true;
                    JULGAMENTOHABILITAO.Hidden = true;
                    JULGAMENTOTECNICA.Hidden = true;
                    WIDGET_622_3628.Hidden = true;
                    LOGPROCESSOS.Hidden = true;


                    FORMULARIO.CanInsert = true;
                    FORMULARIO.CanUpdate = true;
                    FORMULARIO.CanDelete = false;

                    //Log de processos - Adicionar
                    break;
                case 2: //Status == Confirmada
                    FORMULARIO.CanInsert = false;
                    FORMULARIO.CanUpdate = true;
                    FORMULARIO.CanDelete = false;
                    WIDGET_1865.CanInsert = false;
                    WIDGET_1865.CanUpdate = false;
                    WIDGET_1865.CanDelete = false;
                    //Aparece todos os widgets
                    break;
                case 3: //Status == Encerrada
                    LOGPROCESSOS.Hidden = true;

                    FORMULARIO.CanInsert = false;
                    FORMULARIO.CanUpdate = true;
                    FORMULARIO.CanDelete = false;
                    //Log de processos - Adicionar
                    break;
                case 4: //Status == Cancelada
                    LOGPROCESSOS.Hidden = true;

                    FORMULARIO.CanInsert = false;
                    FORMULARIO.CanUpdate = false;
                    FORMULARIO.CanDelete = false;
                    //Log de processos - Adicionar
                    break;
                default:
                    break;
            }

        }

        //Entidades invisiveis por padrão ---
        WIDGET_622_3766.Hidden = true;
        WIDGET_622_3649.Hidden = true;
        WIDGET_622_3656.Hidden = true;
        WIDGET_622_3647.Hidden = true;
        WIDGET_622_3648.Hidden = true;
        WIDGET_622_8144.Hidden = true;


        WIDGET_622_712_1097_3620.Hidden = true;
        WIDGET_622_712_1097_3621.Hidden = true;
        WIDGET_622_712_2211.Hidden = true;
        WIDGET_622_712_2212.Hidden = true;
        WIDGET_622_712_2213.Hidden = true;
        WIDGET_622_712_2214.Hidden = true;

    }

    private void FORMULARIO_CommandExecute(object sender, FormCommandExecuteArgs e)
    {
        if (e.CommandName == "CMD_SELECIONARREQUISICOES")
            ErpEnvironment.AtribuirSessionVar("AQUISICAO_SELECIONADA", e.Entity.Handle.ToString());
    }
}
