<%@ Page Title="Tabelas auxiliares - Códigos de ajuste da parte A" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Tabelas auxiliares - Códigos de ajuste da parte A" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_LA_CODIGOSAJUSTE.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="LA_TABELAS_AUXILIARES__LA_TABELASAUXILIARESCODIGOAJUSTES_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7586" Title="Códigos utilizados no e-Lacs" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LA_CODIGOSAJUSTEPARTEA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="EHCODIGOELACS = 'S' AND (A.TIPOENTIDADE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5213_at7586_hs7e6506a5.aspx" UserDefinedDisableRowSelection="False" PageId="LA_TABELAS_AUXILIARES__LA_TABELASAUXILIARESCODIGOAJUSTES_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7585" Title="Códigos utilizados no e-Lalur" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LA_CODIGOSAJUSTEPARTEA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="EHCODIGOELALUR = 'S' AND (A.TIPOENTIDADE = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5213_at7585_hsfa79f7f0.aspx" UserDefinedDisableRowSelection="False" PageId="LA_TABELAS_AUXILIARES__LA_TABELASAUXILIARESCODIGOAJUSTES_FORM" Level="20" Order="15"  />
        </div>
    
      </asp:Content>
    