<%@ Page Title="Informações Econômicas - REG.X340 - PARTICIPAÇÃO NO EXTERIOR" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Informações Econômicas - REG.X340 - PARTICIPAÇÃO NO EXTERIOR" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_EDCF_PEIDENTIFICACAO.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="CARGA_ECF_BLOCO_X__ECF_X340_PEIDENTIFICACAO_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7854" Title="REG.X350 - RESULTADO PERÍODO DE APURAÇÃO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_PERESULTADOPERIODO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PEIDENTIFICACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5276_at7854_hsf15dd31f.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_ECF_BLOCO_X__ECF_X340_PEIDENTIFICACAO_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7855" Title="REG.X351 - IMPOSTO PAGO NO EXTERIOR" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_DEMONSTRATIVOIEAPAGAR.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PEIDENTIFICACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5277_at7855_hs7f246261.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_ECF_BLOCO_X__ECF_X340_PEIDENTIFICACAO_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7856" Title="REG.X352 - DRE COLIGADAS EM REG.CAIXA" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_DEMONSTRATIVOREGIMECAIXA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PEIDENTIFICACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5278_at7856_hsbd4465c5.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_ECF_BLOCO_X__ECF_X340_PEIDENTIFICACAO_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7857" Title="REG.X353 - DEMONSTRATIVO DE CONSOLIDAÇÃO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_DEMONSTRATIVOCONSOLIDACAO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PEIDENTIFICACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5279_at7857_hs6d153cc6.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_ECF_BLOCO_X__ECF_X340_PEIDENTIFICACAO_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7858" Title="REG.X354 - DEMONSTRATIVO DE PREJUÍZOS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_DEMONSTRATIVOPREJUIZOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PEIDENTIFICACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5280_at7858_hsc76df994.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_ECF_BLOCO_X__ECF_X340_PEIDENTIFICACAO_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7859" Title="REG.X355 - DEMONSTRATIVO DE RENDAS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_DEMONSTRATIVORENDAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PEIDENTIFICACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5281_at7859_hs569eb9bd.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_ECF_BLOCO_X__ECF_X340_PEIDENTIFICACAO_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7860" Title="REG.X356 - DEMONST. ESTRUTURA SOCIETÁRIA" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_DEMONSTRATIVOESTRUTSOCIOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PEIDENTIFICACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5282_at7860_hs6f763eb3.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_ECF_BLOCO_X__ECF_X340_PEIDENTIFICACAO_FORM" Level="20" Order="40"  />
        </div>
    
      </asp:Content>
    