<%@ Page Title="Tabelas auxiliares - Operações comerciais" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Tabelas auxiliares - Operações comerciais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_CM_OPERACOESFATURAMENTO.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="IE_TABELAS_AUXILIARES_IMPORTACAO__OPERACOES_COMERCIAIS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7355" Title="Consulta pública NFe" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_CONSULTANFE.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.OPERACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5010_at7355_hse490ccd4.aspx" UserDefinedDisableRowSelection="False" PageId="IE_TABELAS_AUXILIARES_IMPORTACAO__OPERACOES_COMERCIAIS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2245" Title="Descrições padrões" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_OPERACAODESCRICOESPADROES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.OPERACAOFATURAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1978_at2245_hsbe084ae5.aspx" UserDefinedDisableRowSelection="False" PageId="IE_TABELAS_AUXILIARES_IMPORTACAO__OPERACOES_COMERCIAIS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7342" Title="Operações Faturamento Diferimento ICMS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_OPERACOESFATURAMENTODIFICMS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.OPERACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4994_at7342_hs3b46b3e4.aspx" UserDefinedDisableRowSelection="False" PageId="IE_TABELAS_AUXILIARES_IMPORTACAO__OPERACOES_COMERCIAIS_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1837" Title="Textos padrões" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_OPERACAOTEXTOSPADROES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.OPERACAOFATURAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1774_at1837_hsd1c0f1b4.aspx" UserDefinedDisableRowSelection="False" PageId="IE_TABELAS_AUXILIARES_IMPORTACAO__OPERACOES_COMERCIAIS_FORM" Level="20" Order="25"  />
        </div>
    
      </asp:Content>
    