<%@ Page Title="Por origem - Manual" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Por origem - Manual" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRA.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="CARGA_DE_OC__POR_ORIGEM__OC_MANUAL_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3578" Title="Anexos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRAANEXOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMCOMPRA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2469_at3578_hs27325875.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_OC__POR_ORIGEM__OC_MANUAL_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2400" Title="Condições de pagamento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRAPAGAMENTO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDENSCOMPRA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1532_at2400_hsa44e418e.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_OC__POR_ORIGEM__OC_MANUAL_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2402" Title="Historico" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_STATUS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.HANDLETABELAORIGEM IN (SELECT B.HANDLE FROM Z_TABELAS B WHERE B.NOME = 'CP_ORDENSCOMPRA') AND A.HANDLEREGISTROORIGEM = @RASTRO(CP_ORDENSCOMPRA))" FormUrl="~/aga/a/f/aga_t1951_at2402_hsb114da28.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_OC__POR_ORIGEM__OC_MANUAL_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2401" Title="Itens de OC" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRAITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.ORDEMCOMPRA = @RASTRO(CP_ORDENSCOMPRA)" FormUrl="~/aga/a/f/aga_t1530_at2401_hse45a2297.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_OC__POR_ORIGEM__OC_MANUAL_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_770_3492" Title="Notas fiscais&gt;Efetivas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_FN_DOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.ABRANGENCIA = 'R' AND A.HANDLE IN (SELECT  B.DOCUMENTO FROM CM_ITENS B, CP_ORDENSCOMPRAITENS C  WHERE B.ORDEMCOMPRAITEM = C.HANDLE AND C.ORDEMCOMPRA = @RASTRO(CP_ORDENSCOMPRA))" FormUrl="~/aga/a/f/aga_t1216_at3492_hsc9789e94.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_OC__POR_ORIGEM__OC_MANUAL_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_770_3491" Title="Notas fiscais&gt;Previsões" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_FN_DOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ABRANGENCIA = 'O') AND (A.HANDLE IN (SELECT B.DOCUMENTOFINANCEIRO FROM CP_ORDENSCOMPRAENTREGA B, CP_ORDENSCOMPRAITENS C, CP_ORDENSCOMPRA D WHERE B.ORDENSCOMPRAITENS = C.HANDLE AND C.ORDEMCOMPRA = D.HANDLE AND D.HANDLE = @RASTRO(CP_ORDENSCOMPRA)) OR A.HANDLE IN (SELECT D.DOCUMENTOFINANCEIRO FROM CP_ORDENSCOMPRA D WHERE D.HANDLE = @RASTRO(CP_ORDENSCOMPRA)))" FormUrl="~/aga/a/f/aga_t1216_at3491_hs52d523.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_OC__POR_ORIGEM__OC_MANUAL_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3788" Title="Ordem de compra de reposição" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.HANDLE IN (SELECT B.ORDEMCOMPRA FROM CP_ORDENSCOMPRAITENS B WHERE B.HANDLEOCORIGEM = @RASTRO(CP_ORDENSCOMPRA)))" FormUrl="~/aga/a/f/aga_t1529_at3788_hs1ce525d9.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_OC__POR_ORIGEM__OC_MANUAL_FORM" Level="20" Order="40"  />
        </div>
    
      </asp:Content>
    