<%@ Page Title="Equipamentos" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Equipamentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_MA_RECURSOS.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="MANUTENCAO_INDUSTRIAL__EQUIPAMENTO_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4249" Title="Anexos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MA_RECURSOANEXOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.RECURSO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2341_at4249_hsb7aab07d.aspx" UserDefinedDisableRowSelection="False" PageId="MANUTENCAO_INDUSTRIAL__EQUIPAMENTO_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4285" Title="Componentes do equipamento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MI_ESTRUTURAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PRODUTO IS NOT NULL) AND (A.CONJUNTO IS NULL) AND (A.EQUIPAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2683_at4285_hs7e319919.aspx" UserDefinedDisableRowSelection="False" PageId="MANUTENCAO_INDUSTRIAL__EQUIPAMENTO_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4315" Title="Conjuntos do equipamento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MI_ESTRUTURAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PRODUTO IS NULL) AND (A.EQUIPAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2683_at4315_hs17e1fe97.aspx" UserDefinedDisableRowSelection="False" PageId="MANUTENCAO_INDUSTRIAL__EQUIPAMENTO_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4508" Title="Frequência de manutenções" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MI_FREQUENCIA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.EQUIPAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2769_at4508_hsed07c971.aspx" UserDefinedDisableRowSelection="False" PageId="MANUTENCAO_INDUSTRIAL__EQUIPAMENTO_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4223" Title="Horas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MI_RECURSODESGASTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.VEICULO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2670_at4223_hs9632b20c.aspx" UserDefinedDisableRowSelection="False" PageId="MANUTENCAO_INDUSTRIAL__EQUIPAMENTO_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1264_4381" Title="Inspeções&gt;Cadastradas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MI_INSPECAO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(STATUS = 1) AND (A.EQUIPAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2732_at4381_hs9023e48f.aspx" UserDefinedDisableRowSelection="False" PageId="MANUTENCAO_INDUSTRIAL__EQUIPAMENTO_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1264_4382" Title="Inspeções&gt;Confirmadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MI_INSPECAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(STATUS=2) AND (A.EQUIPAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2732_at4382_hs286f0875.aspx" UserDefinedDisableRowSelection="False" PageId="MANUTENCAO_INDUSTRIAL__EQUIPAMENTO_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4225" Title="Item do ativo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_AT_ITENS.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE = (SELECT B.IMOBILIZADO FROM MA_RECURSOS B WHERE B.HANDLE = @RASTRO(MA_RECURSOS))" FormUrl="~/aga/a/f/aga_t1255_at4225_hs9658b202.aspx" UserDefinedDisableRowSelection="False" PageId="MANUTENCAO_INDUSTRIAL__EQUIPAMENTO_FORM" Level="20" Order="45"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4339" Title="Ordens" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MI_ORDEMSERVICOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.VEICULO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2685_at4339_hsaa517ffc.aspx" UserDefinedDisableRowSelection="False" PageId="MANUTENCAO_INDUSTRIAL__EQUIPAMENTO_FORM" Level="20" Order="50"  />
        </div>
    
      </asp:Content>
    