<%@ Page Title="Monitor - Em execução" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Monitor - Em execução" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_Z_WFMODELOINSTANCIAS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="WF_INSTANCIAS__WF_MONITOREMEXECUCAO_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4623" Title="Atividades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_Z_WFMODELOINSTANCIAATIVIDADES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.MODELOINSTANCIA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2843_at4623_hsa056b092.aspx" UserDefinedDisableRowSelection="False" PageId="WF_INSTANCIAS__WF_MONITOREMEXECUCAO_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4768" Title="Lembretes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_Z_WFLEMBRETES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.TAREFA IS NULL AND (A.MODELOINSTANCIA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2838_at4768_hs98a97b6f.aspx" UserDefinedDisableRowSelection="False" PageId="WF_INSTANCIAS__WF_MONITOREMEXECUCAO_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4624" Title="Linhas de execução" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_Z_WFMODELOINSTANCIAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.SUPERIOR = @RASTRO(Z_WFMODELOINSTANCIAS) AND (A.SUPERIOR = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2827_at4624_hs67e5f6ff.aspx" UserDefinedDisableRowSelection="False" PageId="WF_INSTANCIAS__WF_MONITOREMEXECUCAO_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4767" Title="Mensagens de erro" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_Z_WFMODELOINSTANCIAEXCECOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.MODELOINSTANCIA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2853_at4767_hsdd63ce67.aspx" UserDefinedDisableRowSelection="False" PageId="WF_INSTANCIAS__WF_MONITOREMEXECUCAO_FORM" Level="20" Order="25"  />
        </div>
    
      </asp:Content>
    