<%@ Page Title="REG.M610: DETALHAMENTO DA CONTRIBUIÇÃO" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="REG.M610: DETALHAMENTO DA CONTRIBUIÇÃO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_ED_PCAPURACAODETALHAMENTOCONTR.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="ED_EFDPC_APURACAOCOFINS_M600__ED_EFDPC_APURACAOCOFINS_M610_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6707" Title="REG.M611: SOCIEDADE COOPERATIVAS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PCAPURACAOCOOPERATIVAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DETALHAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4415_at6707_hs1ed8659e.aspx" UserDefinedDisableRowSelection="False" PageId="ED_EFDPC_APURACAOCOFINS_M600__ED_EFDPC_APURACAOCOFINS_M610_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6708" Title="REG.M620: AJUSTES DA CONTRIBUIÇÃO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PCAPURACAOAJUSTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DETALHAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4412_at6708_hs1ed7659b.aspx" UserDefinedDisableRowSelection="False" PageId="ED_EFDPC_APURACAOCOFINS_M600__ED_EFDPC_APURACAOCOFINS_M610_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6709" Title="REG.M630: DIFERIMENTO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PCAPURACAODIFERIMENTO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DETALHAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4417_at6709_hs9caf1846.aspx" UserDefinedDisableRowSelection="False" PageId="ED_EFDPC_APURACAOCOFINS_M600__ED_EFDPC_APURACAOCOFINS_M610_FORM" Level="20" Order="20"  />
        </div>
    
      </asp:Content>
    