<%@ Page Title="ECF - Escrituração Contábil Fiscal" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="ECF - Escrituração Contábil Fiscal" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_EDCF_PERIODOS.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7532" Title="0930 - Identificação do Signatário" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_PERIODOIDSIGNATARIOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5177_at7532_hsc0bdad80.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7886" Title="Consultoria arquivo magnético" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_CONSULTORIASQL.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="REGISTRO IN (
               SELECT HANDLE
                 FROM ED_CONSULTORIAREGISTROS
                WHERE TIPOESCRITURACAO = 9
            ) AND (A.PERIODOEDCF = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4172_at7886_hs807c9d37.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="15"  />
        <wes:AjaxForm runat="server" ID="WIDGET_2254_7531" Title="Dados Cadastrais&gt;0030 - Dados Cadastrais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_PERIODODADOSCADASTRAIS.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" UserDefinedCommandsVisible="True" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7535" Title="Dados Cadastrais&gt;0035 - Identificação da SCP" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_PERIODOIDENTIFICACAOSCP.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(SELECT TIPOESCRITURACAO FROM EDCF_PERIODOS WHERE HANDLE = (@RASTRO(EDCF_PERIODOS))) = 3 AND (A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5175_at7535_hsce53df8f.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="25"  />
        <wes:AjaxForm runat="server" ID="WIDGET_2254_7529" Title="Dados Iniciais&gt;0010 - Parâmetros de Tributação" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_PERIODOTRIBUTACAO.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" UserDefinedCommandsVisible="True" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="30"  />
        <wes:AjaxForm runat="server" ID="WIDGET_2254_7530" Title="Dados Iniciais&gt;0020 - Parâmetros Complementares" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_PERIODOPARAMETROS.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" UserDefinedCommandsVisible="True" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7885" Title="Histórico de geração do arquivo ECF" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LOG.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5353_at7885_hscf4f39de.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7716" Title="IRPJ e CSLL&gt;Arbitrado&gt;T120 - Apuração da Base de Cálculo IRPJ" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LAFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5343_at7716_hs2620655d.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="45"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7717" Title="IRPJ e CSLL&gt;Arbitrado&gt;T150 - Cálculo do IRPJ" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LAFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5343_at7717_hs2621655d.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="50"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7718" Title="IRPJ e CSLL&gt;Arbitrado&gt;T170 - Apuração da Base de Cálculo CSLL" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LAFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5343_at7718_hs2623655d.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="55"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7719" Title="IRPJ e CSLL&gt;Arbitrado&gt;T181 - Cálculo da CSLL" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LAFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5343_at7719_hsc8bdd9f8.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="60"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7740" Title="IRPJ e CSLL&gt;Imune/Isenta&gt;U100 - Balanço Patrimonial" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_ISENTASFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5348_at7740_hs9713d85e.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="65"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7741" Title="IRPJ e CSLL&gt;Imune/Isenta&gt;U150 - Demonstração do Resultado" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_ISENTASFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5348_at7741_hs9713d861.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="70"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7742" Title="IRPJ e CSLL&gt;Imune/Isenta&gt;U180 - Cálculo do IRPJ" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_ISENTASFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5348_at7742_hs9713d866.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="75"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7743" Title="IRPJ e CSLL&gt;Imune/Isenta&gt;U182 - Cálculo da CSLL" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_ISENTASFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5348_at7743_hs9715d866.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="80"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7728" Title="IRPJ e CSLL&gt;Presumido&gt;P100 - Balanço Patrimonial" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LPFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5334_at7728_hs7b3fbd87.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="85"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7729" Title="IRPJ e CSLL&gt;Presumido&gt;P130 - Demonstração Receit. Incentivadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LPFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5334_at7729_hs7b40bd87.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="90"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7730" Title="IRPJ e CSLL&gt;Presumido&gt;P150 - Demonstrativo Resultado Exercício" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LPFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5334_at7730_hs7b3abd87.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="95"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7731" Title="IRPJ e CSLL&gt;Presumido&gt;P200 - Apuração da Base de Cálculo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LPFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5334_at7731_hs7b3fbd88.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="100"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7732" Title="IRPJ e CSLL&gt;Presumido&gt;P230 - Cálculo da Isenção e Redução" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LPFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5334_at7732_hs7b40bd88.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="105"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7733" Title="IRPJ e CSLL&gt;Presumido&gt;P300 - Cálculo do IRPJ" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LPFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5334_at7733_hs7b3fbd89.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="110"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7734" Title="IRPJ e CSLL&gt;Presumido&gt;P400 - Apuração da Base de Cálculo CSLL" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LPFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5334_at7734_hs7b3fbd82.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="115"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_7735" Title="IRPJ e CSLL&gt;Presumido&gt;P500 - Cálculo da CSLL" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LPFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5334_at7735_hs7b3fbd83.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="120"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_7709" Title="IRPJ e CSLL&gt;Real&gt;Cálculo da CSLL&gt;N650 - Base de Cálculo após Compensações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LRFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5323_at7709_hs672b8ddc.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="125"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_7710" Title="IRPJ e CSLL&gt;Real&gt;Cálculo da CSLL&gt;N660 - Cálculo Mensal por Estimativa" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LRFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5323_at7710_hs672b8ddf.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="130"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_7711" Title="IRPJ e CSLL&gt;Real&gt;Cálculo da CSLL&gt;N670 - Cálculo com Base no Lucro Real" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LRFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5323_at7711_hs672b8dde.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="135"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_7703" Title="IRPJ e CSLL&gt;Real&gt;Cálculo do IRPJ&gt;N500 - Base Cálculo Após Prejuízos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LRFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5323_at7703_hs5c5f81c7.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="140"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_7704" Title="IRPJ e CSLL&gt;Real&gt;Cálculo do IRPJ&gt;N600 - Demonstração Lucro da Exploraço" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LRFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5323_at7704_hse7c481c7.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="145"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_7705" Title="IRPJ e CSLL&gt;Real&gt;Cálculo do IRPJ&gt;N610 - Cálculo Isenções Lucro Real" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LRFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5323_at7705_hse7c481c6.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="150"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_7706" Title="IRPJ e CSLL&gt;Real&gt;Cálculo do IRPJ&gt;N615 - Base de Cálculo Incentivos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LRFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5323_at7706_hse7c781c6.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="155"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_7707" Title="IRPJ e CSLL&gt;Real&gt;Cálculo do IRPJ&gt;N620 - Cálculo Mensal por Estimativa" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LRFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5323_at7707_hse7c481c5.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="160"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_7708" Title="IRPJ e CSLL&gt;Real&gt;Cálculo do IRPJ&gt;N630 - Cálculo com Base no Lucro Real" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LRFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5323_at7708_hse7c481c4.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="165"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_7689" Title="IRPJ e CSLL&gt;Real&gt;Demonstrações contábeis&gt;L200 - Método Avaliação Estoque Final" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_RESULTADOFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5316_at7689_hsd2d1ab62.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="170"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_7690" Title="IRPJ e CSLL&gt;Real&gt;Demonstrações contábeis&gt;L210 - Info. da Composição de Custos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_RESULTADOFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5316_at7690_hs476cab62.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="175"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_7662" Title="IRPJ e CSLL&gt;Real&gt;LACS&gt;Parte A - Demonstração Base Cálculo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LEFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5317_at7662_hs68405a02.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="180"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_2310_7660" Title="IRPJ e CSLL&gt;Real&gt;LACS&gt;Parte B - Controle das contas&gt;Demonstrativo de Saldos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LEFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5317_at7660_hscf77e44c.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="185"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_2310_7661" Title="IRPJ e CSLL&gt;Real&gt;LACS&gt;Parte B - Controle das contas&gt;Lançamentos sem reflexo na p" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LEFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5317_at7661_hscf78e44b.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="190"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_2310_7659" Title="IRPJ e CSLL&gt;Real&gt;LACS&gt;Parte B - Controle das contas&gt;REG.M010 - CONTA NA PARTE B" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LECONTAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.TIPOTRIBUTO = 'C' AND (A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5301_at7659_hs77ffba56.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="195"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_7652" Title="IRPJ e CSLL&gt;Real&gt;LALUR&gt;Parte A - Demonstração Base Cálculo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LEFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5317_at7652_hsf9b822d3.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="200"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_2305_7654" Title="IRPJ e CSLL&gt;Real&gt;LALUR&gt;Parte B - Controle das contas&gt;Demonstrativo de Saldos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LEFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5317_at7654_hs1d2be392.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="205"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_2305_7658" Title="IRPJ e CSLL&gt;Real&gt;LALUR&gt;Parte B - Controle das contas&gt;Lançamentos sem reflexo na" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LEFORMASAPURACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5317_at7658_hsbfd2582d.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="210"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2300_2304_2305_7653" Title="IRPJ e CSLL&gt;Real&gt;LALUR&gt;Parte B - Controle das contas&gt;REG.M010 - CONTA NA PARTE B" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LECONTAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.TIPOTRIBUTO = 'I' AND (A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5301_at7653_hs75ecfd89.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="215"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7744" Title="Informações Econômicas&gt;REG.X280 - ATIVIDADES INCENTIVADAS PJ" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_ATIVIDADESINCENTIVADAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5267_at7744_hs79fbf69.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="220"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7745" Title="Informações Econômicas&gt;REG.X291 - OP.EXT. PESSOA VINCULADA" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_OEPESSOAVINCULADA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5269_at7745_hs3ea423b1.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="225"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7746" Title="Informações Econômicas&gt;REG.X292 - OP.EXT. PESSOA NÃO VINCULADA" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_OEPESSOANAOVINCULADA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5270_at7746_hs3bf66659.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="230"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7747" Title="Informações Econômicas&gt;REG.X300 - OP.EXT. EXPORTAÇÕES" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_OEEXPORTACOES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5271_at7747_hs5fcfa6cd.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="235"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7749" Title="Informações Econômicas&gt;REG.X320 - OP.EXT. IMPORTAÇÕES" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_OEIMPORTACOES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5273_at7749_hsc63bb2bf.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="240"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7751" Title="Informações Econômicas&gt;REG.X340 - PARTICIPAÇÃO NO EXTERIOR" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_PEIDENTIFICACAO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5275_at7751_hsfdc227ca.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="245"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7759" Title="Informações Econômicas&gt;REG.X390 - ORIG/APLICAÇÃO-IMUNES/ISENTAS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_RECURSOSISENTOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5283_at7759_hs6d0b5a82.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="250"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7760" Title="Informações Econômicas&gt;REG.X400 - COMÉRCIO ELETRÔNICO E TI" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_CEVENDAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5284_at7760_hse199e69a.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="255"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7761" Title="Informações Econômicas&gt;REG.X410 - COMÉRCIO ELETRÔNICO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_CEVENDAPAISES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5285_at7761_hs4a285b1c.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="260"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7762" Title="Informações Econômicas&gt;REG.X420 - ROYALTIES" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_ROYALTIES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODOS = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5286_at7762_hse4bf6922.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="265"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7763" Title="Informações Econômicas&gt;REG.X430 - RENDIMENTOS SERV, JUR E DIVID" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_RENDIMENTOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5287_at7763_hsec39b6af.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="270"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7764" Title="Informações Econômicas&gt;REG.X450 - PGTOS/REM. SERV, JUR E DIVID" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_PAGAMENTOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODOS = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5288_at7764_hsa90e4213.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="275"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7765" Title="Informações Econômicas&gt;REG.X460 - INOVAÇÃO TECNOLÓGICA" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_INOVACAOTECNOLOGICA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5289_at7765_hs1b456988.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="280"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7766" Title="Informações Econômicas&gt;REG.X470 - CAPACITAÇÃO DE INFORMÁTICA" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_CAPACITACAOINFORMATICA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5290_at7766_hs54b6f90d.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="285"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7767" Title="Informações Econômicas&gt;REG.X480 - REGIMES ESPECIAIS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_BENEFICIOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5291_at7767_hsa490ee2a.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="290"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7768" Title="Informações Econômicas&gt;REG.X490 - PÓLO INDUSTRIAL MANUAS/AMAZ" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_POLOINDUSTRIALMANAUS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5292_at7768_hsc2645f39.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="295"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7769" Title="Informações Econômicas&gt;REG.X500 - PROCESSAMENTO DE EXPORTAÇÃO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_PROCESSAMENTOEXPORTACAO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5293_at7769_hs157aedd6.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="300"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7770" Title="Informações Econômicas&gt;REG.X510 - ÁREAS DE LIVRA COMÉRCIO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_AREASLIVRECOMERCIO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5294_at7770_hsf4090c25.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="305"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7771" Title="Informações Gerais&gt;REG.Y520 - PGTO/RECEBIMENTOS DO EXTERIOR" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGMOVIMENTACOESEXTERIOR.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5266_at7771_hsdec68215.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="310"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7772" Title="Informações Gerais&gt;REG.Y540 - DISCRIMINAÇÃO DE VENDAS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGDISCRIMINACAOVENDAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5265_at7772_hs483c0a29.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="315"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7773" Title="Informações Gerais&gt;REG.Y550 - VENDAS A COML EXPORTADORA" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGVENDASEXPORTACAO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5264_at7773_hs76f9bf70.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="320"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7774" Title="Informações Gerais&gt;REG.Y560 - DETALHAMENTO DA COML EXPORT" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGDETALHAMENTOEXPORTACAO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5263_at7774_hs645ad34d.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="325"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7775" Title="Informações Gerais&gt;REG.Y570 - DEMONST. IR E CSLL RETIDOS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGDEMONSTRATIVOIMPOSTOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5262_at7775_hsa4698989.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="330"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7776" Title="Informações Gerais&gt;REG.Y580 - DOAÇÕES ELEITORAIS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGDOACOESELEITORAIS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5261_at7776_hs4c8170b9.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="335"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7777" Title="Informações Gerais&gt;REG.Y590 - ATIVOS NO EXTERIOR" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGATIVOSEXTERIOR.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5259_at7777_hs3ce07c4c.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="340"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7778" Title="Informações Gerais&gt;REG.Y600 - IDENTIFICAÇÃO DE SÓCIOS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGIDENTIFICACAOSOCIOES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5258_at7778_hs51880ed9.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="345"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7779" Title="Informações Gerais&gt;REG.Y611 - RENDIMENTOS DOS SÓCIOS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGRENDSOCIOTITULAR.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5257_at7779_hsfe8cc27.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="350"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7780" Title="Informações Gerais&gt;REG.Y612 - RENDIMENTOS DIRIG-IMUN/ISENT" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGRENDISENTOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5256_at7780_hs5510c003.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="355"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7781" Title="Informações Gerais&gt;REG.Y620 - PARTIC EM COLIGADA\CONTROLADA" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGPARTICIPACAOPATRIMONIAL.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5255_at7781_hsa6611d34.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="360"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7782" Title="Informações Gerais&gt;REG.Y630 - FUNDOS/CLUBES DE INVESTIMENTO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGFUNDOSINVESTIMENTO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5240_at7782_hs95aac86a.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="365"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7783" Title="Informações Gerais&gt;REG.Y640 - PARTICIPAÇÕES EM CONSÓRCIOS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGPARTICIPACOESCONSORCIOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5254_at7783_hse07f7dd8.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="370"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7785" Title="Informações Gerais&gt;REG.Y660 - DADOS DE SUCESSORAS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGSUCESSORAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5242_at7785_hs3612d546.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="375"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7786" Title="Informações Gerais&gt;REG.Y665 - DEMONSTRATIVO DAS DIFERENÇAS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGDEMONSTDIFERENCAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5243_at7786_hsad28f9e3.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="380"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7787" Title="Informações Gerais&gt;REG.Y671 - OUTRAS INFORMAÇÕES" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGOUTRASINFORMACOES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5248_at7787_hs9264b45f.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="385"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7788" Title="Informações Gerais&gt;REG.Y672 - OUTRAS INFORMALÕES (LP / LA)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGOUTRASINFORMACOESLUCRO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5249_at7788_hs7e87fbed.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="390"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7789" Title="Informações Gerais&gt;REG.Y680 - REFIS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGREFIS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5250_at7789_hs8ca6d893.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="395"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7791" Title="Informações Gerais&gt;REG.Y682 - REFIS (IMUNES OU ISENTAS)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGREFISIMUNE.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5251_at7791_hsd5479e4c.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="400"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7792" Title="Informações Gerais&gt;REG.Y690 - INFORMAÇÕES OPTANTES (PAES)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGPAES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5252_at7792_hs509d0ceb.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="405"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_8151" Title="Informações Gerais&gt;REG.Y720 - INFORMAÇÕES PER. ANTERIORES" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGPERIODOSANTERIORES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5647_at8151_hs50f99650.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="410"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7793" Title="Informações Gerais&gt;REG.Y800 - OUTRAS INFORMAÇÕES" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_IGANEXOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5253_at7793_hs718a3205.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="415"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_8119" Title="Livro Caixa&gt;Q100 - Demonstrativo do Livro Caixa" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_LIVROCAIXA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5637_at8119_hse886286.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="420"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2289_7582" Title="Mapeamento Contábil/Referencial&gt;Plano de contas&gt;J050 - Plano de Contas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_CONTAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT CONTA.HANDLE
               FROM EDCF_PERIODOS PERIODO
               JOIN ED_PARAMETROS PARAMETROECD ON PARAMETROECD.EMPRESA = PERIODO.EMPRESA
               JOIN CT_CONTASGERENCIAIS CONTAGERENCIAL ON CONTAGERENCIAL.PLANO = PARAMETROECD.PLANOCONTAS
               JOIN ED_CONTAS CONTA ON CONTA.ORIGEMCONTAGERENCIAL = CONTAGERENCIAL.HANDLE
              WHERE PERIODO.HANDLE = @RASTRO(EDCF_PERIODOS)
                         AND
                         (
                             (
                                 CONTA.HANDLE =
                                 (
                                     SELECT MAX(MAXCONTA.HANDLE)
                                            FROM ED_CONTAS MAXCONTA
                                           WHERE MAXCONTA.ORIGEMCONTAGERENCIAL = CONTA.ORIGEMCONTAGERENCIAL
                                                 AND MAXCONTA.VERSAO = CONTA.VERSAO
                                                 AND MAXCONTA.EMPRESA = CONTA.EMPRESA
                                                 AND MAXCONTA.DATAINCLUSAO BETWEEN PERIODO.DATAINICIAL AND PERIODO.DATAFINAL
                                                 AND MAXCONTA.DATAINCLUSAO =
                                                 (
                                                     SELECT MAX(MAXDATA.DATAINCLUSAO)
                                                            FROM ED_CONTAS MAXDATA
                                                           WHERE MAXDATA.ORIGEMCONTAGERENCIAL = MAXCONTA.ORIGEMCONTAGERENCIAL
                                                                 AND MAXDATA.VERSAO = MAXCONTA.VERSAO
                                                                 AND MAXDATA.EMPRESA = MAXCONTA.EMPRESA
                                                                 AND MAXDATA.DATAINCLUSAO BETWEEN PERIODO.DATAINICIAL AND PERIODO.DATAFINAL
                                                         )
                                                     )
                                         )
                                         OR
                                         (
                                             CONTA.HANDLE =
                                             (
                                                 SELECT MAX(MAXCONTA.HANDLE)
                                                        FROM ED_CONTAS MAXCONTA
                                                       WHERE MAXCONTA.ORIGEMCONTAGERENCIAL = CONTA.ORIGEMCONTAGERENCIAL
                                                             AND MAXCONTA.VERSAO = CONTA.VERSAO
                                                             AND MAXCONTA.EMPRESA = CONTA.EMPRESA
                                                             AND MAXCONTA.DATAINCLUSAO &lt; PERIODO.DATAINICIAL
                                                             AND MAXCONTA.DATAINCLUSAO =
                                                             (
                                                                 SELECT MAX(MAXDATA.DATAINCLUSAO)
                                                                        FROM ED_CONTAS MAXDATA
                                                                       WHERE MAXDATA.ORIGEMCONTAGERENCIAL = MAXCONTA.ORIGEMCONTAGERENCIAL
                                                                             AND MAXDATA.VERSAO = MAXCONTA.VERSAO
                                                                             AND MAXDATA.EMPRESA = MAXCONTA.EMPRESA
                                                                             AND MAXDATA.DATAINCLUSAO &lt; PERIODO.DATAINICIAL
                                                             )
                                             )
                                         )
                                 )
                             ) 

OR A.HANDLE IN (

                    SELECT CONTA.HANDLE
                      FROM EDCF_PERIODOS PERIODO
                           JOIN ED_PARAMETROS PARAMETROECD ON PARAMETROECD.EMPRESA = PERIODO.EMPRESA
                           JOIN ED_CONTAS CONTA ON CONTA.VERSAO = PARAMETROECD.PLANOATIVO
                           JOIN CT_CONTAS ORIGEM ON ORIGEM.HANDLE = CONTA.ORIGEMCONTA
                     WHERE PERIODO.HANDLE = @RASTRO(EDCF_PERIODOS)
                           AND
                           (
                               (
                                   CONTA.HANDLE =
                                   (
                                       SELECT MAX(MAXCONTA.HANDLE)
                                              FROM ED_CONTAS MAXCONTA
                                             WHERE MAXCONTA.ORIGEMCONTA = CONTA.ORIGEMCONTA
                                                   AND MAXCONTA.VERSAO = CONTA.VERSAO
                                                   AND MAXCONTA.EMPRESA = CONTA.EMPRESA
                                                   AND MAXCONTA.DATAINCLUSAO BETWEEN PERIODO.DATAINICIAL AND PERIODO.DATAFINAL
                                                   AND MAXCONTA.DATAINCLUSAO =
                                                   (
                                                       SELECT MAX(MAXDATA.DATAINCLUSAO)
                                                              FROM ED_CONTAS MAXDATA
                                                             WHERE MAXDATA.ORIGEMCONTA = MAXCONTA.ORIGEMCONTA
                                                                   AND MAXDATA.VERSAO = MAXCONTA.VERSAO
                                                                   AND MAXDATA.EMPRESA = MAXCONTA.EMPRESA
                                                                   AND MAXDATA.DATAINCLUSAO BETWEEN PERIODO.DATAINICIAL AND PERIODO.DATAFINAL
                                                           )
                                                       )
                                           )
                                           OR
                                           (
                                               CONTA.HANDLE =
                                               (
                                                        SELECT MAX(MAXCONTA.HANDLE)
                                                          FROM ED_CONTAS MAXCONTA
                                                         WHERE MAXCONTA.ORIGEMCONTA = CONTA.ORIGEMCONTA
                                                               AND MAXCONTA.VERSAO = CONTA.VERSAO
                                                               AND MAXCONTA.EMPRESA = CONTA.EMPRESA
                                                               AND MAXCONTA.DATAINCLUSAO &lt; PERIODO.DATAINICIAL
                                                               AND MAXCONTA.DATAINCLUSAO =
                                                               (
                                                                   SELECT MAX(MAXDATA.DATAINCLUSAO)
                                                                          FROM ED_CONTAS MAXDATA
                                                                         WHERE MAXDATA.ORIGEMCONTA = MAXCONTA.ORIGEMCONTA
                                                                               AND MAXDATA.VERSAO = MAXCONTA.VERSAO
                                                                               AND MAXDATA.EMPRESA = MAXCONTA.EMPRESA
                                                                               AND MAXDATA.DATAINCLUSAO &lt; PERIODO.DATAINICIAL
                                                                       )
                                                                   )
                                                       )
                                                   )

)" FormUrl="~/aga/a/f/aga_t3229_at7582_hse6c0800d.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="425"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_2289_7583" Title="Mapeamento Contábil/Referencial&gt;Plano de contas&gt;J100 - Centro de Custo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_CENTROSCUSTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT CENTROCUSTO.HANDLE
               FROM ED_CENTROSCUSTOS CENTROCUSTO
              WHERE CENTROCUSTO.EMPRESA = (SELECT EMPRESA
                                             FROM EDCF_PERIODOS
                                            WHERE HANDLE = @RASTRO(EDCF_PERIODOS))
                AND CENTROCUSTO.HANDLE IN (SELECT MAX(HANDLE)
                                             FROM ED_CENTROSCUSTOS
                                            WHERE EMPRESA = CENTROCUSTO.EMPRESA
                                              AND CODIGO = CENTROCUSTO.CODIGO
                                              AND DATAINCLUSAO = (SELECT MAX(DATAINCLUSAO)
                                                                    FROM ED_CENTROSCUSTOS
                                                                   WHERE DATAINCLUSAO &lt;= (SELECT DATAFINAL
                                                                                            FROM EDCF_PERIODOS
                                                                                           WHERE HANDLE = @RASTRO(EDCF_PERIODOS))
                                                                     AND EMPRESA = CENTROCUSTO.EMPRESA
                                                                     AND CODIGO = CENTROCUSTO.CODIGO)))" FormUrl="~/aga/a/f/aga_t3233_at7583_hs50128445.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="430"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2254_7687" Title="Mapeamento Contábil/Referencial&gt;Saldos contábeis" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_EDCF_SALDOCONTAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PERIODO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5318_at7687_hs7621a198.aspx" UserDefinedDisableRowSelection="False" PageId="SPED_COMPETENCIAS__ECF_ESCRITURACAO_CONTABIL_FISCAL_FORM" Level="20" Order="435"  />
        </div>
    
      </asp:Content>
    