<%@ Page Title="Carga média por CNAE - MT" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:HtmlPanel runat="server" ID="ATENO" Title="Atenção" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" HtmlBase64="PGRpdiBpZD0ibmF2ZWdhZG9yTmFvU3Vwb3J0YWRvIiBjbGFzcz0ibm90ZSBub3RlLWluZm8gbm90ZS1ib3JkZXJlZCI+CjxwPkVzc2UgY2FkYXN0cm8gZGV2ZSBzZXIgdXRpbGl6YWRvIHBhcmEgY2FkYXN0cmFyIG9zIHBlcmNlbnR1YWlzIHBvciBDTkFFIHByZXZpc3RvcyBubyBSSUNNUyAKZG8gTWF0byBHcm9zc28gbm8gcmVnaW1lIGRlIGVzdGltYXRpdmEgc2ltcGxpZmljYWRvLCBvIHF1YWwgc2Vyw6EgdXRpbGl6YWRvIG5vIGPDoWxjdWxvIGRhIApTdWJzdGl0dWnDp8OjbyBUcmlidXTDoXJpYSBuYXMgc2HDrWRhcyAobcOzZHVsbyBDb21lcmNpYWwgPiBGYXR1cmFtZW50bykgcGFyYSBvIE1hdG8gR3Jvc3NvLgpBcyBDTkFFcyBuw6NvIHN1Ym1ldGlkYXMgYW8gcmVnaW1lLCBwcmV2aXN0YXMgbmEgUG9ydGFyaWEgMjIwLzE0LCB0YW1iw6ltIGRldmVtIHNlciBpbnNlcmlkYXMgCm5lc3NhIGNhcmdhIGNvbSBhIHJlc3BlY3RpdmEgbWFyY2HDp8OjbyBxdWUgbsOjbyBlc3TDoSBzdWJtZXRpZGEuCjwvcD4KPGJyIC8+CjxwPk8gYm90w6NvIENhcnJlZ2FyIENOQUUgaW5zZXJlIGF1dG9tYXRpY2FtZW50ZSBvcyBDTkFFcyBjYWRhc3RyYWRvcyBuYSBCYXNlIGRlIGRhZG9zLCAKZGUgYWNvcmRvIGNvbSB1bWEgbGlzdGEgaW50ZXJuYSBkbyBFUlAuIE8gdXNvIGRlc3NhIG9ww6fDo28gbsOjbyBkaXNwZW5zYSBhIGNvbmZlcsOqbmNpYSAKc2Ugb3MgcGVyY2VudHVhaXMgZXN0w6NvIGRlIGFjb3JkbyBjb20gYSBsZWdpc2xhw6fDo28gdmlnZW50ZSwgdW1hIHZleiBxdWUgYSBtYW51dGVuw6fDo28gCmRlc3NlIGNhZGFzdHJvIMOpIGRlIHJlc3BvbnNhYmlsaWRhZGUgZGUgY2FkYSBlbXByZXNhPC9wPgo8L2Rpdj4K" PageId="CARGA_DE_IMPOSTOS__CARGA_MEDIA_MT_FORM" Level="20" Order="0"  />
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Carga média por CNAE" Subtitle="Mato Grosso" PortletCssClass="" PortletLayout="Default" BootstrapCols="4" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_TR_IMPOSTOCNAEMTVIGENCIA.FORM" FormMode="View" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="CARGA_DE_IMPOSTOS__CARGA_MEDIA_MT_FORM" Level="20" Order="1"  />
        <wes:EditableGrid runat="server" ID="CLASSIFICAONACIONALDEATIVIDADESECONMICAS" Title="Classificação Nacional de Atividades Econômicas" Subtitle="CNAE" PortletCssClass="" PortletLayout="Default" BootstrapCols="8" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="AGA_TR_IMPOSTOCNAEMT.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.CNAEVIGENCIA = @CAMPO(HANDLE))" PageId="CARGA_DE_IMPOSTOS__CARGA_MEDIA_MT_FORM" Level="20" Order="11"  />
        </div>
    
      </asp:Content>
    