<%@ Page Title="Aquisições - Confirmar" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Aquisições - Confirmar" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICOES.FORM" CanDelete="False" CanUpdate="True" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8302" Title="Alterar responsável pela aquisição" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOHISTRESPONSAVEIS.GRID" CanDelete="False" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5763_at8302_hs36dd9860.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2603" Title="Anexos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOANEXOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.RECURSO IS NULL) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1964_at2603_hsd6c3d1a3.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4453" Title="Cláusulas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CN_CONTRATOCLAUSULAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="CLAUSULA IS NULL AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2111_at4453_hs73966300.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2602" Title="Critérios para técnica" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOCRITERIOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1916_at2602_hs348adce4.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2597" Title="Documentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAODOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ITEM IS NULL) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1799_at2597_hs384f8298.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3614" Title="Documentos emitidos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_MODELODOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="((A.INATIVO = 'N') OR (A.INATIVO IS NULL)) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2468_at3614_hs48d4abf9.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8307" Title="Integrantes da comissão" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_COMISSAOINTEGRANTES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1950_at8307_hs60f79c81.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_3653" Title="Itens Aquisição&gt;Cancelados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS IN (2,8) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1801_at3653_hs48e0e903.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="45"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_3657" Title="Itens Aquisição&gt;Comprados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="( A.AQUISICAO IN (SELECT AQUISICAO FROM CP_ORDENSCOMPRA 
                   WHERE HANDLE IN (SELECT ORDEMCOMPRA FROM CP_ORDENSCOMPRAITENS 
                                     WHERE PRODUTO IN (SELECT PRODUTO FROM LC_AQUISICAOITENS 
                                                        WHERE HANDLE = A.HANDLE)))
)OR
( A.STATUS = 7 ) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1801_at3657_hs819b3cf8.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="50"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_3651" Title="Itens Aquisição&gt;Desertos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS=4 AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1801_at3651_hsdb821998.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="55"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_3652" Title="Itens Aquisição&gt;Fracassados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS=5 AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1801_at3652_hs31dc70bb.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="60"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_8145" Title="Itens Aquisição&gt;Não encerrados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 1 AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1801_at8145_hs5e90da43.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="65"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_3650" Title="Itens Aquisição&gt;Todos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOITENS.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1801_at3650_hsfa7262c6.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="70"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_712_1097_3620" Title="Julgamento&gt;Comercial&gt;Classificados&gt;Fornecedores" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOPARTICIPANTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.DESCLASSIFICADO &lt;&gt; 'S' 
AND A.DESCLASSIFICADODOCUMENTOS &lt;&gt; 'S' 
AND A.HANDLE IN (SELECT PARTICIPANTE FROM  LC_AQUISICAOCOTACOESITEM WHERE STATUS &lt;&gt; 2 AND AQUISICAO = A.AQUISICAO) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1803_at3620_hsd2c5136.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="75"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_712_1097_3621" Title="Julgamento&gt;Comercial&gt;Desclassificados&gt;Fornecedores" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOPARTICIPANTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DESCLASSIFICADO = 'S' OR DESCLASSIFICADODOCUMENTOS = 'S')
OR A.HANDLE IN (SELECT PARTICIPANTE FROM  LC_AQUISICAOCOTACOESITEM
                 WHERE SELECIONADO &lt;&gt; 'S' 
                   AND A.DESCLASSIFICADO &lt;&gt; 'S' 
                   AND STATUS = 2 
                   AND AQUISICAO = A.AQUISICAO
                   AND AQUISICAOITEM NOT IN (SELECT AQUISICAOITEM FROM LC_AQUISICAOCOTACOESITEM 
                                              WHERE SELECIONADO = 'S'
                                                AND PARTICIPANTE = A.HANDLE ) ) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1803_at3621_hs7543e8db.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="80"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_712_2211" Title="Julgamento&gt;Habilitação&gt;Habilitados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOPARTICIPANTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ARVOREHABILITACAO='S' AND A.JULGADOHABILITACAO='S' AND HABILITADO='S') AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1803_at2211_hscc9539ae.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="85"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_712_2212" Title="Julgamento&gt;Habilitação&gt;Inabilitados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOPARTICIPANTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="((A.ARVOREHABILITACAO='S' AND A.HABILITADO='N' AND JULGADOHABILITACAO='S')
OR (INABILITADOPORINVERSAO='S')) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1803_at2212_hs13c4cb2a.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="90"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_712_2213" Title="Julgamento&gt;Técnica&gt;Classificados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOPARTICIPANTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ARVORETECNICA='S' AND A.CLASSIFICADOTECNICA='S' AND JULGADOTECNICA='S') AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1803_at2213_hs659bbee9.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="95"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_712_2214" Title="Julgamento&gt;Técnica&gt;Desclassificados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOPARTICIPANTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ARVORETECNICA='S' AND A.CLASSIFICADOTECNICA='N' AND JULGADOTECNICA='S') AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1803_at2214_hs37ca4ff3.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="100"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_3628" Title="Julgamento&gt;Vencedores" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOPARTICIPANTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.PARTICIPANTE IN (SELECT HANDLE FROM GN_PESSOAS WHERE
EHFORNECEDOR = 'S' AND HANDLE IN (SELECT FORNECEDOR FROM CP_ORDENSCOMPRA WHERE 

AQUISICAO=@RASTRO(LC_AQUISICOES) AND FORNECEDOR IN (SELECT PARTICIPANTE FROM LC_AQUISICAOPARTICIPANTES 

WHERE AQUISICAO=@RASTRO(LC_AQUISICOES))))
OR 
A.PARTICIPANTE IN (SELECT HANDLE FROM GN_PESSOAS WHERE
EHFORNECEDOR = 'S' AND HANDLE IN (SELECT PARTICIPANTE FROM LC_AQUISICAOPARTICIPANTES WHERE 

AQUISICAO=@RASTRO(LC_AQUISICOES) AND HANDLE IN (SELECT PARTICIPANTE FROM LC_AQUISICAOCOTACOESITEM WHERE 

AQUISICAO=@RASTRO(LC_AQUISICOES) AND SELECIONADO='S'))) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1803_at3628_hs60033741.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="105"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6095" Title="Log e-mail" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_LOGEMAIL.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.TABELAORIGEM = (SELECT HANDLE FROM Z_TABELAS WHERE NOME = 'LC_AQUISICOES') AND (A.HANDLEORIGEM = @RASTRO(LC_AQUISICOES))" FormUrl="~/aga/a/f/aga_t3904_at6095_hsf619439a.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="110"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3668" Title="Lotes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOLOTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2494_at3668_hs706bd00a.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="115"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3809" Title="Parecer" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_PARECER.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2583_at3809_hs1cf96e1c.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="120"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2599" Title="Participantes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOPARTICIPANTES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1803_at2599_hs5eb20719.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="125"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3764" Title="Participantes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOPARTICIPANTES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1803_at3764_hsdf65e650.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="130"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2598" Title="Publicações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOPUBLICACOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1802_at2598_hs54f3fc0.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="135"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_6107" Title="Recursos/Impugnação&gt;Aprovadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAORECURSOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 3 AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1804_at6107_hs2f823a06.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="140"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_6106" Title="Recursos/Impugnação&gt;Aprovar" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAORECURSOS.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 2 
AND ((A.GRUPOASSINATURAS IN(SELECT C.HANDLE FROM CP_GRUPOALCADASINTEGRANTES B, CP_GRUPOALCADAS C
                                 WHERE B.GRUPO = C.HANDLE AND ((C.EHHIERARQUIA = 'S' AND B.SEQUENCIA &gt;= A.SEQUENCIAALCADA) OR
                                                                                             (C.EHHIERARQUIA &lt;&gt; 'S' AND B.SEQUENCIA = A.SEQUENCIAALCADA)) 
                                 AND B.USUARIO = @USUARIO AND B.ATIVO = 'S')) OR
         (A.GRUPOASSINATURAS IN (SELECT D.GRUPO FROM CP_GRUPOALCADASUSUARIOS D, CP_GRUPOALCADASINTEGRANTES I, CP_GRUPOALCADAS G
                                  WHERE D.GRUPO = G.HANDLE AND I.GRUPO = G.HANDLE AND I.HANDLE = D.INTEGRANTE
                                  AND ((G.EHHIERARQUIA = 'S' AND I.SEQUENCIA &gt;= A.SEQUENCIAALCADA) OR (G.EHHIERARQUIA = 'N' AND I.SEQUENCIA = A.SEQUENCIAALCADA))
                                  AND D.USUARIOAUTORIZADO = @USUARIO AND I.USUARIO = D.USUARIO AND D.ATIVO = 'S' AND I.ATIVO = 'S' AND I.AUSENTE = 'S'))
        ) AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1804_at6106_hs2820dbf8.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="145"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_6103" Title="Recursos/Impugnação&gt;Cadastradas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAORECURSOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 1 AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1804_at6103_hs8f423d07.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="150"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_6108" Title="Recursos/Impugnação&gt;Canceladas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAORECURSOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 4 AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1804_at6108_hs6d959bb4.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="155"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_6105" Title="Recursos/Impugnação&gt;Em aprovação" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAORECURSOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 2 AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1804_at6105_hs8aabf03.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="160"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_6109" Title="Recursos/Impugnação&gt;Rejeitadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAORECURSOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.STATUS = 5 AND (A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1804_at6109_hs8025184f.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="165"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_824_6104" Title="Recursos/Impugnação&gt;Todas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAORECURSOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1804_at6104_hs97b3a4d5.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="170"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2601" Title="Requisições" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="(A.AQUISICAOGERADA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1792_at2601_hs46053819.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="175"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8220" Title="Responsáveis" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CN_CONTRATOCOORDENADORES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2051_at8220_hse80ae49f.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="180"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3619" Title="Retificações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAORETIFICACOES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2490_at3619_hs92333067.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="185"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3740" Title="Roteiros" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_AQUISICAOROTEIROS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.AQUISICAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2535_at3740_hs14eef60c.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="190"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8355" Title="Termo de referência" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_TR.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.HANDLE IN (SELECT REQUISICAO.TERMOREFERENCIA  
                FROM LC_REQUISICOES REQUISICAO
               WHERE REQUISICAO.AQUISICAOGERADA = @RASTRO(LC_AQUISICOES)))" FormUrl="~/aga/a/f/aga_t5780_at8355_hs2481fa8d.aspx" UserDefinedDisableRowSelection="False" PageId="LC_PASTA_DE_AQUISICOES__CONFIRMAR_FORM" Level="20" Order="195"  />
        </div>
    
      </asp:Content>
    