<%@ Page Title="Industrializados" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Industrializados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_PR_ORDEMINDUSTRIALIZADOS.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="CARGA_DE_ITENS_OP__INDUSTRIALIZADOS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4798" Title="Itens" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PR_ORDEMINDUSTRIALIZADOITENS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.ORDEMINDUSTRIALIZADO = (SELECT HANDLE FROM PR_ORDEMINDUSTRIALIZADOS WHERE HANDLE = @RASTRO(PR_ORDEMINDUSTRIALIZADOS)) AND (A.ORDEMINDUSTRIALIZADO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2870_at4798_hsbd4cb7.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_ITENS_OP__INDUSTRIALIZADOS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4796" Title="Ordens de compra" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT ORDEMCOMPRA FROM PR_ORDEMINDUSTRIALIZADOS WHERE HANDLE =  @RASTRO(PR_ORDEMINDUSTRIALIZADOS))" FormUrl="~/aga/a/f/aga_t1529_at4796_hsda9c06cb.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_ITENS_OP__INDUSTRIALIZADOS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4797" Title="Requisições de compra" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOESPAI.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT REQUISICAOCOMPRA FROM PR_ORDEMINDUSTRIALIZADOS WHERE HANDLE =  @RASTRO(PR_ORDEMINDUSTRIALIZADOS))" FormUrl="~/aga/a/f/aga_t2311_at4797_hs311f7b50.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_ITENS_OP__INDUSTRIALIZADOS_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5237" Title="Simples remessas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_FN_DOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT B.DOCUMENTO FROM PR_INSUMOSENVIADOS A, CM_ITENS B, PR_ORDEMINDUSTRIALIZADOITENS C WHERE A.ITEMNF = B.HANDLE AND A.ORDEMINDUSTRIALIZADOITEM = C.HANDLE AND C.ORDEMINDUSTRIALIZADO = @RASTRO(PR_ORDEMINDUSTRIALIZADOS))" FormUrl="~/aga/a/f/aga_t1216_at5237_hsb3520544.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_ITENS_OP__INDUSTRIALIZADOS_FORM" Level="20" Order="25"  />
        </div>
    
      </asp:Content>
    