<%@ Page Title="Produtos - Almoxarifados" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Produtos - Almoxarifados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_PD_ALMOXARIFADOS.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="IE_PRODUTOS__ALMOXARIFADOS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5394" Title="Estoque terceiros" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_MOVIMENTACAOTERCEIROTOTAIS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ALMOXARIFADO = @RASTRO(PD_ALMOXARIFADOS) AND A.TIPO = 'R') AND (A.ALMOXARIFADO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3307_at5394_hs17469ac0.aspx" UserDefinedDisableRowSelection="False" PageId="IE_PRODUTOS__ALMOXARIFADOS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3284" Title="Histórico de controle de reposição" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_STATUS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.HANDLETABELAORIGEM IN (SELECT B.HANDLE FROM Z_TABELAS B WHERE B.NOME = 'PD_ALMOXARIFADOS') AND A.HANDLEREGISTROORIGEM = @RASTRO(PD_ALMOXARIFADOS))" FormUrl="~/aga/a/f/aga_t1951_at3284_hs9972f88d.aspx" UserDefinedDisableRowSelection="False" PageId="IE_PRODUTOS__ALMOXARIFADOS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1343" Title="Itens" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_ALMOXARIFADOPRODUTOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ALMOXARIFADO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1527_at1343_hsbe27b9b8.aspx" UserDefinedDisableRowSelection="False" PageId="IE_PRODUTOS__ALMOXARIFADOS_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1314" Title="Localizações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_ALMOXARIFADOLOCALIZACOES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ALMOXARIFADO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1495_at1314_hsd3490529.aspx" UserDefinedDisableRowSelection="False" PageId="IE_PRODUTOS__ALMOXARIFADOS_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_264_1723" Title="Ordens de contagem&gt;Cadastrada" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_ORDENSCONTAGEM.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="STATUS = 1 AND (A.ALMOXARIFADO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1626_at1723_hsd2640fc1.aspx" UserDefinedDisableRowSelection="False" PageId="IE_PRODUTOS__ALMOXARIFADOS_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_264_1725" Title="Ordens de contagem&gt;Canceladas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_ORDENSCONTAGEM.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="STATUS = 3 AND (A.ALMOXARIFADO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1626_at1725_hs47818364.aspx" UserDefinedDisableRowSelection="False" PageId="IE_PRODUTOS__ALMOXARIFADOS_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_264_1724" Title="Ordens de contagem&gt;Confirmada" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_ORDENSCONTAGEM.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="STATUS = 2 AND (A.ALMOXARIFADO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1626_at1724_hs17aaa372.aspx" UserDefinedDisableRowSelection="False" PageId="IE_PRODUTOS__ALMOXARIFADOS_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_264_1726" Title="Ordens de contagem&gt;Encerradas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_ORDENSCONTAGEM.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="STATUS = 4 AND (A.ALMOXARIFADO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1626_at1726_hsb1a1ca9d.aspx" UserDefinedDisableRowSelection="False" PageId="IE_PRODUTOS__ALMOXARIFADOS_FORM" Level="20" Order="45"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_264_1468" Title="Requisições do almoxarifado&gt;Atendidos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(STATUS IN (4,8) AND QUANTIDADE &lt;= QUANTIDADEATENDIDA AND (TIPO = 'O' OR TIPO='T') AND ALMOXARIFADO = @RASTRO(PD_ALMOXARIFADOS) AND ( @USUARIO IN (SELECT RESPONSAVEL FROM PD_ALMOXARIFADOS WHERE HANDLE = @RASTRO(PD_ALMOXARIFADOS) ) OR @USUARIO IN (SELECT ALMOXARIFE FROM PD_ALMOXARIFES WHERE ALMOXARIFADO  = @RASTRO(PD_ALMOXARIFADOS) ))) AND (A.ALMOXARIFADODESTINO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t868_at1468_hs82816aae.aspx" UserDefinedDisableRowSelection="False" PageId="IE_PRODUTOS__ALMOXARIFADOS_FORM" Level="20" Order="50"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_264_1469" Title="Requisições do almoxarifado&gt;Cancelados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(STATUS = 5 AND (TIPO = 'O' OR TIPO='T') AND ALMOXARIFADO = @RASTRO(PD_ALMOXARIFADOS) AND ( @USUARIO IN (SELECT RESPONSAVEL FROM PD_ALMOXARIFADOS WHERE HANDLE = @RASTRO(PD_ALMOXARIFADOS) ) OR @USUARIO IN (SELECT ALMOXARIFE FROM PD_ALMOXARIFES WHERE ALMOXARIFADO  = @RASTRO(PD_ALMOXARIFADOS) ))) AND (A.ALMOXARIFADODESTINO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t868_at1469_hs179322c4.aspx" UserDefinedDisableRowSelection="False" PageId="IE_PRODUTOS__ALMOXARIFADOS_FORM" Level="20" Order="55"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_264_1467" Title="Requisições do almoxarifado&gt;À atender" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(STATUS = 2 AND QUANTIDADE &lt;&gt; QUANTIDADEATENDIDA AND (TIPO = 'O' OR TIPO='T') AND ALMOXARIFADO = @RASTRO(PD_ALMOXARIFADOS) AND ( @USUARIO IN (SELECT RESPONSAVEL FROM PD_ALMOXARIFADOS WHERE HANDLE = @RASTRO(PD_ALMOXARIFADOS) ) OR @USUARIO IN (SELECT ALMOXARIFE FROM PD_ALMOXARIFES WHERE ALMOXARIFADO  = @RASTRO(PD_ALMOXARIFADOS) ))) AND (A.ALMOXARIFADODESTINO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t868_at1467_hs978251ba.aspx" UserDefinedDisableRowSelection="False" PageId="IE_PRODUTOS__ALMOXARIFADOS_FORM" Level="20" Order="60"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_5395" Title="Saldo inicial estoque terceiros" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_MOVIMENTACAOTERCEIROTOTAIS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ALMOXARIFADO = @RASTRO(PD_ALMOXARIFADOS) AND A.TIPO = 'C') AND (A.ALMOXARIFADO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t3307_at5395_hs61cc11d.aspx" UserDefinedDisableRowSelection="False" PageId="IE_PRODUTOS__ALMOXARIFADOS_FORM" Level="20" Order="65"  />
        </div>
    
      </asp:Content>
    