<%@ Page Title="REG.C100: NF CÓDIGOS 01, 1B, 04, 55 - Não gerados" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="REG.C100: NF CÓDIGOS 01, 1B, 04, 55 - Não gerados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_ED_PCDOCUMENTOS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="ED_CARGA_EFDPC_SAIDAS_REGISTROC100__ED_CARGA_EFDPC_SAIDAS_REGISTROC100NGR_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6334" Title="REG.C110: INFORMAÇÕES COMPLEMENTARES" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PCDOCUMENTOOBSERVACOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DOCUMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4004_at6334_hs15309e54.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFDPC_SAIDAS_REGISTROC100__ED_CARGA_EFDPC_SAIDAS_REGISTROC100NGR_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6335" Title="REG.C111: PROCESSOS REFERENCIADOS" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PCDOCUMENTOPROCESSO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DOCUMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4082_at6335_hs15309e55.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFDPC_SAIDAS_REGISTROC100__ED_CARGA_EFDPC_SAIDAS_REGISTROC100NGR_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6337" Title="REG.C120: OPERAÇÕES DE IMPORTAÇÃO" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PCDOCUMENTOIMPORTACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.DOCUMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4005_at6337_hs73019e54.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFDPC_SAIDAS_REGISTROC100__ED_CARGA_EFDPC_SAIDAS_REGISTROC100NGR_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6336" Title="REG.C170: ITENS DO DOC (01, 1B, 04 e 55)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_ED_PCDOCUMENTOITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="ED_PCDOCUMENTOS.CODIGOMODELO NOT IN ('65') AND (A.DOCUMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4003_at6336_hsd0d29e54.aspx" UserDefinedDisableRowSelection="False" PageId="ED_CARGA_EFDPC_SAIDAS_REGISTROC100__ED_CARGA_EFDPC_SAIDAS_REGISTROC100NGR_FORM" Level="20" Order="25"  />
        </div>
    
      </asp:Content>
    