<%@ Page Title="Conjuntos mecânicos e eixos - Eixos" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Conjuntos mecânicos e eixos - Eixos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_MF_VEICULOMODELOEIXOS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="MF_VEICULOPARTES_SOLEITURA__EIXOS_VEICULO_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4153" Title="Pneu no centro" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MA_RECURSOPARTES.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="EXISTS (SELECT 1 FROM MF_HISTORICOLOCACAOPARTES B WHERE B.PARTE = A.HANDLE AND B.TIPO = 1 AND B.VEICULO = @RASTRO(MA_RECURSOS) AND B.LOCALVEICULO = 3 AND B.LOCALMODELO = 2 AND B.EIXO = @RASTRO(MF_VEICULOMODELOEIXOS) AND B.POSICAO = 0 AND B.DATA = (SELECT MAX(C.DATA) FROM MF_HISTORICOLOCACAOPARTES C WHERE C.PARTE = B.PARTE)) AND (A.EIXO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2349_at4153_hsb358fcc8.aspx" UserDefinedDisableRowSelection="False" PageId="MF_VEICULOPARTES_SOLEITURA__EIXOS_VEICULO_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4151" Title="Pneus lado direito" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MA_RECURSOPARTES.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="EXISTS (SELECT 1 FROM MF_HISTORICOLOCACAOPARTES B WHERE B.PARTE = A.HANDLE AND B.TIPO = 1 AND B.VEICULO = @RASTRO(MA_RECURSOS) AND B.LOCALVEICULO = 3 AND B.LOCALMODELO = 2 AND B.EIXO = @RASTRO(MF_VEICULOMODELOEIXOS) AND B.POSICAO &lt; 0 AND B.DATA = (SELECT MAX(C.DATA) FROM MF_HISTORICOLOCACAOPARTES C WHERE C.PARTE = B.PARTE)) AND (A.EIXO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2349_at4151_hsad99aa4c.aspx" UserDefinedDisableRowSelection="False" PageId="MF_VEICULOPARTES_SOLEITURA__EIXOS_VEICULO_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4152" Title="Pneus lado esquerdo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_MA_RECURSOPARTES.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="EXISTS (SELECT 1 FROM MF_HISTORICOLOCACAOPARTES B WHERE B.PARTE = A.HANDLE AND B.TIPO = 1 AND B.VEICULO = @RASTRO(MA_RECURSOS) AND B.LOCALVEICULO = 3 AND B.LOCALMODELO = 2 AND B.EIXO = @RASTRO(MF_VEICULOMODELOEIXOS) AND B.POSICAO &gt; 0 AND B.DATA = (SELECT MAX(C.DATA) FROM MF_HISTORICOLOCACAOPARTES C WHERE C.PARTE = B.PARTE)) AND (A.EIXO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2349_at4152_hs1bafb695.aspx" UserDefinedDisableRowSelection="False" PageId="MF_VEICULOPARTES_SOLEITURA__EIXOS_VEICULO_FORM" Level="20" Order="20"  />
        </div>
    
      </asp:Content>
    