<%@ Page Title="Rotinas de correspondências - Todas" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Rotinas de correspondências - Todas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_GN_ROTINASCORRESPONDENCIA.FORM" CanDelete="True" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="ADM_ROTINAS_DE_CORRESPONDENCIA__TODAS_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2452" Title="Agentes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PESSOACORRESPONDENCIAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PESSOA IN (SELECT B.HANDLE FROM GN_PESSOAS B WHERE B.EHAGENTEVENDAS='S')) AND (A.ROTINA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2058_at2452_hsb6cbebe0.aspx" UserDefinedDisableRowSelection="False" PageId="ADM_ROTINAS_DE_CORRESPONDENCIA__TODAS_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2451" Title="Cedentes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PESSOACORRESPONDENCIAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PESSOA IN (SELECT B.HANDLE FROM GN_PESSOAS B WHERE B.EHCEDENTE='S')) AND (A.ROTINA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2058_at2451_hs95bba552.aspx" UserDefinedDisableRowSelection="False" PageId="ADM_ROTINAS_DE_CORRESPONDENCIA__TODAS_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2449" Title="Clientes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PESSOACORRESPONDENCIAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PESSOA IN (SELECT B.HANDLE FROM GN_PESSOAS B WHERE B.EHCLIENTE='S')) AND (A.ROTINA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2058_at2449_hs102fa3dd.aspx" UserDefinedDisableRowSelection="False" PageId="ADM_ROTINAS_DE_CORRESPONDENCIA__TODAS_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2450" Title="Fornecedores" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PESSOACORRESPONDENCIAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PESSOA IN (SELECT B.HANDLE FROM GN_PESSOAS B WHERE B.EHFORNECEDOR='S')) AND (A.ROTINA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2058_at2450_hsad021ce7.aspx" UserDefinedDisableRowSelection="False" PageId="ADM_ROTINAS_DE_CORRESPONDENCIA__TODAS_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2453" Title="Funcionários" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PESSOACORRESPONDENCIAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PESSOA IN (SELECT B.HANDLE FROM GN_PESSOAS B WHERE B.EHFUNCIONARIO='S')) AND (A.ROTINA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2058_at2453_hsf1ef8cfd.aspx" UserDefinedDisableRowSelection="False" PageId="ADM_ROTINAS_DE_CORRESPONDENCIA__TODAS_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2454" Title="Todos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PESSOACORRESPONDENCIAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ROTINA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2058_at2454_hs4545730d.aspx" UserDefinedDisableRowSelection="False" PageId="ADM_ROTINAS_DE_CORRESPONDENCIA__TODAS_FORM" Level="20" Order="35"  />
        </div>
    
      </asp:Content>
    