<%@ Page Title="Operações" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Operações" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_TR_SSRVSOPERACOES.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="SS_LOTES_ASSOC_RVS__SS_LOTES_OPERACOES_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8466" Title="Declaração de Importação" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_SSRVSDECLARACAOIMPORTACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN ( SELECT TR_SSLOTESASSOCIACAO.LIGACAO FROM TR_SSLOTESASSOCIACAO WHERE TR_SSLOTESASSOCIACAO.TIPO = 8 AND TR_SSLOTESASSOCIACAO.LOTE = @RASTRO(TR_SSLOTES) ) 
AND A.OPERACAO = @RASTRO(TR_SSRVSOPERACOES) AND (A.OPERACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5813_at8466_hs4bace5e5.aspx" UserDefinedDisableRowSelection="False" PageId="SS_LOTES_ASSOC_RVS__SS_LOTES_OPERACOES_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8465" Title="Enquadramento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_SSRVSOPERACAOENQUADRAMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN ( SELECT TR_SSLOTESASSOCIACAO.LIGACAO FROM TR_SSLOTESASSOCIACAO WHERE TR_SSLOTESASSOCIACAO.TIPO = 10 AND TR_SSLOTESASSOCIACAO.LOTE = @RASTRO(TR_SSLOTES) ) 
AND A.OPERACAORVS = @RASTRO(TR_SSRVSOPERACOES) AND (A.OPERACAORVS = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4626_at8465_hs67d2a7a0.aspx" UserDefinedDisableRowSelection="False" PageId="SS_LOTES_ASSOC_RVS__SS_LOTES_OPERACOES_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8467" Title="Registro de Exportação" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_TR_SSRVSREGISTROEXPORTACAO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN ( SELECT TR_SSLOTESASSOCIACAO.LIGACAO FROM TR_SSLOTESASSOCIACAO WHERE TR_SSLOTESASSOCIACAO.TIPO = 11 AND TR_SSLOTESASSOCIACAO.LOTE = @RASTRO(TR_SSLOTES) ) 
AND A.OPERACAO = @RASTRO(TR_SSRVSOPERACOES) AND (A.OPERACAO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5812_at8467_hsc7eafd11.aspx" UserDefinedDisableRowSelection="False" PageId="SS_LOTES_ASSOC_RVS__SS_LOTES_OPERACOES_FORM" Level="20" Order="20"  />
        </div>
    
      </asp:Content>
    