<%@ Page Title="Lalur - Lucro Real - Contas da parte A" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Lalur - Lucro Real - Contas da parte A" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_LA_CONTASPARTEA.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="LA_LALUR_LUCROREAL__CONTASPARTEA_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4817" Title="Contas contábeis" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LA_CONTAPARTEACONTAS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.CONTA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2900_at4817_hs300d23e7.aspx" UserDefinedDisableRowSelection="False" PageId="LA_LALUR_LUCROREAL__CONTASPARTEA_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_8075" Title="Contas contábeis do ativo imobilizado" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LA_CONTASDOATIVOIMOBILIZADO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.CONTAPARTEA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5565_at8075_hsaa4cc8e2.aspx" UserDefinedDisableRowSelection="False" PageId="LA_LALUR_LUCROREAL__CONTASPARTEA_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7629" Title="Lançamentos contábeis" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CT_LANCAMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN ( SELECT RELACIONAMENTO.LANCAMENTOCONTABIL FROM LA_RELACAOPARTEALANCAMENTOCONT RELACIONAMENTO WHERE RELACIONAMENTO.LANCAMENTOPARTEA = @TABELA(LA_CONTASPARTEA))" FormUrl="~/aga/a/f/aga_t923_at7629_hs1ba995fc.aspx" UserDefinedDisableRowSelection="False" PageId="LA_LALUR_LUCROREAL__CONTASPARTEA_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7950" Title="Lançamentos contábeis (sub conta)" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CT_LANCAMENTOCC.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN ( 

SELECT RELACIONAMENTO.LANCAMENTOCONTABILCC 
  FROM LA_RELACAOPARTEALANCAMENTOCONT RELACIONAMENTO 
 WHERE RELACIONAMENTO.LANCAMENTOPARTEA = @TABELA(LA_CONTASPARTEA)

)" FormUrl="~/aga/a/f/aga_t925_at7950_hs6e482fd0.aspx" UserDefinedDisableRowSelection="False" PageId="LA_LALUR_LUCROREAL__CONTASPARTEA_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7794" Title="Lançamentos da parte B" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LA_LANCAMENTOSPARTEB.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.CONTAPARTEA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2817_at7794_hsef8b8e34.aspx" UserDefinedDisableRowSelection="False" PageId="LA_LALUR_LUCROREAL__CONTASPARTEA_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4818" Title="Lançamentos manuais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LA_CONTAPARTEALANCAMENTOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.CONTA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2899_at4818_hs890a4898.aspx" UserDefinedDisableRowSelection="False" PageId="LA_LALUR_LUCROREAL__CONTASPARTEA_FORM" Level="20" Order="35"  />
        </div>
    
      </asp:Content>
    