<%@ Page Title="Parâmetro" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Parâmetro" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_GN_PLANOMETAPARAMETROS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="CARGA_GN_PLANOMETAPARAMETROS_001_SL__CARGA_GN_PLANOMETAPARAMETROS_PARAMETRO_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6832" Title="Cliente" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PLANOMETAITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOMETAPARAMETRO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4556_at6832_hsf5dbf224.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_GN_PLANOMETAPARAMETROS_001_SL__CARGA_GN_PLANOMETAPARAMETROS_PARAMETRO_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6833" Title="Estado" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PLANOMETAITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOMETAPARAMETRO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4556_at6833_hs13836f02.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_GN_PLANOMETAPARAMETROS_001_SL__CARGA_GN_PLANOMETAPARAMETROS_PARAMETRO_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6836" Title="Família" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PLANOMETAITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOMETAPARAMETRO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4556_at6836_hs2d1a002d.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_GN_PLANOMETAPARAMETROS_001_SL__CARGA_GN_PLANOMETAPARAMETROS_PARAMETRO_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6835" Title="Fornecedor" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PLANOMETAITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOMETAPARAMETRO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4556_at6835_hs87170980.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_GN_PLANOMETAPARAMETROS_001_SL__CARGA_GN_PLANOMETAPARAMETROS_PARAMETRO_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6837" Title="Grupo de itens" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PLANOMETAITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOMETAPARAMETRO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4556_at6837_hsd8c9d433.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_GN_PLANOMETAPARAMETROS_001_SL__CARGA_GN_PLANOMETAPARAMETROS_PARAMETRO_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7215" Title="Linha principal" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PLANOMETAITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOMETAPARAMETRO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4556_at7215_hs7f7114a1.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_GN_PLANOMETAPARAMETROS_001_SL__CARGA_GN_PLANOMETAPARAMETROS_PARAMETRO_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7214" Title="Marca produto" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PLANOMETAITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOMETAPARAMETRO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4556_at7214_hsa490aecf.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_GN_PLANOMETAPARAMETROS_001_SL__CARGA_GN_PLANOMETAPARAMETROS_PARAMETRO_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6838" Title="Produto" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PLANOMETAITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOMETAPARAMETRO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4556_at6838_hs55c3cdfa.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_GN_PLANOMETAPARAMETROS_001_SL__CARGA_GN_PLANOMETAPARAMETROS_PARAMETRO_FORM" Level="20" Order="45"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6840" Title="Ramo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PLANOMETAITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOMETAPARAMETRO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4556_at6840_hs173b91c9.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_GN_PLANOMETAPARAMETROS_001_SL__CARGA_GN_PLANOMETAPARAMETROS_PARAMETRO_FORM" Level="20" Order="50"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6839" Title="Variação" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PLANOMETAITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOMETAPARAMETRO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4556_at6839_hs2ee93dfb.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_GN_PLANOMETAPARAMETROS_001_SL__CARGA_GN_PLANOMETAPARAMETROS_PARAMETRO_FORM" Level="20" Order="55"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6834" Title="Vendedor" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PLANOMETAITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.PLANOMETAPARAMETRO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4556_at6834_hs8ce1ec91.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_GN_PLANOMETAPARAMETROS_001_SL__CARGA_GN_PLANOMETAPARAMETROS_PARAMETRO_FORM" Level="20" Order="60"  />
        </div>
    
      </asp:Content>
    