<%@ Page Title="Cálculos do custo por absorção" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Cálculos do custo por absorção" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_CS_CALCULOS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="PRODUCAO__CALCULOSCUSTOABSORCAO_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7895" Title="CPV" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CS_CPV.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.FILIAL = (SELECT Z.FILIAL FROM CS_CALCULOS Z WHERE Z.HANDLE = @RASTRO(CS_CALCULOS))
AND 
A.COMPETENCIA = (SELECT X.COMPETENCIA FROM CS_CALCULOS X WHERE X.HANDLE = @RASTRO(CS_CALCULOS))" FormUrl="~/aga/a/f/aga_t2503_at7895_hs7266d080.aspx" UserDefinedDisableRowSelection="False" PageId="PRODUCAO__CALCULOSCUSTOABSORCAO_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7891" Title="Centros de custo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CS_CONTABILIDADERATEIOCC.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.FILIAL = (SELECT X.FILIAL FROM CS_CALCULOS X WHERE X.HANDLE = @RASTRO(CS_CALCULOS))
AND A.COMPETENCIA = (SELECT Y.COMPETENCIA FROM CS_CALCULOS Y WHERE Y.HANDLE = @RASTRO(CS_CALCULOS))" FormUrl="~/aga/a/f/aga_t4036_at7891_hs1996c858.aspx" UserDefinedDisableRowSelection="False" PageId="PRODUCAO__CALCULOSCUSTOABSORCAO_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7894" Title="Lançamentos da produção" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CS_PRODUCAOAPONTAMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.FILIAL = (SELECT Z.FILIAL FROM CS_CALCULOS Z WHERE Z.HANDLE = @RASTRO(CS_CALCULOS))
AND
A.COMPETENCIA = (SELECT Y.COMPETENCIA FROM CS_CALCULOS Y WHERE Y.HANDLE = @RASTRO(CS_CALCULOS))" FormUrl="~/aga/a/f/aga_t5410_at7894_hs5d42244a.aspx" UserDefinedDisableRowSelection="False" PageId="PRODUCAO__CALCULOSCUSTOABSORCAO_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7898" Title="Logs" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CS_LOG.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.FILIAL = (SELECT Z.FILIAL FROM CS_CALCULOS Z WHERE Z.HANDLE = @RASTRO(CS_CALCULOS))
AND
A.PERIODO = (SELECT Y.COMPETENCIA FROM CS_CALCULOS Y WHERE Y.HANDLE = @RASTRO(CS_CALCULOS))" FormUrl="~/aga/a/f/aga_t2501_at7898_hs6ff7d4db.aspx" UserDefinedDisableRowSelection="False" PageId="PRODUCAO__CALCULOSCUSTOABSORCAO_FORM" Level="20" Order="25"  />
        </div>
    
      </asp:Content>
    