<%@ Page Title="Tabelas auxiliares - Famílias de item" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Tabelas auxiliares - Famílias de item" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_PD_FAMILIASPRODUTOS.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="MI_CONFIGURACOES__FAMILIAS_DE_ITEM_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1346" Title="Clientes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_PESSOAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(EHCLIENTE = 'S')" FormUrl="~/aga/a/f/aga_t717_at1346_hs3e0e3a67.aspx" UserDefinedDisableRowSelection="False" PageId="MI_CONFIGURACOES__FAMILIAS_DE_ITEM_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6632" Title="Códigos de atividade" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_FAMILIACODIGOATIVIDADE.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.FAMILIA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4312_at6632_hs19cbb7b7.aspx" UserDefinedDisableRowSelection="False" PageId="MI_CONFIGURACOES__FAMILIAS_DE_ITEM_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_705" Title="Itens da empresa" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_PRODUTOSPAI.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(STATUS = 3) AND (A.FAMILIA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1772_at705_hs3a9e9af0.aspx" UserDefinedDisableRowSelection="False" PageId="MI_CONFIGURACOES__FAMILIAS_DE_ITEM_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6739" Title="Políticas comerciais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_POLITICASCOMERCIAIS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.FAMILIA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4453_at6739_hs47c2a186.aspx" UserDefinedDisableRowSelection="False" PageId="MI_CONFIGURACOES__FAMILIAS_DE_ITEM_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7522" Title="Tipos de documento habilitação" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_GN_DOCUMENTOHABILITACAOITEM.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.FAMILIA = @RASTRO(PD_FAMILIASPRODUTOS) AND (A.FAMILIA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t5169_at7522_hsa7d91583.aspx" UserDefinedDisableRowSelection="False" PageId="MI_CONFIGURACOES__FAMILIAS_DE_ITEM_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1278" Title="Tipos de variação da família" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PD_FAMILIATIPOSVARIACAO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.FAMILIA = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1484_at1278_hs8323b7ff.aspx" UserDefinedDisableRowSelection="False" PageId="MI_CONFIGURACOES__FAMILIAS_DE_ITEM_FORM" Level="20" Order="35"  />
        </div>
    
      </asp:Content>
    