<%@ Page Title="Ordens de compra" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Ordens de compra" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRA.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="MF_ORDEMSERVICOS_CADASTRAR__ORDENS_DE_COMPRA_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4470" Title="Aguardando confirmação" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="((A.LIBERADA = 'S' OR A.LIBERADA IS NULL) AND (A.STATUS = 1 OR A.STATUS = 7) AND (A.ORIGEM = 8) AND ((A.GRUPODEASSINATURAS IS NULL AND A.CONFIRMANTE = @USUARIO) OR (A.GRUPODEASSINATURAS IN(SELECT C.HANDLE FROM CP_GRUPOALCADASINTEGRANTES B,CP_GRUPOALCADAS C WHERE B.GRUPO = C.HANDLE AND C.EHHIERARQUIA = 'S' AND B.SEQUENCIA &gt;= A.SEQUENCIAALCADA AND B.USUARIO = @USUARIO AND B.ATIVO = 'S') OR (A.GRUPODEASSINATURAS IN (SELECT C.HANDLE FROM CP_GRUPOALCADASINTEGRANTES B,CP_GRUPOALCADAS C WHERE B.GRUPO = C.HANDLE AND C.EHHIERARQUIA &lt;&gt; 'S' AND B.SEQUENCIA = A.SEQUENCIAALCADA AND B.USUARIO = @USUARIO AND B.ATIVO = 'S')))))" FormUrl="~/aga/a/f/aga_t1529_at4470_hs3d37a827.aspx" UserDefinedDisableRowSelection="False" PageId="MF_ORDEMSERVICOS_CADASTRAR__ORDENS_DE_COMPRA_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4469" Title="Cadastradas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="((A.LIBERADA &lt;&gt; 'S' OR A.LIBERADA IS NULL) AND (A.ORIGEM=8) AND (A.STATUS=1 OR A.STATUS = 7) AND (A.USUARIOINCLUIU = @USUARIO OR A.USUARIOALTEROU = @USUARIO))" FormUrl="~/aga/a/f/aga_t1529_at4469_hs38c1ad83.aspx" UserDefinedDisableRowSelection="False" PageId="MF_ORDEMSERVICOS_CADASTRAR__ORDENS_DE_COMPRA_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4471" Title="Canceladas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS = 5) AND (A.ORIGEM = 8)" FormUrl="~/aga/a/f/aga_t1529_at4471_hsda7e1bca.aspx" UserDefinedDisableRowSelection="False" PageId="MF_ORDEMSERVICOS_CADASTRAR__ORDENS_DE_COMPRA_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4472" Title="Confirmadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS = 2) AND (A.ORIGEM = 8)" FormUrl="~/aga/a/f/aga_t1529_at4472_hsf5716de6.aspx" UserDefinedDisableRowSelection="False" PageId="MF_ORDEMSERVICOS_CADASTRAR__ORDENS_DE_COMPRA_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4474" Title="Encerradas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS = 4) AND (A.ORIGEM = 8)" FormUrl="~/aga/a/f/aga_t1529_at4474_hs8c8639e9.aspx" UserDefinedDisableRowSelection="False" PageId="MF_ORDEMSERVICOS_CADASTRAR__ORDENS_DE_COMPRA_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4473" Title="Recebendo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS = 3) AND (A.ORIGEM =8)" FormUrl="~/aga/a/f/aga_t1529_at4473_hsedfa19a1.aspx" UserDefinedDisableRowSelection="False" PageId="MF_ORDEMSERVICOS_CADASTRAR__ORDENS_DE_COMPRA_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_4475" Title="Todas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS &lt;&gt; 6) AND (A.ORIGEM = 8)" FormUrl="~/aga/a/f/aga_t1529_at4475_hs96fba28c.aspx" UserDefinedDisableRowSelection="False" PageId="MF_ORDEMSERVICOS_CADASTRAR__ORDENS_DE_COMPRA_FORM" Level="20" Order="40"  />
        </div>
    
      </asp:Content>
    