<%@ Page Title="Orçamentos créditos" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Orçamentos créditos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_PJ_TAREFAORCAMENTOS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="PJ_TAREFA_LEITURA__ORCAMENTOS_TIPO2_SL_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3842" Title="Competências" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PJ_ORCAMENTOCOMPETENCIAS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1905_at3842_hsc9f905c5.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTOS_TIPO2_SL_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3841" Title="Compromissos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PJ_ORCAMENTOCOMPROMISSOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1903_at3841_hs3768f3d3.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTOS_TIPO2_SL_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1168_3846" Title="Entradas de convênios&gt;Cadastradas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PJ_ORCAMENTODOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(DOCUMENTOGERADO IS NULL) AND (NATUREZA= 'C') AND (TIPO = 2) AND (A.ORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2585_at3846_hs94992beb.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTOS_TIPO2_SL_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1168_3848" Title="Entradas de convênios&gt;Cancelados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PJ_ORCAMENTODOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(NATUREZA= 'X') AND (TIPO = 2) AND (A.ORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2585_at3848_hsadaa4ff9.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTOS_TIPO2_SL_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1168_3847" Title="Entradas de convênios&gt;Emitidos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PJ_ORCAMENTODOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(DOCUMENTOGERADO IS NOT NULL) AND (NATUREZA= 'C') AND (TIPO = 2) AND (A.ORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2585_at3847_hs947096d6.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTOS_TIPO2_SL_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1168_4366" Title="Ordens de venda&gt;Canceladas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS=5 ) AND (A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4366_hs955d91ec.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTOS_TIPO2_SL_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1168_4363" Title="Ordens de venda&gt;Confirmadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS=2 ) AND (A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4363_hsb96fb5d3.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTOS_TIPO2_SL_FORM" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1168_4367" Title="Ordens de venda&gt;Confirmar" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="((A.LIBERADOCONFIRMACAO = 'S' OR A.LIBERADOCONFIRMACAO IS NULL) AND 
(A.STATUS = 1) AND ((A.GRUPOASSINATURAS IS NULL AND A.CONFIRMANTE = @USUARIO) OR
 (A.GRUPOASSINATURAS IN(SELECT C.HANDLE FROM CP_GRUPOALCADASINTEGRANTES B,
CP_GRUPOALCADAS C WHERE B.GRUPO = C.HANDLE AND C.EHHIERARQUIA = 'S' 
AND B.SEQUENCIA &gt;= A.SEQUENCIAALCADA AND B.USUARIO = @USUARIO AND B.ATIVO = 'S') OR 
(A.GRUPOASSINATURAS IN
 (SELECT C.HANDLE FROM CP_GRUPOALCADASINTEGRANTES B,CP_GRUPOALCADAS C 
WHERE B.GRUPO = C.HANDLE AND C.EHHIERARQUIA &lt;&gt; 'S' AND
 B.SEQUENCIA = A.SEQUENCIAALCADA AND B.USUARIO = @USUARIO AND B.ATIVO = 'S'))))) AND (A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4367_hs104c05dd.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTOS_TIPO2_SL_FORM" Level="20" Order="45"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1168_4362" Title="Ordens de venda&gt;Em elaboração" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS=1 AND A.LIBERADOCONFIRMACAO &lt;&gt; 'S') AND (A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4362_hs66b7783a.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTOS_TIPO2_SL_FORM" Level="20" Order="50"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1168_4364" Title="Ordens de venda&gt;Em faturamento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS=3) AND (A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4364_hs6b2c578f.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTOS_TIPO2_SL_FORM" Level="20" Order="55"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1168_4365" Title="Ordens de venda&gt;Encerradas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS=4) AND (A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4365_hs84f9639c.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTOS_TIPO2_SL_FORM" Level="20" Order="60"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1168_4369" Title="Ordens de venda&gt;Faturadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS = 6) AND (A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4369_hsc4035823.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTOS_TIPO2_SL_FORM" Level="20" Order="65"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1168_4368" Title="Ordens de venda&gt;Todas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDENSVENDA.GRID" CanDelete="False" CanUpdate="True" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.TAREFAORCAMENTO = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1757_at4368_hs94a79834.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_TAREFA_LEITURA__ORCAMENTOS_TIPO2_SL_FORM" Level="20" Order="70"  />
        </div>
    
      </asp:Content>
    