<%@ Page Title="Itens de OC" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Itens de OC" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRAITENS.FORM" CanDelete="False" CanUpdate="False" CanInsert="False" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="CARGA_DE_OC__ITENS_SO_LEITURA_2__ITENS_DE_OC_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_7322" Title="Inspeções Adicionais" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ROTEIROSADICIONAIS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMCOMPRAITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t4889_at7322_hsf1476853.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_OC__ITENS_SO_LEITURA_2__ITENS_DE_OC_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_6854" Title="Ordem venda origem" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CM_ORDEMVENDAITENS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT OVI.HANDLE FROM CM_ORDEMVENDAITENS OVI JOIN CP_ORDEMCOMPRAORDEMVENDA OCOV ON OVI.HANDLE = OCOV.ORDEMVENDAITEM
WHERE OCOV.ORDEMCOMPRAITEM = @RASTRO(CP_ORDENSCOMPRAITENS))" FormUrl="~/aga/a/f/aga_t1944_at6854_hs415222a0.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_OC__ITENS_SO_LEITURA_2__ITENS_DE_OC_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1436" Title="Previsão de entregas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_ORDENSCOMPRAENTREGA.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.ORDENSCOMPRAITENS = @RASTRO(CP_ORDENSCOMPRAITENS)" FormUrl="~/aga/a/f/aga_t1531_at1436_hs7c9ed073.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_OC__ITENS_SO_LEITURA_2__ITENS_DE_OC_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1527" Title="Recebimento físico" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_RECEBIMENTOFISICO.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.STATUS = 3 OR A.STATUS = 2 OR A.STATUS IS NULL) AND (A.ORDEMCOMPRAITEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1584_at1527_hs5375fd9d.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_OC__ITENS_SO_LEITURA_2__ITENS_DE_OC_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_1478" Title="Requisição item" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_CP_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" FormUrl="~/aga/a/f/aga_t868_at1478_hs2aee0e2c.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_OC__ITENS_SO_LEITURA_2__ITENS_DE_OC_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2595" Title="Requisições de aquisição" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_LC_REQUISICOES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT D.HANDLE FROM CP_ORDENSCOMPRAITENS E, LC_AQUISICAOITENS B, LC_REQUISICAOITENS C,
LC_REQUISICOES D WHERE E.HANDLE = @RASTRO(CP_ORDENSCOMPRAITENS) AND E.HANDLE = B.ORDEMCOMPRAITEM AND 
B.REQUISICAOITEM = C.HANDLE AND C.REQUISICAO = D.HANDLE)" FormUrl="~/aga/a/f/aga_t1792_at2595_hs24811090.aspx" UserDefinedDisableRowSelection="False" PageId="CARGA_DE_OC__ITENS_SO_LEITURA_2__ITENS_DE_OC_FORM" Level="20" Order="35"  />
        </div>
    
      </asp:Content>
    