<%@ Page Title="Ordens de viagem" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMULARIO" Title="Ordens de viagem" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="AGA_OV_ORDENSVIAGEM.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCriteriaWhereClause="'forcar_carga_form'='forcar_carga_form'" UserDefinedCommandsVisible="True" PageId="PJ_ORCAMENTO__ORDENSVIAGEM_FORM" Level="20" Order="1"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2882" Title="Adiantamentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_FN_DOCUMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.HANDLE IN(SELECT B.DOCUMENTO FROM OV_ORDENSVIAGEM B WHERE B.HANDLE = @RASTRO(OV_ORDENSVIAGEM)))" FormUrl="~/aga/a/f/aga_t1216_at2882_hs5ef59929.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_ORCAMENTO__ORDENSVIAGEM_FORM" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2878" Title="Complementos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_OV_ORDENSCOMPLEMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMVIAGEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1868_at2878_hs80952862.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_ORCAMENTO__ORDENSVIAGEM_FORM" Level="20" Order="15"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2880" Title="Despesas de responsabilidades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_OV_ORDENSRESPONSABILIDADES.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMVIAGEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1873_at2880_hsdc1761b5.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_ORCAMENTO__ORDENSVIAGEM_FORM" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2881" Title="Destinos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_OV_ORDENSDESTINOS.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMVIAGEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1872_at2881_hsb5aa76bf.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_ORCAMENTO__ORDENSVIAGEM_FORM" Level="20" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2879" Title="Outros adiantamentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_OV_OUTROSADIANTAMENTOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMVIAGEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1408_at2879_hs71b9efec.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_ORCAMENTO__ORDENSVIAGEM_FORM" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_3012" Title="Rateios das fontes financiadoras" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_PJ_ORCAMENTOENTIDADES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMVIAGEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t2006_at3012_hsc0285408.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_ORCAMENTO__ORDENSVIAGEM_FORM" Level="20" Order="35"  />
        <wes:SimpleGrid runat="server" ID="WIDGET_2883" Title="Relatórios de retornos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="FORMULARIO" ChromeState="Normal" EntityViewName="AGA_OV_RETORNOS.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="CompanyAndBranch" UserDefinedCriteriaWhereClause="(A.ORDEMVIAGEM = @CAMPO(HANDLE))" FormUrl="~/aga/a/f/aga_t1411_at2883_hs90dbf101.aspx" UserDefinedDisableRowSelection="False" PageId="PJ_ORCAMENTO__ORDENSVIAGEM_FORM" Level="20" Order="40"  />
        </div>
    
      </asp:Content>
    