//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Definicoes.Suprimentos;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Services;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using Ninject;
using System;

public partial class fDuplicarAlcadaFilialPage : WesPage
{
    [Inject]
    public ISessionVars SessionVars { get; set; }

    [Inject]
    public ICPGrupoAlcadaDao GrupoAlcadaDao { get; set; }

    private long HandleGrupoAlcada
    {
        get
        {
            return SessionVars.GetSessionVar("HANDLE_GRUPOALCADA").ToLong();
        }
    }

    private bool CopiarIntegrantes
    {
        get
        {
            return Page.Request.Form["ctl00$Main$COPIARINTEGRANTES$PageControl$GERAL$GERAL$CAMPOLOGICO_CHECKBOX"] == "on";
        }
    }

    protected override void OnLoad(EventArgs e)
    {
        base.OnLoad(e);
        SELECIONARFILIAL.CommandExecute += SELECIONARFILIAL_CommandExecute;       
    }

    private void SELECIONARFILIAL_CommandExecute(object sender, GridCommandExecuteArgs e)
    {
        if (e.Command.Name == "CMD_DUPLICAR_ALCADA")
        {
            if (SELECIONARFILIAL.SelectedEntitiesHandles.Count <= 0)
                return;            
            
            BennerContext.BusinessComponent.Call(
                "Benner.Corporativo.Financeiro.Alcadas.ControladorAlcadasFinanceiro, " +
                "Benner.Corporativo.Financeiro", 
                "DuplicarAlcadaFilial", 
                HandleGrupoAlcada, 
                SELECIONARFILIAL.SelectedEntitiesHandles.ConvertAll(h => (long) h),
                CopiarIntegrantes);
        }
    }
}
