//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Wes.WebApp.Dashboards;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Ninject;
using Benner.Corporativo.DataContracts.Comercial.Dashboard;
using Benner.Tecnologia.Business;
using System.Web.Script.Serialization;
using Benner.Corporativo.Definicoes.Administracao;
using Benner.Tecnologia.Common.Authorization;
using System.Threading;
using Benner.Corporativo.Definicoes.Financeiro;
using Benner.Corporativo.Common.Extensions;
using Benner.Corporativo.Definicoes.Comercial;

public partial class comercialinicioPage : WesPage
{

    public bool PermiteColetar
    {
        get
        {
            if (BennerPrincipal.Current.IsDeveloperRoleActive)
            {
                return true;
            }
            else
            {
                var papelAtual = BennerPrincipal.Current.ActiveRole;
                return BennerContext.Authorization
                                    .GetTasksFromRole(BennerConfiguration.DefaultSystemInstanceName, papelAtual)
                                    .Contains("COMERCIAL_COLETAR_DASHBOARD");
            }
        }
    }

    public bool PermiteVisualizarModuloComercial
    {
        get
        {
            if (BennerPrincipal.Current.IsDeveloperRoleActive)
            {
                return true;
            }
            else
            {
                var papelAtual = BennerPrincipal.Current.ActiveRole;
                return BennerContext.Authorization
                                    .GetTasksFromRole(BennerConfiguration.DefaultSystemInstanceName, papelAtual)
                                    .Contains("MODULO_COMERCIAL");
            }
        }
    }
    public bool PermiteVisualizarDashComercial
    {
        get
        {
            if (BennerPrincipal.Current.IsDeveloperRoleActive)
            {
                return true;
            }
            else
            {
                var papelAtual = BennerPrincipal.Current.ActiveRole;
                return BennerContext.Authorization
                                    .GetTasksFromRole(BennerConfiguration.DefaultSystemInstanceName, papelAtual)
                                    .Contains("VISUALIZAR_DASHCOMERCIALGERENCIAL");
            }
        }
    }

    public DateTime Competencia
    {
        get
        {
            if (Request.QueryString.GetValues("competencia") != null)
            {
                return Request.QueryString.GetValues("competencia").First().ToDateTime();
            }
            else
            {
                return DateTime.Now;
            }
        }
    }

    protected void Page_Load(object sender, System.EventArgs e)
    {
        LinkDefinition link = new LinkDefinition();
        link.IsModalPage = true;
    }

    protected override void OnInit(EventArgs e)
    {
        base.OnInit(e);
        if (!IsPostBack)
        {
            ScriptManager.RegisterHiddenField(this, "PERMITEVISUALIZARDASHBOARD", (PermiteVisualizarDashComercial || PermiteVisualizarModuloComercial).ToString());
            COMERCIALCOMANDOS.Hidden = Empresas.EsconderComandosModulosWes();
        }
            
    }
}
