//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class faturamentoNovaNotaPage : WesPage
{
    
    protected void Page_Load(object sender, System.EventArgs e)
    {
        NOVANOTA.CommandExecuted += NOVANOTA_CommandExecuted;
    }

    private void NOVANOTA_CommandExecuted(object sender, FormCommandExecuteArgs e)
    {
        if (e.CommandName == "Save")
        {
            var entity = NOVANOTA.GetEntity();
            long handleDocumento = entity["DOCUMENTO"].GetDBValue().ToLong();

            FormLinkDefinition link = new FormLinkDefinition();
            link.TargetSystemInstanceName = BennerContext.Administration.DefaultSystemInstanceName;
            link.WhereClause = new WhereClause("A.HANDLE = :DOCUMENTO", new Benner.Tecnologia.Common.Parameter("DOCUMENTO", handleDocumento));
            link.TargetEntityDefinitionName = "FN_DOCUMENTOS";
            link.TargetFormMode = FormLinkDefinition.FormMode.View;
            link.Url = "~/aga/e/comercial/faturamento/FormFaturamento.aspx";

            var url = Benner.Tecnologia.Wes.Components.UriBuilder.Create(link);

            Response.Redirect(url);            
        }
    }
}
