<%@ Page Title="Suspect/Prospect/Customer" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="WIDGETID_635709354498703436" Title="Suspect/Prospect/Customer" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="GN_PESSOAS.CUSTOM.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="PESSOAS" Level="20" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WIDGETID_635787903246344820" Title="Telefones" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="WIDGETID_635709354498703436" ChromeState="Normal" EntityViewName="GN_PESSOATELEFONES.CUSTOM.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PESSOA = @CAMPO(HANDLE)" FormUrl="~/PortalCRM/a/GN_PESSOATELEFONES/Form.aspx" UserDefinedDisableRowSelection="False" PageId="PESSOAS" Level="20" Order="20"  />
        <wes:SimpleGrid runat="server" ID="WIDGETID_635712707382938015" Title="Contatos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="WIDGETID_635709354498703436" ChromeState="Normal" EntityViewName="GN_PESSOACONTATOS.CUSTOM.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PESSOA = @CAMPO(HANDLE)" FormUrl="~/PortalCRM/a/GN_PESSOACONTATOS/Form.aspx" UserDefinedDisableRowSelection="False" PageId="PESSOAS" Level="20" Order="30"  />
        <wes:SimpleGrid runat="server" ID="WIDGETID_635714306960951004" Title="Oportunidades" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="WIDGETID_635709354498703436" ChromeState="Normal" EntityViewName="CRM_OPORTUNIDADES.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.PESSOA = @CAMPO(HANDLE)" FormUrl="~/PortalCRM/a/CRM_OPORTUNIDADES/Form.aspx" UserDefinedDisableRowSelection="False" PageId="PESSOAS" Level="20" Order="40"  />
        <wes:SimpleGrid runat="server" ID="WIDGETID_635787910168077822" Title="Ações de relacionamento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="WIDGETID_635709354498703436" ChromeState="Normal" EntityViewName="CRM_ACOESRELACIONAMENTO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT ACAORELACIONAMENTO FROM CRM_ACAOPESSOAS WHERE PESSOA = @CAMPO(HANDLE))" FormUrl="~/PortalCRM/a/CRM_ACOESRELACIONAMENTO/Form.aspx" UserDefinedDisableRowSelection="False" PageId="PESSOAS" Level="20" Order="50"  />
        </div>
    
      </asp:Content>
    