//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Frotas.Definicoes.Entidades;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using Benner.Tecnologia.Common.IoC;

public partial class OperadorFormPage : WesPage
{

    protected void Page_Load(object sender, System.EventArgs e)
    {
        btnCadastra_Click.Click += BtnCadastra_Click_Click;
    }

    private void BtnCadastra_Click_Click(object sender, EventArgs e)
    {
        //var Mf_PessoasDao = DependencyContainer.Get<IMf_PessoasDao>();
        var unidadeAbastecimentoPessoasDao = DependencyContainer.Get<IMFUnidadeAbastecimentoPessoaDao>();

        //var consultaPessoa = Mf_PessoasDao.GetMany(x => x.CgcCpf == txtCPF.Text);
        var unidadeAbastecimento = unidadeAbastecimentoPessoasDao.Create();
        //foreach (var data in consultaPessoa)
        //{
        unidadeAbastecimento.OperadorHandle = 1;
        unidadeAbastecimento.UnidadeabastecimentoHandle = 1;

        //}
        unidadeAbastecimentoPessoasDao.Save(unidadeAbastecimento);
    }





}
