//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class RemessaBancariaInserirPage : WesPage
{
    
    protected void Page_Load(object sender, System.EventArgs e)
    {
        if (!IsPostBack)
            SelecionarTodasAsParcelas();

        GRIDPARCELAS.CommandExecute += GRIDPARCELAS_CommandExecute;

    }

    private void GRIDPARCELAS_CommandExecute(object sender, GridCommandExecuteArgs e)
    {
        if (e.Command.Name == "CMD_GerarArquivoRemessa")
        {
            var link = Page.GetLinkDefinition() as GridLinkDefinition;
            if (link == null)
                return;
            var bancoHandle = link.Parameters["BANCO"];
            var contaHandle = link.Parameters["CONTA"];

            e.TransitoryVars["FN_Parcelas_ParcelasSelecionadas"] = GRIDPARCELAS.SelectedEntitiesHandles;
            e.TransitoryVars["FN_Parcelas_BancoHandle"] = bancoHandle;
            e.TransitoryVars["FN_Parcelas_ContaHandle"] = contaHandle;
        }
    }

    private void FORMREMESSABANCARIACRE_CommandExecute(object sender, FormCommandExecuteArgs e)
    {
        if (e.CommandName == PredefinedAction.ActionType.Save.ToString())
        {
            var trasitoryData = new TransitoryData();
            e.Entity.TransitoryData["GNHbRemessas_Incluir"] = GRIDPARCELAS.SelectedEntitiesHandles;
        }
    }




    private void SelecionarTodasAsParcelas()
    {
        GRIDPARCELAS.EnsureDataLoad();
        var entities = GRIDPARCELAS.DataSource as Entities<EntityBase>;

        if (entities == null)
            return;

        foreach (var entity in entities)
            GRIDPARCELAS.SelectedEntitiesHandles.Add(entity.Handle);
    }
}
