<%@ Page Title="Ações de Relacionamento" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FORMWIDGET_635713565360378209" Title="Ações de Relacionamento" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" EntityViewName="CRM_ACOESRELACIONAMENTO.CUSTOM.FORM" CanDelete="True" CanUpdate="True" CanInsert="True" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="FORMPAGEID_635713565360378209" Level="20" Order="100"  />
        <wes:SimpleGrid runat="server" ID="WIDGETID_635784273095322303" Title="Público alvo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMWIDGET_635713565360378209" ChromeState="Normal" EntityViewName="CRM_ACAOPESSOAS.CUSTOM.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.ACAORELACIONAMENTO = @CAMPO(HANDLE)" FormUrl="~/PortalCRM/a/CRM_ACAOPESSOAS/Form.aspx" UserDefinedDisableRowSelection="False" PageId="FORMPAGEID_635713565360378209" Level="20" Order="120"  />
        <wes:SimpleGrid runat="server" ID="WIDGETID_635785973227998540" Title="Documentos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMWIDGET_635713565360378209" ChromeState="Normal" EntityViewName="CRM_ACAODOCUMENTOS.CUSTOM.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.ACAORELACIONAMENTO = @CAMPO(HANDLE)" FormUrl="~/PortalCRM/a/CRM_ACAODOCUMENTOS/Form.aspx" UserDefinedDisableRowSelection="False" PageId="FORMPAGEID_635713565360378209" Level="20" Order="130"  />
        <wes:SimpleGrid runat="server" ID="WIDGETID_635786013780678845" Title="Produtos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMWIDGET_635713565360378209" ChromeState="Normal" EntityViewName="CRM_ACAOPRODUTOS.CUSTOM.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.ACAORELACIONAMENTO = @CAMPO(HANDLE)" FormUrl="~/PortalCRM/a/CRM_ACAOPRODUTOS/Form.aspx" UserDefinedDisableRowSelection="False" PageId="FORMPAGEID_635713565360378209" Level="20" Order="140"  />
        <wes:SimpleGrid runat="server" ID="WIDGETID_635799955116865683" Title="Tarefas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FORMWIDGET_635713565360378209" ChromeState="Normal" EntityViewName="CRM_TAREFAS.CUSTOM.ACAORELACIONAMENTO.GRID" CanDelete="True" CanUpdate="True" CanInsert="True" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.ACAORELACIONAMENTO = @CAMPO(HANDLE)" FormUrl="~/PortalCRM/a/CRM_TAREFAS/FormAcaoRelacionamentos.aspx" UserDefinedDisableRowSelection="False" PageId="FORMPAGEID_635713565360378209" Level="20" Order="150"  />
        </div>
    
      </asp:Content>
    