//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Definicoes.Financeiro;
using Benner.Corporativo.Definicoes.Web.Financeiro;
using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class AglutinadorCREGeralPage : WesPage
{
    protected void Page_Load(object sender, System.EventArgs e)
    {
        DOCUMENTOS.CommandExecute += DOCUMENTOS_CommandExecute;
    }

    void DOCUMENTOS_CommandExecute(object sender, GridCommandExecuteArgs e)
    {
        if (e.Command.Name.Equals("CMD_AGLUTINAR"))
            if (DOCUMENTOS.SelectedEntitiesHandles.Count > 0)
            {
                if (DOCUMENTOS.SelectedEntitiesHandles.Count > 1)
                {
                    Criteria criteriaFnDocumeto = new Criteria(@"A.HANDLE IN (" + string.Join(", ", DOCUMENTOS.SelectedEntitiesHandles.ToList()) + ")");
                    var moedas = FNDocumento.GetMany(criteriaFnDocumeto).Select(a => a.Moeda);
                    if (moedas.Any())
                    {
                        var m = moedas.First().Handle;
                        foreach (var moeda in moedas)
                        {
                            if (m != moeda.Handle)
                            {
                                throw new BusinessException("Não é possível aglutinar documentos com moedas diferentes!");
                            }
                        }
                    }
                }

                e.Command.OutputDefinition.Parameters.Add("DOCUMENTOS", DOCUMENTOS.SelectedEntitiesHandles);
                e.Command.OutputDefinition.Parameters.Add("EhCRE", true);
            }
            else
            {
                throw new BusinessException("Necessário selecionar ao menos um documento!");
            }
    }
}
