<%@ Page Title="R-9015 - Consolidação das retenções na fonte" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
    <wes:AjaxForm runat="server" ID="R9015CONSOLIDAODASRETENESNAFONTE" Title="R-9015 - Consolidação das retenções na fonte" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="REINF_R9015.FORM" FormMode="None" IncludeRecordInRecentItems="True" UserDefinedCommandsVisible="True" PageId="REINF_REGISTRO_R9015_FORM" Level="20" Order="10"  />
      <div class="col-md-12"><div class="portlet light">
    <div class="tabbable-line">
      <ul class="nav nav-tabs">
        <li onclick="Benner.Page.changeSelectedTab(this)" data-widget-id="INFORELATIVASATOTALIZADORESPELANATUREZADORENDIMENTOECDIGODERECEITA" class="active"><a data-toggle="tab" href="#tabINFORELATIVASATOTALIZADORESPELANATUREZADORENDIMENTOECDIGODERECEITA"><%= Benner.Tecnologia.Wes.Components.LanguageTranslator.Translate(@"Info. relativas a totalizadores pela natureza do rendimento e código de receita")%></a></li>
        <li onclick="Benner.Page.changeSelectedTab(this)" data-widget-id="OCORRNCIA"><a data-toggle="tab" href="#tabOCORRNCIA"><%= Benner.Tecnologia.Wes.Components.LanguageTranslator.Translate(@"Ocorrência")%></a></li>
        <li onclick="Benner.Page.changeSelectedTab(this)" data-widget-id="INFORMAESCONSOLIDADASCOMPERODODEAPURAOMENSAL"><a data-toggle="tab" href="#tabINFORMAESCONSOLIDADASCOMPERODODEAPURAOMENSAL"><%= Benner.Tecnologia.Wes.Components.LanguageTranslator.Translate(@"Informações consolidadas com período de apuração mensal")%></a></li>
        <li onclick="Benner.Page.changeSelectedTab(this)" data-widget-id="INFORMAESCONSOLIDADASCOMPERODODEAPURAOQUINZENAL"><a data-toggle="tab" href="#tabINFORMAESCONSOLIDADASCOMPERODODEAPURAOQUINZENAL"><%= Benner.Tecnologia.Wes.Components.LanguageTranslator.Translate(@"Informações consolidadas com período de apuração quinzenal")%></a></li>
        <li onclick="Benner.Page.changeSelectedTab(this)" data-widget-id="INFORMAESCONSOLIDADASCOMPERODODEAPURAODECENDIAL"><a data-toggle="tab" href="#tabINFORMAESCONSOLIDADASCOMPERODODEAPURAODECENDIAL"><%= Benner.Tecnologia.Wes.Components.LanguageTranslator.Translate(@"Informações consolidadas com período de apuração decendial")%></a></li>
        <li onclick="Benner.Page.changeSelectedTab(this)" data-widget-id="INFORMAESCONSOLIDADASCOMPERODODEAPURAOSEMANAL"><a data-toggle="tab" href="#tabINFORMAESCONSOLIDADASCOMPERODODEAPURAOSEMANAL"><%= Benner.Tecnologia.Wes.Components.LanguageTranslator.Translate(@"Informações consolidadas com período de apuração semanal")%></a></li>
        <li onclick="Benner.Page.changeSelectedTab(this)" data-widget-id="INFORMAESCONSOLIDADASCOMPERODODEAPURAODIRIO"><a data-toggle="tab" href="#tabINFORMAESCONSOLIDADASCOMPERODODEAPURAODIRIO"><%= Benner.Tecnologia.Wes.Components.LanguageTranslator.Translate(@"Informações consolidadas com período de apuração diário")%></a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tabINFORELATIVASATOTALIZADORESPELANATUREZADORENDIMENTOECDIGODERECEITA">
                    <div class="row">
    <wes:SimpleGrid runat="server" ID="INFORELATIVASATOTALIZADORESPELANATUREZADORENDIMENTOECDIGODERECEITA" Title="Info. relativas a totalizadores pela natureza do rendimento e código de receita" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="R9015CONSOLIDAODASRETENESNAFONTE" ChromeState="Fixed" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="REINF_INFORMACOESBASETRIBUTOS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.R9015 = @CAMPO(HANDLE)" FormUrl="~/PortalReinf/a/Registros/R9015/InformacaoNaturezaRendimentoCR.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="REINF_REGISTRO_R9015_FORM" Level="20" Order="20"  /></div>
        </div>
        <div class="tab-pane" id="tabOCORRNCIA">
                    <div class="row">
    <wes:SimpleGrid runat="server" ID="OCORRNCIA" Title="Ocorrência" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="R9015CONSOLIDAODASRETENESNAFONTE" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="REINF_OCORRENCIAS.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.R9015 = @CAMPO(HANDLE)" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="REINF_REGISTRO_R9015_FORM" Level="20" Order="30"  /></div>
        </div>
        <div class="tab-pane" id="tabINFORMAESCONSOLIDADASCOMPERODODEAPURAOMENSAL">
                    <div class="row">
    <wes:SimpleGrid runat="server" ID="INFORMAESCONSOLIDADASCOMPERODODEAPURAOMENSAL" Title="Informações consolidadas com período de apuração mensal" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="R9015CONSOLIDAODASRETENESNAFONTE" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="REINF_TOTALIZADORAPURACAOMEN_9015_InfoConsolidadas.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.R9015 = @CAMPO(HANDLE)" FormUrl="~/PortalReinf/a/Registros/R9015/InfoConsolidadas/TotalizadorMensal.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="REINF_REGISTRO_R9015_FORM" Level="20" Order="40"  /></div>
        </div>
        <div class="tab-pane" id="tabINFORMAESCONSOLIDADASCOMPERODODEAPURAOQUINZENAL">
                    <div class="row">
    <wes:SimpleGrid runat="server" ID="INFORMAESCONSOLIDADASCOMPERODODEAPURAOQUINZENAL" Title="Informações consolidadas com período de apuração quinzenal" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="R9015CONSOLIDAODASRETENESNAFONTE" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="REINF_TOTALIZADORAPURACAOQUI_9015_InfoConsolidadas.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.R9015 = @CAMPO(HANDLE)" FormUrl="~/PortalReinf/a/Registros/R9015/InfoConsolidadas/TotalizadorQuinzenal.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="REINF_REGISTRO_R9015_FORM" Level="20" Order="50"  /></div>
        </div>
        <div class="tab-pane" id="tabINFORMAESCONSOLIDADASCOMPERODODEAPURAODECENDIAL">
                    <div class="row">
    <wes:SimpleGrid runat="server" ID="INFORMAESCONSOLIDADASCOMPERODODEAPURAODECENDIAL" Title="Informações consolidadas com período de apuração decendial" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="R9015CONSOLIDAODASRETENESNAFONTE" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="REINF_TOTALIZADORAPURACAODEC_9015_InfoConsolidadas.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.R9015 = @CAMPO(HANDLE)" FormUrl="~/PortalReinf/a/Registros/R9015/InfoConsolidadas/TotalizadorDecendial.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="REINF_REGISTRO_R9015_FORM" Level="20" Order="60"  /></div>
        </div>
        <div class="tab-pane" id="tabINFORMAESCONSOLIDADASCOMPERODODEAPURAOSEMANAL">
                    <div class="row">
    <wes:SimpleGrid runat="server" ID="INFORMAESCONSOLIDADASCOMPERODODEAPURAOSEMANAL" Title="Informações consolidadas com período de apuração semanal" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="R9015CONSOLIDAODASRETENESNAFONTE" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="REINF_TOTALIZADORAPURACAOSEM_9015_InfoConsolidadas.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.R9015 = @CAMPO(HANDLE)" FormUrl="~/PortalReinf/a/Registros/R9015/InfoConsolidadas/TotalizadorSemanal.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="REINF_REGISTRO_R9015_FORM" Level="20" Order="70"  /></div>
        </div>
        <div class="tab-pane" id="tabINFORMAESCONSOLIDADASCOMPERODODEAPURAODIRIO">
                    <div class="row">
    <wes:SimpleGrid runat="server" ID="INFORMAESCONSOLIDADASCOMPERODODEAPURAODIRIO" Title="Informações consolidadas com período de apuração diário" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="false" ProviderWidgetUniqueId="R9015CONSOLIDAODASRETENESNAFONTE" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" EntityViewName="REINF_TOTALIZADORAPURACAODIA_9015_InfoConsolidadas.GRID" Mode="Selectable" UserDefinedSelectColumnVisible="False" UserDefinedPageSize="10" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="OnlyCompany" UserDefinedCriteriaWhereClause="A.R9015 = @CAMPO(HANDLE)" FormUrl="~/PortalReinf/a/Registros/R9015/InfoConsolidadas/TotalizadorDiario.aspx" ShowExport="True" UserDefinedDisableRowSelection="False" PageId="REINF_REGISTRO_R9015_FORM" Level="20" Order="80"  /></div>
        </div>
      </div>
    </div>
  </div>
</div></div>
      </asp:Content>
    