//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Corporativo.Wes.WebApp.aga.a.suprimentos.Requisicoes;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Application;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using SM.Crm.Definicoes.Entidades;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class K_CRM_EMAILSformPage : WesPage
{
    
    protected void Page_Load(object sender, System.EventArgs e)
    {
         this.K_EMAIL.CommandExecuted += K_EMAIL_CommandExecuted;
        //var a = BennerAppInfraServices.Default.LegacySystem.GetSessionPath();
        //var path = K_EMAIL.GetEntity();
        //string path = Path.Combine(BennerAppInfraServices.Default.LegacySystem.GetSessionPath(), (K_EMAIL.GetEntity().Fields["ANEXO"] as FileField).TemporaryId.ToString());

        //var b = path;
    }

    private void K_EMAIL_CommandExecuted(object sender, FormCommandExecuteArgs e)
    {
        //if(e.CommandName == "CmdEnviar")
        //{
        //    var email = this.K_EMAIL.GetEntity();
        //    email.Save();
        //}
        if (e.CommandName == "CmdTeste")
        {
            var email = this.K_EMAIL.GetEntity();

            
            var a = CrmEmails.Get(email.Handle,GetMode.Edit);
            a.Save();
            //email.Save();
        }
    }

    protected override void OnLoadComplete(EventArgs e)
    {
        base.OnLoadComplete(e);

        var path = K_EMAIL.GetEntity();

        var a = path;
    }
}
