//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.Links;
using Benner.Tecnologia.Wes.Components.WebApp;
using SM.Crm.Definicoes.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class K_CRM_EMAILSGridPage : WesPage
{
    
    protected void Page_Load(object sender, System.EventArgs e)
    {
        PnlBotaoEnviar.Visible = BennerPrincipal.Current.ActiveRole == "K_CRM_ADMIN";//Thread.CurrentPrincipal.IsInRole("K_CRM_ADMIN");
        var a = PnlBotaoEnviar.Visible;
    }

    protected void BtnNovoEmail_Click(object sender, EventArgs e)
    {
        var link = new FormLinkDefinition();
        link.TargetSystemInstanceName = BennerContext.Administration.BServerSystemName;
        link.Url = "/CRM/Pages/K_CRM_EMAILS/Form.aspx";
        link.TargetEntityDefinitionName = CrmEmails.GetEntityDefinition().Name;
        link.TargetFormMode = FormLinkDefinition.FormMode.Insert;
        var url = Benner.Tecnologia.Wes.Components.UriBuilder.Create(link);
        Response.Redirect(url);
    }
}
